<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_arrange_draw' => 'Organiser le tirage',
    'action_clear_draw' => 'Effacer le tirage',
    'action_end_next_bout' => 'Terminer le prochain combat',
    'action_generate_draw' => 'Générer le tirage',
    'call_mat_tbc' => 'votre arène',
    'call_opponent_tbc' => 'À déterminer',
    'call_room_body' => ':mat · combat :bout · contre :opponent',
    'call_room_title' => 'Rendez-vous à la salle d’appel — :mat',
    'call_warmup_body' => ':ahead combats avant vous · environ :minutes min',
    'call_warmup_title' => 'Échauffement — vous êtes sur :mat bientôt',
    'day_mats' => 'Jour :day: :count arènes',
    'draw_arranged' => 'Tirage mis à jour 🥋',
    'draw_cleared' => 'Tirage vidé — tous les inscrits sont de nouveau sur la liste',
    'draw_final' => 'Le championnat a commencé — le tirage est définitif et ne peut pas être régénéré.',
    'draw_generated' => 'Tirage provisoire généré',
    'end_next_bout_done' => ':winner gagne sur :court. Les écrans de cette arène ont été mis au courant.',
    'end_next_bout_none' => 'Aucun combat n’est prêt à être terminé — tous les combats en attente attendent un combat préalable.',
    'ended_locked' => 'Ce championnat est terminé — ses résultats sont définitifs.',
    'gate_no_division' => 'Votre catégorie de poids n’est pas l’une des divisions de ce championnat, vous n’êtes donc pas éligible à participer à cet événement.',
    'gate_no_division_spectator' => 'Votre catégorie de poids n’est pas l’une des divisions de ce championnat, vous ne pouvez donc pas participer — mais vous êtes bienvenu(e) pour assister en tant que spectateur.',
    'gate_no_profile' => 'Ajoutez votre genre et votre date de naissance à votre profil afin que nous puissions vous classer dans une catégorie de poids.',
    'gate_no_weight' => 'Ajoutez votre poids actuel à votre profil santé afin que nous puissions vous classer dans une catégorie de poids.',
    'notify_draw_body' => 'Votre division a été tirée. Ouvrez l’événement pour voir votre adversaire, arène et numéro de combat.',
    'notify_draw_title' => 'Le tirage est publié — :title',
    'notify_weigh_in_body' => 'La pesée commence à :time à :place. Apportez votre pièce d’identité.',
    'notify_weigh_in_title' => 'Pesée demain — :title',
    'result_body_done' => 'C’était votre dernier combat de la journée.',
    'result_body_next' => 'Suivant :round sur :mat, environ :minutes min',
    'result_loss_title' => 'Combat terminé',
    'result_win_title' => 'Vous avez gagné 🎉',
    'roster_registered' => 'Inscrit(e)',
    'roster_unclassified' => 'Non classé(e)',
    'type_label' => 'Championnat de Jiu-Jitsu',

];
