<?php

/*
|--------------------------------------------------------------------------
| auth — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/auth.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'auth_desktop_login_check_inbox_after' => '। इसे क्लिक करके लॉगिन करें।',
    'auth_desktop_login_check_inbox_before' => 'हमने लॉगिन लिंक भेजा है',
    'auth_desktop_login_check_inbox_title' => 'अपने इनबॉक्स की जाँच करें',
    'auth_desktop_login_email_me_link' => 'लॉगिन लिंक ईमेल करें',
    'auth_desktop_login_email_placeholder' => 'फ़ोन नंबर या ईमेल',
    'auth_desktop_login_forgot_password' => 'पासवर्ड भूल गए?',
    'auth_desktop_login_magic_hint' => 'कोई पासवर्ड नहीं? हम आपको एक एक बार के लॉगिन लिंक ईमेल करेंगे।',
    'auth_desktop_login_password_placeholder' => 'पासवर्ड',
    'auth_desktop_login_register' => 'खाता बनाएं',
    'auth_desktop_login_remember_me' => 'मुझे याद रखें',
    'auth_desktop_login_resend_verification' => 'सत्यापन ईमेल फिर से भेजें',
    'auth_desktop_login_sign_in' => 'साइन इन करें',
    'auth_desktop_login_subtitle' => 'स्वागत है! जारी रखने के लिए साइन इन करें',
    'auth_desktop_login_tab_link' => 'लॉगिन लिंक',
    'auth_desktop_login_tab_password' => 'पासवर्ड',
    'auth_desktop_login_unverified_hint' => 'क्या ईमेल प्राप्त नहीं हुआ या यह समाप्त हो गया है?',
    'auth_desktop_login_unverified_title' => 'ईमेल सत्यापित नहीं हुआ',
    'auth_desktop_login_your_email_placeholder' => 'आपका ईमेल',
    'auth_forgot_password_back_to_login' => 'लॉगिन पर वापस जाएं',
    'auth_forgot_password_email_placeholder' => 'ईमेल',
    'auth_forgot_password_send_reset_link' => 'पासवर्ड रीसेट लिंक भेजें',
    'auth_forgot_password_subtitle' => 'कोई बात नहीं — अपना ईमेल दर्ज करें और हम आपको रीसेट लिंक भेजेंगे।',
    'auth_forgot_password_title' => 'अपना पासवर्ड भूल गए?',
    'auth_register_birthdate' => 'जन्मदिन',
    'auth_register_confirm_password' => 'पासवर्ड की पुष्टि करें',
    'auth_register_email' => 'ईमेल पता',
    'auth_register_full_name' => 'पूरा नाम',
    'auth_register_joining_club' => 'आप शामिल हो रहे हैं',
    'auth_register_mobile_number' => 'मोबाइल नंबर',
    'auth_register_nationality' => 'राष्ट्रीयता',
    'auth_register_password' => 'पासवर्ड',
    'auth_register_submit' => 'रजिस्टर करें',
    'auth_register_subtitle' => 'अपना खाता बनाएं',
    'auth_register_wizard_err_generic_post' => ')। कृपया पुनः प्रयास करें।',
    'auth_register_wizard_err_generic_pre' => 'कुछ गड़बड़ी हुई (त्रुटि',
    'auth_register_wizard_err_network' => 'नेटवर्क त्रुटि। कृपया अपने कनेक्शन की जाँच करें और पुनः प्रयास करें।',
    'auth_register_wizard_err_session_expired' => 'आपका सत्र समाप्त हो गया है। कृपया पृष्ठ को रीफ्रेश करें और पुनः प्रयास करें।',
    'auth_register_wizard_ph_child_name' => 'बच्चे का पूरा नाम',
    'auth_register_wizard_ph_email' => 'ईमेल पता',
    'auth_register_wizard_ph_full_name' => 'पूरा नाम',
    'auth_register_wizard_ph_health' => 'कृपया किसी भी स्वास्थ्य स्थिति का वर्णन करें',
    'auth_register_wizard_ph_mobile' => 'मोबाइल नंबर',
    'auth_register_wizard_rel_daughter' => 'बेटी',
    'auth_register_wizard_rel_member_fallback' => 'परिवार का सदस्य',
    'auth_register_wizard_rel_other' => 'अन्य',
    'auth_register_wizard_rel_son' => 'बेटा',
    'auth_register_wizard_rel_spouse' => 'पति',
    'auth_register_wizard_terms_changes_body' => 'इन नियमों को समय-समय पर अपडेट किया जा सकता है; सेवा के उपयोग करने का अर्थ है इन नियमों को स्वीकार करना।',
    'auth_register_wizard_terms_changes_title' => 'नियमों में परिवर्तन',
    'auth_register_wizard_terms_conduct_body' => 'सदस्यों को क्लब के नियमों का पालन करना और स्टाफ और अन्य सदस्यों के प्रति सम्मानपूर्ण व्यवहार करना चाहिए।',
    'auth_register_wizard_terms_conduct_title' => 'व्यवहार नियम',
    'auth_register_wizard_terms_confirm' => 'नीचे दिए गए बॉक्स को चेक करके, आप पुष्टि करते हैं कि आपने इन नियमों को पढ़ा है और उनसे सहमत हैं।',
    'auth_register_wizard_terms_default_intro' => ':club में स्वागत है! रजिस्टर करके, आप निम्नलिखित शर्तों से सहमत हैं:',
    'auth_register_wizard_terms_medical_body' => 'कृपया उन चिकित्सा या स्वास्थ्य स्थितियों को स्पष्ट करें जो भाग लेने पर प्रभाव डाल सकती हैं।',
    'auth_register_wizard_terms_medical_title' => 'चिकित्सा और स्वास्थ्य',
    'auth_register_wizard_terms_membership_body' => 'आपकी सदस्यता तब शुरू होती है जब आपका रजिस्टरेशन स्वीकृत हो जाए और भुगतान (अगर आवश्यक हो) पुष्टि हो जाए।',
    'auth_register_wizard_terms_membership_title' => 'सदस्यता',
    'auth_register_wizard_terms_payment_body' => 'सभी भुगतान रजिस्टरेशन के समय देय होते हैं अगर \'बाद में भुगतान करें\' विकल्प चुना जाए।',
    'auth_register_wizard_terms_payment_title' => 'भुगतान',
    'auth_register_wizard_terms_privacy_body' => 'आपका व्यक्तिगत डेटा केवल आपके सदस्यता प्रबंधन के लिए उपयोग किया जाता है और सहमति के बिना साझा नहीं किया जाएगा।',
    'auth_register_wizard_terms_privacy_title' => 'गोपनीयता',
    'auth_reset_password_back_to_login' => 'लॉगिन पर वापस जाएं',
    'auth_reset_password_confirm_password_label' => 'नया पासवर्ड की पुष्टि करें',
    'auth_reset_password_email_label' => 'ईमेल पता',
    'auth_reset_password_new_password_label' => 'नया पासवर्ड',
    'auth_reset_password_submit' => 'पासवर्ड रीसेट करें',
    'auth_reset_password_title' => 'अपना पासवर्ड रीसेट करें',
    'auth_verify_email_check_inbox_line1' => 'हमने आपके ईमेल पते पर एक सत्यापन लिंक भेजा है।',
    'auth_verify_email_check_inbox_line2' => 'कृपया अपने खाते को सत्यापित करने के लिए लिंक पर क्लिक करें।',
    'auth_verify_email_check_inbox_title' => 'अपना ईमेल जाँचें',
    'auth_verify_email_didnt_receive' => 'ईमेल प्राप्त नहीं हुआ?',
    'auth_verify_email_fresh_link_sent' => 'आपके ईमेल पते पर एक नया सत्यापन लिंक भेजा गया है।',
    'auth_verify_email_go_to_app' => 'जारी रखें',
    'auth_verify_email_one_step_away' => 'सामाजिक शामिल होने के लिए एक और कदम',
    'auth_verify_email_redirecting_prefix' => 'में रीडायरेक्ट हो रहा है',
    'auth_verify_email_redirecting_suffix' => 'सेकंड...',
    'auth_verify_email_resend_button' => 'सत्यापन ईमेल फिर से भेजें',
    'auth_verify_email_sign_out' => 'साइन आउट करें',
    'auth_verify_email_verified_body' => 'आपका ईमेल सफलतापूर्वक सत्यापित कर दिया गया है।',
    'auth_verify_email_verified_title' => 'ईमेल सत्यापित किया गया!',
    'auth_verify_email_wrong_account' => 'गलत खाता?',
    'choose_not_you' => 'एक अलग नंबर या ईमेल का उपयोग करें',
    'choose_sub' => 'इस नंबर का उपयोग करने वाले एक से अधिक व्यक्ति हैं। जिसे लॉगिन कर रहा है उसे टैप करें।',
    'choose_title' => 'कौन लॉगिन कर रहा है?',
    'club_waiting' => 'आपका क्लब इंतज़ार कर रहा है। चलिए चलते हैं।',
    'create_account' => 'खाता बनाएं',
    'didnt_receive' => 'क्या ईमेल प्राप्त नहीं हुआ या यह समाप्त हो गया है?',
    'email' => 'ईमेल',
    'email_not_verified' => 'ईमेल सत्यापित नहीं हुआ',
    'email_or_phone' => 'फ़ोन नंबर या ईमेल',
    'forgot_password' => 'पासवर्ड भूल गए?',
    'hide_password' => 'पासवर्ड छिपाएं',
    'magic_cta' => 'लॉगिन लिंक ईमेल करें',
    'magic_prompt' => 'कोई पासवर्ड नहीं? हम आपको एक एक बार के लॉगिन लिंक ईमेल करेंगे।',
    'magic_sent_body' => 'अगर उस ईमेल के लिए कोई खाता मौजूद है, तो हमने एक लॉगिन लिंक भेजा है। लॉगिन करने के लिए ईमेल में बटन पर क्लिक करें — कोई पासवर्ड आवश्यक नहीं है।',
    'magic_sent_title' => 'अपने इनबॉक्स की जाँच करें',
    'new_to_takeone' => 'TAKEONE में नए हैं?',
    'or' => 'या',
    'password' => 'पासवर्ड',
    'remember_me' => 'मुझे याद रखें',
    'resend_verification' => 'सत्यापन ईमेल फिर से भेजें',
    'show_password' => 'पासवर्ड दिखाएं',
    'sign_in' => 'साइन इन करें',
    'tab_magic' => 'लॉगिन लिंक',
    'tab_password' => 'पासवर्ड',
    'welcome_back' => 'वापसी पर स्वागत है',

];
