<?php

/*
|--------------------------------------------------------------------------
| explore — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/explore.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'apply_location' => 'स्थान लागू करें',
    'book_session' => 'सत्र बुक करें',
    'cat_all' => 'सभी',
    'cat_clubs' => 'क्लब',
    'cat_events' => 'कार्यक्रम',
    'cat_food_plans' => 'भोजन योजनाएं',
    'cat_nutrition' => 'पोषण',
    'cat_physiotherapy' => 'शरीर चिकित्सा',
    'cat_shops' => 'दुकानें',
    'cat_supplements' => 'पूरक पदार्थ',
    'cat_trainers' => 'प्रशिक्षक',
    'cat_venues' => 'स्थान',
    'choose_option_body' => 'प्रत्येक चयनित उपकरण आइटम के लिए एक विकल्प चुनें।',
    'choose_option_title' => 'विकल्प आवश्यक',
    'detecting_location' => 'स्थान का पता लगा रहा है...',
    'drag_marker' => 'अपना स्थान सेट करने के लिए मार्कर खींचें',
    'error_fetching_clubs' => 'क्लब लोड करते समय एक त्रुटि हुई।',
    'ev_coming_up' => 'आगामी',
    'ev_failed' => 'इवेंट लोड करने में विफल। कृपया पुनः प्रयास करें।',
    'ev_finding' => 'इवेंट लोड हो रहे हैं...',
    'ev_free' => 'नि:शुल्क',
    'ev_full' => 'भरा हुआ',
    'ev_going' => 'जा रहा है',
    'ev_happening_now' => 'अभी हो रहा है',
    'ev_live' => 'लाइव',
    'ev_none_hint' => 'फिलहाल आपके लिए कोई चल रहा या निर्धारित नहीं है।',
    'ev_none_title' => 'कोई खुला इवेंट नहीं',
    'ev_open' => 'खुला',
    'ev_spots_left' => 'स्पॉट बचे हैं',
    'ev_starts_in' => 'शुरू होने वाला है',
    'ev_tba' => 'तय नहीं',
    'ev_until' => 'तक',
    'ev_view_event' => 'इवेंट देखें',
    'explore' => 'अन्वेषण करें',
    'failed_to_fetch_clubs' => 'क्लब लोड करने में विफल। कृपया पुनः प्रयास करें।',
    'finding' => 'आपके आसपास की चीजें खोज रहे हैं...',
    'geolocation_not_supported' => 'आपके ब्राउज़र द्वारा भू स्थान समर्थित नहीं है।',
    'hero_eyebrow' => 'आसपास की खोज करें',
    'hero_sub' => 'आपके आसपास क्लब, प्रशिक्षक, क्लिनिक और अधिक',
    'hero_title' => 'आपके लिए सही खोजें',
    'join_club' => 'क्लब में शामिल हों',
    'km_away' => 'किमी दूर',
    'loading' => 'लोड हो रहा है...',
    'location_access_denied' => 'स्थान पहुँच अस्वीकृत।',
    'location_available' => 'स्थान उपलब्ध',
    'location_request_timed_out' => 'स्थान अनुरोध समय समाप्त हो गया।',
    'location_unavailable' => 'स्थान जानकारी अनुपलब्ध।',
    'members' => 'सदस्य',
    'na' => 'N/A',
    'near_me' => 'आपके आसपास',
    'no_members_selected_body' => 'जारी रखने के लिए कम से कम एक सदस्य चुनें।',
    'no_members_selected_title' => 'कोई सदस्य चयनित नहीं',
    'no_results' => 'कोई परिणाम नहीं मिला',
    'no_results_hint' => 'अपनी खोज या स्थान समायोजित करने का प्रयास करें',
    'packages' => 'पैकेज',
    'packages_required_body' => 'प्रत्येक चयनित सदस्य के लिए एक पैकेज चुनें।',
    'packages_required_title' => 'पैकेज आवश्यक',
    'payment_required_body' => 'भुगतान स्क्रीनशॉट अपलोड करें या बाद में भुगतान करने का चुनाव करें।',
    'payment_required_title' => 'भुगतान साबिती आवश्यक',
    'personal_trainer_badge' => 'व्यक्तिगत प्रशिक्षक',
    'please_try_again' => 'कृपया पुनः प्रयास करें।',
    'rating' => 'रेटिंग',
    'registration_error_body' => 'आपके पंजीकरण सबमिट करते समय कुछ गड़बड़ी हुई।',
    'registration_failed_title' => 'पंजीकरण विफल',
    'registration_submitted_body' => 'आपका पंजीकरण क्लब के अनुमोदन के लिए भेज दिया गया है।',
    'registration_submitted_title' => 'पंजीकरण सबमिट किया गया',
    'reviews' => 'समीक्षाएं',
    'search_placeholder' => 'क्लब, प्रशिक्षक खोजें...',
    'set_location' => 'अपना स्थान सेट करें',
    'sports_club_badge' => 'खेल क्लब',
    'trainers' => 'प्रशिक्षक',
    'unable_to_get_location' => 'आपका स्थान प्राप्त करने में असमर्थ।',
    'view_details' => 'विवरण देखें',
    'years_exp' => 'वर्ष अनुभव',

];
