<?php

/*
|--------------------------------------------------------------------------
| header — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/header.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'cart' => 'कार्ट',
    'cart_soon' => 'कार्ट जल्द आ रहा है',
    'chat' => 'चैट',
    'clear_all' => 'सभी साफ करें',
    'club_management' => 'क्लब प्रबंधन',
    'just_now' => 'अभी के बाद',
    'mark_all_read' => 'सभी को पढ़ा हुआ चिह्नित करें',
    'menu' => 'मेनू',
    'no_notifications' => 'अभी तक कोई सूचना नहीं',
    'notification' => 'सूचना',
    'notifications' => 'सूचनाएँ',
    'personal_desc' => 'मेरी प्रोफाइल, बुकिंग, भुगतान',
    'personal_view' => 'व्यक्तिगत दृश्य',
    'scan_code_placeholder' => 'ABC123',
    'scan_foreign_host' => 'यह QR कोड किसी अन्य वेबसाइट को इंगित करता है, इसलिए इसे नहीं खोला गया।',
    'scan_hint' => 'QR कोड के सामने अपना कैमरा सेट करें',
    'scan_no_camera' => 'कैमरा तक पहुँच नहीं सका।',
    'scan_or_type' => 'या 6-अक्षर वाला कोड टाइप करें',
    'scan_qr' => 'QR कोड स्कैन करें',
    'scan_unsupported' => 'इस ब्राउज़र में QR स्कैनिंग समर्थित नहीं है।',
    'switch_view' => 'दृश्य बदलें',

];
