<?php

/*
|--------------------------------------------------------------------------
| notifications — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/notifications.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'comment' => ':actor ने आपके पोस्ट में टिप्पणी की',
    'follow' => ':actor ने आपका अनुसरण किया',
    'like' => ':actor ने आपके पोस्ट को पसंद किया',
    'payment_approved' => 'भुगतान स्वीकृत',
    'payment_refunded' => 'भुगतान वापस किया गया',
    'post' => ':actor ने एक नया पोस्ट साझा किया',

];
