<?php

/*
|--------------------------------------------------------------------------
| security — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/security.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'add_otp_desc' => 'प्रत्येक लॉगिन पर अपने प्रमाणीकरण ऐप से एक बार का कोड जोड़ें।',
    'cancel' => 'रद्द करें',
    'change_password' => 'पासवर्ड बदलें',
    'change_password_desc' => 'जब आप इसे बदलते हैं तो अन्य सभी सक्रिय सत्र लॉग आउट हो जाते हैं।',
    'code_placeholder' => '6-अंक कोड',
    'code_placeholder_long' => '6-अंक या रिकवरी कोड',
    'confirm_new_password' => 'नया पासवर्ड की पुष्टि करें',
    'current_password' => 'वर्तमान पासवर्ड',
    'disable' => 'अक्षम करें',
    'disable_2fa' => '2FA अक्षम करें',
    'disable_confirm_desc' => 'पुष्टि करने के लिए एक वर्तमान प्रमाणीकरण कोड (या एक रिकवरी कोड) दर्ज करें।',
    'disable_two_factor' => 'द्विकारक प्रमाणीकरण अक्षम करें',
    'enable_2fa' => '2FA सक्षम करें',
    'lockdown_message' => 'आइए अपने खाते को लॉक कर दें।',
    'new_password' => 'नया पासवर्ड',
    'protected_message' => 'आपका खाता अच्छी तरह से सुरक्षित है।',
    'protected_with_app' => 'गूगल ऑथेंटिकेटर के साथ सुरक्षित।',
    'recovery_codes' => 'रिकवरी कोड',
    'recovery_codes_desc' => 'जब आपको अपने प्रमाणीकरण ऐप से एक्सेस खोने के मामले में एक बार के बैकअप कोड।',
    'regenerate' => 'फिर से उत्पन्न करें',
    'regenerate_codes' => 'कोड फिर से उत्पन्न करें',
    'regenerate_codes_title' => 'कोड फिर से उत्पन्न करें',
    'regenerate_confirm_desc' => 'आपके मौजूदा रिकवरी कोड अब काम नहीं करेंगे। अपने प्रमाणीकरण कोड को पुष्टि करने के लिए दर्ज करें।',
    'security' => 'सुरक्षा',
    'security_challenge_back_to_login' => 'लॉगिन पर वापस जाएं',
    'security_challenge_backup_hint' => 'अपने 8-अक्षर बैकअप कोड में से एक दर्ज करें।',
    'security_challenge_subtitle' => 'अपने प्रमाणीकरण ऐप से कोड दर्ज करें।',
    'security_challenge_title' => 'द्विकारक प्रमाणीकरण',
    'security_challenge_use_authenticator' => 'प्रमाणीकरण ऐप का उपयोग करें',
    'security_challenge_use_recovery' => 'रिकवरी कोड का उपयोग करें',
    'security_challenge_verify' => 'पुष्टि करें',
    'security_index_2fa_disabled_desc' => 'अपने खाते को एक अतिरिक्त सुरक्षा परत जोड़ें।',
    'security_index_2fa_enabled_desc' => 'आपका खाता गूगल ऑथेंटिकेटर के साथ सुरक्षित है।',
    'security_index_2fa_title' => 'द्विकारक प्रमाणीकरण',
    'security_index_change_password' => 'पासवर्ड बदलें',
    'security_index_change_password_desc' => 'जब आप अपना पासवर्ड बदलते हैं तो अन्य सभी सक्रिय सत्र लॉग आउट हो जाएंगे।',
    'security_index_code_or_recovery_placeholder' => '6-अंक कोड या रिकवरी कोड',
    'security_index_code_placeholder' => '6-अंक कोड',
    'security_index_confirm_new_password' => 'नया पासवर्ड की पुष्टि करें',
    'security_index_current_password' => 'वर्तमान पासवर्ड',
    'security_index_disable_2fa' => '2FA अक्षम करें',
    'security_index_disable_2fa_modal_desc' => 'पुष्टि करने के लिए अपना वर्तमान प्रमाणीकरण कोड (या एक रिकवरी कोड) दर्ज करें।',
    'security_index_disable_2fa_modal_title' => 'द्विकारक प्रमाणीकरण अक्षम करें',
    'security_index_disabled' => 'अक्षम',
    'security_index_enable_2fa' => '2FA सक्षम करें',
    'security_index_enabled' => 'सक्षम',
    'security_index_new_password' => 'नया पासवर्ड',
    'security_index_recovery_codes' => 'रिकवरी कोड',
    'security_index_recovery_codes_desc' => 'अगर आपको अपने प्रमाणीकरण ऐप से एक्सेस खोने के मामले में एक बार के बैकअप कोड।',
    'security_index_regen_codes_modal_desc' => 'आपके मौजूदा रिकवरी कोड अब अमान्य हो जाएंगे। अपने प्रमाणीकरण कोड को पुष्टि करने के लिए दर्ज करें।',
    'security_index_regen_codes_modal_title' => 'रिकवरी कोड फिर से उत्पन्न करें',
    'security_index_regenerate' => 'फिर से उत्पन्न करें',
    'security_index_regenerate_codes' => 'कोड फिर से उत्पन्न करें',
    'security_index_subtitle' => 'अपने खाते की सुरक्षा और द्विकारक प्रमाणीकरण का प्रबंधन करें',
    'security_index_title' => 'सुरक्षा सेटिंग्स',
    'security_index_update_password' => 'पासवर्ड अपडेट करें',
    'security_recovery_codes_account_protected' => 'आपका खाता अब सुरक्षित है।',
    'security_recovery_codes_copied' => 'कॉपी कर लिया गया!',
    'security_recovery_codes_copy_all' => 'सभी कोड कॉपी करें',
    'security_recovery_codes_heading_enabled' => 'द्विपावरण प्रमाणीकरण सक्रिय हो गया',
    'security_recovery_codes_heading_new' => 'नए पुनर्प्राप्ति कोड',
    'security_recovery_codes_page_title' => 'पुनर्प्राप्ति कोड',
    'security_recovery_codes_save_safe' => 'कृपया इन पुनर्प्राप्ति कोड को किसी सुरक्षित स्थान पर संग्रहीत करें।',
    'security_recovery_codes_store_desc' => 'प्रत्येक कोड का केवल एक बार उपयोग किया जा सकता है।',
    'security_recovery_codes_store_safely' => 'इन कोड को सुरक्षित स्थान पर संग्रहीत करें।',
    'security_recovery_codes_success_alert' => 'आपके खाते पर द्विपावरण प्रमाणीकरण सफलतापूर्वक सक्रिय कर दिया गया है।',
    'security_setup_manual_entry' => 'स्कैन नहीं कर पा रहे? ऐप में इस कुंजी को मैन्युअल रूप से दर्ज करें:',
    'security_setup_step1_app_name' => 'गूगल ऑथेंटिकेटर',
    'security_setup_step1_app_store' => 'एप स्टोर',
    'security_setup_step1_download' => 'डाउनलोड',
    'security_setup_step1_from' => 'अपने फ़ोन पर',
    'security_setup_step1_heading' => 'गूगल ऑथेंटिकेटर स्थापित करें',
    'security_setup_step1_or' => 'या',
    'security_setup_step1_play_store' => 'प्ले स्टोर',
    'security_setup_step2_heading' => 'क्यूआर कोड स्कैन करें',
    'security_setup_step2_open' => 'ऐप खोलें, टैप करें',
    'security_setup_step2_scan_option' => 'क्यूआर कोड स्कैन करें',
    'security_setup_step2_then_choose' => ', फिर चुनें',
    'security_setup_step3_heading' => 'अपना कोड पुष्टि करें',
    'security_setup_step3_subtitle' => 'स्थापना की पुष्टि करने के लिए ऐप में दिखाई गई 6-अंकीय कोड दर्ज करें।',
    'security_setup_subtitle' => 'अपने खाते को गूगल ऑथेंटिकेटर के साथ सुरक्षित करने के लिए नीचे दिए गए चरणों का पालन करें।',
    'security_setup_time_based' => 'समय आधारित',
    'security_setup_time_based_prefix' => 'चुनें',
    'security_setup_time_based_suffix' => 'जब प्राप्त हो',
    'security_setup_title' => 'द्विपावरण प्रमाणीकरण स्थापित करें',
    'security_setup_verify_button' => 'पुष्टि करें और सक्रिय करें',
    'title' => 'सुरक्षा सेटिंग्स',
    'two_factor_auth' => 'द्विकारक प्रमाणीकरण',
    'two_factor_off' => 'द्विकारक प्रमाणीकरण बंद',
    'two_factor_on' => 'द्विकारक प्रमाणीकरण चालू',
    'update_password' => 'पासवर्ड अपडेट करें',

];
