<?php

/*
|--------------------------------------------------------------------------
| auth — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/auth.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'auth_desktop_login_check_inbox_after' => '。点击它以登录。',
    'auth_desktop_login_check_inbox_before' => '我们已发送登录链接至',
    'auth_desktop_login_check_inbox_title' => '检查您的收件箱',
    'auth_desktop_login_email_me_link' => '发送登录链接到邮箱',
    'auth_desktop_login_email_placeholder' => '手机号或邮箱',
    'auth_desktop_login_forgot_password' => '忘记密码？',
    'auth_desktop_login_magic_hint' => '没有密码？我们会给您发送一个一次性登录链接。',
    'auth_desktop_login_password_placeholder' => '密码',
    'auth_desktop_login_register' => '创建账户',
    'auth_desktop_login_remember_me' => '记住我',
    'auth_desktop_login_resend_verification' => '重新发送验证邮件',
    'auth_desktop_login_sign_in' => '登录',
    'auth_desktop_login_subtitle' => '欢迎回来！登录以继续',
    'auth_desktop_login_tab_link' => '登录链接',
    'auth_desktop_login_tab_password' => '密码',
    'auth_desktop_login_unverified_hint' => '没有收到邮件或已过期？',
    'auth_desktop_login_unverified_title' => '邮箱未验证',
    'auth_desktop_login_your_email_placeholder' => '您的邮箱',
    'auth_forgot_password_back_to_login' => '返回登录',
    'auth_forgot_password_email_placeholder' => '电子邮件',
    'auth_forgot_password_send_reset_link' => '发送密码重置链接',
    'auth_forgot_password_subtitle' => '不用担心——输入您的电子邮件，我们会发送重置链接。',
    'auth_forgot_password_title' => '忘记密码？',
    'auth_register_birthdate' => '出生日期',
    'auth_register_confirm_password' => '确认密码',
    'auth_register_email' => '邮箱地址',
    'auth_register_full_name' => '全名',
    'auth_register_joining_club' => '您正在加入',
    'auth_register_mobile_number' => '手机号码',
    'auth_register_nationality' => '国籍',
    'auth_register_password' => '密码',
    'auth_register_submit' => '注册',
    'auth_register_subtitle' => '创建您的账户',
    'auth_register_wizard_err_generic_post' => '）。请重试。',
    'auth_register_wizard_err_generic_pre' => '出错了（错误',
    'auth_register_wizard_err_network' => '网络错误。请检查您的连接并重试。',
    'auth_register_wizard_err_session_expired' => '您的会话已过期。请刷新页面并重试。',
    'auth_register_wizard_ph_child_name' => '孩子的全名',
    'auth_register_wizard_ph_email' => '电子邮件地址',
    'auth_register_wizard_ph_full_name' => '全名',
    'auth_register_wizard_ph_health' => '请描述任何健康状况',
    'auth_register_wizard_ph_mobile' => '手机号码',
    'auth_register_wizard_rel_daughter' => '女儿',
    'auth_register_wizard_rel_member_fallback' => '家庭成员',
    'auth_register_wizard_rel_other' => '其他',
    'auth_register_wizard_rel_son' => '儿子',
    'auth_register_wizard_rel_spouse' => '配偶',
    'auth_register_wizard_terms_changes_body' => '这些条款可能会不时更新；继续使用服务即表示接受。',
    'auth_register_wizard_terms_changes_title' => '条款变更',
    'auth_register_wizard_terms_conduct_body' => '会员应遵守俱乐部的规定，并尊重工作人员和其他会员。',
    'auth_register_wizard_terms_conduct_title' => '行为准则',
    'auth_register_wizard_terms_confirm' => '勾选下方的复选框，确认您已阅读并同意这些条款。',
    'auth_register_wizard_terms_default_intro' => '欢迎来到 :club！注册即表示您同意以下条款：',
    'auth_register_wizard_terms_medical_body' => '请披露可能影响参与的任何医疗或健康状况。',
    'auth_register_wizard_terms_medical_title' => '医疗与健康',
    'auth_register_wizard_terms_membership_body' => '您的会员资格在注册获批且付款（如需）确认后开始。',
    'auth_register_wizard_terms_membership_title' => '会员资格',
    'auth_register_wizard_terms_payment_body' => '除非选择了“稍后付款”选项，否则所有付款均需在注册时支付。',
    'auth_register_wizard_terms_payment_title' => '付款',
    'auth_register_wizard_terms_privacy_body' => '您的个人数据仅用于管理会员资格，未经同意不会被共享。',
    'auth_register_wizard_terms_privacy_title' => '隐私',
    'auth_reset_password_back_to_login' => '返回登录',
    'auth_reset_password_confirm_password_label' => '确认新密码',
    'auth_reset_password_email_label' => '电子邮件地址',
    'auth_reset_password_new_password_label' => '新密码',
    'auth_reset_password_submit' => '重置密码',
    'auth_reset_password_title' => '重置密码',
    'auth_verify_email_check_inbox_line1' => '我们已向您的电子邮件地址发送了验证链接。',
    'auth_verify_email_check_inbox_line2' => '请点击链接验证您的账户。',
    'auth_verify_email_check_inbox_title' => '检查您的电子邮件',
    'auth_verify_email_didnt_receive' => '没有收到邮件？',
    'auth_verify_email_fresh_link_sent' => '新的验证链接已发送到您的电子邮件地址。',
    'auth_verify_email_go_to_app' => '继续',
    'auth_verify_email_one_step_away' => '加入的最后一步',
    'auth_verify_email_redirecting_prefix' => '将在',
    'auth_verify_email_redirecting_suffix' => '秒后跳转...',
    'auth_verify_email_resend_button' => '重新发送验证邮件',
    'auth_verify_email_sign_out' => '退出登录',
    'auth_verify_email_verified_body' => '您的电子邮件已成功验证。',
    'auth_verify_email_verified_title' => '电子邮件已验证！',
    'auth_verify_email_wrong_account' => '账户错误？',
    'choose_not_you' => '使用不同的号码或电子邮件',
    'choose_sub' => '有多个人使用此号码。点击正在登录的人。',
    'choose_title' => '谁在登录？',
    'club_waiting' => '您的俱乐部在等您。我们走吧。',
    'create_account' => '创建账户',
    'didnt_receive' => '没有收到邮件或已过期？',
    'email' => '邮箱',
    'email_not_verified' => '邮箱未验证',
    'email_or_phone' => '手机号或邮箱',
    'forgot_password' => '忘记密码？',
    'hide_password' => '隐藏密码',
    'magic_cta' => '发送登录链接到邮箱',
    'magic_prompt' => '没有密码？我们会给您发送一个一次性登录链接。',
    'magic_sent_body' => '如果该邮箱存在账户，我们已发送登录链接。点击邮件中的按钮登录——无需密码。',
    'magic_sent_title' => '检查您的收件箱',
    'new_to_takeone' => '首次使用 TAKEONE？',
    'or' => '或',
    'password' => '密码',
    'remember_me' => '记住我',
    'resend_verification' => '重新发送验证邮件',
    'show_password' => '显示密码',
    'sign_in' => '登录',
    'tab_magic' => '登录链接',
    'tab_password' => '密码',
    'welcome_back' => '欢迎回来',

];
