<?php

/*
|--------------------------------------------------------------------------
| errors — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/errors.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    '429_body' => '很多用户正在同时使用此页面，因此我们暂停了新的请求几秒钟。没有出错，您输入的内容也没有丢失。',
    '429_retry' => '{1}请在 :seconds 秒后重试|[2,*]请在 :seconds 秒后重试',
    '429_retry_action' => '重试',
    '429_title' => '请稍等',

];
