<?php

/*
|--------------------------------------------------------------------------
| explore — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/explore.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'apply_location' => '应用位置',
    'book_session' => '预约课程',
    'cat_all' => '全部',
    'cat_clubs' => '俱乐部',
    'cat_events' => '活动',
    'cat_food_plans' => '饮食计划',
    'cat_nutrition' => '营养',
    'cat_physiotherapy' => '物理治疗',
    'cat_shops' => '商店',
    'cat_supplements' => '补剂',
    'cat_trainers' => '教练',
    'cat_venues' => '场地',
    'choose_option_body' => '为每个选定的设备项目选择一个选项。',
    'choose_option_title' => '需要选项',
    'detecting_location' => '正在检测位置...',
    'drag_marker' => '拖动标记以设置您的位置',
    'error_fetching_clubs' => '加载俱乐部时发生错误。',
    'ev_coming_up' => '即将开始',
    'ev_failed' => '加载活动失败。请重试。',
    'ev_finding' => '正在加载活动...',
    'ev_free' => '免费',
    'ev_full' => '已满',
    'ev_going' => '进行中',
    'ev_happening_now' => '正在举行',
    'ev_live' => '直播',
    'ev_none_hint' => '目前没有为您安排的进行中或已安排的活动。',
    'ev_none_title' => '暂无开放活动',
    'ev_open' => '开放',
    'ev_spots_left' => '剩余名额',
    'ev_starts_in' => '开始于',
    'ev_tba' => '待定',
    'ev_until' => '至',
    'ev_view_event' => '查看活动',
    'explore' => '探索',
    'failed_to_fetch_clubs' => '加载俱乐部失败。请重试。',
    'finding' => '正在查找您附近的内容...',
    'geolocation_not_supported' => '您的浏览器不支持地理定位。',
    'hero_eyebrow' => '发现附近',
    'hero_sub' => '您附近的俱乐部、教练、训练营等',
    'hero_title' => '找到您的完美匹配',
    'join_club' => '加入俱乐部',
    'km_away' => '公里外',
    'loading' => '加载中...',
    'location_access_denied' => '位置访问被拒绝。',
    'location_available' => '位置可用',
    'location_request_timed_out' => '位置请求超时。',
    'location_unavailable' => '位置信息不可用。',
    'members' => '成员',
    'na' => '不适用',
    'near_me' => '在我附近',
    'no_members_selected_body' => '请选择至少一名成员以继续。',
    'no_members_selected_title' => '未选择成员',
    'no_results' => '未找到结果',
    'no_results_hint' => '请调整您的搜索或位置',
    'packages' => '套餐',
    'packages_required_body' => '为每个选定的成员选择一个套餐。',
    'packages_required_title' => '需要套餐',
    'payment_required_body' => '上传付款截图或选择稍后付款。',
    'payment_required_title' => '需要付款凭证',
    'personal_trainer_badge' => '私人教练',
    'please_try_again' => '请重试。',
    'rating' => '评分',
    'registration_error_body' => '提交注册时出现问题。',
    'registration_failed_title' => '注册失败',
    'registration_submitted_body' => '您的注册已发送至俱乐部等待批准。',
    'registration_submitted_title' => '注册已提交',
    'reviews' => '评论',
    'search_placeholder' => '搜索俱乐部、教练...',
    'set_location' => '设置您的位置',
    'sports_club_badge' => '体育俱乐部',
    'trainers' => '教练',
    'unable_to_get_location' => '无法获取您的位置。',
    'view_details' => '查看详情',
    'years_exp' => '经验年数',

];
