<?php

/*
|--------------------------------------------------------------------------
| header — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/header.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'cart' => '购物车',
    'cart_soon' => '购物车即将上线',
    'chat' => '聊天',
    'clear_all' => '清空全部',
    'club_management' => '俱乐部管理',
    'just_now' => '刚刚',
    'mark_all_read' => '全部标为已读',
    'menu' => '菜单',
    'no_notifications' => '暂无通知',
    'notification' => '通知',
    'notifications' => '通知',
    'personal_desc' => '我的资料、预约、支付',
    'personal_view' => '个人视图',
    'scan_code_placeholder' => 'ABC123',
    'scan_foreign_host' => '该二维码指向其他网站，因此未自动打开。',
    'scan_hint' => '将摄像头对准二维码',
    'scan_no_camera' => '无法访问摄像头。',
    'scan_or_type' => '或输入6位验证码',
    'scan_qr' => '扫描二维码',
    'scan_unsupported' => '此浏览器不支持二维码扫描。',
    'switch_view' => '切换视图',

];
