<?php

/*
|--------------------------------------------------------------------------
| security — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/security.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'add_otp_desc' => '每次登录时，从您的认证应用中输入一次性代码。',
    'cancel' => '取消',
    'change_password' => '修改密码',
    'change_password_desc' => '更改密码时，所有其他活跃会话将被登出。',
    'code_placeholder' => '6位数字代码',
    'code_placeholder_long' => '6位数字代码或恢复代码',
    'confirm_new_password' => '确认新密码',
    'current_password' => '当前密码',
    'disable' => '关闭',
    'disable_2fa' => '关闭双重身份验证',
    'disable_confirm_desc' => '请输入当前认证代码（或恢复代码）以确认。',
    'disable_two_factor' => '关闭双重身份验证',
    'enable_2fa' => '开启双重身份验证',
    'lockdown_message' => '让我们锁定您的账户。',
    'new_password' => '新密码',
    'protected_message' => '您的账户保护良好。',
    'protected_with_app' => '已使用 Google Authenticator 保护。',
    'recovery_codes' => '恢复代码',
    'recovery_codes_desc' => '当您失去认证应用访问权限时的一次性备份代码。',
    'regenerate' => '重新生成',
    'regenerate_codes' => '重新生成代码',
    'regenerate_codes_title' => '重新生成代码',
    'regenerate_confirm_desc' => '您现有的恢复代码将失效。请输入您的认证代码以确认。',
    'security' => '安全',
    'security_challenge_back_to_login' => '返回登录页面',
    'security_challenge_backup_hint' => '请输入您8位字符的备份代码之一。',
    'security_challenge_subtitle' => '请输入您认证应用中的代码。',
    'security_challenge_title' => '双重身份验证',
    'security_challenge_use_authenticator' => '改用认证应用',
    'security_challenge_use_recovery' => '使用恢复代码',
    'security_challenge_verify' => '验证',
    'security_index_2fa_disabled_desc' => '为您的账户增加额外的安全层。',
    'security_index_2fa_enabled_desc' => '您的账户已使用 Google Authenticator 保护。',
    'security_index_2fa_title' => '双重身份验证',
    'security_index_change_password' => '修改密码',
    'security_index_change_password_desc' => '更改密码时，所有其他活跃会话将被登出。',
    'security_index_code_or_recovery_placeholder' => '6位数字代码或恢复代码',
    'security_index_code_placeholder' => '6位数字代码',
    'security_index_confirm_new_password' => '确认新密码',
    'security_index_current_password' => '当前密码',
    'security_index_disable_2fa' => '关闭双重身份验证',
    'security_index_disable_2fa_modal_desc' => '请输入当前认证代码（或恢复代码）以确认。',
    'security_index_disable_2fa_modal_title' => '关闭双重身份验证',
    'security_index_disabled' => '已关闭',
    'security_index_enable_2fa' => '开启双重身份验证',
    'security_index_enabled' => '已开启',
    'security_index_new_password' => '新密码',
    'security_index_recovery_codes' => '恢复代码',
    'security_index_recovery_codes_desc' => '如果您失去认证应用访问权限时的一次性备份代码。',
    'security_index_regen_codes_modal_desc' => '您现有的恢复代码将失效。请输入您的认证代码以确认。',
    'security_index_regen_codes_modal_title' => '重新生成恢复代码',
    'security_index_regenerate' => '重新生成',
    'security_index_regenerate_codes' => '重新生成代码',
    'security_index_subtitle' => '管理您的账户安全和双重身份验证',
    'security_index_title' => '安全设置',
    'security_index_update_password' => '更新密码',
    'security_recovery_codes_account_protected' => '您的账户现在受到保护。',
    'security_recovery_codes_copied' => '已复制！',
    'security_recovery_codes_copy_all' => '复制所有代码',
    'security_recovery_codes_heading_enabled' => '已启用双重身份验证',
    'security_recovery_codes_heading_new' => '新恢复代码',
    'security_recovery_codes_page_title' => '恢复代码',
    'security_recovery_codes_save_safe' => '请将这些恢复代码保存在安全的地方。',
    'security_recovery_codes_store_desc' => '每个代码只能使用一次。',
    'security_recovery_codes_store_safely' => '请妥善保存这些代码。',
    'security_recovery_codes_success_alert' => '您的账户已成功启用双重身份验证。',
    'security_setup_manual_entry' => '无法扫描？请在应用中手动输入此密钥：',
    'security_setup_step1_app_name' => 'Google Authenticator',
    'security_setup_step1_app_store' => 'App Store',
    'security_setup_step1_download' => '下载',
    'security_setup_step1_from' => '手机上的',
    'security_setup_step1_heading' => '安装 Google Authenticator',
    'security_setup_step1_or' => '或',
    'security_setup_step1_play_store' => 'Play Store',
    'security_setup_step2_heading' => '扫描二维码',
    'security_setup_step2_open' => '打开应用，点击',
    'security_setup_step2_scan_option' => '扫描二维码',
    'security_setup_step2_then_choose' => '，然后选择',
    'security_setup_step3_heading' => '确认代码',
    'security_setup_step3_subtitle' => '输入应用中显示的 6 位数字代码以验证设置。',
    'security_setup_subtitle' => '按照以下步骤使用 Google Authenticator 保护您的账户。',
    'security_setup_time_based' => '基于时间',
    'security_setup_time_based_prefix' => '选择',
    'security_setup_time_based_suffix' => '（在提示时）。',
    'security_setup_title' => '设置双重身份验证',
    'security_setup_verify_button' => '验证并启用',
    'title' => '安全设置',
    'two_factor_auth' => '双重身份验证',
    'two_factor_off' => '未开启双重身份验证',
    'two_factor_on' => '已开启双重身份验证',
    'update_password' => '更新密码',

];
