<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'belt_black' => 'سیاه',
    'belt_blue' => 'آبی',
    'belt_brown' => 'قهوه‌ای',
    'belt_purple' => 'بنفش',
    'belt_white' => 'سفید',
    'corner_blue' => 'آبی',
    'corner_white' => 'سفید',
    'division_label' => 'کلاس وزنی',
    'mat' => 'مات',
    'official_mat_organiser' => 'سازمان‌دهنده مات',
    'official_mat_organiser_hint' => 'نگهبان مات برای زمان‌بندی و فراخواندن رقبا.',
    'official_referee' => 'داور',
    'official_referee_hint' => 'برگزارکننده مسابقه در مات: شروع و توقف مسابقه، و اعلام هر امتیاز.',
    'official_scorekeeper' => 'نگهبان امتیاز',
    'official_scorekeeper_hint' => 'ورود امتیازها، مزایا و مجازات‌ها در جدول.',
    'official_timekeeper' => 'نگهبان زمان',
    'official_timekeeper_hint' => 'نگهبان ساعت: زمان مسابقه، توقف‌ها و زنگ نهایی.',
    'score_four' => '۴ امتیاز',
    'score_three' => '۳ امتیاز',
    'score_two' => '۲ امتیاز',
    'sport_label' => 'برازیلی ژی-جیتسو',
    'weigh_in' => 'وزن‌گیری',

];
