<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_arrange_draw' => '抽選を調整',
    'action_clear_draw' => '抽選が空です',
    'action_end_next_bout' => '次の試合を終了（テスト）',
    'action_generate_draw' => '抽選を生成',
    'board_heading' => '出場順序',
    'board_idle' => '試合中なし',
    'board_live' => 'ライブ',
    'board_on_deck' => '出場準備中',
    'board_stale' => '再接続中',
    'board_title' => 'マットボード— :event',
    'call_mat_tbc' => 'あなたのマット',
    'call_opponent_tbc' => '未定',
    'call_room_body' => ':mat · 試合 :bout · 対 :opponent',
    'call_room_title' => 'コールルームへ移動— :mat',
    'call_warmup_body' => ':ahead 個の試合が先にあります · およそ :minutes 分',
    'call_warmup_title' => 'ウォームアップ—まもなく :mat です',
    'day_mats' => '日 :day: :count マット',
    'draw_arranged' => '抽選が更新されました 🥋',
    'draw_cleared' => '抽選が空になりました—すべての参加者はリストに戻っています',
    'draw_final' => '大会が開始されました—抽選は最終版であり、再生成することはできません。',
    'draw_generated' => '暫定抽選が生成されました',
    'end_next_bout_done' => ':winner が :court で勝ちました。そのマットのスクリーンに通知が送られました。',
    'end_next_bout_none' => '終了できる試合がありません—すべての予約された試合はフィーダーの待機中です。',
    'ended_locked' => 'この大会は終了しました—結果は最終です。',
    'gate_no_division' => 'あなたの体重級はこの大会の部門の一つではありませんので、このイベントに参加する資格はありません。',
    'gate_no_division_spectator' => 'あなたの体重級はこの大会の部門の一つではありませんので、参加することはできませんが、観客としてご参加いただけます。',
    'gate_no_profile' => 'プロフィールに性別と生年月日を追加して、重量級に配置できるようにしてください。',
    'gate_no_weight' => '体重を健康プロフィールに追加して、重量級に配置できるようにしてください。',
    'next_up_ahead' => '試合が残っています',
    'next_up_done' => '今日はこれで終了です。',
    'next_up_estimate' => '推定、マットと移動',
    'next_up_finished' => '終了',
    'next_up_none' => '現在スケジュールされていません。',
    'next_up_opponent_tbc' => '対戦相手待機中',
    'next_up_squad' => '私のチーム',
    'next_up_title' => '次の試合',
    'next_up_you_are_next' => '次が来ました—マットへ移動',
    'notify_draw_body' => '対戦相手、マット、および試合番号が公開されました。',
    'notify_draw_title' => '抽選が発表されました— :title',
    'notify_weigh_in_body' => '公式体重計測 :time, :place。重量級の制限に達する必要があります。',
    'notify_weigh_in_title' => '明日の体重計測— :title',
    'result_body_done' => '今日はこれで最後の試合です。',
    'result_body_next' => '次: :round :mat で、およそ :minutes 分',
    'result_loss_title' => '試合終了',
    'result_win_title' => 'あなたの勝ち 🎉',
    'roster_registered' => '登録済み',
    'roster_unclassified' => '未分類',
    'type_label' => '空手大会',

];
