<?php

/*
|--------------------------------------------------------------------------
| auth — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/auth.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'auth_desktop_login_check_inbox_after' => '。クリックしてログインしてください。',
    'auth_desktop_login_check_inbox_before' => 'ログインリンクを送信しました',
    'auth_desktop_login_check_inbox_title' => '受信箱をご確認ください',
    'auth_desktop_login_email_me_link' => 'ログインリンクをメールで送信',
    'auth_desktop_login_email_placeholder' => '電話番号またはメールアドレス',
    'auth_desktop_login_forgot_password' => 'パスワードをお忘れですか？',
    'auth_desktop_login_magic_hint' => 'パスワードがありませんか？一度限りのログインリンクをメールでお送りします。',
    'auth_desktop_login_password_placeholder' => 'パスワード',
    'auth_desktop_login_register' => 'アカウントを作成',
    'auth_desktop_login_remember_me' => 'ログイン状態を保持',
    'auth_desktop_login_resend_verification' => '確認メールを再送信',
    'auth_desktop_login_sign_in' => 'ログイン',
    'auth_desktop_login_subtitle' => 'おかえりなさい！続けるにはログインしてください',
    'auth_desktop_login_tab_link' => 'ログインリンク',
    'auth_desktop_login_tab_password' => 'パスワード',
    'auth_desktop_login_unverified_hint' => 'メールが届かない、または期限切れになりましたか？',
    'auth_desktop_login_unverified_title' => 'メールアドレスが確認されていません',
    'auth_desktop_login_your_email_placeholder' => 'あなたのメールアドレス',
    'auth_forgot_password_back_to_login' => 'ログインに戻る',
    'auth_forgot_password_email_placeholder' => 'メール',
    'auth_forgot_password_send_reset_link' => 'パスワードリセットリンクを送信',
    'auth_forgot_password_subtitle' => '心配ありません。メールアドレスを入力してください。リセットリンクをお送りします。',
    'auth_forgot_password_title' => 'パスワードをお忘れですか？',
    'auth_register_birthdate' => '生年月日',
    'auth_register_confirm_password' => 'パスワードの確認',
    'auth_register_email' => 'メールアドレス',
    'auth_register_full_name' => '氏名',
    'auth_register_joining_club' => '参加するクラブ',
    'auth_register_mobile_number' => '携帯電話番号',
    'auth_register_nationality' => '国籍',
    'auth_register_password' => 'パスワード',
    'auth_register_submit' => '登録',
    'auth_register_subtitle' => 'アカウントを作成',
    'auth_register_wizard_err_generic_post' => '）。もう一度お試しください。',
    'auth_register_wizard_err_generic_pre' => '問題が発生しました（エラー',
    'auth_register_wizard_err_network' => 'ネットワークエラー。接続を確認してもう一度お試しください。',
    'auth_register_wizard_err_session_expired' => 'セッションの有効期限が切れました。ページを更新してもう一度お試しください。',
    'auth_register_wizard_ph_child_name' => '子供の氏名',
    'auth_register_wizard_ph_email' => 'メールアドレス',
    'auth_register_wizard_ph_full_name' => '氏名',
    'auth_register_wizard_ph_health' => '健康状態についてご記入ください',
    'auth_register_wizard_ph_mobile' => '電話番号',
    'auth_register_wizard_rel_daughter' => '娘',
    'auth_register_wizard_rel_member_fallback' => '家族',
    'auth_register_wizard_rel_other' => 'その他',
    'auth_register_wizard_rel_son' => '息子',
    'auth_register_wizard_rel_spouse' => '配偶者',
    'auth_register_wizard_terms_changes_body' => 'これらの規約は随時更新される場合があります。サービスの継続使用は規約の受け入れを意味します。',
    'auth_register_wizard_terms_changes_title' => '利用規約の変更',
    'auth_register_wizard_terms_conduct_body' => '会員はクラブの規則に従い、スタッフや他の会員に対して尊重の態度を示すべきです。',
    'auth_register_wizard_terms_conduct_title' => '行動規範',
    'auth_register_wizard_terms_confirm' => '以下のチェックボックスにチェックすることで、これらの規約を読み、同意したことを確認します。',
    'auth_register_wizard_terms_default_intro' => ':clubへようこそ！登録することで、以下の条件に同意するものとします：',
    'auth_register_wizard_terms_medical_body' => '参加に影響を与える可能性のある医療または健康状態を必ず開示してください。',
    'auth_register_wizard_terms_medical_title' => '医療・健康',
    'auth_register_wizard_terms_membership_body' => '登録が承認され、支払い（必要な場合）が確認された時点で会員資格が開始されます。',
    'auth_register_wizard_terms_membership_title' => '会員',
    'auth_register_wizard_terms_payment_body' => '「後で支払う」オプションが選択されていない限り、すべての支払いは登録時に行われます。',
    'auth_register_wizard_terms_payment_title' => '支払い',
    'auth_register_wizard_terms_privacy_body' => '個人情報は会員管理のみに使用され、同意なしに共有されることはありません。',
    'auth_register_wizard_terms_privacy_title' => 'プライバシー',
    'auth_reset_password_back_to_login' => 'ログインに戻る',
    'auth_reset_password_confirm_password_label' => '新しいパスワードの確認',
    'auth_reset_password_email_label' => 'メールアドレス',
    'auth_reset_password_new_password_label' => '新しいパスワード',
    'auth_reset_password_submit' => 'パスワードをリセット',
    'auth_reset_password_title' => 'パスワードをリセット',
    'auth_verify_email_check_inbox_line1' => '確認リンクをメールアドレスに送信しました。',
    'auth_verify_email_check_inbox_line2' => 'アカウントを確認するにはリンクをクリックしてください。',
    'auth_verify_email_check_inbox_title' => 'メールをご確認ください',
    'auth_verify_email_didnt_receive' => 'メールが届きませんか？',
    'auth_verify_email_fresh_link_sent' => '新しい確認リンクがメールアドレスに送信されました。',
    'auth_verify_email_go_to_app' => '続ける',
    'auth_verify_email_one_step_away' => '参加のための最後のステップ',
    'auth_verify_email_redirecting_prefix' => 'リダイレクトまで',
    'auth_verify_email_redirecting_suffix' => '秒...',
    'auth_verify_email_resend_button' => '確認メールを再送信',
    'auth_verify_email_sign_out' => 'サインアウト',
    'auth_verify_email_verified_body' => 'メールアドレスが正常に確認されました。',
    'auth_verify_email_verified_title' => 'メールアドレスが確認されました！',
    'auth_verify_email_wrong_account' => '間違ったアカウントですか？',
    'choose_not_you' => '別の番号またはメールアドレスを使用',
    'choose_sub' => 'この番号を使用している人が複数います。ログインする人をタップしてください。',
    'choose_title' => '誰がログインしていますか？',
    'club_waiting' => 'あなたのクラブをお待ちしています。行ってみましょう。',
    'create_account' => 'アカウントを作成',
    'didnt_receive' => 'メールが届かない、または期限切れになりましたか？',
    'email' => 'メールアドレス',
    'email_not_verified' => 'メールアドレスが確認されていません',
    'email_or_phone' => '電話番号またはメールアドレス',
    'forgot_password' => 'パスワードをお忘れですか？',
    'hide_password' => 'パスワードを隠す',
    'magic_cta' => 'ログインリンクをメールで送信',
    'magic_prompt' => 'パスワードがありませんか？一度限りのログインリンクをメールでお送りします。',
    'magic_sent_body' => 'そのメールアドレスにアカウントが存在する場合、ログインリンクを送信しました。メール内のボタンをクリックしてログインしてください — パスワードは必要ありません。',
    'magic_sent_title' => '受信箱をご確認ください',
    'new_to_takeone' => 'TAKEONEに初めての方ですか？',
    'or' => 'または',
    'password' => 'パスワード',
    'remember_me' => 'ログイン状態を保持',
    'resend_verification' => '確認メールを再送信',
    'show_password' => 'パスワードを表示',
    'sign_in' => 'ログイン',
    'tab_magic' => 'ログインリンク',
    'tab_password' => 'パスワード',
    'welcome_back' => 'おかえりなさい',

];
