<?php

/*
|--------------------------------------------------------------------------
| errors — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/errors.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    '429_body' => 'このページを使用している人が多く、数秒間新しいリクエストを一時停止しています。何も問題はおきていませんし、入力した内容は失われていません。',
    '429_retry' => '{1}:seconds秒後に再度お試しください|[2,*]:seconds秒後に再度お試しください',
    '429_retry_action' => '再度お試しください',
    '429_title' => 'お待ちください',

];
