<?php

/*
|--------------------------------------------------------------------------
| explore — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/explore.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'apply_location' => '位置情報を適用',
    'book_session' => 'セッションを予約',
    'cat_all' => 'すべて',
    'cat_clubs' => 'クラブ',
    'cat_events' => 'イベント',
    'cat_food_plans' => '食事プラン',
    'cat_nutrition' => '栄養',
    'cat_physiotherapy' => '理学療法',
    'cat_shops' => 'ショップ',
    'cat_supplements' => 'サプリメント',
    'cat_trainers' => 'トレーナー',
    'cat_venues' => '会場',
    'choose_option_body' => '選択した各機材アイテムにオプションを選択してください。',
    'choose_option_title' => 'オプションが必要です',
    'detecting_location' => '位置情報を検出中...',
    'drag_marker' => 'マーカーをドラッグして位置情報を設定',
    'error_fetching_clubs' => 'クラブの読み込み中にエラーが発生しました。',
    'ev_coming_up' => '今後開催',
    'ev_failed' => 'イベントの読み込みに失敗しました。もう一度お試しください。',
    'ev_finding' => 'イベントを読み込み中...',
    'ev_free' => '無料',
    'ev_full' => '満員',
    'ev_going' => '進行中',
    'ev_happening_now' => '今開催中',
    'ev_live' => 'ライブ',
    'ev_none_hint' => '現在、実施中または予定されているイベントはありません',
    'ev_none_title' => '開催予定のイベントはありません',
    'ev_open' => '受付中',
    'ev_spots_left' => '残り枠',
    'ev_starts_in' => '開始まで',
    'ev_tba' => '日程未定',
    'ev_until' => 'まで',
    'ev_view_event' => 'イベントを見る',
    'explore' => '探す',
    'failed_to_fetch_clubs' => 'クラブの読み込みに失敗しました。もう一度お試しください。',
    'finding' => 'あなたに近いものを検索中...',
    'geolocation_not_supported' => 'お使いのブラウザは位置情報の取得をサポートしていません。',
    'hero_eyebrow' => '近隣を検索',
    'hero_sub' => 'あなたに近いクラブ、トレーナー、クラインิกなど',
    'hero_title' => 'あなたの perfect なフィットを見つける',
    'join_club' => 'クラブに参加',
    'km_away' => 'km先',
    'loading' => '読み込み中...',
    'location_access_denied' => '位置情報へのアクセスが拒否されました。',
    'location_available' => '位置情報が利用可能',
    'location_request_timed_out' => '位置情報の要求がタイムアウトしました。',
    'location_unavailable' => '位置情報が利用できません。',
    'members' => 'メンバー',
    'na' => '該当なし',
    'near_me' => '近隣',
    'no_members_selected_body' => '少なくとも1人のメンバーを選択してください。',
    'no_members_selected_title' => 'メンバーが選択されていません',
    'no_results' => '結果が見つかりません',
    'no_results_hint' => '検索条件または位置情報を調整してみてください',
    'packages' => 'パッケージ',
    'packages_required_body' => '選択した各メンバーにパッケージを選択してください。',
    'packages_required_title' => 'パッケージが必要です',
    'payment_required_body' => '支払いスクリーンショットをアップロードするか、後で支払うを選択してください。',
    'payment_required_title' => '支払い証明が必要です',
    'personal_trainer_badge' => 'パーソナルトレーナー',
    'please_try_again' => 'もう一度お試しください。',
    'rating' => '評価',
    'registration_error_body' => '登録の送信中に問題が発生しました。',
    'registration_failed_title' => '登録に失敗しました',
    'registration_submitted_body' => 'あなたの登録はクラブに送信され、承認待ちです。',
    'registration_submitted_title' => '登録が送信されました',
    'reviews' => 'レビュー',
    'search_placeholder' => 'クラブ、トレーナーを検索...',
    'set_location' => '位置情報を設定',
    'sports_club_badge' => 'スポーツクラブ',
    'trainers' => 'トレーナー',
    'unable_to_get_location' => '位置情報を取得できません。',
    'view_details' => '詳細を表示',
    'years_exp' => '経験年数',

];
