<?php

/*
|--------------------------------------------------------------------------
| header — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/header.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'cart' => 'カート',
    'cart_soon' => 'カートは近日登場',
    'chat' => 'チャット',
    'clear_all' => 'すべてクリア',
    'club_management' => 'クラブ管理',
    'just_now' => 'たった今',
    'mark_all_read' => 'すべて既読にする',
    'menu' => 'メニュー',
    'no_notifications' => '通知はありません',
    'notification' => '通知',
    'notifications' => '通知',
    'personal_desc' => 'マイプロフィール、予約、支払い',
    'personal_view' => '個人ビュー',
    'scan_code_placeholder' => 'ABC123',
    'scan_foreign_host' => 'そのQRコードは別のウェブサイトを指しているため、開かれませんでした。',
    'scan_hint' => 'カメラをQRコードに向けてください',
    'scan_no_camera' => 'カメラにアクセスできませんでした。',
    'scan_or_type' => '6文字のコードを入力',
    'scan_qr' => 'QRコードをスキャン',
    'scan_unsupported' => 'このブラウザではQRスキャンがサポートされていません。',
    'switch_view' => '表示切り替え',

];
