<?php

/*
|--------------------------------------------------------------------------
| security — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/security.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'add_otp_desc' => 'ログイン時に認証アプリのワンタイムコードを入力してください。',
    'cancel' => 'キャンセル',
    'change_password' => 'パスワード変更',
    'change_password_desc' => '変更すると他のすべてのアクティブセッションがログアウトされます。',
    'code_placeholder' => '6桁のコード',
    'code_placeholder_long' => '6桁のコードまたはリカバリーコード',
    'confirm_new_password' => '新しいパスワードの確認',
    'current_password' => '現在のパスワード',
    'disable' => '無効にする',
    'disable_2fa' => '2FAを無効にする',
    'disable_confirm_desc' => '確認のために現在の認証コード（またはリカバリーコード）を入力してください。',
    'disable_two_factor' => '二段階認証を無効にする',
    'enable_2fa' => '2FAを有効にする',
    'lockdown_message' => 'アカウントを強化しましょう。',
    'new_password' => '新しいパスワード',
    'protected_message' => 'アカウントは十分に保護されています。',
    'protected_with_app' => 'Google Authenticatorで保護されています。',
    'recovery_codes' => 'リカバリーコード',
    'recovery_codes_desc' => '認証アプリのアクセスを失った場合の一次性バックアップコードです。',
    'regenerate' => '再生成',
    'regenerate_codes' => 'コードを再生成する',
    'regenerate_codes_title' => 'コードを再生成する',
    'regenerate_confirm_desc' => '既存のリカバリーコードは機能しなくなります。認証コードを入力して確認してください。',
    'security' => 'セキュリティ',
    'security_challenge_back_to_login' => 'ログイン画面に戻る',
    'security_challenge_backup_hint' => '8文字のバックアップコードのいずれかを入力してください。',
    'security_challenge_subtitle' => '認証アプリからコードを入力してください。',
    'security_challenge_title' => '二段階認証',
    'security_challenge_use_authenticator' => '認証アプリを使用',
    'security_challenge_use_recovery' => 'リカバリーコードを使用',
    'security_challenge_verify' => '確認',
    'security_index_2fa_disabled_desc' => 'アカウントに追加のセキュリティ層を追加します。',
    'security_index_2fa_enabled_desc' => 'アカウントはGoogle Authenticatorで保護されています。',
    'security_index_2fa_title' => '二段階認証',
    'security_index_change_password' => 'パスワード変更',
    'security_index_change_password_desc' => 'パスワードを変更すると他のすべてのアクティブセッションがログアウトされます。',
    'security_index_code_or_recovery_placeholder' => '6桁のコードまたはリカバリーコード',
    'security_index_code_placeholder' => '6桁のコード',
    'security_index_confirm_new_password' => '新しいパスワードの確認',
    'security_index_current_password' => '現在のパスワード',
    'security_index_disable_2fa' => '2FAを無効にする',
    'security_index_disable_2fa_modal_desc' => '確認のために現在の認証コード（またはリカバリーコード）を入力してください。',
    'security_index_disable_2fa_modal_title' => '二段階認証を無効にする',
    'security_index_disabled' => '無効',
    'security_index_enable_2fa' => '2FAを有効にする',
    'security_index_enabled' => '有効',
    'security_index_new_password' => '新しいパスワード',
    'security_index_recovery_codes' => 'リカバリーコード',
    'security_index_recovery_codes_desc' => '認証アプリのアクセスを失った場合の一次性バックアップコードです。',
    'security_index_regen_codes_modal_desc' => '既存のリカバリーコードは無効になります。認証コードを入力して確認してください。',
    'security_index_regen_codes_modal_title' => 'リカバリーコードを再生成する',
    'security_index_regenerate' => '再生成',
    'security_index_regenerate_codes' => 'コードを再生成する',
    'security_index_subtitle' => 'アカウントのセキュリティと二段階認証を管理',
    'security_index_title' => 'セキュリティ設定',
    'security_index_update_password' => 'パスワードを更新',
    'security_recovery_codes_account_protected' => 'アカウントは現在保護されています。',
    'security_recovery_codes_copied' => 'コピーしました！',
    'security_recovery_codes_copy_all' => 'すべてのコードをコピー',
    'security_recovery_codes_heading_enabled' => '二段階認証が有効化されました',
    'security_recovery_codes_heading_new' => '新しい回復コード',
    'security_recovery_codes_page_title' => '回復コード',
    'security_recovery_codes_save_safe' => 'これらの回復コードを安全な場所に保存してください。',
    'security_recovery_codes_store_desc' => '各コードは一度しか使用できません。',
    'security_recovery_codes_store_safely' => 'これらのコードを安全に保管してください。',
    'security_recovery_codes_success_alert' => '二段階認証がアカウントで正常に有効化されました。',
    'security_setup_manual_entry' => 'スキャンできませんか？アプリでこのキーを手動で入力してください：',
    'security_setup_step1_app_name' => 'Google認証アプリ',
    'security_setup_step1_app_store' => 'App Store',
    'security_setup_step1_download' => 'ダウンロード',
    'security_setup_step1_from' => 'お使いの携帯電話から',
    'security_setup_step1_heading' => 'Google認証アプリをインストール',
    'security_setup_step1_or' => 'または',
    'security_setup_step1_play_store' => 'Play Store',
    'security_setup_step2_heading' => 'QRコードをスキャン',
    'security_setup_step2_open' => 'アプリを開き、タップ',
    'security_setup_step2_scan_option' => 'QRコードをスキャン',
    'security_setup_step2_then_choose' => 'を選択し、',
    'security_setup_step3_heading' => 'コードを確認',
    'security_setup_step3_subtitle' => 'アプリに表示される6桁のコードを入力して設定を確認してください。',
    'security_setup_subtitle' => '以下の手順に従って、Google認証アプリでアカウントを保護してください。',
    'security_setup_time_based' => '時間ベース',
    'security_setup_time_based_prefix' => '選択',
    'security_setup_time_based_suffix' => 'と表示されたときに。',
    'security_setup_title' => '二段階認証の設定',
    'security_setup_verify_button' => '確認して有効化',
    'title' => 'セキュリティ設定',
    'two_factor_auth' => '二段階認証',
    'two_factor_off' => '二段階認証が無効',
    'two_factor_on' => '二段階認証が有効',
    'update_password' => 'パスワードを更新',

];
