<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_arrange_draw' => 'ترتيب القرعة',
    'action_clear_draw' => 'إفراغ القرعة',
    'action_end_next_bout' => 'إنهاء النزال التالي',
    'action_generate_draw' => 'إنشاء القرعة',
    'call_mat_tbc' => 'بساطك',
    'call_opponent_tbc' => 'يُحدد لاحقًا',
    'call_room_body' => ':mat · نزال :bout · ضد :opponent',
    'call_room_title' => 'توجّه إلى غرفة النداء — :mat',
    'call_warmup_body' => ':ahead نزال قبلك · حوالي :minutes دقيقة',
    'call_warmup_title' => 'استعد للإحماء — دورك قريبًا على :mat',
    'day_mats' => 'اليوم :day: :count بساط',
    'draw_arranged' => 'تم تحديث القرعة 🥋',
    'draw_cleared' => 'تم إفراغ القرعة — عاد جميع المشاركين إلى القائمة',
    'draw_final' => 'بدأت البطولة — القرعة نهائية ولا يمكن إعادة إنشائها.',
    'draw_generated' => 'تم إنشاء القرعة المبدئية',
    'end_next_bout_done' => 'فاز :winner على :court. تم إبلاغ الشاشات على ذلك البساط.',
    'end_next_bout_none' => 'لا يوجد نزال جاهز للإنهاء — كل نزال في الطابور ما زال ينتظر نتيجة سابقة.',
    'ended_locked' => 'انتهت هذه البطولة — نتائجها نهائية.',
    'gate_no_division' => 'فئة وزنك ليست ضمن فئات هذه البطولة، لذا لا يمكنك المشاركة كمتسابق في هذا الحدث.',
    'gate_no_division_spectator' => 'فئة وزنك ليست ضمن فئات هذه البطولة، لذا لا يمكنك المنافسة — لكن يمكنك الحضور كمشاهد.',
    'gate_no_profile' => 'أضف جنسك وتاريخ ميلادك إلى ملفك الشخصي حتى نتمكن من تحديد فئة وزنك.',
    'gate_no_weight' => 'أضف وزنك الحالي إلى ملفك الصحي حتى نتمكن من تحديد فئة وزنك.',
    'notify_draw_body' => 'تم سحب قرعة فئتك. افتح الحدث لمعرفة خصمك والبساط ورقم النزال.',
    'notify_draw_title' => 'صدرت القرعة — :title',
    'notify_weigh_in_body' => 'يفتح الوزن الرسمي الساعة :time في :place. أحضر بطاقتك الشخصية.',
    'notify_weigh_in_title' => 'الوزن الرسمي غدًا — :title',
    'result_body_done' => 'كان ذلك آخر نزال لك اليوم.',
    'result_body_next' => 'التالي: :round على :mat، حوالي :minutes دقيقة',
    'result_loss_title' => 'انتهى النزال',
    'result_win_title' => 'لقد فزت 🎉',
    'roster_registered' => 'مسجل',
    'roster_unclassified' => 'غير مصنف',
    'type_label' => 'بطولة جوجيتسو',

];
