<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_add_entrants' => 'Kesî lê zêde bike',
    'action_close' => 'Dawî bê',
    'action_queue_bout' => 'Lêkolînê li lîsteyê bide',
    'action_remove_entrant' => 'Kesî rakirin',
    'action_set_mats' => 'Matên saz bike',
    'action_unqueue_bout' => 'Lêkolînê li lîsteyê rakirin',
    'bout_fought' => 'Vê lêkolînê hatiye xebitandin.',
    'bout_queued' => 'Li lîsteyê ye.',
    'bout_removed' => 'Li lîsteyê hatiye rakirin.',
    'console_add_people' => 'Kesî lê zêde bike',
    'console_add_selected' => 'Li ser matê :n zêde bike',
    'console_bouts_today' => ':n îro',
    'console_clear_pick' => 'Paqij bike',
    'console_closed' => 'Vê lêkolînê hatiye bidî.',
    'console_end_confirm' => 'Vê lêkolînê bidî? Tîkîna lêkolînê rawestîne û sesîyonê li serî dîtin.',
    'console_end_session' => 'Sesîyonê bidî',
    'console_floor' => 'Kî ne',
    'console_floor_hint' => 'Du kesî li ser matê bide',
    'console_fought' => 'Lêkolînê hatiye xebitandin',
    'console_fought_empty' => 'Hîn lêkolîn nîne.',
    'console_mat_count' => 'Tê xebitandin :n',
    'console_mats' => 'Mat',
    'console_mats_label' => 'Matên tê xebitandin',
    'console_no_members' => 'Kesî nîne.',
    'console_open_table' => 'Tîkîna lêkolînê',
    'console_pair_hint' => 'Du kesî li ser matê bide',
    'console_pick_blue' => 'Kûrê şîn',
    'console_pick_red' => 'Kûrê reş',
    'console_queue' => 'Lîsteya lêkolînê',
    'console_queue_empty' => 'Hîn lêkolîn li ser matê nîne.',
    'console_queue_it' => 'Lêkolînê li lîsteyê bide',
    'console_screens' => 'Ekranên salona',
    'console_search_members' => 'Lêkolînê lê bigere',
    'console_table_needs_bout' => 'Lêkolînê li ser matê bide û tîkîna lêkolînê vekê.',
    'entrant_queued' => 'Li ser lêkolînê nîne ku hatiye xebitandin.',
    'entrant_removed' => 'Li ser matê hatiye rakirin.',
    'entrants_added' => 'Li ser matê hatiye zêde kirin.',
    'label' => 'Sparring',
    'launch_bouts_n' => ':n lêkolîn',
    'launch_eyebrow' => 'Tîkîna lêkolînê',
    'launch_lead' => 'Du kesî li ser matê bide û salona tîkînê dîtin. Tîkînê nîne, têketin nîne — vê vêr bike, dema lêkolînê bidî.',
    'launch_mats' => 'Çend mat',
    'launch_minutes' => 'Dirêjahiya lêkolînê',
    'launch_minutes_n' => ':n xulek',
    'launch_no_sport' => 'Vê klubê hîn spòrtek nîne ku tîkînê li ser matê bê.',
    'launch_open_since' => 'Ji :time ve vekê',
    'launch_past' => 'Sesîyonên berê',
    'launch_past_none' => 'Hîn sesîyon nîne.',
    'launch_resume' => 'Sesîyonê îro vekê',
    'launch_running' => 'Niha tê xebitandin',
    'launch_sport' => 'Çi spòrt',
    'launch_start' => 'Lêkolînê dest pê bike',
    'launch_title' => 'Sparring',
    'mat_n' => 'Mat :n',
    'mats_saved' => 'Matên hatiye nûvekirin.',
    'same_person' => 'Du kesî cuda bide.',
    'session_closed' => 'Vê lêkolînê hatiye bidî.',
    'session_ended' => 'Sesîyonê hatiye bidî.',
    'session_title' => 'Sparring · :date',
    'unknown_entrant' => 'Her du kûrê li ser matê pêşî bê.',
    'unknown_mat' => 'Vê matê nîne ku vê lêkolînê tê xebitandin.',

];
