<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'corner_chung' => 'CHUNG',
    'corner_hong' => 'HONG',
    'division_label' => 'Categoria de peso',
    'mat' => 'Pista',
    'official_center_referee' => 'Árbitro Central',
    'official_center_referee_hint' => 'Dirige a luta no centro da pista.',
    'official_corner_judge' => 'Juiz do canto :n',
    'official_corner_judge_hint' => 'Avalia de um canto da pista.',
    'official_court_supervisor' => 'Supervisor da Pista',
    'official_court_supervisor_hint' => 'Supervisiona a pista e seus oficiais.',
    'official_review_jury' => 'Júri de Revisão',
    'official_review_jury_hint' => 'Julga pedidos de revisão por vídeo.',
    'official_table_recorder' => 'Guarda de Mesa',
    'official_table_recorder_hint' => 'Mantém o registro oficial na mesa.',
    'official_timekeeper' => 'Cronometrista',
    'official_timekeeper_hint' => 'Controla o relógio: tempo de round, paradas e sino.',
    'score_body_kick' => 'Chute de corpo',
    'score_head_kick' => 'Chute de cabeça',
    'score_punch' => 'Soco',
    'score_turning_body' => 'Chute de corpo giratório',
    'score_turning_head' => 'Chute de cabeça giratório',
    'sport_label' => 'Taekwondo',
    'weigh_in' => 'Peso',

];
