<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_add_entrants' => 'Shto persona',
    'action_close' => 'Mbyll sesionin',
    'action_queue_bout' => 'Shto një boll',
    'action_remove_entrant' => 'Largo personin',
    'action_set_mats' => 'Vendos matra',
    'action_unqueue_bout' => 'Largo një boll',
    'bout_fought' => 'Ky boll është tashmë luajtur.',
    'bout_queued' => 'U shtua në radhë.',
    'bout_removed' => 'U largua nga radha.',
    'console_add_people' => 'Shto persona',
    'console_add_selected' => 'Shto :n në shtëpi',
    'console_bouts_today' => ':n sot',
    'console_clear_pick' => 'Pastro',
    'console_closed' => 'Ky sesion është mbaruar.',
    'console_end_confirm' => 'Mbyll këtë sesion sparring? Tabela e rezultateve ndalohet dhe sesioni arkivohet.',
    'console_end_session' => 'Mbyll sesionin',
    'console_floor' => 'Kush është këtu',
    'console_floor_hint' => 'Prek dy për t\'i përparesur',
    'console_fought' => 'U luajt',
    'console_fought_empty' => 'Ende asnjë boll.',
    'console_mat_count' => 'Po xhiron :n',
    'console_mats' => 'Matra',
    'console_mats_label' => 'Matra në xhirim',
    'console_no_members' => 'Asnjë anëtar i gjetur.',
    'console_open_table' => 'Tabela e rezultateve',
    'console_pair_hint' => 'Zgjidh dy persona nga shtëpi',
    'console_pick_blue' => 'Këndi i blu',
    'console_pick_red' => 'Këndi i kuq',
    'console_queue' => 'Radha',
    'console_queue_empty' => 'Asnjë gjë në radhë në këtë mat.',
    'console_queue_it' => 'Shto këtë boll',
    'console_screens' => 'Ekrane të holli',
    'console_search_members' => 'Kërko anëtarë',
    'console_table_needs_bout' => 'Shto një boll në këtë mat për të hapur tabelën e rezultateve.',
    'entrant_queued' => 'Ata janë në një boll që nuk është luajtur ende.',
    'entrant_removed' => 'U largua nga shtëpi.',
    'entrants_added' => 'U shtua në shtëpi.',
    'label' => 'Sparring',
    'launch_bouts_n' => ':n bolla',
    'launch_eyebrow' => 'Tabelë rezultatish',
    'launch_lead' => 'Vendos dy persona në një mat dhe holli shikon rezultatin. Asnjë draw, as një hyrje — hapeni tani, mbylleni kur mbaron entrenimi.',
    'launch_mats' => 'Sa matra',
    'launch_minutes' => 'Gjatësia e bollit',
    'launch_minutes_n' => ':n min',
    'launch_no_sport' => 'Ky klubi nuk ka ende asnjë sport me tabelë rezultatish në mat.',
    'launch_open_since' => 'Hapur që prej :time',
    'launch_past' => 'Sesione të mëparshme',
    'launch_past_none' => 'Ende asnjë sesion.',
    'launch_resume' => 'Hap sesionin e sotme',
    'launch_running' => 'Po xhiron tani',
    'launch_sport' => 'Çfarë sporti',
    'launch_start' => 'Filloni sparring',
    'launch_title' => 'Sparring',
    'mat_n' => 'Mat :n',
    'mats_saved' => 'Matra u përditësuan.',
    'same_person' => 'Zgjidh dy persona të ndryshme.',
    'session_closed' => 'Ky sesion është mbaruar.',
    'session_ended' => 'Sesioni mbaroi.',
    'session_title' => 'Sparring · :date',
    'unknown_entrant' => 'Të dy këndet duhet të jenë në shtëpi së pari.',
    'unknown_mat' => 'Kjo nuk është një mat që kjo sesion xhiron.',

];
