<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'add_language' => 'भाषा जोड़ें',
    'choose_language' => 'भाषा चुनें',
    'complete' => ':done के :total में',
    'continue_anyway' => 'मूल भाषा में जारी रखें',
    'edited_by_you' => 'आपके द्वारा संपादित',
    'field_about' => 'इस घटना के बारे में',
    'field_cta' => 'बटन का पाठ',
    'field_division' => 'विभाजन',
    'field_fee' => 'शुल्क पंक्ति',
    'field_level' => 'स्तर',
    'field_location' => 'स्थान',
    'field_prize' => 'पुरस्कार',
    'field_requirement' => 'आवश्यकता',
    'field_ribbon' => 'रिबन',
    'field_title' => 'शीर्षक',
    'interface_note' => 'यह घटना :language में है। बटन और लेबल अंग्रेज़ी में रहेंगे।',
    'languages' => 'भाषाएं',
    'languages_sub' => 'प्रत्येक भाषा में यह घटना क्या कहती है',
    'machine' => 'स्वचालित',
    'more_languages' => 'अन्य भाषा',
    'needs_review' => 'समीक्षा की आवश्यकता है',
    'needs_review_note' => 'मूल इसके बाद बदल गया था।',
    'no_language_found' => 'इससे कोई मेल नहीं है।',
    'no_provider' => 'कोई AI प्रदाता कॉन्फ़िगर नहीं है। अनुवाद लिखने से पहले Admin → AI Providers में एक जोड़ें।',
    'not_translated' => 'अभी तक अनुवाद नहीं किया गया',
    'nothing_yet' => 'अभी तक कोई ने इस घटना को अन्य भाषा में पढ़ा नहीं है।',
    'nothing_yet_note' => 'जैसे ही कोई सार्वजनिक पृष्ठ पर एक चुनता है, तो यह लिखा जाता है और रखा जाता है।',
    'preparing' => ':language तैयार किया जा रहा है…',
    'preparing_failed' => 'हम अभी :language को तैयार नहीं कर पाए। मूल दिखाया जा रहा है।',
    'preparing_note' => 'यह घटना :language में लिखी गई है। यह केवल एक बार होती है — आपके बाद सभी को तुरंत मिल जाएगा।',
    'queued' => 'कतार में। यह एक पल में तैयार हो जाएगा।',
    'read_in' => 'इसे इस भाषा में पढ़ें',
    'remove_language' => 'इस भाषा को हटाएं',
    'remove_language_confirm' => 'क्या :language हटाएं? आपके इसके संशोधन भी मिट जाएंगे। मशीन अनुवाद को पुनः उत्पन्न किया जा सकता है; आपके संपादन नहीं।',
    'removed' => 'भाषा हटाई गई।',
    'retranslate' => 'फिर से अनुवाद करें',
    'saved' => 'सहेजा गया।',
    'search_languages' => 'भाषाएं खोजें',
    'source_language' => ':language में लिखा गया',
    'translated_by_ai' => 'स्वचालित अनुवाद',

];
