<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_arrange_draw' => 'برگزاری',
    'action_clear_draw' => 'پاک کردن برگزاری',
    'action_end_next_bout' => 'پایان دادن به مسابقه بعدی',
    'action_generate_draw' => 'ایجاد برگزاری',
    'call_mat_tbc' => 'مات شما',
    'call_opponent_tbc' => 'در انتظار',
    'call_room_body' => ':mat · مسابقه :bout · مقابل :opponent',
    'call_room_title' => 'به اتاق فراخوان بروید — :mat',
    'call_warmup_body' => ':ahead مسابقه پیش از شما · حدوداً :minutes دقیقه',
    'call_warmup_title' => 'آماده‌سازی — شما در :mat به زودی هستید',
    'day_mats' => 'روز :day: :count مات',
    'draw_arranged' => 'برگزاری به‌روزرسانی شد 🥋',
    'draw_cleared' => 'برگزاری خالی شد — همه شرکت‌کنندگان دوباره در لیست هستند',
    'draw_final' => 'مسابقه شروع شده است — برگزاری نهایی است و نمی‌توان آن را دوباره ایجاد کرد.',
    'draw_generated' => 'برگزاری موقت ایجاد شد',
    'end_next_bout_done' => ':winner بر روی :court برنده شد. صفحات این مات اطلاع داده شدند.',
    'end_next_bout_none' => 'هیچ مسابقه‌ای آماده برای پایان نیست — همه مسابقات در انتظار یک مسابقه قبلی هستند.',
    'ended_locked' => 'این مسابقه پایان یافته است — نتایج آن نهایی است.',
    'gate_no_division' => 'کلاس وزن شما یکی از بخش‌های این مسابقه نیست، بنابراین شما مجاز به شرکت در این رویداد نیستید.',
    'gate_no_division_spectator' => 'کلاس وزن شما یکی از بخش‌های این مسابقه نیست، بنابراین نمی‌توانید شرکت کنید — اما شما می‌توانید به عنوان بازدیدکننده حضور یابید.',
    'gate_no_profile' => 'جنسیت و تاریخ تولد خود را به پروفایل خود اضافه کنید تا بتوانیم شما را در یک کلاس وزنی قرار دهیم.',
    'gate_no_weight' => 'وزن فعلی خود را به پروفایل سلامت خود اضافه کنید تا بتوانیم شما را در یک کلاس وزنی قرار دهیم.',
    'notify_draw_body' => 'بخش شما برگزار شده است. رویداد را باز کنید تا حریف، مات و شماره مسابقه خود را ببینید.',
    'notify_draw_title' => 'برگزاری منتشر شد — :title',
    'notify_weigh_in_body' => 'وزن‌گیری از ساعت :time در :place. کارت شناسایی خود را بیاورید.',
    'notify_weigh_in_title' => 'وزن‌گیری فردا — :title',
    'result_body_done' => 'این آخرین مسابقه روز شما بود.',
    'result_body_next' => 'بعدی: :round روی :mat، حدوداً :minutes دقیقه',
    'result_loss_title' => 'مسابقه تمام شد',
    'result_win_title' => 'شما برنده شدید 🎉',
    'roster_registered' => 'ثبت‌نام شده',
    'roster_unclassified' => 'بدون کلاس',
    'type_label' => 'مسابقه جیو جیتسو',

];
