node { name = "emqx@127.0.0.1"  cookie = "takeone-realtime"  data_dir = "/opt/emqx/data" }

listeners.tcp.default  { bind = "0.0.0.0:1883" }
listeners.ws.default   { bind = "0.0.0.0:8083"  websocket.mqtt_path = "/mqtt" }
listeners.wss.default  { enable = false }
listeners.ssl.default  { enable = false }

dashboard.listeners.http.bind = "0.0.0.0:18083"

authentication = [
  {
    mechanism = jwt
    from = password
    use_jwks = false
    algorithm = "hmac-based"
    secret = "2b5ee4f5ac8362f7fa4450f99183a7103d5e3394843b93608a5748308ddeffc1"
    acl_claim_name = "acl"
  }
]

authorization {
  no_match = deny
  deny_action = ignore
  sources = []
}
