<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_add_entrants' => '人を追加',
    'action_close' => 'セッションを終了',
    'action_queue_bout' => '試合をキューに入れる',
    'action_remove_entrant' => '人を削除',
    'action_set_mats' => 'マットを設定',
    'action_unqueue_bout' => '試合を削除',
    'bout_fought' => 'その試合はすでに試合されています。',
    'bout_queued' => 'キューに追加しました。',
    'bout_removed' => 'キューから削除しました。',
    'console_add_people' => '人を追加',
    'console_add_selected' => ':n を床に追加',
    'console_bouts_today' => '本日 :n',
    'console_clear_pick' => 'クリア',
    'console_closed' => 'このセッションは終了しました。',
    'console_end_confirm' => 'この対戦セッションを終了しますか？スコアボードが停止し、セッションはアーカイブされます。',
    'console_end_session' => 'セッション終了',
    'console_floor' => '誰がいるか',
    'console_floor_hint' => '2人をタップしてペアリング',
    'console_fought' => '試合済み',
    'console_fought_empty' => '試合がまだありません。',
    'console_mat_count' => ':n 実行中',
    'console_mats' => 'マット',
    'console_mats_label' => '実行中のマット',
    'console_no_members' => '会員が見つかりません。',
    'console_open_table' => 'スコアテーブル',
    'console_pair_hint' => 'フロアから2人を選択',
    'console_pick_blue' => '青コーナー',
    'console_pick_red' => '赤コーナー',
    'console_queue' => 'キュー',
    'console_queue_empty' => 'このマットにはキューがありません。',
    'console_queue_it' => 'この試合をキューに入れる',
    'console_screens' => 'ホールスクリーン',
    'console_search_members' => '会員を検索',
    'console_table_needs_bout' => 'このマットで試合をキューに入れてスコアテーブルを開きます。',
    'entrant_queued' => 'まだ試合されていない試合にいます。',
    'entrant_removed' => '床から削除しました。',
    'entrants_added' => '床に追加しました。',
    'label' => '対戦',
    'launch_bouts_n' => ':n 試合',
    'launch_eyebrow' => 'トレーニングスコアボード',
    'launch_lead' => 'マットに2人を配置し、ホールでスコアを確認します。抽選もエントリーも不要—今すぐオープンし、トレーニング終了時に閉鎖します。',
    'launch_mats' => 'マット数',
    'launch_minutes' => '試合時間',
    'launch_minutes_n' => ':n 分',
    'launch_no_sport' => 'このクラブにはマットスコアボードを持つスポーツがまだありません。',
    'launch_open_since' => ':time から実行中',
    'launch_past' => '過去のセッション',
    'launch_past_none' => 'セッションがまだありません。',
    'launch_resume' => '本日のセッションを開く',
    'launch_running' => '実行中',
    'launch_sport' => 'スポーツを選択',
    'launch_start' => '対戦開始',
    'launch_title' => '対戦',
    'mat_n' => 'マット :n',
    'mats_saved' => 'マットが更新されました。',
    'same_person' => '2人の異なる人を選択',
    'session_closed' => 'このセッションは終了しました。',
    'session_ended' => 'セッションが終了しました。',
    'session_title' => '対戦 · :date',
    'unknown_entrant' => 'まず両方のコーナーが床にいなければなりません。',
    'unknown_mat' => 'そのマットはこのセッションで実行されていません。',

];
