<?php

/*
|--------------------------------------------------------------------------
| explore — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/explore.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'apply_location' => 'Apliko Vendndodhjen',
    'book_session' => 'Rezervo Sesion',
    'cat_all' => 'Të gjitha',
    'cat_clubs' => 'Klubë',
    'cat_events' => 'Ngjarje',
    'cat_food_plans' => 'Plani ushqimesh',
    'cat_nutrition' => 'Nutricion',
    'cat_physiotherapy' => 'Fizioterapi',
    'cat_shops' => 'Shops',
    'cat_supplements' => 'Suplemente',
    'cat_trainers' => 'Antarë',
    'cat_venues' => 'Vende',
    'choose_option_body' => 'Zgjidh një opsion për secilin artikull të përzgjedhur të pajisjeve.',
    'choose_option_title' => 'Kërkohet opsion',
    'detecting_location' => 'Po zbulohet vendndodhja...',
    'drag_marker' => 'Tërhiq markerin për të vendosur vendndodhjen tënde',
    'error_fetching_clubs' => 'Ndodhi një gabim gjatë ngarkimit të klubëve.',
    'ev_coming_up' => 'Të ardhura',
    'ev_failed' => 'Dështoi ngarkimi i eventeve. Ju lutemi provoni përsëri.',
    'ev_finding' => 'Po ngarkohen eventet...',
    'ev_free' => 'Falas',
    'ev_full' => 'Të plotë',
    'ev_going' => 'po shkon',
    'ev_happening_now' => 'Po ndodh tani',
    'ev_live' => 'Në zhvillim',
    'ev_none_hint' => 'Nuk ka asnjë gjë që po zhvillohet ose është programuar për ju aktualisht.',
    'ev_none_title' => 'Nuk ka evente të hapura',
    'ev_open' => 'Hapur',
    'ev_spots_left' => 'vende të lira',
    'ev_starts_in' => 'Fillon në',
    'ev_tba' => 'TBD',
    'ev_until' => 'deri në',
    'ev_view_event' => 'Shiko eventin',
    'explore' => 'Eksploroni',
    'failed_to_fetch_clubs' => 'Dështoi ngarkimi i klubëve. Ju lutem provoni përsëri.',
    'finding' => 'Po gjen gjërat që janë afër juve...',
    'geolocation_not_supported' => 'Gjeolokacioni nuk mbështetet nga shfletuesi juaj.',
    'hero_eyebrow' => 'Zbulo atypërat',
    'hero_sub' => 'Klubë, antarë, klasa & më tepër gjerë në afërsi',
    'hero_title' => 'Gjeni Përshtatjen e Saktë',
    'join_club' => 'Bashkohu Klubit',
    'km_away' => 'km larg',
    'loading' => 'Po ngarkohet...',
    'location_access_denied' => 'Qasja e vendndodhjes u mohua.',
    'location_available' => 'Vendndodhja e disponueshme',
    'location_request_timed_out' => 'Kërkesa për vendndodhje ka skaduar.',
    'location_unavailable' => 'Informacioni i vendndodhjes nuk është i disponueshëm.',
    'members' => 'Anëtarë',
    'na' => 'N/A',
    'near_me' => 'Gjatë Kësaj',
    'no_members_selected_body' => 'Përzgjidh të paktën një anëtar për të vazhduar.',
    'no_members_selected_title' => 'Nuk është përzgjedhur asnjë anëtar',
    'no_results' => 'Nuk u Gjet Asnjë Rezultat',
    'no_results_hint' => 'Provo të rregullosh kërkimin ose vendndodhjen',
    'packages' => 'Paketë',
    'packages_required_body' => 'Zgjidh një paketë për secilin anëtar të përzgjedhur.',
    'packages_required_title' => 'Kërkohet paketë',
    'payment_required_body' => 'Ngarko një foto të ekranit të pagesës ose zgjidh të paguaj më vonë.',
    'payment_required_title' => 'Kërkohet provë pagese',
    'personal_trainer_badge' => 'Antar i Personalizuar',
    'please_try_again' => 'Ju lutem provoni përsëri.',
    'rating' => 'Vlerësim',
    'registration_error_body' => 'Diç shkoi keq gjatë dërgimit të regjistrimit tuaj.',
    'registration_failed_title' => 'Regjistrimi dështoi',
    'registration_submitted_body' => 'Regjistrimi juaj është dërguar klubit për aprovim.',
    'registration_submitted_title' => 'Regjistrimi u dërgua',
    'reviews' => 'Recenzime',
    'search_placeholder' => 'Kërko klubë, antarë...',
    'set_location' => 'Vendos Vendndodhjen tënde',
    'sports_club_badge' => 'Klub Sportiv',
    'trainers' => 'Antarë',
    'unable_to_get_location' => 'E pamundur të merrni vendndodhjen tuaj.',
    'view_details' => 'Shiko Detajet',
    'years_exp' => 'Viti i Përvojës',

];
