<?php

/*
|--------------------------------------------------------------------------
| security — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/security.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'add_otp_desc' => 'Shtoni një kod të një herë nga aplikacioni juaj i autentifikimit në çdo hyrje.',
    'cancel' => 'Anulo',
    'change_password' => 'Ndrysho Fjalëkalimin',
    'change_password_desc' => 'Të gjitha sesionet aktive të tjera janë shkëputur kur e ndryshoni.',
    'code_placeholder' => 'Kod 6-shifror',
    'code_placeholder_long' => 'Kod 6-shifror ose kod rekuperimi',
    'confirm_new_password' => 'Konfirmo Fjalëkalimin e Ri',
    'current_password' => 'Fjalëkalimi i Tanishëm',
    'disable' => 'Çaktivizo',
    'disable_2fa' => 'Çaktivizo 2FA',
    'disable_confirm_desc' => 'Futni një kod të tanishëm të autentifikuesit (ose një kod rekuperimi) për të konfirmuar.',
    'disable_two_factor' => 'Çaktivizo Autentifikimin me Dy Faktorë',
    'enable_2fa' => 'Aktivizo 2FA',
    'lockdown_message' => 'Le të mbyllim llogarinë tuaj.',
    'new_password' => 'Fjalëkalimi i Ri',
    'protected_message' => 'Llogaria juaj është mirë mbrojtur.',
    'protected_with_app' => 'Mbrojtur me Google Authenticator.',
    'recovery_codes' => 'Kodet e Rekuperimit',
    'recovery_codes_desc' => 'Kodet e backup të një herë për rastin kur humbni autentifikuesin tuaj.',
    'regenerate' => 'Rikrijo',
    'regenerate_codes' => 'Rikrijo kodet',
    'regenerate_codes_title' => 'Rikrijo Kodet',
    'regenerate_confirm_desc' => 'Kodet tuaja të mbetur të rekuperimit do të ndalohen. Futni kodin tuaj të autentifikuesit për të konfirmuar.',
    'security' => 'Siguria',
    'security_challenge_back_to_login' => 'Kthehu në hyrje',
    'security_challenge_backup_hint' => 'Futni një nga kodet tuaja 8-shifrorre të backup.',
    'security_challenge_subtitle' => 'Futni kodin nga aplikacioni juaj i autentifikuesit.',
    'security_challenge_title' => 'Autentifikimi me Dy Faktorë',
    'security_challenge_use_authenticator' => 'Përdor aplikacionin e autentifikuesit në vend të kësaj',
    'security_challenge_use_recovery' => 'Përdor një kod rekuperimi',
    'security_challenge_verify' => 'VERIFIKO',
    'security_index_2fa_disabled_desc' => 'Shtoni një shtresë të shtuar sigurie në llogarinë tuaj.',
    'security_index_2fa_enabled_desc' => 'Llogaria juaj është mbrojtur me Google Authenticator.',
    'security_index_2fa_title' => 'Autentifikimi me Dy Faktorë',
    'security_index_change_password' => 'Ndrysho Fjalëkalimin',
    'security_index_change_password_desc' => 'Të gjitha sesionet aktive të tjera do të shkëputen kur e ndryshoni fjalëkalimin tuaj.',
    'security_index_code_or_recovery_placeholder' => 'Kod 6-shifror ose kod rekuperimi',
    'security_index_code_placeholder' => 'Kod 6-shifror',
    'security_index_confirm_new_password' => 'Konfirmo Fjalëkalimin e Ri',
    'security_index_current_password' => 'Fjalëkalimi i Tanishëm',
    'security_index_disable_2fa' => 'Çaktivizo 2FA',
    'security_index_disable_2fa_modal_desc' => 'Futni kodin tuaj të tanishëm të autentifikuesit (ose një kod rekuperimi) për të konfirmuar.',
    'security_index_disable_2fa_modal_title' => 'Çaktivizo Autentifikimin me Dy Faktorë',
    'security_index_disabled' => 'Çaktivizuar',
    'security_index_enable_2fa' => 'Aktivizo 2FA',
    'security_index_enabled' => 'Aktivizuar',
    'security_index_new_password' => 'Fjalëkalimi i Ri',
    'security_index_recovery_codes' => 'Kodet e Rekuperimit',
    'security_index_recovery_codes_desc' => 'Kodet e backup të një herë në rastin kur humbni qasjen në aplikacionin tuaj të autentifikuesit.',
    'security_index_regen_codes_modal_desc' => 'Kodet tuaja të mbetur të rekuperimit do të anulohen. Futni kodin tuaj të autentifikuesit për të konfirmuar.',
    'security_index_regen_codes_modal_title' => 'Rikrijo Kodet e Rekuperimit',
    'security_index_regenerate' => 'Rikrijo',
    'security_index_regenerate_codes' => 'Rikrijo Kodet',
    'security_index_subtitle' => 'Menaxho sigurinë e llogarisë tuaj dhe autentifikimin me dy faktorë',
    'security_index_title' => 'Cilësitë e Sigurisë',
    'security_index_update_password' => 'Përditëso Fjalëkalimin',
    'security_recovery_codes_account_protected' => 'Llogaria juaj tani është e mbrojtur.',
    'security_recovery_codes_copied' => 'Kopjuar!',
    'security_recovery_codes_copy_all' => 'Kopjo të Gjitha Kodet',
    'security_recovery_codes_heading_enabled' => 'Autentifikimi Dy-Faktorës Aktivizuar',
    'security_recovery_codes_heading_new' => 'Kodet e Reja të Rimarrjes',
    'security_recovery_codes_page_title' => 'Kodet e Rimarrjes',
    'security_recovery_codes_save_safe' => 'Ruaj këto kodet e rimarrjes në një vend të sigurt.',
    'security_recovery_codes_store_desc' => 'Çdo kod mund të përdoret vetëm një herë.',
    'security_recovery_codes_store_safely' => 'Ruaj këto kodet me siguri.',
    'security_recovery_codes_success_alert' => 'Autentifikimi Dy-Faktorës është aktivizuar me sukses në llogarinë tuaj.',
    'security_setup_manual_entry' => 'Nuk mund të skanoni? Futni këtë çelës manualisht në aplikacion:',
    'security_setup_step1_app_name' => 'Google Authenticator',
    'security_setup_step1_app_store' => 'App Store',
    'security_setup_step1_download' => 'Shkarko',
    'security_setup_step1_from' => 'në telefonin tuaj nga',
    'security_setup_step1_heading' => 'Instaloni Google Authenticator',
    'security_setup_step1_or' => 'ose',
    'security_setup_step1_play_store' => 'Play Store',
    'security_setup_step2_heading' => 'Skanoni Kodin QR',
    'security_setup_step2_open' => 'Hapni aplikacionin, prekni',
    'security_setup_step2_scan_option' => 'Skanoni një kod QR',
    'security_setup_step2_then_choose' => ', pastaj zgjidhni',
    'security_setup_step3_heading' => 'Konfirmoni Kodin tuaj',
    'security_setup_step3_subtitle' => 'Futni kodin 6-shifror të shfaqur në aplikacion për të verifikuar konfigurimin.',
    'security_setup_subtitle' => 'Ndiqni hapësit e mëposhtëm për të siguruar llogarinë tuaj me Google Authenticator.',
    'security_setup_time_based' => 'Bazuar në kohë',
    'security_setup_time_based_prefix' => 'Zgjidhni',
    'security_setup_time_based_suffix' => 'kur kërkuhet.',
    'security_setup_title' => 'Konfiguro Autentifikimin Dy-Faktorës',
    'security_setup_verify_button' => 'Verifikoni & Aktivizo',
    'title' => 'Cilësitë e Sigurisë',
    'two_factor_auth' => 'Autentifikimi me Dy Faktorë',
    'two_factor_off' => 'Autentifikimi me dy faktorë i çaktivizuar',
    'two_factor_on' => 'Autentifikimi me dy faktorë i aktivizuar',
    'update_password' => 'Përditëso Fjalëkalimin',

];
