<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'add_language' => 'Adicionar um idioma',
    'choose_language' => 'Escolha um idioma',
    'complete' => ':done de :total',
    'continue_anyway' => 'Continuar no original',
    'edited_by_you' => 'Editado por você',
    'field_about' => 'Sobre este evento',
    'field_cta' => 'Texto do botão',
    'field_division' => 'Divisão',
    'field_fee' => 'Linha de taxa',
    'field_level' => 'Nível',
    'field_location' => 'Localização',
    'field_prize' => 'Prêmio',
    'field_requirement' => 'Requisito',
    'field_ribbon' => 'Faixa',
    'field_title' => 'Título',
    'interface_note' => 'O evento está em :language. Botões e rótulos permanecem em inglês.',
    'languages' => 'Idiomas',
    'languages_sub' => 'O que este evento diz em cada idioma em que foi lido',
    'machine' => 'Automático',
    'more_languages' => 'Outro idioma',
    'needs_review' => 'Necessita revisão',
    'needs_review_note' => 'O original foi alterado depois que isto foi escrito.',
    'no_language_found' => 'Nenhum idioma corresponde a isso.',
    'no_provider' => 'Nenhum provedor de IA está configurado. Adicione um em Admin → Provedores de IA antes que as traduções possam ser escritas.',
    'not_translated' => 'Ainda não traduzido',
    'nothing_yet' => 'Ninguém leu este evento em outro idioma ainda.',
    'nothing_yet_note' => 'No momento em que alguém escolher um na página pública, ele é escrito e mantido.',
    'preparing' => 'Preparando :language…',
    'preparing_failed' => 'Não conseguimos preparar :language agora. Mostrando o original.',
    'preparing_note' => 'Este evento está sendo escrito em :language. Acontece apenas uma vez — todos os que vierem depois receberão instantaneamente.',
    'queued' => 'Na fila. Estará pronto em um momento.',
    'read_in' => 'Ler isto em',
    'remove_language' => 'Remover este idioma',
    'remove_language_confirm' => 'Remover :language? Suas próprias correções também são excluídas. A tradução automática pode ser regenerada; suas edições não podem.',
    'removed' => 'Idioma removido.',
    'retranslate' => 'Traduzir novamente',
    'saved' => 'Salvo.',
    'search_languages' => 'Pesquisar idiomas',
    'source_language' => 'Escrito em :language',
    'translated_by_ai' => 'Traduzido automaticamente',

];
