<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_arrange_draw' => 'ड्रा व्यवस्थित करें',
    'action_clear_draw' => 'खाली ड्रा',
    'action_end_next_bout' => 'अगला बाउट समाप्त करें (टेस्ट)',
    'action_generate_draw' => 'ड्रा उत्पन्न करें',
    'board_heading' => 'चलने का क्रम',
    'board_idle' => 'खेल में कोई बाउट नहीं है',
    'board_live' => 'लाइव',
    'board_on_deck' => 'प्रतीक्षा में',
    'board_stale' => 'पुनः कनेक्ट हो रहा है',
    'board_title' => 'मैट बोर्ड — :event',
    'call_mat_tbc' => 'आपका मैट',
    'call_opponent_tbc' => 'बीएसी',
    'call_room_body' => ':mat · बाउट :bout · vs :opponent',
    'call_room_title' => 'कॉल रूम में जाएं — :mat',
    'call_warmup_body' => ':ahead बाउट्स आपके आगे हैं · लगभग :minutes मिनट',
    'call_warmup_title' => 'तापमान — आप :mat पर जल्दी आएंगे',
    'day_mats' => 'दिन :day: :count मैट्स',
    'draw_arranged' => 'ड्रा अपडेट किया गया 🥋',
    'draw_cleared' => 'ड्रा खाली कर दिया गया — प्रत्येक पंजीकृत व्यक्ति सूची पर वापस है',
    'draw_final' => 'चैंपियनशिप शुरू हो चुकी है — ड्रा अंतिम है और फिर से उत्पन्न नहीं किया जा सकता।',
    'draw_generated' => 'अस्थायी ड्रा उत्पन्न किया गया',
    'end_next_bout_done' => ':winner wins on :court. उस मैट पर स्क्रीन्स को सूचित किया गया है।',
    'end_next_bout_none' => 'कोई बाउट अंतिम करने के लिए तैयार नहीं है — प्रत्येक कतारबद्ध बाउट अभी भी फीडर की प्रतीक्षा में है।',
    'ended_locked' => 'यह चैंपियनशिप समाप्त हो चुकी है — इसके परिणाम अंतिम हैं।',
    'gate_no_division' => 'आपकी वजन श्रेणी इस चैंपियनशिप के विभाजनों में नहीं है, इसलिए आप इस घटना में प्रतियोगिता नहीं कर सकते।',
    'gate_no_division_spectator' => 'आपकी वजन श्रेणी इस चैंपियनशिप के विभाजनों में नहीं है, इसलिए आप प्रतियोगिता नहीं कर सकते — लेकिन आप दर्शक के रूप में भाग ले सकते हैं।',
    'gate_no_profile' => 'अपने प्रोफाइल में अपना लिंग और जन्मतिथि जोड़ें ताकि हम आपको एक वजन श्रेणी में स्थान दे सकें।',
    'gate_no_weight' => 'अपने स्वास्थ्य प्रोफाइल में अपना वर्तमान वजन जोड़ें ताकि हम आपको एक वजन श्रेणी में स्थान दे सकें।',
    'next_up_ahead' => 'बाउट्स आगे',
    'next_up_done' => 'आपका दिन समाप्त हो चुका है।',
    'next_up_estimate' => 'अनुमान, मैट के साथ चलता है',
    'next_up_finished' => 'समाप्त',
    'next_up_none' => 'आपके लिए अभी कुछ नहीं निर्धारित है।',
    'next_up_opponent_tbc' => 'प्रतिद्वंद्वी की प्रतीक्षा',
    'next_up_squad' => 'मेरा स्क्वाड',
    'next_up_title' => 'मेरा अगला बाउट',
    'next_up_you_are_next' => 'आपका बाउट अब आ रहा है — मैट पर जाएं',
    'notify_draw_body' => 'अपना प्रतिद्वंद्वी, मैट और बाउट संख्या अब प्रकाशित है।',
    'notify_draw_title' => 'ड्रा उपलब्ध है — :title',
    'notify_weigh_in_body' => 'आधिकारिक वजन निर्धारण :time, :place. आपको अपनी श्रेणी की सीमा पर आना होगा ताकि आप प्रतियोगिता कर सकें।',
    'notify_weigh_in_title' => 'कल वजन निर्धारण — :title',
    'result_body_done' => 'यह आपका दिन का अंतिम बाउट था।',
    'result_body_next' => 'अगला: :round on :mat, लगभग :minutes मिनट',
    'result_loss_title' => 'बाउट समाप्त',
    'result_win_title' => 'आप जीत गए 🎉',
    'roster_registered' => 'पंजीकृत',
    'roster_unclassified' => 'अनवर्गीकृत',
    'type_label' => 'टेकवंडो चैंपियनशिप',

];
