<?php

/*
|--------------------------------------------------------------------------
| explore — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/explore.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'apply_location' => 'Appliquer la localisation',
    'book_session' => 'Réserver une séance',
    'cat_all' => 'Tout',
    'cat_clubs' => 'Clubs',
    'cat_events' => 'Événements',
    'cat_food_plans' => 'Plans alimentaires',
    'cat_nutrition' => 'Nutrition',
    'cat_physiotherapy' => 'Physiothérapie',
    'cat_shops' => 'Boutiques',
    'cat_supplements' => 'Suppléments',
    'cat_trainers' => 'Entraîneurs',
    'cat_venues' => 'Lieux',
    'choose_option_body' => 'Choisissez une option pour chaque article d\'équipement sélectionné.',
    'choose_option_title' => 'Option requise',
    'detecting_location' => 'Détection de localisation...',
    'drag_marker' => 'Glissez le marqueur pour définir votre localisation',
    'error_fetching_clubs' => 'Une erreur s\'est produite lors du chargement des clubs.',
    'ev_coming_up' => 'À venir',
    'ev_failed' => 'Échec du chargement des événements. Veuillez réessayer.',
    'ev_finding' => 'Chargement des événements...',
    'ev_free' => 'Gratuit',
    'ev_full' => 'Complet',
    'ev_going' => 'en cours',
    'ev_happening_now' => 'En cours maintenant',
    'ev_live' => 'En direct',
    'ev_none_hint' => 'Rien ne se déroule ou n\'est programmé pour vous en ce moment.',
    'ev_none_title' => 'Aucun événement ouvert',
    'ev_open' => 'Ouvert',
    'ev_spots_left' => 'places restantes',
    'ev_starts_in' => 'Débute dans',
    'ev_tba' => 'À venir',
    'ev_until' => 'jusqu\'à',
    'ev_view_event' => 'Voir l\'événement',
    'explore' => 'Explorer',
    'failed_to_fetch_clubs' => 'Échec du chargement des clubs. Veuillez réessayer.',
    'finding' => 'Recherche des éléments à proximité...',
    'geolocation_not_supported' => 'La géolocalisation n\'est pas prise en charge par votre navigateur.',
    'hero_eyebrow' => 'Découvrir à proximité',
    'hero_sub' => 'Clubs, entraîneurs, stages et plus encore près de chez vous',
    'hero_title' => 'Trouvez votre combinaison parfaite',
    'join_club' => 'Rejoindre le club',
    'km_away' => 'km à distance',
    'loading' => 'Chargement...',
    'location_access_denied' => 'L\'accès à la localisation a été refusé.',
    'location_available' => 'Localisation disponible',
    'location_request_timed_out' => 'La requête de localisation a expiré.',
    'location_unavailable' => 'Les informations de localisation ne sont pas disponibles.',
    'members' => 'Membres',
    'na' => 'N/A',
    'near_me' => 'À proximité',
    'no_members_selected_body' => 'Sélectionnez au moins un membre pour continuer.',
    'no_members_selected_title' => 'Aucun membre sélectionné',
    'no_results' => 'Aucun résultat trouvé',
    'no_results_hint' => 'Essayez de modifier votre recherche ou votre localisation',
    'packages' => 'Forfaits',
    'packages_required_body' => 'Choisissez un forfait pour chaque membre sélectionné.',
    'packages_required_title' => 'Forfait requis',
    'payment_required_body' => 'Téléchargez une capture d\'écran de paiement ou choisissez de payer plus tard.',
    'payment_required_title' => 'Preuve de paiement requise',
    'personal_trainer_badge' => 'Entraîneur personnel',
    'please_try_again' => 'Veuillez réessayer.',
    'rating' => 'Note',
    'registration_error_body' => 'Une erreur s\'est produite lors de la soumission de votre inscription.',
    'registration_failed_title' => 'Échec de l\'inscription',
    'registration_submitted_body' => 'Votre inscription a été envoyée au club pour approbation.',
    'registration_submitted_title' => 'Inscription soumise',
    'reviews' => 'Avis',
    'search_placeholder' => 'Rechercher des clubs, des entraîneurs...',
    'set_location' => 'Définir votre localisation',
    'sports_club_badge' => 'Club sportif',
    'trainers' => 'Entraîneurs',
    'unable_to_get_location' => 'Impossible d\'obtenir votre localisation.',
    'view_details' => 'Voir les détails',
    'years_exp' => 'Années d\'expérience',

];
