<?php

/*
|--------------------------------------------------------------------------
| header — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/header.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'cart' => 'Panier',
    'cart_soon' => 'Panier bientôt disponible',
    'chat' => 'Chat',
    'clear_all' => 'Tout effacer',
    'club_management' => 'Gestion du club',
    'just_now' => 'à l\'instant',
    'mark_all_read' => 'Tout marquer comme lu',
    'menu' => 'Menu',
    'no_notifications' => 'Aucune notification pour le moment',
    'notification' => 'Notification',
    'notifications' => 'Notifications',
    'personal_desc' => 'Mon profil, réservations, paiements',
    'personal_view' => 'Vue personnelle',
    'scan_code_placeholder' => 'ABC123',
    'scan_foreign_host' => 'Ce code QR pointe vers un autre site web, il n\'a donc pas été ouvert.',
    'scan_hint' => 'Pointez votre appareil photo vers un code QR',
    'scan_no_camera' => 'Impossible d\'accéder à l\'appareil photo.',
    'scan_or_type' => 'Ou saisir le code de 6 caractères',
    'scan_qr' => 'Scanner le code QR',
    'scan_unsupported' => 'La numérisation QR n\'est pas prise en charge par ce navigateur.',
    'switch_view' => 'Changer de vue',

];
