<?php

/*
|--------------------------------------------------------------------------
| security — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/security.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'add_otp_desc' => 'Ajoutez un code unique à partir de votre application d\'authentification à chaque connexion.',
    'cancel' => 'Annuler',
    'change_password' => 'Changer le mot de passe',
    'change_password_desc' => 'Toutes les autres sessions actives sont déconnectées lorsque vous le modifiez.',
    'code_placeholder' => 'Code à 6 chiffres',
    'code_placeholder_long' => 'Code à 6 chiffres ou code de récupération',
    'confirm_new_password' => 'Confirmer le nouveau mot de passe',
    'current_password' => 'Mot de passe actuel',
    'disable' => 'Désactiver',
    'disable_2fa' => 'Désactiver l\'authentification à deux facteurs',
    'disable_confirm_desc' => 'Entrez un code d\'authentification actuel (ou un code de récupération) pour confirmer.',
    'disable_two_factor' => 'Désactiver l\'authentification à deux facteurs',
    'enable_2fa' => 'Activer l\'authentification à deux facteurs',
    'lockdown_message' => 'Verrouillons votre compte.',
    'new_password' => 'Nouveau mot de passe',
    'protected_message' => 'Votre compte est bien protégé.',
    'protected_with_app' => 'Protégé avec Google Authenticator.',
    'recovery_codes' => 'Codes de récupération',
    'recovery_codes_desc' => 'Codes de récupération uniques au cas où vous perdriez votre application d\'authentification.',
    'regenerate' => 'Regénérer',
    'regenerate_codes' => 'Regénérer les codes',
    'regenerate_codes_title' => 'Regénérer les codes',
    'regenerate_confirm_desc' => 'Vos codes de récupération existants cesseront de fonctionner. Entrez votre code d\'authentification pour confirmer.',
    'security' => 'Sécurité',
    'security_challenge_back_to_login' => 'Retour à la connexion',
    'security_challenge_backup_hint' => 'Entrez l\'un de vos codes de récupération de 8 caractères.',
    'security_challenge_subtitle' => 'Entrez le code de votre application d\'authentification.',
    'security_challenge_title' => 'Authentification à deux facteurs',
    'security_challenge_use_authenticator' => 'Utiliser une application d\'authentification à la place',
    'security_challenge_use_recovery' => 'Utiliser un code de récupération',
    'security_challenge_verify' => 'VÉRIFIER',
    'security_index_2fa_disabled_desc' => 'Ajoutez une couche supplémentaire de sécurité à votre compte.',
    'security_index_2fa_enabled_desc' => 'Votre compte est protégé avec Google Authenticator.',
    'security_index_2fa_title' => 'Authentification à deux facteurs',
    'security_index_change_password' => 'Changer le mot de passe',
    'security_index_change_password_desc' => 'Toutes les autres sessions actives seront déconnectées lorsque vous modifierez votre mot de passe.',
    'security_index_code_or_recovery_placeholder' => 'Code à 6 chiffres ou code de récupération',
    'security_index_code_placeholder' => 'Code à 6 chiffres',
    'security_index_confirm_new_password' => 'Confirmer le nouveau mot de passe',
    'security_index_current_password' => 'Mot de passe actuel',
    'security_index_disable_2fa' => 'Désactiver l\'authentification à deux facteurs',
    'security_index_disable_2fa_modal_desc' => 'Entrez votre code d\'authentification actuel (ou un code de récupération) pour confirmer.',
    'security_index_disable_2fa_modal_title' => 'Désactiver l\'authentification à deux facteurs',
    'security_index_disabled' => 'Désactivé',
    'security_index_enable_2fa' => 'Activer l\'authentification à deux facteurs',
    'security_index_enabled' => 'Activé',
    'security_index_new_password' => 'Nouveau mot de passe',
    'security_index_recovery_codes' => 'Codes de récupération',
    'security_index_recovery_codes_desc' => 'Codes de récupération uniques au cas où vous perdriez l\'accès à votre application d\'authentification.',
    'security_index_regen_codes_modal_desc' => 'Vos codes de récupération existants seront invalidés. Entrez votre code d\'authentification pour confirmer.',
    'security_index_regen_codes_modal_title' => 'Regénérer les codes de récupération',
    'security_index_regenerate' => 'Regénérer',
    'security_index_regenerate_codes' => 'Regénérer les codes',
    'security_index_subtitle' => 'Gérez la sécurité de votre compte et l\'authentification à deux facteurs',
    'security_index_title' => 'Paramètres de sécurité',
    'security_index_update_password' => 'Mettre à jour le mot de passe',
    'security_recovery_codes_account_protected' => 'Votre compte est maintenant protégé.',
    'security_recovery_codes_copied' => 'Copié !',
    'security_recovery_codes_copy_all' => 'Copier tous les codes',
    'security_recovery_codes_heading_enabled' => 'Authentification à deux facteurs activée',
    'security_recovery_codes_heading_new' => 'Nouveaux codes de récupération',
    'security_recovery_codes_page_title' => 'Codes de récupération',
    'security_recovery_codes_save_safe' => 'Enregistrez ces codes de récupération en lieu sûr.',
    'security_recovery_codes_store_desc' => 'Chaque code ne peut être utilisé qu\'une seule fois.',
    'security_recovery_codes_store_safely' => 'Conservez ces codes en sécurité.',
    'security_recovery_codes_success_alert' => 'L\'authentification à deux facteurs a été activée avec succès sur votre compte.',
    'security_setup_manual_entry' => 'Impossible de scanner ? Entrez cette clé manuellement dans l\'application :',
    'security_setup_step1_app_name' => 'Google Authenticator',
    'security_setup_step1_app_store' => 'App Store',
    'security_setup_step1_download' => 'Télécharger',
    'security_setup_step1_from' => 'sur votre téléphone depuis le',
    'security_setup_step1_heading' => 'Installer Google Authenticator',
    'security_setup_step1_or' => 'ou',
    'security_setup_step1_play_store' => 'Play Store',
    'security_setup_step2_heading' => 'Scanner le code QR',
    'security_setup_step2_open' => 'Ouvrir l\'application, appuyer sur',
    'security_setup_step2_scan_option' => 'Scanner un code QR',
    'security_setup_step2_then_choose' => ', puis choisir',
    'security_setup_step3_heading' => 'Confirmer votre code',
    'security_setup_step3_subtitle' => 'Entrez le code à 6 chiffres affiché dans l\'application pour vérifier la configuration.',
    'security_setup_subtitle' => 'Suivez les étapes ci-dessous pour sécuriser votre compte avec Google Authenticator.',
    'security_setup_time_based' => 'Basé sur le temps',
    'security_setup_time_based_prefix' => 'Sélectionner',
    'security_setup_time_based_suffix' => 'lorsqu\'on vous le demande.',
    'security_setup_title' => 'Configurer l\'authentification à deux facteurs',
    'security_setup_verify_button' => 'Vérifier et activer',
    'title' => 'Paramètres de sécurité',
    'two_factor_auth' => 'Authentification à deux facteurs',
    'two_factor_off' => 'Authentification à deux facteurs désactivée',
    'two_factor_on' => 'Authentification à deux facteurs activée',
    'update_password' => 'Mettre à jour le mot de passe',

];
