<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_add_entrants' => 'Agregar personas',
    'action_close' => 'Finalizar sesión',
    'action_queue_bout' => 'Agregar combate',
    'action_remove_entrant' => 'Eliminar persona',
    'action_set_mats' => 'Establecer pistas',
    'action_unqueue_bout' => 'Eliminar combate',
    'bout_fought' => 'Ese combate ya se ha luchado.',
    'bout_queued' => 'Agregado a la cola.',
    'bout_removed' => 'Eliminado de la cola.',
    'console_add_people' => 'Agregar personas',
    'console_add_selected' => 'Agregar :n al suelo',
    'console_bouts_today' => ':n hoy',
    'console_clear_pick' => 'Limpiar',
    'console_closed' => 'Esta sesión ha terminado.',
    'console_end_confirm' => '¿Finalizar esta sesión de entrenamiento? El puntaje se detiene y la sesión se archiva.',
    'console_end_session' => 'Finalizar sesión',
    'console_floor' => '¿Quién está aquí',
    'console_floor_hint' => 'Toca dos para emparejarlos',
    'console_fought' => 'Luchados',
    'console_fought_empty' => 'Aún no hay combates.',
    'console_mat_count' => 'En curso :n',
    'console_mats' => 'Pistas',
    'console_mats_label' => 'Pistas en curso',
    'console_no_members' => 'No se encontraron miembros.',
    'console_open_table' => 'Tabla de puntaje',
    'console_pair_hint' => 'Elige a dos personas del suelo',
    'console_pick_blue' => 'Esquina azul',
    'console_pick_red' => 'Esquina roja',
    'console_queue' => 'Cola',
    'console_queue_empty' => 'Nada en cola en esta pista.',
    'console_queue_it' => 'Agregar este combate',
    'console_screens' => 'Pantallas de la sala',
    'console_search_members' => 'Buscar miembros',
    'console_table_needs_bout' => 'Agrega un combate en esta pista para abrir su tabla de puntaje.',
    'entrant_queued' => 'Están en un combate que aún no se ha luchado.',
    'entrant_removed' => 'Eliminado del suelo.',
    'entrants_added' => 'Agregado al suelo.',
    'label' => 'Entrenamiento',
    'launch_bouts_n' => ':n combates',
    'launch_eyebrow' => 'Puntaje de entrenamiento',
    'launch_lead' => 'Coloca a dos personas en una pista y la sala ve el puntaje. Sin sorteo, sin inscripciones — ábrelo ahora, ciérralo cuando termine el entrenamiento.',
    'launch_mats' => '¿Cuántas pistas',
    'launch_minutes' => 'Duración del combate',
    'launch_minutes_n' => ':n min',
    'launch_no_sport' => 'Este club aún no tiene un deporte con puntaje en pista.',
    'launch_open_since' => 'Abierto desde :time',
    'launch_past' => 'Sesiones anteriores',
    'launch_past_none' => 'Aún no hay sesiones.',
    'launch_resume' => 'Abrir sesión de hoy',
    'launch_running' => 'En curso',
    'launch_sport' => '¿Qué deporte',
    'launch_start' => 'Iniciar entrenamiento',
    'launch_title' => 'Entrenamiento',
    'mat_n' => 'Pista :n',
    'mats_saved' => 'Pistas actualizadas.',
    'same_person' => 'Elige a dos personas diferentes.',
    'session_closed' => 'Esta sesión ha terminado.',
    'session_ended' => 'Sesión finalizada.',
    'session_title' => 'Entrenamiento · :date',
    'unknown_entrant' => 'Ambas esquinas deben estar en el suelo primero.',
    'unknown_mat' => 'Esa no es una pista en la que se corre esta sesión.',

];
