<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_arrange_draw' => 'ڈراو ترتیب دیں',
    'action_clear_draw' => 'خالی ڈراو',
    'action_end_next_bout' => 'اگلے باؤٹ کو ختم کریں (ٹیسٹ)',
    'action_generate_draw' => 'ڈراو تیار کریں',
    'board_heading' => 'چلنے کا آرڈر',
    'board_idle' => 'کوئی باؤٹس چل رہے نہیں',
    'board_live' => 'لائیو',
    'board_on_deck' => 'ڈیک پر',
    'board_stale' => 'دوبارہ جڑ رہا ہے',
    'board_title' => 'میٹ بورڈ — :event',
    'call_mat_tbc' => 'آپ کا میٹ',
    'call_opponent_tbc' => 'ٹی بی سی',
    'call_room_body' => ':mat · باؤٹ :bout · مقابلہ :opponent',
    'call_room_title' => 'کال کمر میں جائیں — :mat',
    'call_warmup_body' => ':ahead باؤٹس آپ کے آگے ہیں · تقریباً :minutes منٹ',
    'call_warmup_title' => 'گرم کریں — آپ اب :mat پر ہوں گے',
    'day_mats' => 'دن :day: :count میٹس',
    'draw_arranged' => 'ڈراو اپ ڈیٹ ہو گیا 🥋',
    'draw_cleared' => 'ڈراو خالی کر دیا گیا — ہر اندراج کار کو فہرست پر واپس کیا گیا',
    'draw_final' => 'کیمپیئن شپ شروع ہو چکی ہے — ڈراو نہایت اور دوبارہ تیار نہیں کیا جا سکتا۔',
    'draw_generated' => 'عارضی ڈراو تیار کیا گیا',
    'end_next_bout_done' => ':winner نے :court پر جیتی۔ اس میٹ پر موجود اسکرینس کو بتایا گیا ہے۔',
    'end_next_bout_none' => 'کوئی باؤٹ تیار نہیں ہے جو ختم کیا جا سکے — ہر قطار والے باؤٹ کو ایک فیڈر کی انتظار ہے۔',
    'ended_locked' => 'اس کیمپیئن شپ ختم ہو چکی ہے — اس کے نتائج نہایت ہیں۔',
    'gate_no_division' => 'آپ کا وزن زمرہ اس کیمپیئن شپ کے تقسیم میں سے کوئی نہیں ہے، اس لیے آپ اس ایونٹ میں کام کرنے کے لیے مؤهل نہیں ہیں۔',
    'gate_no_division_spectator' => 'آپ کا وزن زمرہ اس کیمپیئن شپ کے تقسیم میں سے کوئی نہیں ہے، اس لیے آپ کو کام نہیں کر سکتے — لیکن آپ کو شہادت کے طور پر شرکت کرنے کی اجازت ہے۔',
    'gate_no_profile' => 'اپنے پروفائل میں اپنی جنس اور پیدائش کی تاریخ شامل کریں تاکہ ہم آپ کو ایک وزن زمرہ میں رکھ سکیں۔',
    'gate_no_weight' => 'اپنے پروفائل میں اپنی موجودہ وزن شامل کریں تاکہ ہم آپ کو ایک وزن زمرہ میں رکھ سکیں۔',
    'next_up_ahead' => 'باؤٹس آگے',
    'next_up_done' => 'آپ نے دن ختم کر دیا ہے۔',
    'next_up_estimate' => 'قدر، میٹ کے ساتھ حرکت کرتا ہے',
    'next_up_finished' => 'ختم',
    'next_up_none' => 'ابھی آپ کے لیے کچھ نہیں منصوبہ بند کیا گیا۔',
    'next_up_opponent_tbc' => 'مقابلہ کار کی انتظار',
    'next_up_squad' => 'میرا سکوڈ',
    'next_up_title' => 'میرا اگلا باؤٹ',
    'next_up_you_are_next' => 'آپ اگلے ہیں — میٹ پر جائیں',
    'notify_draw_body' => 'آپ کا مقابلہ کار، میٹ اور باؤٹ نمبر اب شائع ہو چکے ہیں۔',
    'notify_draw_title' => 'ڈراو آؤٹ ہو گیا — :title',
    'notify_weigh_in_body' => 'آفسیشل وزن کی ترتیب :time، :place۔ آپ کو اپنی تقسیم کی حد کو پہنچنے کی ضرورت ہے تاکہ کام کر سکیں۔',
    'notify_weigh_in_title' => 'کھیلنے کی تاریخ آج — :title',
    'result_body_done' => 'یہ آپ کا دن کا آخری باؤٹ تھا۔',
    'result_body_next' => 'اگلا: :round پر :mat، تقریباً :minutes منٹ',
    'result_loss_title' => 'باؤٹ ختم ہو گیا',
    'result_win_title' => 'آپ نے جیتی 🎉',
    'roster_registered' => 'رجسٹرڈ',
    'roster_unclassified' => 'غیر مصنف',
    'type_label' => 'کریٹ کیمپیئن شپ',

];
