<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'add_language' => '言語を追加',
    'choose_language' => '言語を選択',
    'complete' => ':done / :total',
    'continue_anyway' => '元の言語で続ける',
    'edited_by_you' => 'あなたが編集',
    'field_about' => 'このイベントについて',
    'field_cta' => 'ボタンのテキスト',
    'field_division' => '部門',
    'field_fee' => '料金行',
    'field_level' => 'レベル',
    'field_location' => '場所',
    'field_prize' => '賞品',
    'field_requirement' => '要件',
    'field_ribbon' => 'リボン',
    'field_title' => 'タイトル',
    'interface_note' => 'このイベントは :language です。ボタンとラベルは英語のままです。',
    'languages' => '言語',
    'languages_sub' => 'このイベントがすべての言語で記述されている内容',
    'machine' => '自動',
    'more_languages' => '別の言語',
    'needs_review' => 'レビューが必要',
    'needs_review_note' => 'この文章が記述された後に元の文章が変更されました。',
    'no_language_found' => '該当する言語がありません。',
    'no_provider' => 'AIプロバイダーが設定されていません。翻訳を記述する前に、管理者 → AIプロバイダーで追加してください。',
    'not_translated' => 'まだ翻訳されていません',
    'nothing_yet' => 'このイベントを他の言語で読んだ人はまだいません。',
    'nothing_yet_note' => '公開ページで誰かが選択すると、記述され保存されます。',
    'preparing' => ':language を準備中…',
    'preparing_failed' => ':language を準備できませんでした。元の言語を表示します。',
    'preparing_note' => 'このイベントは :language で記述されています。一度だけ発生し、あなた以降の人は即座に取得します。',
    'queued' => '処理待ちです。間もなく準備が完了します。',
    'read_in' => 'この言語で読む',
    'remove_language' => 'この言語を削除',
    'remove_language_confirm' => ':language を削除しますか？あなたの独自の修正も削除されます。機械翻訳は再生成できますが、あなたの編集は復元できません。',
    'removed' => '言語を削除しました。',
    'retranslate' => '再翻訳',
    'saved' => '保存しました。',
    'search_languages' => '言語を検索',
    'source_language' => ':language で記述',
    'translated_by_ai' => '自動翻訳',

];
