<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_arrange_draw' => 'ڈرا ترتیب دیں',
    'action_clear_draw' => 'ڈرا صاف کریں',
    'action_end_next_bout' => 'اگلا میچ ختم کریں',
    'action_generate_draw' => 'ڈرا تیار کریں',
    'call_mat_tbc' => 'آپ کا میٹ',
    'call_opponent_tbc' => 'معلوم نہیں',
    'call_room_body' => ':mat · میچ :bout · کے خلاف :opponent',
    'call_room_title' => 'کال کمر میں جائیں — :mat',
    'call_warmup_body' => ':ahead میچز آپ کے آگے · تقریباً :minutes منٹ',
    'call_warmup_title' => 'گرم کریں — آپ کا :mat پر آنا ہے',
    'day_mats' => 'دن :day: :count میٹس',
    'draw_arranged' => 'ڈرا اپ ڈیٹ ہو گیا 🥋',
    'draw_cleared' => 'ڈرا خالی کر دیا گیا — ہر اندراج کار کو فہرست پر واپس کر دیا گیا ہے',
    'draw_final' => 'چیمپیونشپ شروع ہو چکی ہے — ڈرا نہایت ہے اور دوبارہ تیار نہیں کیا جا سکتا۔',
    'draw_generated' => 'عارضی ڈرا تیار ہو گیا',
    'end_next_bout_done' => ':winner کو :court پر جیتا۔ اس میٹ پر موجود اسکرینس کو بتایا گیا ہے۔',
    'end_next_bout_none' => 'کوئی میچ ختم کرنے کے لیے تیار نہیں ہے — ہر قطار والے میچ ابھی بھی فیڈر کی انتظار میں ہے۔',
    'ended_locked' => 'اس چیمپیونشپ کا اختتام ہو چکا ہے — اس کے نتائج نہایت ہیں۔',
    'gate_no_division' => 'آپ کی وزن کلاس اس چیمپیونشپ کی تقسیم میں سے کوئی نہیں ہے، اس لیے آپ اس ایونٹ میں کھیل کے لائق نہیں ہیں۔',
    'gate_no_division_spectator' => 'آپ کی وزن کلاس اس چیمپیونشپ کی تقسیم میں سے کوئی نہیں ہے، اس لیے آپ کھیل نہیں کر سکتے — لیکن آپ کو مشاہدہ کے طور پر شرکت کی اجازت ہے۔',
    'gate_no_profile' => 'اپنے پروفائل میں اپنی جنس اور پیدائش کی تاریخ شامل کریں تاکہ ہم آپ کو ایک وزن کلاس میں رکھ سکیں۔',
    'gate_no_weight' => 'اپنے پروفائل میں اپنی موجودہ وزن شامل کریں تاکہ ہم آپ کو ایک وزن کلاس میں رکھ سکیں۔',
    'notify_draw_body' => 'آپ کا تقسیم ڈرا ہو چکی ہے۔ ایونٹ کھولیں تاکہ آپ اپنے میچ کے خلاف کس کے ہوں، میٹ اور میچ نمبر دیکھ سکیں۔',
    'notify_draw_title' => 'ڈرا آ گیا — :title',
    'notify_weigh_in_body' => 'وزن چیک کریں :time پر :place میں شروع ہوتا ہے۔ اپنی شناخت کا دستاویز لے کر آئیں۔',
    'notify_weigh_in_title' => 'کل وزن چیک کریں — :title',
    'result_body_done' => 'یہ آپ کا دن کا آخری میچ تھا۔',
    'result_body_next' => 'اگلا: :round پر :mat، تقریباً :minutes منٹ',
    'result_loss_title' => 'میچ ختم ہو گیا',
    'result_win_title' => 'آپ نے جیتا 🎉',
    'roster_registered' => 'رجسٹرڈ',
    'roster_unclassified' => 'بے تقسیم',
    'type_label' => 'جیو جیٹس چیمپیونشپ',

];
