<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'belt_black' => 'E zi',
    'belt_blue' => 'Blu',
    'belt_brown' => 'E zezë',
    'belt_purple' => 'Purpurt',
    'belt_white' => 'E bardhë',
    'corner_blue' => 'BLU',
    'corner_white' => 'E bardhë',
    'division_label' => 'Klasa e pesës',
    'mat' => 'Mat',
    'official_mat_organiser' => 'Organizuesi i matit',
    'official_mat_organiser_hint' => 'Mbështet funksionimin e matit dhe thirr nxirrësit në radhë.',
    'official_referee' => 'Refere',
    'official_referee_hint' => 'Kontrollon mënyrën e luajtjes në mat: fillon dhe ndalon, dhe njofton çdo pikë.',
    'official_scorekeeper' => 'Regjistruesi i pikëve',
    'official_scorekeeper_hint' => 'Shkruan pikët, avantazhet dhe dënimet në tavolinë.',
    'official_timekeeper' => 'Kronometri',
    'official_timekeeper_hint' => 'Mbështet kohën: koha e lojës, ndërprerjet dhe zilja finale.',
    'score_four' => '4 pikë',
    'score_three' => '3 pikë',
    'score_two' => '2 pikë',
    'sport_label' => 'Brazilian Jiu-Jitsu',
    'weigh_in' => 'Pesë',

];
