<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_add_entrants' => '添加人员',
    'action_close' => '结束会话',
    'action_queue_bout' => '排队比赛',
    'action_remove_entrant' => '移除人员',
    'action_set_mats' => '设置场地',
    'action_unqueue_bout' => '移除比赛',
    'bout_fought' => '该场比赛已进行完毕。',
    'bout_queued' => '已排队。',
    'bout_removed' => '已从排队中移除。',
    'console_add_people' => '添加人员',
    'console_add_selected' => '添加 :n 到场地',
    'console_bouts_today' => ':n 场今日',
    'console_clear_pick' => '清除',
    'console_closed' => '该训练已结束。',
    'console_end_confirm' => '结束本次对练？计分板将停止，训练记录将被归档。',
    'console_end_session' => '结束训练',
    'console_floor' => '在场人员',
    'console_floor_hint' => '点击两人进行配对',
    'console_fought' => '已进行',
    'console_fought_empty' => '暂无比赛。',
    'console_mat_count' => '运行中 :n',
    'console_mats' => '场地',
    'console_mats_label' => '正在运行的场地',
    'console_no_members' => '未找到成员。',
    'console_open_table' => '计分表',
    'console_pair_hint' => '从场地中选择两人',
    'console_pick_blue' => '蓝方',
    'console_pick_red' => '红方',
    'console_queue' => '排队',
    'console_queue_empty' => '该场地暂无排队的比赛。',
    'console_queue_it' => '排队此场比赛',
    'console_screens' => '大厅屏幕',
    'console_search_members' => '搜索成员',
    'console_table_needs_bout' => '在该场地排队一场比赛以开启计分表。',
    'entrant_queued' => '他们正在尚未进行的比赛。',
    'entrant_removed' => '已从场地移除。',
    'entrants_added' => '已添加到场地。',
    'label' => '对练',
    'launch_bouts_n' => ':n 场比赛',
    'launch_eyebrow' => '训练计分板',
    'launch_lead' => '在场地中安排两人，观众可以看到分数。没有抽签，没有报名——现在开启，训练结束时关闭。',
    'launch_mats' => '需要多少个场地',
    'launch_minutes' => '比赛时长',
    'launch_minutes_n' => ':n 分钟',
    'launch_no_sport' => '该俱乐部尚未设置有场地计分板的运动项目。',
    'launch_open_since' => '自 :time 开始运行',
    'launch_past' => '历史训练',
    'launch_past_none' => '暂无训练记录。',
    'launch_resume' => '开启今日训练',
    'launch_running' => '正在进行中',
    'launch_sport' => '选择运动项目',
    'launch_start' => '开始对练',
    'launch_title' => '对练',
    'mat_n' => '场地 :n',
    'mats_saved' => '场地已更新。',
    'same_person' => '请选择两个不同的人。',
    'session_closed' => '该训练已结束。',
    'session_ended' => '训练已结束。',
    'session_title' => '对练 · :date',
    'unknown_entrant' => '双方必须先在场地。',
    'unknown_mat' => '该场地不在本次训练范围内。',

];
