<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_arrange_draw' => 'Hilbijêre draw',
    'action_clear_draw' => 'Paqij bike draw',
    'action_end_next_bout' => 'Maseyê pêşîn bidawîne',
    'action_generate_draw' => 'Hilbijêre draw',
    'call_mat_tbc' => 'mat xwe',
    'call_opponent_tbc' => 'TBC',
    'call_room_body' => ':mat · maseyê :bout · vs :opponent',
    'call_room_title' => 'Li hêmanê bêrê bîne — :mat',
    'call_warmup_body' => ':ahead maseyên pêşîn yên hûn · biqûl :minutes min',
    'call_warmup_title' => 'Bêrê bîne — hûn li :mat dê bidin',
    'day_mats' => 'Roj :day: :count mats',
    'draw_arranged' => 'Draw hate nûvekirin 🥋',
    'draw_cleared' => 'Draw hate paqij kirin — her kes dîsa li nav navnîşanê ye',
    'draw_final' => 'Şampiyonîya dest pê kir — draw dê nekeve û nikarî bi nû ve çê bikî.',
    'draw_generated' => 'Draw pêşîn hatiye çêkirin',
    'end_next_bout_done' => ':winner li :court vêniye. Ekranên wê mat hatine agahî dan.',
    'end_next_bout_none' => 'Maseyek nîne ku em bikarin bidawînin — hemû maseyên ku hatine nîvandin dê li ser pêşbîrê bêjin.',
    'ended_locked' => 'Vê şampiyonîyê biqedîtiye — encamên wê dê nekevin.',
    'gate_no_division' => 'Pirtûka ağırlîka xwe ne li nav pirtûkên vê şampiyonîyê de ye, ji bo ku em bikarin hûn li heman pirtûkê de bikevin.',
    'gate_no_division_spectator' => 'Pirtûka ağırlîka xwe ne li nav pirtûkên vê şampiyonîyê de ye, ji bo ku em bikarin hûn li heman pirtûkê de bikevin, lê hûn dikarin wekî şahedan bidin.',
    'gate_no_profile' => 'Ji bo ku em bikarin hûn li heman pirtûkê de bikevin, jins û dîroka lêdanê xwe li profîla xwe zêde bikin.',
    'gate_no_weight' => 'Ji bo ku em bikarin hûn li heman pirtûkê de bikevin, ağırlîka xwe li profîla xwe zêde bikin.',
    'notify_draw_body' => 'Pirtûka xwe hatiye hilbijartin. Evê vê şampiyonîyê veke ku em bikarin hûn li heman pirtûkê de bikevin, maseyê û nîşana xwe bibînin.',
    'notify_draw_title' => 'Draw hatiye çêkirin — :title',
    'notify_weigh_in_body' => 'Dîroka lêdanî di :time de di :place de dest pê dike. ID xwe bîne.',
    'notify_weigh_in_title' => 'Dîroka lêdanî rojî — :title',
    'result_body_done' => 'Vê rojê maseyekî dîtin.',
    'result_body_next' => 'Pêşîn: :round li :mat, biqûl :minutes min',
    'result_loss_title' => 'Maseyê biqedîtiye',
    'result_win_title' => 'Hûn vêniye 🎉',
    'roster_registered' => 'Têketî',
    'roster_unclassified' => 'Bêpirtûk',
    'type_label' => 'Şampiyonîya Jiu-Jitsu',

];
