<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'belt_black' => 'काला',
    'belt_blue' => 'नीला',
    'belt_brown' => 'भूरा',
    'belt_purple' => 'बैंगनी',
    'belt_white' => 'सफेद',
    'corner_blue' => 'नीला',
    'corner_white' => 'सफेद',
    'division_label' => 'वजन श्रेणी',
    'mat' => 'मैट',
    'official_mat_organiser' => 'मैट संगठक',
    'official_mat_organiser_hint' => 'मैट चलाता है: इसे अनुसूची के अनुसार चलाता है और एथलीटों को बुलाता है।',
    'official_referee' => 'मैदान कर्मचारी',
    'official_referee_hint' => 'मैट पर मैच चलाता है: इसे शुरू करता है और रोकता है, और प्रत्येक स्कोर की संकेत देता है।',
    'official_scorekeeper' => 'स्कोरकीपर',
    'official_scorekeeper_hint' => 'टेबल पर अंक, लाभ और पेनल्टी दर्ज करता है।',
    'official_timekeeper' => 'टाइमकीपर',
    'official_timekeeper_hint' => 'घड़ी रखता है: मैच का समय, स्थगित करने और अंतिम घंटी।',
    'score_four' => '4 अंक',
    'score_three' => '3 अंक',
    'score_two' => '2 अंक',
    'sport_label' => 'ब्राजिलियन जी जी',
    'weigh_in' => 'वजन नापना',

];
