<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_arrange_draw' => 'ארגן מערך',
    'action_clear_draw' => 'מערך ריק',
    'action_end_next_bout' => 'סיים את match הבא (בדיקה)',
    'action_generate_draw' => 'צור מערך',
    'board_heading' => 'סדר הפעולה',
    'board_idle' => 'אין matchים פעילים',
    'board_live' => 'חי',
    'board_on_deck' => 'בשלב הבא',
    'board_stale' => 'מתחבר מחדש',
    'board_title' => 'לוח מיטות — :event',
    'call_mat_tbc' => 'המיטה שלך',
    'call_opponent_tbc' => 'בשלב הבא',
    'call_room_body' => ':mat · match :bout · נגד :opponent',
    'call_room_title' => 'דווח לחדר הקריאה — :mat',
    'call_warmup_body' => ':ahead מ.MATCHים לפנייך · בערך :minutes דק',
    'call_warmup_title' => 'התכנת להתאמן — אתה על :mat בקרוב',
    'day_mats' => 'יום :day: :count מיטות',
    'draw_arranged' => 'המערך עודכן 🥋',
    'draw_cleared' => 'המערך נמחק — כל המשתתף חזר לרשימה',
    'draw_final' => 'המפעל החל — המערך הוא نهائي ולא ניתן לחדש.',
    'draw_generated' => 'המערך הושלם באופן זמני',
    'end_next_bout_done' => ':winner מנצח על :court. המסכים על מיטה זו הוזכרו.',
    'end_next_bout_none' => 'אין match מוכן לסיום — כל match ממתין ל feeder.',
    'ended_locked' => 'המפעל הסתיים — התוצאות הן סופיות.',
    'gate_no_division' => 'קטגוריית המשקל שלך אינה אחת מהקטגוריות של המפעל הזה, לכן אינך مؤهل להשתתף בפעילות זו.',
    'gate_no_division_spectator' => 'קטגוריית המשקל שלך אינה אחת מהקטגוריות של המפעל הזה, לכן אינך יכול להשתתף — אך מוזמן להשתתף כצופים.',
    'gate_no_profile' => 'הוסף את המין ואת תאריך הלידה שלך לפרופיל כדי שנוכל למקם אותך בקטגוריה משקלית.',
    'gate_no_weight' => 'הוסף את המשקל הנוכחי שלך לפרופיל הבריאות כדי שנוכל למקם אותך בקטגוריה משקלית.',
    'next_up_ahead' => 'matchים לפנייך',
    'next_up_done' => 'סיימת ליום.',
    'next_up_estimate' => 'הערכה, מזיזים עם המיטה',
    'next_up_finished' => 'הסתיים',
    'next_up_none' => 'אין לך nada מתוכנן כרגע.',
    'next_up_opponent_tbc' => 'ממתין ליריב',
    'next_up_squad' => 'הקבוצה שלי',
    'next_up_title' => 'match הבא שלי',
    'next_up_you_are_next' => 'אתה הבא — לך למיטה',
    'notify_draw_body' => 'היריב שלך, המיטה והמספר של המatch עכשיו פורסמו.',
    'notify_draw_title' => 'המערך מפורסם — :title',
    'notify_weigh_in_body' => 'בדיקה משקל רשמית ב-:time, :place. עליך להגיע למגבלת הקטגוריה שלך כדי להשתתף.',
    'notify_weigh_in_title' => 'בדיקה משקל מחר — :title',
    'result_body_done' => 'זו הייתה match האחרונה של היום.',
    'result_body_next' => 'הבא: :round על :mat, בערך :minutes דק',
    'result_loss_title' => 'match הסתיים',
    'result_win_title' => 'הרווחת 🎉',
    'roster_registered' => 'רשום',
    'roster_unclassified' => 'ללא קטגוריה',
    'type_label' => 'מפעל טאיקונדו',

];
