<?php

namespace App\Translation\Services;

/**
 * Puts a generated language file on disk — or refuses to.
 *
 * ⚠️ THE HARD GATE. A lang file that does not parse is a fatal error on EVERY
 * page for that locale, so nothing reaches `lang/` until it has been written to
 * a temporary path, linted, executed in an ISOLATED process, and compared key
 * for key against the English it came from. A generated file that fails any of
 * those is deleted and the locale keeps whatever it had.
 *
 * The isolated `require` matters more than it looks: a syntax error is caught
 * by `php -l`, but a file that parses and then throws — or emits output, or
 * returns a string — only shows itself when something runs it, and running it
 * in THIS process would poison the request that is checking it.
 */
class LangFileWriter
{
    /**
     * Merge translations into a locale's file and save it.
     *
     * @param  array<string,string>  $existing    what the file already holds
     * @param  array<string,string>  $translated  the new strings
     * @return array{written: int, kept: int, error: ?string}
     */
    public function write(string $target, array $existing, array $translated): array
    {
        /*
         * ⚠️ EXISTING KEYS WIN. Anything already in the file was either
         * hand-written or reviewed, and a re-run must never quietly replace it
         * — the same promise `Translations::correct()` makes for content, for
         * the same reason. `translate:interface --rewrite` is the explicit way
         * to overrule it.
         */
        $merged = $existing + $translated;
        $written = count(array_diff_key($translated, $existing));

        ksort($merged);

        $php = $this->render($merged, basename($target, '.php'));

        $temp = tempnam(sys_get_temp_dir(), 'lang').'.php';
        file_put_contents($temp, $php);

        try {
            if ($error = $this->rejectFile($temp, $merged)) {
                return ['written' => 0, 'kept' => count($existing), 'error' => $error];
            }

            $dir = dirname($target);

            if (! is_dir($dir) && ! @mkdir($dir, 0775, true) && ! is_dir($dir)) {
                return ['written' => 0, 'kept' => count($existing), 'error' => 'could not create '.$dir];
            }

            // Atomic: the file is complete the instant it appears, so a page
            // rendering mid-write can never see half of it.
            if (! @rename($temp, $target)) {
                return ['written' => 0, 'kept' => count($existing), 'error' => 'could not move into '.$target];
            }

            @chmod($target, 0664);

            return ['written' => $written, 'kept' => count($existing), 'error' => null];
        } finally {
            if (is_file($temp)) {
                @unlink($temp);
            }
        }
    }

    /**
     * Is this file safe to install? Returns the reason it is not, or null.
     *
     * @param  array<string,string>  $expected
     */
    private function rejectFile(string $path, array $expected): ?string
    {
        // 1. Does it parse at all?
        exec('php -l '.escapeshellarg($path).' 2>&1', $out, $code);

        if ($code !== 0) {
            return 'does not parse: '.trim(implode(' ', $out));
        }

        /*
         * 2. Does it RUN, and return what a lang file must return? Executed in
         * a separate process so a file that throws, echoes, or exits cannot
         * take down the process doing the checking.
         */
        $probe = '$d = require '.var_export($path, true).';'
            .'if (!is_array($d)) { fwrite(STDERR, "not an array"); exit(1); }'
            .'echo count($d);';

        exec('php -r '.escapeshellarg($probe).' 2>&1', $runOut, $runCode);

        if ($runCode !== 0) {
            return 'fails to load: '.trim(implode(' ', $runOut));
        }

        // 3. Every key present, and no key invented. A count is enough here —
        // the per-key comparison already happened in LangFileValidator.
        if ((int) trim(implode('', $runOut)) !== count($expected)) {
            return 'key count changed on load (a duplicate key, or a key PHP folded)';
        }

        return null;
    }

    /**
     * Render the array as PHP, in the same shape as the hand-written files so a
     * diff between `lang/en` and a generated locale reads normally.
     *
     * @param  array<string,string>  $strings
     */
    private function render(array $strings, string $group): string
    {
        $lines = [
            '<?php',
            '',
            '/*',
            '|--------------------------------------------------------------------------',
            '| '.$group.' — machine translated',
            '|--------------------------------------------------------------------------',
            '|',
            '| Generated by `php artisan translate:interface`, and validated against',
            '| lang/en/'.$group.'.php before it was written: placeholders, plural',
            '| forms, HTML tags and numbers all had to survive.',
            '|',
            '| (The header deliberately names no class. These files live inside event',
            '|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a',
            '|  private class name in a comment here fails the build for a reference',
            '|  that does not exist.)',
            '|',
            '| SAFE TO EDIT. A key you change here is never overwritten by a later',
            '| run — the generator only ever fills in keys that are absent. Correct',
            '| anything that reads badly; it will stay corrected.',
            '|',
            '| A key missing from this file falls back to English on its own, per key,',
            '| so this file is useful even when it is incomplete.',
            '*/',
            '',
            'return [',
            '',
        ];

        foreach ($strings as $key => $value) {
            $lines[] = '    '.var_export((string) $key, true).' => '.var_export((string) $value, true).',';
        }

        $lines[] = '';
        $lines[] = '];';

        return implode("\n", $lines)."\n";
    }
}
