<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'belt_black' => '黑',
    'belt_blue' => '蓝色',
    'belt_brown' => '棕',
    'belt_purple' => '紫',
    'belt_white' => '白',
    'corner_blue' => '蓝方',
    'corner_white' => '白方',
    'division_label' => '体重级别',
    'mat' => '场地',
    'official_mat_organiser' => '场地组织者',
    'official_mat_organiser_hint' => '负责场地运行和安排：叫运动员上场。',
    'official_referee' => '裁判',
    'official_referee_hint' => '在场地中主持比赛：开始和停止比赛，并发出每次得分信号。',
    'official_scorekeeper' => '记分员',
    'official_scorekeeper_hint' => '在桌上输入分数、优势和罚分。',
    'official_timekeeper' => '计时员',
    'official_timekeeper_hint' => '负责计时：比赛时间、暂停和终场铃声。',
    'score_four' => '4分',
    'score_three' => '3分',
    'score_two' => '2分',
    'sport_label' => '巴西柔术',
    'weigh_in' => '称重',

];
