<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_arrange_draw' => 'Organizar sorteio',
    'action_clear_draw' => 'Esvaziar sorteio',
    'action_end_next_bout' => 'Terminar o próximo combate (teste)',
    'action_generate_draw' => 'Gerar sorteio',
    'board_heading' => 'Ordem de entrada',
    'board_idle' => 'Nenhum combate em curso',
    'board_live' => 'Ao vivo',
    'board_on_deck' => 'A seguir',
    'board_stale' => 'A reconectar',
    'board_title' => 'Quadro do tatame — :event',
    'call_mat_tbc' => 'o seu tatame',
    'call_opponent_tbc' => 'A confirmar',
    'call_room_body' => ':mat · combate :bout · vs :opponent',
    'call_room_title' => 'Apresente-se na sala de chamada — :mat',
    'call_warmup_body' => ':ahead combates à sua frente · cerca de :minutes min',
    'call_warmup_title' => 'Aqueça — entra em breve no :mat',
    'day_mats' => 'Dia :day: :count tatames',
    'draw_arranged' => 'Sorteio atualizado 🥋',
    'draw_cleared' => 'Sorteio esvaziado — todos os inscritos voltaram à lista',
    'draw_final' => 'O campeonato já começou — o sorteio é final e não pode ser gerado novamente.',
    'draw_generated' => 'Sorteio provisório gerado',
    'end_next_bout_done' => ':winner vence no :court. Os ecrãs desse tatame foram notificados.',
    'end_next_bout_none' => 'Não há nenhum combate pronto a terminar — todos os combates em fila aguardam resultados anteriores.',
    'ended_locked' => 'Este campeonato terminou — os resultados são finais.',
    'gate_no_division' => 'A sua categoria de peso não consta das divisões deste campeonato, pelo que não pode competir neste evento.',
    'gate_no_division_spectator' => 'A sua categoria de peso não consta das divisões deste campeonato, pelo que não pode competir — mas é bem-vindo como espectador.',
    'gate_no_profile' => 'Adicione o seu género e data de nascimento ao perfil para o podermos colocar numa categoria de peso.',
    'gate_no_weight' => 'Adicione o seu peso atual ao perfil de saúde para o podermos colocar numa categoria de peso.',
    'next_up_ahead' => 'combates à frente',
    'next_up_done' => 'Terminou por hoje.',
    'next_up_estimate' => 'estimativa, varia com o tatame',
    'next_up_finished' => 'Terminado',
    'next_up_none' => 'Não tem nada agendado neste momento.',
    'next_up_opponent_tbc' => 'À espera de adversário',
    'next_up_squad' => 'A minha equipa',
    'next_up_title' => 'O meu próximo combate',
    'next_up_you_are_next' => 'É o próximo — vá para o tatame',
    'notify_draw_body' => 'O seu adversário, tatame e número de combate já estão publicados.',
    'notify_draw_title' => 'O sorteio já saiu — :title',
    'notify_weigh_in_body' => 'Pesagem oficial às :time, :place. Tem de cumprir o limite da sua divisão para competir.',
    'notify_weigh_in_title' => 'Pesagem amanhã — :title',
    'result_body_done' => 'Foi o seu último combate do dia.',
    'result_body_next' => 'Seguinte: :round no :mat, cerca de :minutes min',
    'result_loss_title' => 'Combate terminado',
    'result_win_title' => 'Venceu 🎉',
    'roster_registered' => 'Inscrito',
    'roster_unclassified' => 'Sem classificação',
    'type_label' => 'Campeonato de Taekwondo',

];
