<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_arrange_draw' => 'Çekiliş düzenle',
    'action_clear_draw' => 'Çekilişi temizle',
    'action_end_next_bout' => 'Sonraki maçı bitir',
    'action_generate_draw' => 'Çekiliş oluştur',
    'call_mat_tbc' => 'sahneniz',
    'call_opponent_tbc' => 'Yapılacak',
    'call_room_body' => ':mat · maç :bout · :opponent ile',
    'call_room_title' => 'Çağrı odasına git — :mat',
    'call_warmup_body' => ':ahead maçınız var · yaklaşık :minutes dakika',
    'call_warmup_title' => 'Isınma — :mat sahnesinde yakında',
    'day_mats' => 'Gün :day: :count sahne',
    'draw_arranged' => 'Çekiliş güncellendi 🥋',
    'draw_cleared' => 'Çekiliş boşaltıldı — her katılımcı listede tekrar yer aldı',
    'draw_final' => 'Şampiyonluk başladı — çekiliş son ve yeniden oluşturulamaz.',
    'draw_generated' => 'Geçici çekiliş oluşturuldu',
    'end_next_bout_done' => ':winner :court sahnesinde kazandı. Bu sahnedeki ekranlara bildirildi.',
    'end_next_bout_none' => 'Bitirilecek bir maç yok — sıradaki her maç besleme bekliyor.',
    'ended_locked' => 'Bu şampiyonluk sona erdi — sonuçları son ve değişmez.',
    'gate_no_division' => 'Ağırlık sınıfınız bu şampiyonluğun bölümlerinden biri değil, bu yüzden bu etkinlikte yarışamazsınız.',
    'gate_no_division_spectator' => 'Ağırlık sınıfınız bu şampiyonluğun bölümlerinden biri değil, bu yüzden yarışamazsınız — ama izleyici olarak katılabilirsiniz.',
    'gate_no_profile' => 'Profilinize cinsiyetinizi ve doğum tarihinizi ekleyin ki ağırlık sınıfınıza yerleştirilebilsin.',
    'gate_no_weight' => 'Profilinize mevcut ağırlığınızı ekleyin ki ağırlık sınıfınıza yerleştirilebilsin.',
    'notify_draw_body' => 'Bölümünüz çekildi. Rakibinizi, sahneyi ve maç numarasını görmek için etkinliği açın.',
    'notify_draw_title' => 'Çekiliş yayınlandı — :title',
    'notify_weigh_in_body' => 'Ağırlık kontrolü :time saat :place konumunda başlıyor. Kimlik belgenizi getirin.',
    'notify_weigh_in_title' => 'Yarın ağırlık kontrolü — :title',
    'result_body_done' => 'Bugünün son maçınız.',
    'result_body_next' => 'Sonraki: :round :mat sahnesinde, yaklaşık :minutes dakika',
    'result_loss_title' => 'Maç bitti',
    'result_win_title' => 'Kazandınız 🎉',
    'roster_registered' => 'Kayıtlı',
    'roster_unclassified' => 'Sınıflandırılmamış',
    'type_label' => 'Jiu-Jitsu Şampiyonluğu',

];
