<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'corner_chung' => 'CHUNG',
    'corner_hong' => 'HONG',
    'division_label' => 'Categoría de peso',
    'mat' => 'Mata',
    'official_center_referee' => 'Árbitro central',
    'official_center_referee_hint' => 'Dirige la pelea en el centro de la pista.',
    'official_corner_judge' => 'Juez de rincón :n',
    'official_corner_judge_hint' => 'Evalúa desde un rincón de la pista.',
    'official_court_supervisor' => 'Supervisor de pista',
    'official_court_supervisor_hint' => 'Supervisa la pista y sus funcionarios.',
    'official_review_jury' => 'Juria de revisión',
    'official_review_jury_hint' => 'Resuelve las solicitudes de revisión por video.',
    'official_table_recorder' => 'Registrador de mesa',
    'official_table_recorder_hint' => 'Mantiene el registro oficial en la mesa.',
    'official_timekeeper' => 'Cronometrista',
    'official_timekeeper_hint' => 'Mantiene el reloj: tiempo de ronda, paradas y campana.',
    'score_body_kick' => 'Patada de cuerpo',
    'score_head_kick' => 'Patada de cabeza',
    'score_punch' => 'Puño',
    'score_turning_body' => 'Patada de cuerpo giratoria',
    'score_turning_head' => 'Patada de cabeza giratoria',
    'sport_label' => 'Taekwondo',
    'weigh_in' => 'Peso de entrada',

];
