<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_arrange_draw' => '安排抽签',
    'action_clear_draw' => '空抽签',
    'action_end_next_bout' => '结束下一场比赛（测试）',
    'action_generate_draw' => '生成抽签',
    'board_heading' => '赛程安排',
    'board_idle' => '无进行中的比赛',
    'board_live' => '直播中',
    'board_on_deck' => '候场中',
    'board_stale' => '正在重新连接',
    'board_title' => '比赛台 —— :event',
    'call_mat_tbc' => '您的比赛台',
    'call_opponent_tbc' => '待定',
    'call_room_body' => ':mat · 比赛 :bout · 对阵 :opponent',
    'call_room_title' => '前往候场室 —— :mat',
    'call_warmup_body' => ':ahead 比赛在您之前 · 大约 :minutes 分钟',
    'call_warmup_title' => '热身中——您即将在 :mat 上比赛',
    'day_mats' => '第 :day: 天：:count 个比赛台',
    'draw_arranged' => '抽签已更新 🥋',
    'draw_cleared' => '抽签已清空——所有参赛者都回到名单中',
    'draw_final' => '锦标赛已经开始——抽签已最终确定，无法重新生成。',
    'draw_generated' => '临时抽签已生成',
    'end_next_bout_done' => ':winner 在 :court 获胜。该比赛台的屏幕已更新。',
    'end_next_bout_none' => '没有比赛可以结束——所有排队的比赛仍在等待裁判。',
    'ended_locked' => '此锦标赛已结束——其结果为最终结果。',
    'gate_no_division' => '您的体重级别不在该锦标赛的参赛级别中，因此您不符合参加本次活动的资格。',
    'gate_no_division_spectator' => '您的体重级别不在该锦标赛的参赛级别中，因此您无法参赛——但欢迎您作为观众出席。',
    'gate_no_profile' => '请在您的个人资料中添加性别和出生日期，以便我们将您分配到合适的体重级别。',
    'gate_no_weight' => '请在您的健康档案中添加当前体重，以便我们将您分配到合适的体重级别。',
    'next_up_ahead' => '场次在前',
    'next_up_done' => '您当天的比赛已结束。',
    'next_up_estimate' => '估计，随比赛台移动',
    'next_up_finished' => '已完成',
    'next_up_none' => '目前没有为您安排的比赛。',
    'next_up_opponent_tbc' => '等待对手',
    'next_up_squad' => '我的队伍',
    'next_up_title' => '我的下一场比赛',
    'next_up_you_are_next' => '轮到您了——前往比赛台',
    'notify_draw_body' => '您的对手、比赛台和比赛编号现已公布。',
    'notify_draw_title' => '抽签已公布 —— :title',
    'notify_weigh_in_body' => '正式称重时间：:time，地点：:place。您必须达到所属级别的体重限制才能参赛。',
    'notify_weigh_in_title' => '明天称重 —— :title',
    'result_body_done' => '这是您当天的最后一场比赛。',
    'result_body_next' => '下一场：:round 在 :mat 上，大约 :minutes 分钟',
    'result_loss_title' => '比赛结束',
    'result_win_title' => '您获胜了 🎉',
    'roster_registered' => '已注册',
    'roster_unclassified' => '未分类',
    'type_label' => '跆拳道锦标赛',

];
