<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'corner_aka' => 'AKA',
    'corner_ao' => 'AO',
    'division_label' => 'Categoría de peso',
    'mat' => 'Pista',
    'official_judge' => 'Juez :n (Fukushin)',
    'official_judge_hint' => 'Se sienta en una esquina y marca los puntos que observa.',
    'official_match_supervisor' => 'Supervisor de combate (Kansa)',
    'official_match_supervisor_hint' => 'Observa a los árbitros y resuelve protestas.',
    'official_referee' => 'Árbitro (Shushin)',
    'official_referee_hint' => 'Dirige el combate en la pista: inicia y detiene el tiempo, y anuncia los puntos.',
    'official_scorekeeper' => 'Marcador de puntos',
    'official_scorekeeper_hint' => 'Registra los puntos y las infracciones en el formulario.',
    'official_tatami_manager' => 'Administrador de tatami',
    'official_tatami_manager_hint' => 'Mantiene la pista en funcionamiento según el horario y llama a los atletas.',
    'official_timekeeper' => 'Cronometrador',
    'official_timekeeper_hint' => 'Controla el cronómetro: tiempo del combate, paradas y campana final.',
    'score_ippon' => 'Ippon',
    'score_wazari' => 'Waza-ari',
    'score_yuko' => 'Yuko',
    'sport_label' => 'Karate',
    'weigh_in' => 'Peso de inscripción',

];
