<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'corner_chung' => 'CHUNG',
    'corner_hong' => 'HONG',
    'division_label' => 'Ağırlık kategorisi',
    'mat' => 'Masa',
    'official_center_referee' => 'Merkez hakem',
    'official_center_referee_hint' => 'Masanın ortasında maç yürüten.',
    'official_corner_judge' => 'Köşe hakemi :n',
    'official_corner_judge_hint' => 'Masanın bir köşesinden skor yapan.',
    'official_court_supervisor' => 'Saha sorumlusu',
    'official_court_supervisor_hint' => 'Sahayı ve yetkilileri denetleyen.',
    'official_review_jury' => 'İnceleme jürisi',
    'official_review_jury_hint' => 'Video inceleme taleplerini yöneten.',
    'official_table_recorder' => 'Tablo kaydedici',
    'official_table_recorder_hint' => 'Tabloda resmi kayıtları tutan.',
    'official_timekeeper' => 'Saat tutan',
    'official_timekeeper_hint' => 'Saat tutar: round süresi, duraklamalar ve zil.',
    'score_body_kick' => 'Gövde tekmesi',
    'score_head_kick' => 'Yüz tekmesi',
    'score_punch' => 'Yumruk',
    'score_turning_body' => 'Gövde çevirme tekmesi',
    'score_turning_head' => 'Yüz çevirme tekmesi',
    'sport_label' => 'Taekwondo',
    'weigh_in' => 'Ağırlık kontrolü',

];
