<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_add_entrants' => 'Adicionar pessoas',
    'action_close' => 'Terminar sessão',
    'action_queue_bout' => 'Pôr combate em fila',
    'action_remove_entrant' => 'Remover pessoa',
    'action_set_mats' => 'Definir tatamis',
    'action_unqueue_bout' => 'Remover combate',
    'bout_fought' => 'Esse combate já foi realizado.',
    'bout_queued' => 'Em fila.',
    'bout_removed' => 'Removido da fila.',
    'console_add_people' => 'Adicionar pessoas',
    'console_add_selected' => 'Adicionar :n à sala',
    'console_bouts_today' => ':n hoje',
    'console_clear_pick' => 'Limpar',
    'console_closed' => 'Esta sessão terminou.',
    'console_end_confirm' => 'Terminar esta sessão de sparring? O placar para e a sessão é arquivada.',
    'console_end_session' => 'Terminar sessão',
    'console_floor' => 'Quem está presente',
    'console_floor_hint' => 'Toca em dois para os emparelhar',
    'console_fought' => 'Realizados',
    'console_fought_empty' => 'Ainda sem combates.',
    'console_mat_count' => 'A decorrer :n',
    'console_mats' => 'Tatamis',
    'console_mats_label' => 'Tatamis a decorrer',
    'console_no_members' => 'Nenhum membro encontrado.',
    'console_open_table' => 'Tabela de pontuação',
    'console_pair_hint' => 'Escolhe duas pessoas presentes',
    'console_pick_blue' => 'Canto azul',
    'console_pick_red' => 'Canto vermelho',
    'console_queue' => 'Fila',
    'console_queue_empty' => 'Nada em fila neste tatami.',
    'console_queue_it' => 'Pôr combate em fila',
    'console_screens' => 'Ecrãs da sala',
    'console_search_members' => 'Pesquisar membros',
    'console_table_needs_bout' => 'Põe um combate em fila neste tatami para abrir a tabela de pontuação.',
    'entrant_queued' => 'Está num combate que ainda não foi realizado.',
    'entrant_removed' => 'Retirado da sala.',
    'entrants_added' => 'Adicionado à sala.',
    'label' => 'Sparring',
    'launch_bouts_n' => ':n combates',
    'launch_eyebrow' => 'Placar de treino',
    'launch_lead' => 'Coloca duas pessoas num tatami e a sala vê a pontuação. Sem chave, sem inscrições — abre agora, fecha quando o treino terminar.',
    'launch_mats' => 'Quantos tatamis',
    'launch_minutes' => 'Duração do combate',
    'launch_minutes_n' => ':n min',
    'launch_no_sport' => 'Este clube ainda não tem modalidade com placar de tatami.',
    'launch_open_since' => 'Aberta desde :time',
    'launch_past' => 'Sessões anteriores',
    'launch_past_none' => 'Ainda sem sessões.',
    'launch_resume' => 'Abrir sessão de hoje',
    'launch_running' => 'A decorrer',
    'launch_sport' => 'Que modalidade',
    'launch_start' => 'Iniciar sparring',
    'launch_title' => 'Sparring',
    'mat_n' => 'Tatami :n',
    'mats_saved' => 'Tatamis atualizados.',
    'same_person' => 'Escolhe duas pessoas diferentes.',
    'session_closed' => 'Esta sessão terminou.',
    'session_ended' => 'Sessão terminada.',
    'session_title' => 'Sparring · :date',
    'unknown_entrant' => 'Ambos os cantos têm de estar na sala primeiro.',
    'unknown_mat' => 'Este tatami não faz parte desta sessão.',

];
