<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'add_language' => 'Bir dil ekle',
    'choose_language' => 'Bir dil seçin',
    'complete' => ':done / :total',
    'continue_anyway' => 'Orijinalinde devam et',
    'edited_by_you' => 'Düzenlediğiniz versiyon',
    'field_about' => 'Bu etkinlik hakkında',
    'field_cta' => 'Düğme metni',
    'field_division' => 'Bölüm',
    'field_fee' => 'Ücret satırı',
    'field_level' => 'Seviye',
    'field_location' => 'Konum',
    'field_prize' => 'Ödül',
    'field_requirement' => 'Gereklilik',
    'field_ribbon' => 'Şerit',
    'field_title' => 'Başlık',
    'interface_note' => 'Etkinlik :language ile yazılmış. Düğmeler ve etiketler İngilizce kalır.',
    'languages' => 'Diller',
    'languages_sub' => 'Bu etkinliğin her dildeki yazılışı',
    'machine' => 'Otomatik',
    'more_languages' => 'Başka bir dil',
    'needs_review' => 'İnceleme gerekiyor',
    'needs_review_note' => 'Bu yazılmadan sonra orijinal değişti.',
    'no_language_found' => 'Bu kriterlere uyan dil bulunamadı.',
    'no_provider' => 'Yapay zeka sağlayıcısı yapılandırılmadı. Çeviriler yazılmadan önce Admin → AI Sağlayıcılar altına bir tane ekleyin.',
    'not_translated' => 'Henüz çevrilmemiş',
    'nothing_yet' => 'Bu etkinliği başka bir dilde okuyan kimse yok.',
    'nothing_yet_note' => 'Halk sayfasından biri bir dil seçtiğinde, o anda yazılmış ve saklanır.',
    'preparing' => ':language hazırlanıyor…',
    'preparing_failed' => 'Şu anda :language hazırlanamadı. Orijinal gösteriliyor.',
    'preparing_note' => 'Bu etkinlik :language ile yazıldı. Sadece bir kez olur — sizden sonra gelen herkes hemen alır.',
    'queued' => 'Sırada. Birazdan hazır olacak.',
    'read_in' => 'Bunu şu dilde oku',
    'remove_language' => 'Bu dili kaldır',
    'remove_language_confirm' => ':language kaldırılsın mı? Kendi düzeltmeleriniz de silinir. Makine çevirisi yeniden oluşturulabilir; düzeltmeleriniz olmaz.',
    'removed' => 'Dil kaldırıldı.',
    'retranslate' => 'Yeniden çevir',
    'saved' => 'Kaydedildi.',
    'search_languages' => 'Dil ara',
    'source_language' => ':language ile yazılmış',
    'translated_by_ai' => 'Otomatik çevrildi',

];
