<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'corner_aka' => 'أكا',
    'corner_ao' => 'آو',
    'division_label' => 'الفئة الوزنية',
    'mat' => 'بساط',
    'official_judge' => 'حكم زاوية :n (فوكوشين)',
    'official_judge_hint' => 'يجلس في الزاوية ويشير إلى النقاط التي يراها.',
    'official_match_supervisor' => 'مراقب المباراة (كانسا)',
    'official_match_supervisor_hint' => 'يراقب الحكام ويحسم الاعتراضات.',
    'official_referee' => 'حكم الوسط (شوشين)',
    'official_referee_hint' => 'يدير النزال على البساط: يبدأه ويوقفه ويعلن النقاط.',
    'official_scorekeeper' => 'مسجّل النقاط',
    'official_scorekeeper_hint' => 'يسجّل النقاط والعقوبات في الكشف.',
    'official_tatami_manager' => 'مدير البساط',
    'official_tatami_manager_hint' => 'ينظّم سير البساط ويستدعي اللاعبين.',
    'official_timekeeper' => 'مسجّل الوقت',
    'official_timekeeper_hint' => 'يضبط الوقت: زمن النزال والتوقفات وصافرة النهاية.',
    'score_ippon' => 'إيبون',
    'score_wazari' => 'وازا-آري',
    'score_yuko' => 'يوكو',
    'sport_label' => 'الكاراتيه',
    'weigh_in' => 'الوزن الرسمي',

];
