<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_arrange_draw' => 'Pêşniyekê saz bike',
    'action_clear_draw' => 'Pêşniyekê vala',
    'action_end_next_bout' => 'Pêşniyekê ya pêşîn bidawîne (test)',
    'action_generate_draw' => 'Çêkirina pêşniyê',
    'board_heading' => 'Rêzeya xebitandinê',
    'board_idle' => 'Ne pêşniyekê li xebitandinê',
    'board_live' => 'Li xebitandinê',
    'board_on_deck' => 'Li pêş',
    'board_stale' => 'Dîsa tê girêdan',
    'board_title' => 'Rûpela mat — :event',
    'call_mat_tbc' => 'matê xwe',
    'call_opponent_tbc' => 'TBC',
    'call_room_body' => ':mat · pêşniyek :bout · vs :opponent',
    'call_room_title' => 'Bêjî rûpela pêşniyek — :mat',
    'call_warmup_body' => ':ahead pêşniyekên pêşî · biqûl :minutes min',
    'call_warmup_title' => 'Bikin pêşniyek — hûn li :mat yên nêzîk in',
    'day_mats' => 'Roj :day: :count mats',
    'draw_arranged' => 'Pêşniyek hate nûvekirin 🥋',
    'draw_cleared' => 'Pêşniyek hate vala kirin — her kes li listeyê dîsa ye',
    'draw_final' => 'Şampiyonîyek hat destpêkirin — pêşniyek hatiye danîn û nikare were çêkirin.',
    'draw_generated' => 'Pêşniyekê provîzorî çêbû',
    'end_next_bout_done' => ':winner wins on :court. The screens on that mat have been told.',
    'end_next_bout_none' => 'Ne pêşniyekê hatiye dawîn — hemû pêşniyekên hatiye pêşniyek kirin hîn li xebitandinê.',
    'ended_locked' => 'Vê şampiyonîyê hatiye dawîn — encamên wê hatiye danîn.',
    'gate_no_division' => 'Kategoriyê ağırlîkê xwe ne yek ji pêşniyaran ya vê şampiyonîyê ye, ji bo ku hûn bikarin pêşniyaran bikevin.',
    'gate_no_division_spectator' => 'Kategoriyê ağırlîkê xwe ne yek ji pêşniyaran ya vê şampiyonîyê ye, ji bo ku hûn nikarin pêşniyaran bikevin — lê hûn dikarin wekî şahedan bigerin.',
    'gate_no_profile' => 'Ji bo ku em bikarin hûn li kategoriyê xwe bigirin, jins û dîroka lêdanê xwe li profîla xwe zêde bikin.',
    'gate_no_weight' => 'Ji bo ku em bikarin hûn li kategoriyê xwe bigirin, ağırlîkê xwe li profîla xwe zêde bikin.',
    'next_up_ahead' => 'pêşniyekên pêşî',
    'next_up_done' => 'Hûn hatiye dawîn.',
    'next_up_estimate' => 'estimate, moves with the mat',
    'next_up_finished' => 'Hate dawîn',
    'next_up_none' => 'Hê jî ne pêşniyekê hatiye nîşan dan.',
    'next_up_opponent_tbc' => 'Têketî',
    'next_up_squad' => 'Koma min',
    'next_up_title' => 'Pêşniyekê xwe',
    'next_up_you_are_next' => 'Hûn yên pêşîn — biçe mat',
    'notify_draw_body' => 'Rivîsî, mat û hejmarê pêşniyê xwe hatiye nîşan dan.',
    'notify_draw_title' => 'Pêşniyek hate nîşan dan — :title',
    'notify_weigh_in_body' => 'Pêşniyekê resmî li :time, :place. Hûn divê limita kategoriyê xwe bikevin.',
    'notify_weigh_in_title' => 'Pêşniyekê rojî — :title',
    'result_body_done' => 'Ev wê pêşniyekê ya dawîn ya rojê ye.',
    'result_body_next' => 'Pêş: :round li :mat, biqûl :minutes min',
    'result_loss_title' => 'Pêşniyek hate dawîn',
    'result_win_title' => 'Hûn vê wînîn 🎉',
    'roster_registered' => 'Têketî',
    'roster_unclassified' => 'Bêpêşniyî',
    'type_label' => 'Şampiyonîya Karateyê',

];
