<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_arrange_draw' => 'Organizar chave',
    'action_clear_draw' => 'Limpar chave',
    'action_end_next_bout' => 'Terminar próximo combate',
    'action_generate_draw' => 'Gerar chave',
    'call_mat_tbc' => 'o seu tatame',
    'call_opponent_tbc' => 'A confirmar',
    'call_room_body' => ':mat · combate :bout · vs :opponent',
    'call_room_title' => 'Apresente-se na sala de chamada — :mat',
    'call_warmup_body' => ':ahead combates antes de você · cerca de :minutes min',
    'call_warmup_title' => 'Aqueça — vai entrar em breve no :mat',
    'day_mats' => 'Dia :day: :count tatames',
    'draw_arranged' => 'Chave atualizada 🥋',
    'draw_cleared' => 'Chave esvaziada — todos os inscritos voltaram à lista',
    'draw_final' => 'O campeonato já começou — a chave é final e não pode ser gerada novamente.',
    'draw_generated' => 'Chave provisória gerada',
    'end_next_bout_done' => ':winner vence no :court. Os ecrãs desse tatame foram atualizados.',
    'end_next_bout_none' => 'Nenhum combate está pronto para terminar — todos os combates em fila aguardam resultados anteriores.',
    'ended_locked' => 'Este campeonato terminou — os resultados são finais.',
    'gate_no_division' => 'A sua categoria de peso não faz parte das divisões deste campeonato, por isso não pode competir neste evento.',
    'gate_no_division_spectator' => 'A sua categoria de peso não faz parte das divisões deste campeonato, por isso não pode competir — mas pode assistir como espectador.',
    'gate_no_profile' => 'Adicione o seu género e data de nascimento ao seu perfil para podermos atribuir-lhe uma categoria de peso.',
    'gate_no_weight' => 'Adicione o seu peso atual ao seu perfil de saúde para podermos atribuir-lhe uma categoria de peso.',
    'notify_draw_body' => 'A sua divisão foi sorteada. Abra o evento para ver o adversário, o tatame e o número do combate.',
    'notify_draw_title' => 'A chave já saiu — :title',
    'notify_weigh_in_body' => 'A pesagem abre às :time em :place. Traga a sua identificação.',
    'notify_weigh_in_title' => 'Pesagem amanhã — :title',
    'result_body_done' => 'Foi o seu último combate do dia.',
    'result_body_next' => 'A seguir: :round no :mat, cerca de :minutes min',
    'result_loss_title' => 'Combate terminado',
    'result_win_title' => 'Venceu 🎉',
    'roster_registered' => 'Inscrito',
    'roster_unclassified' => 'Sem categoria',
    'type_label' => 'Campeonato de Jiu-Jitsu',

];
