<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'add_language' => 'Shto një gjuhë',
    'choose_language' => 'Zgjidhni një gjuhë',
    'complete' => ':done nga :total',
    'continue_anyway' => 'Vazhdoni në origjinal',
    'edited_by_you' => 'Redaktuar nga ju',
    'field_about' => 'Rreth kësaj ngjarjeje',
    'field_cta' => 'Teksti i butonit',
    'field_division' => 'Pjesa',
    'field_fee' => 'Rreshti i pagesës',
    'field_level' => 'Niveli',
    'field_location' => 'Vendndodhja',
    'field_prize' => 'Kursi',
    'field_requirement' => 'Kërkesa',
    'field_ribbon' => 'Ribbon',
    'field_title' => 'Titulli',
    'interface_note' => 'Ngjarja është në :language. Butonat dhe etiketat mbeten në anglisht.',
    'languages' => 'Gjuhët',
    'languages_sub' => 'Çfarë thotë kjo ngjarje në çdo gjuhë që është lexuar',
    'machine' => 'Automatik',
    'more_languages' => 'Gjuhë tjetër',
    'needs_review' => 'Kërkon shqyrtim',
    'needs_review_note' => 'Origjinali ndryshoi pasi u shkrua kjo.',
    'no_language_found' => 'Asnjë gjuhë nuk përputhet me këtë.',
    'no_provider' => 'Asnjë ofrues AI nuk është konfiguruar. Shtoni një në Admin → Ofrues AI para se përkthimet të mund të shkruhen.',
    'not_translated' => 'Nuk është përkthyer ende',
    'nothing_yet' => 'Asnji nuk ka lexuar këtë ngjarje në gjuhë të tjera ende.',
    'nothing_yet_note' => 'Për momentin që dikush zgjedh një në faqen publike, ai shkruhet dhe mbahet.',
    'preparing' => 'Po përgatitet :language…',
    'preparing_failed' => 'Nuk mundëm të përgatitem :language sot. Duke shfaqur origjinalin.',
    'preparing_note' => 'Ky ngjarje është shkruar në :language. Kjo ndodh vetëm një herë — të gjithë pas juaj e marrin menjëherë.',
    'queued' => 'Në radhë. Do të jetë gati pas një momenti.',
    'read_in' => 'Lexo këtë në',
    'remove_language' => 'Hiq këtë gjuhë',
    'remove_language_confirm' => 'Hiq :language? Korrigjimet tuaja të kësaj fshihen gjithashtu. Përkthimi automatik mund të rikthehet; korrigjimet tuaja nuk mund të rikthehen.',
    'removed' => 'Gjuha u hoq.',
    'retranslate' => 'Përkthe përsëri',
    'saved' => 'Ruajtur.',
    'search_languages' => 'Kërko gjuhë',
    'source_language' => 'Shkruar në :language',
    'translated_by_ai' => 'Përkthyer automatikisht',

];
