<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_add_entrants' => 'افراد شامل کریں',
    'action_close' => 'سیشن ختم کریں',
    'action_queue_bout' => 'بائٹ کو قطار میں رکھیں',
    'action_remove_entrant' => 'فراد کو ہٹائیں',
    'action_set_mats' => 'میٹس سیٹ کریں',
    'action_unqueue_bout' => 'بائٹ کو ہٹائیں',
    'bout_fought' => 'یہ بائٹ پہلے ہی لڑی گئی ہے۔',
    'bout_queued' => 'قطار میں رکھا گیا۔',
    'bout_removed' => 'قطار سے ہٹا دیا گیا۔',
    'console_add_people' => 'افراد شامل کریں',
    'console_add_selected' => ':n کو فلور میں شامل کریں',
    'console_bouts_today' => ':n آج',
    'console_clear_pick' => 'صاف کریں',
    'console_closed' => 'یہ سیشن ختم ہو چکی ہے۔',
    'console_end_confirm' => 'کیا آپ یہ سپارنگ سیشن ختم کرنا چاہتے ہیں؟ اسکور بورڈ روک جائے گا اور سیشن ارکائیو ہو جائے گا۔',
    'console_end_session' => 'سیشن ختم کریں',
    'console_floor' => 'کون یہاں ہیں',
    'console_floor_hint' => 'دو کو جوڑنے کے لیے ٹیپ کریں',
    'console_fought' => 'لڑی گئی',
    'console_fought_empty' => 'ابھی تک کوئی بائٹ نہیں۔',
    'console_mat_count' => 'چل رہا :n',
    'console_mats' => 'میٹس',
    'console_mats_label' => 'میٹس چل رہے ہیں',
    'console_no_members' => 'کوئی ممبر نہیں ملا۔',
    'console_open_table' => 'اسکور ٹیبل',
    'console_pair_hint' => 'فلور سے دو افراد منتخب کریں',
    'console_pick_blue' => 'نیلا کونٹر',
    'console_pick_red' => 'لال کونٹر',
    'console_queue' => 'قطار',
    'console_queue_empty' => 'اس میٹ پر کوئی قطار نہیں۔',
    'console_queue_it' => 'اس بائٹ کو قطار میں رکھیں',
    'console_screens' => 'ہال اسکرینز',
    'console_search_members' => 'ممبروں کو تلاش کریں',
    'console_table_needs_bout' => 'اس میٹ پر بائٹ کو قطار میں رکھیں تاکہ اسکور ٹیبل کھولیں۔',
    'entrant_queued' => 'ونہاں ایک بائٹ ہے جو ابھی تک لڑی نہیں گئی۔',
    'entrant_removed' => 'فلور سے نکال دیا گیا۔',
    'entrants_added' => 'فلور میں شامل کر دیا گیا۔',
    'label' => 'سپارنگ',
    'launch_bouts_n' => ':n بائٹس',
    'launch_eyebrow' => 'ٹریننگ کے اسکور بورڈ',
    'launch_lead' => 'دو افراد کو ایک میٹ پر رکھیں اور ہال اسکور دیکھے گا۔ کوئی دراوازہ، کوئی اندراج نہیں — ابھی کھولیں، ٹریننگ ختم ہونے پر بند کریں۔',
    'launch_mats' => 'کتنے میٹس',
    'launch_minutes' => 'بائٹ کی لمبائی',
    'launch_minutes_n' => ':n منٹ',
    'launch_no_sport' => 'اس کلب کے پاس ابھی تک میٹ پر اسکور بورڈ کے ساتھ کوئی کھیل نہیں ہے۔',
    'launch_open_since' => ':time سے شروع ہونے والی سیشن',
    'launch_past' => 'پرانی سیشنز',
    'launch_past_none' => 'ابھی تک کوئی سیشن نہیں۔',
    'launch_resume' => 'آج کی سیشن کھولیں',
    'launch_running' => 'ابھی چل رہا ہے',
    'launch_sport' => 'کون سا کھیل',
    'launch_start' => 'سپارنگ شروع کریں',
    'launch_title' => 'سپارنگ',
    'mat_n' => 'میٹ :n',
    'mats_saved' => 'میٹس اپ ڈیٹ کر دیے گئے۔',
    'same_person' => 'دو مختلف افراد منتخب کریں۔',
    'session_closed' => 'یہ سیشن ختم ہو چکی ہے۔',
    'session_ended' => 'سیشن ختم ہو گئی۔',
    'session_title' => 'سپارنگ · :date',
    'unknown_entrant' => 'پہلے دونوں کونٹرز کو فلور پر رکھنا ہوگا۔',
    'unknown_mat' => 'یہ ایک میٹ نہیں ہے جو اس سیشن کے لیے چل رہا ہے۔',

];
