<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'add_language' => 'افزودن زبان',
    'choose_language' => 'زبان را انتخاب کنید',
    'complete' => ':done از :total',
    'continue_anyway' => 'ادامه با اصلی',
    'edited_by_you' => 'ویرایش شده توسط شما',
    'field_about' => 'درباره این رویداد',
    'field_cta' => 'متن دکمه',
    'field_division' => 'دیویژن',
    'field_fee' => 'خط هزینه',
    'field_level' => 'سطح',
    'field_location' => 'مکان',
    'field_prize' => 'جوایز',
    'field_requirement' => 'نیازمندی',
    'field_ribbon' => 'بند',
    'field_title' => 'عنوان',
    'interface_note' => 'این رویداد به زبان :language نوشته شده است. دکمه‌ها و برچسب‌ها به زبان انگلیسی باقی می‌مانند.',
    'languages' => 'زبان‌ها',
    'languages_sub' => 'این رویداد در همه زبان‌هایی که توسط کاربران خوانده شده است چه می‌گوید',
    'machine' => 'خودکار',
    'more_languages' => 'زبان دیگر',
    'needs_review' => 'نیازمند بازبینی',
    'needs_review_note' => 'نسخه اصلی پس از نوشتن این متن تغییر کرده است.',
    'no_language_found' => 'هیچ زبانی با این مشخصات یافت نشد.',
    'no_provider' => 'ارائه‌دهنده هوش مصنوعی پیکربندی نشده است. قبل از تولید ترجمه‌ها، یکی را در بخش مدیریت → ارائه‌دهندگان هوش مصنوعی اضافه کنید.',
    'not_translated' => 'هنوز ترجمه نشده',
    'nothing_yet' => 'هنوز کسی این رویداد را به زبان دیگری نخوانده است.',
    'nothing_yet_note' => 'به محض اینکه کسی آن را از صفحه عمومی انتخاب کند، نوشته شده و ذخیره می‌شود.',
    'preparing' => 'در حال آماده‌سازی :language…',
    'preparing_failed' => 'در حال حاضر نتوانستیم :language را آماده کنیم. نمایش نسخه اصلی.',
    'preparing_note' => 'این رویداد در :language نوشته شده است. تنها یک‌بار اتفاق می‌افتد — همه کسانی که بعد از شما آن را ببینند فوراً آن را دریافت می‌کنند.',
    'queued' => 'در صف قرار گرفته. تا چند لحظه دیگر آماده خواهد شد.',
    'read_in' => 'این را بخوانید به زبان',
    'remove_language' => 'حذف این زبان',
    'remove_language_confirm' => 'حذف :language؟ تصحیحات شما در آن نیز حذف خواهد شد. ترجمه ماشینی را می‌توان دوباره تولید کرد؛ اما ویرایش‌های شما قابل بازیابی نیستند.',
    'removed' => 'زبان حذف شد.',
    'retranslate' => 'ترجمه دوباره',
    'saved' => 'ذخیره شد.',
    'search_languages' => 'جستجوی زبان‌ها',
    'source_language' => 'نوشته شده به زبان :language',
    'translated_by_ai' => 'ترجمه شده به صورت خودکار',

];
