<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_add_entrants' => 'إضافة أشخاص',
    'action_close' => 'إنهاء الجلسة',
    'action_queue_bout' => 'إضافة نزال',
    'action_remove_entrant' => 'استبعاد شخص',
    'action_set_mats' => 'تحديد البُسط',
    'action_unqueue_bout' => 'إزالة نزال',
    'bout_fought' => 'هذا النزال خُضْ بالفعل.',
    'bout_queued' => 'أُضيف إلى القائمة.',
    'bout_removed' => 'أُزيل من القائمة.',
    'console_add_people' => 'إضافة أشخاص',
    'console_add_selected' => 'أضف :n إلى الحاضرين',
    'console_bouts_today' => ':n اليوم',
    'console_clear_pick' => 'مسح',
    'console_closed' => 'انتهت هذه الجلسة.',
    'console_end_confirm' => 'إنهاء جلسة المبارزة؟ تتوقف لوحة النتائج وتُؤرشف الجلسة.',
    'console_end_session' => 'إنهاء الجلسة',
    'console_floor' => 'الحاضرون',
    'console_floor_hint' => 'اختر اثنين لمواجهتهما',
    'console_fought' => 'ما تم خوضه',
    'console_fought_empty' => 'لا نزالات بعد.',
    'console_mat_count' => 'قيد التشغيل :n',
    'console_mats' => 'البُسط',
    'console_mats_label' => 'البُسط العاملة',
    'console_no_members' => 'لا يوجد أعضاء.',
    'console_open_table' => 'طاولة التحكيم',
    'console_pair_hint' => 'اختر شخصين من الحاضرين',
    'console_pick_blue' => 'الزاوية الزرقاء',
    'console_pick_red' => 'الزاوية الحمراء',
    'console_queue' => 'قائمة الانتظار',
    'console_queue_empty' => 'لا شيء في انتظار هذا البساط.',
    'console_queue_it' => 'أضف هذا النزال',
    'console_screens' => 'شاشات القاعة',
    'console_search_members' => 'ابحث عن الأعضاء',
    'console_table_needs_bout' => 'أضف نزالًا على هذا البساط لفتح طاولة التحكيم.',
    'entrant_queued' => 'لديه نزال لم يُخض بعد.',
    'entrant_removed' => 'تم الاستبعاد.',
    'entrants_added' => 'تمت الإضافة.',
    'label' => 'مبارزة',
    'launch_bouts_n' => ':n نزال',
    'launch_eyebrow' => 'لوحة نتائج التدريب',
    'launch_lead' => 'ضع لاعبين على البساط وترى القاعة النتيجة. بلا قرعة وبلا تسجيل — افتحها الآن وأغلقها بعد التدريب.',
    'launch_mats' => 'كم بساط',
    'launch_minutes' => 'مدة النزال',
    'launch_minutes_n' => ':n دقيقة',
    'launch_no_sport' => 'لا توجد في هذا النادي رياضة لها لوحة نتائج على البساط.',
    'launch_open_since' => 'مفتوحة منذ :time',
    'launch_past' => 'جلسات سابقة',
    'launch_past_none' => 'لا توجد جلسات بعد.',
    'launch_resume' => 'افتح جلسة اليوم',
    'launch_running' => 'جارية الآن',
    'launch_sport' => 'أي رياضة',
    'launch_start' => 'ابدأ المبارزة',
    'launch_title' => 'مبارزة',
    'mat_n' => 'بساط :n',
    'mats_saved' => 'تم تحديث البُسط.',
    'same_person' => 'اختر شخصين مختلفين.',
    'session_closed' => 'انتهت هذه الجلسة.',
    'session_ended' => 'انتهت الجلسة.',
    'session_title' => 'مبارزة · :date',
    'unknown_entrant' => 'يجب أن يكون الطرفان من الحاضرين.',
    'unknown_mat' => 'هذا ليس بساطًا في هذه الجلسة.',

];
