<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_arrange_draw' => 'Dîsînê saz bike',
    'action_clear_draw' => 'Dîsînê vala',
    'action_end_next_bout' => 'Dîsînê pêşînê bidawî bike (test)',
    'action_generate_draw' => 'Dîsînê çêke',
    'board_heading' => 'Rûpêşînê',
    'board_idle' => 'Dîsînên ku ne li pêşîn',
    'board_live' => 'Li xebitîn',
    'board_on_deck' => 'Li pêşîn',
    'board_stale' => 'Dîsînê dîsa',
    'board_title' => 'Matê rûpêşînê — :event',
    'call_mat_tbc' => 'matê xwe',
    'call_opponent_tbc' => 'TBC',
    'call_room_body' => ':mat · dîsîn :bout · vs :opponent',
    'call_room_title' => 'Ji bo rûpêşînê bidin hûn li rûpêşînê — :mat',
    'call_warmup_body' => ':ahead dîsînên pêşînên hûn · biqûl :minutes min',
    'call_warmup_title' => 'Pêşbûnê — hûn li :mat dê bêjin',
    'day_mats' => 'Roj :day: :count mats',
    'draw_arranged' => 'Dîsînê nûve kir 🥋',
    'draw_cleared' => 'Dîsînê vala kir — her kes li nav lîsteyê dîsa ye',
    'draw_final' => 'Şampiyonîya dest pê kir — dîsînê dawî ye û nikare were çêkirin.',
    'draw_generated' => 'Dîsînê pêşîn çêbû',
    'end_next_bout_done' => ':winner wins on :court. The screens on that mat have been told.',
    'end_next_bout_none' => 'Dîsînê tune ku bêjî — her dîsînê ku li pêşîn e dê bêjî.',
    'ended_locked' => 'Vê şampiyonîyê bidawî bû — encamên wê dawî ye.',
    'gate_no_division' => 'Kategorîya paqijê hûn ne li nav pêşniyazên vê şampiyonîyê de ye, ji bo ku em bikarin hûn li vê çalakîyê bide.',
    'gate_no_division_spectator' => 'Kategorîya paqijê hûn ne li nav pêşniyazên vê şampiyonîyê de ye, ji bo ku em bikarin hûn li vê çalakîyê bide, lê hûn dikarin wekî şahedan bidin.',
    'gate_no_profile' => 'Ji bo ku em bikarin hûn li kategorîya xwe ya paqijê bide, jins û dîroka lidê bêje.',
    'gate_no_weight' => 'Ji bo ku em bikarin hûn li kategorîya xwe ya paqijê bide, paqijê xwe bêje.',
    'next_up_ahead' => 'dîsînên pêşîn',
    'next_up_done' => 'Hûn bidawî bûn.',
    'next_up_estimate' => 'bîr, bi matê ve tê',
    'next_up_finished' => 'Qediya',
    'next_up_none' => 'Ji bo hûn niha çalakî tune.',
    'next_up_opponent_tbc' => 'Rivîsînê bêjî',
    'next_up_squad' => 'Koma min',
    'next_up_title' => 'Dîsînê pêşînê min',
    'next_up_you_are_next' => 'Hûn pêşîn — bidin matê',
    'notify_draw_body' => 'Rivîsînê, mat û hejmarê dîsînê hatiye nîşan dan.',
    'notify_draw_title' => 'Dîsînê derket — :title',
    'notify_weigh_in_body' => 'Paqijê rûpêşînî di :time, :place. Hûn divê paqijê xwe ya pêşniyazê bikin.',
    'notify_weigh_in_title' => 'Paqijê rûpêşînî roj — :title',
    'result_body_done' => 'Ev dîsînê ya rojê bû.',
    'result_body_next' => 'Pêşîn: :round li :mat, biqûl :minutes min',
    'result_loss_title' => 'Dîsînê qediya',
    'result_win_title' => 'Hûn vencîn 🎉',
    'roster_registered' => 'Têketî',
    'roster_unclassified' => 'Bêpêşniyaz',
    'type_label' => 'Şampiyonîya Taekwondo',

];
