<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'corner_chung' => 'CHUNG',
    'corner_hong' => 'HONG',
    'division_label' => 'Kategoria e pesës',
    'mat' => 'Mat',
    'official_center_referee' => 'Shqyrtuesi qendror',
    'official_center_referee_hint' => 'Kryen batin në qendër të sallës.',
    'official_corner_judge' => 'Shqyrtuesi i këndit :n',
    'official_corner_judge_hint' => 'Voton nga një kënd i sallës.',
    'official_court_supervisor' => 'Supervizori i sallës',
    'official_court_supervisor_hint' => 'Kontrollon sallën dhe oficerët e saj.',
    'official_review_jury' => 'Komisioni i rishikimit',
    'official_review_jury_hint' => 'Qanë në kërkesat e rishikimit të videos.',
    'official_table_recorder' => 'Regjistruesi i tabelës',
    'official_table_recorder_hint' => 'Mbajnë regjistrin e oficiale në tabelë.',
    'official_timekeeper' => 'Mënyra e kohës',
    'official_timekeeper_hint' => 'Mbajnë kohën: koha e rrotës, ndërprerjet dhe zilja.',
    'score_body_kick' => 'Trupi i këndit',
    'score_head_kick' => 'Këmbë e këndit',
    'score_punch' => 'Hapësirë',
    'score_turning_body' => 'Trupi i këndit të ktheur',
    'score_turning_head' => 'Këmbë e këndit të ktheur',
    'sport_label' => 'Taekwondo',
    'weigh_in' => 'Pesëm',

];
