<?php

/*
|--------------------------------------------------------------------------
| shared — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/shared.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'back' => 'Atrás',
    'cancel' => 'Cancelar',
    'clear' => 'Borrar',
    'close' => 'Cerrar',
    'components_qr_code_chat' => 'Chat',
    'components_qr_code_copy_link' => 'Copiar enlace',
    'components_qr_code_could_not_copy_link' => 'No se pudo copiar el enlace',
    'components_qr_code_could_not_export_png' => 'No se pudo exportar PNG.',
    'components_qr_code_could_not_send' => 'No se pudo enviar.',
    'components_qr_code_could_not_start_chat' => 'No se pudo iniciar el chat.',
    'components_qr_code_hide_options' => 'Ocultar opciones',
    'components_qr_code_link_copied' => 'Enlace copiado',
    'components_qr_code_more_options' => 'Más opciones',
    'components_qr_code_network_error' => 'Error de red — inténtelo de nuevo.',
    'components_qr_code_no_one_found' => 'No se encontró a nadie con quien enviar un mensaje.',
    'components_qr_code_png' => 'PNG',
    'components_qr_code_poster' => 'Póster',
    'components_qr_code_search_hint' => 'Buscar compañeros del club o conexiones con las que compartir.',
    'components_qr_code_search_placeholder' => 'Buscar a una persona para enviarle…',
    'components_qr_code_searching' => 'Buscando…',
    'components_qr_code_send_in_chat' => 'Enviar en el chat',
    'components_qr_code_sent_to' => 'Enviado a',
    'components_qr_code_share' => 'Compartir',
    'components_qr_code_svg' => 'SVG',
    'delete' => 'Eliminar',
    'edit' => 'Editar',
    'link_copied' => 'Enlace copiado',
    'open_in_new_tab' => 'Abrir en una pestaña nueva',
    'reset_zoom' => 'Ajustar a la pantalla',
    'save' => 'Guardar',
    'share' => 'Compartir',
    'something_went_wrong' => 'Algo salió mal',
    'unknown' => 'Desconocido',
    'zoom_in' => 'Ampliar',
    'zoom_out' => 'Reducir',

];
