<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_arrange_draw' => '抽選を調整',
    'action_clear_draw' => '抽選をクリア',
    'action_end_next_bout' => '次の試合を終了',
    'action_generate_draw' => '抽選を生成',
    'call_mat_tbc' => 'あなたのマット',
    'call_opponent_tbc' => '未定',
    'call_room_body' => ':mat · 試合 :bout · 対 :opponent',
    'call_room_title' => 'コールルームへご報告— :mat',
    'call_warmup_body' => ':ahead 個の試合がお前に続き · およそ :minutes 分',
    'call_warmup_title' => 'ウォームアップ—まもなく :mat で',
    'day_mats' => '日 :day: :count 個のマット',
    'draw_arranged' => '抽選が更新されました 🥋',
    'draw_cleared' => '抽選がクリアされました—全出場者はリストに戻っています',
    'draw_final' => '大会が開始されました—抽選は最終決定であり、再生成することはできません。',
    'draw_generated' => '暫定抽選が生成されました',
    'end_next_bout_done' => ':winner が :court で勝利しました。そのマットのスクリーンに通知しました。',
    'end_next_bout_none' => '終了できる試合がありません—すべての予約試合はフィーダーを待っています。',
    'ended_locked' => 'この大会は終了しました—結果は最終です。',
    'gate_no_division' => 'あなたの重量級はこの大会の級別ではありませんので、このイベントに参加する資格はありません。',
    'gate_no_division_spectator' => 'あなたの重量級はこの大会の級別ではありませんので、参加することはできませんが、観客としてご参加いただけます。',
    'gate_no_profile' => 'プロフィールに性別と生年月日を追加して、重量級に配置できるようにしてください。',
    'gate_no_weight' => '健康プロフィールに現在の体重を追加して、重量級に配置できるようにしてください。',
    'notify_draw_body' => 'あなたの級別が抽選されました。イベントを開いて相手、マット、試合番号をご確認ください。',
    'notify_draw_title' => '抽選が発表されました— :title',
    'notify_weigh_in_body' => '体重計測は :time に :place で開始します。身分証明書をご持参ください。',
    'notify_weigh_in_title' => '明日の体重計測— :title',
    'result_body_done' => '今日はこれで一日の最後の試合です。',
    'result_body_next' => '次: :round は :mat で、およそ :minutes 分',
    'result_loss_title' => '試合終了',
    'result_win_title' => '勝利しました 🎉',
    'roster_registered' => '登録済み',
    'roster_unclassified' => '級別未設定',
    'type_label' => '柔術選手権大会',

];
