<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_arrange_draw' => 'ארגן מערך',
    'action_clear_draw' => 'נקה מערך',
    'action_end_next_bout' => 'סיים את המאבק הבא',
    'action_generate_draw' => 'צור מערך',
    'call_mat_tbc' => 'מגרשך',
    'call_opponent_tbc' => 'בשלב הבא',
    'call_room_body' => ':mat · מאבק :bout · נגד :opponent',
    'call_room_title' => 'דווח לחדר הקריאה — :mat',
    'call_warmup_body' => ':ahead מאבקים לפנייך · בערך :minutes דק',
    'call_warmup_title' => 'התאמץ — אתה על :mat בקרוב',
    'day_mats' => 'יום :day: :count מגרשים',
    'draw_arranged' => 'המערך עודכן 🥋',
    'draw_cleared' => 'המערך נוקה — כל המשתתפים חזרו לרשימה',
    'draw_final' => 'המפעל החל — המערך סופי ואינו ניתן ליצירה מחדש.',
    'draw_generated' => 'נוצר מערך זמני',
    'end_next_bout_done' => ':winner מנצח על :court. הלחצנים על מגרש זה הוזכרו.',
    'end_next_bout_none' => 'אף מאבק לא מוכן לסיום — כל המאבקים הממתינים עדיין מחכים למאבק מוקדם יותר.',
    'ended_locked' => 'המפעל הסתיים — התוצאות סופיות.',
    'gate_no_division' => 'קטגוריית המשקל שלך אינה אחת מהקטגוריות של המפעל הזה, לכן אינך مؤهل להשתתף באירוע זה.',
    'gate_no_division_spectator' => 'קטגוריית המשקל שלך אינה אחת מהקטגוריות של המפעל הזה, לכן אינך יכול להשתתף — אך מוזמן להשתתף כצופר.',
    'gate_no_profile' => 'הוסף את המין ואת תאריך הלידה שלך לפרופיל כדי שנוכל למקם אותך בקטגוריית משקל.',
    'gate_no_weight' => 'הוסף את המשקל הנוכחי שלך לפרופיל הבריאות כדי שנוכל למקם אותך בקטגוריית משקל.',
    'notify_draw_body' => 'הקטגוריה שלך נבחרה. פתח את האירוע כדי לראות את היריב, המגרש והמספר של המאבק.',
    'notify_draw_title' => 'המערך מפורסם — :title',
    'notify_weigh_in_body' => 'בדיקה משקל נפתח ב-:time ב-:place. הביאו את תעודת הזהות.',
    'notify_weigh_in_title' => 'בדיקה משקל מחר — :title',
    'result_body_done' => 'זה היה המאבק האחרון שלך של היום.',
    'result_body_next' => 'הבא: :round על :mat, בערך :minutes דק',
    'result_loss_title' => 'המאבק הסתיים',
    'result_win_title' => 'השגתי 🎉',
    'roster_registered' => 'רשום',
    'roster_unclassified' => 'ללא קטגוריה',
    'type_label' => 'מפעל ג\'יו-ג\'יטسو',

];
