<?php

/*
|--------------------------------------------------------------------------
| auth — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/auth.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'auth_desktop_login_check_inbox_after' => '. Clica nele para iniciar sessão.',
    'auth_desktop_login_check_inbox_before' => 'Enviámos um link de acesso para',
    'auth_desktop_login_check_inbox_title' => 'Verifica a tua caixa de entrada',
    'auth_desktop_login_email_me_link' => 'Enviar link de acesso',
    'auth_desktop_login_email_placeholder' => 'Telemóvel ou email',
    'auth_desktop_login_forgot_password' => 'Esqueceste-te da palavra-passe?',
    'auth_desktop_login_magic_hint' => 'Sem palavra-passe? Enviamos-te um link de acesso único por email.',
    'auth_desktop_login_password_placeholder' => 'Palavra-passe',
    'auth_desktop_login_register' => 'Criar conta',
    'auth_desktop_login_remember_me' => 'Manter sessão iniciada',
    'auth_desktop_login_resend_verification' => 'Reenviar email de verificação',
    'auth_desktop_login_sign_in' => 'Iniciar sessão',
    'auth_desktop_login_subtitle' => 'Bem-vindo de volta! Inicia sessão para continuar',
    'auth_desktop_login_tab_link' => 'Link de acesso',
    'auth_desktop_login_tab_password' => 'Palavra-passe',
    'auth_desktop_login_unverified_hint' => 'Não recebeste o email ou expirou?',
    'auth_desktop_login_unverified_title' => 'Email não verificado',
    'auth_desktop_login_your_email_placeholder' => 'O teu email',
    'auth_forgot_password_back_to_login' => 'Voltar ao início de sessão',
    'auth_forgot_password_email_placeholder' => 'E-mail',
    'auth_forgot_password_send_reset_link' => 'Enviar link de reposição',
    'auth_forgot_password_subtitle' => 'Sem problema — introduza o seu e-mail e enviamos-lhe um link de reposição.',
    'auth_forgot_password_title' => 'Esqueceu-se da palavra-passe?',
    'auth_register_birthdate' => 'Data de nascimento',
    'auth_register_confirm_password' => 'Confirmar palavra-passe',
    'auth_register_email' => 'Endereço de email',
    'auth_register_full_name' => 'Nome completo',
    'auth_register_joining_club' => 'Estás a juntar-te a',
    'auth_register_mobile_number' => 'Telemóvel',
    'auth_register_nationality' => 'Nacionalidade',
    'auth_register_password' => 'Palavra-passe',
    'auth_register_submit' => 'Registar',
    'auth_register_subtitle' => 'Cria a tua conta',
    'auth_register_wizard_err_generic_post' => '). Tente novamente.',
    'auth_register_wizard_err_generic_pre' => 'Ocorreu um erro (erro',
    'auth_register_wizard_err_network' => 'Erro de rede. Verifique a sua ligação e tente novamente.',
    'auth_register_wizard_err_session_expired' => 'A sua sessão expirou. Atualize a página e tente novamente.',
    'auth_register_wizard_ph_child_name' => 'Nome completo da criança',
    'auth_register_wizard_ph_email' => 'Endereço de e-mail',
    'auth_register_wizard_ph_full_name' => 'Nome completo',
    'auth_register_wizard_ph_health' => 'Descreva quaisquer problemas de saúde',
    'auth_register_wizard_ph_mobile' => 'Número de telemóvel',
    'auth_register_wizard_rel_daughter' => 'Filha',
    'auth_register_wizard_rel_member_fallback' => 'Familiar',
    'auth_register_wizard_rel_other' => 'Outro',
    'auth_register_wizard_rel_son' => 'Filho',
    'auth_register_wizard_rel_spouse' => 'Cônjuge',
    'auth_register_wizard_terms_changes_body' => 'Estes termos podem ser atualizados periodicamente; a utilização continuada do serviço implica a sua aceitação.',
    'auth_register_wizard_terms_changes_title' => 'Alterações aos Termos',
    'auth_register_wizard_terms_conduct_body' => 'Espera-se que os membros cumpram as regras do clube e tratem com respeito o pessoal e os restantes membros.',
    'auth_register_wizard_terms_conduct_title' => 'Código de conduta',
    'auth_register_wizard_terms_confirm' => 'Ao selecionar a caixa abaixo, confirma que leu e aceita estes termos.',
    'auth_register_wizard_terms_default_intro' => 'Bem-vindo ao :club! Ao registares-te, aceitas os seguintes termos:',
    'auth_register_wizard_terms_medical_body' => 'Indica quaisquer condições médicas ou de saúde que possam afetar a participação.',
    'auth_register_wizard_terms_medical_title' => 'Saúde e questões médicas',
    'auth_register_wizard_terms_membership_body' => 'A tua inscrição começa assim que o registo for aprovado e o pagamento (se aplicável) confirmado.',
    'auth_register_wizard_terms_membership_title' => 'Inscrição',
    'auth_register_wizard_terms_payment_body' => 'Todos os pagamentos são devidos no momento do registo, salvo se for escolhida a opção «pagar mais tarde».',
    'auth_register_wizard_terms_payment_title' => 'Pagamento',
    'auth_register_wizard_terms_privacy_body' => 'Os seus dados pessoais são usados apenas para gerir a sua inscrição e não serão partilhados sem consentimento.',
    'auth_register_wizard_terms_privacy_title' => 'Privacidade',
    'auth_reset_password_back_to_login' => 'Voltar ao início de sessão',
    'auth_reset_password_confirm_password_label' => 'Confirmar nova palavra-passe',
    'auth_reset_password_email_label' => 'Endereço de e-mail',
    'auth_reset_password_new_password_label' => 'Nova palavra-passe',
    'auth_reset_password_submit' => 'Repor palavra-passe',
    'auth_reset_password_title' => 'Repor a palavra-passe',
    'auth_verify_email_check_inbox_line1' => 'Enviámos um link de verificação para o seu endereço de e-mail.',
    'auth_verify_email_check_inbox_line2' => 'Clique no link para verificar a sua conta.',
    'auth_verify_email_check_inbox_title' => 'Verifique o seu e-mail',
    'auth_verify_email_didnt_receive' => 'Não recebeu o e-mail?',
    'auth_verify_email_fresh_link_sent' => 'Foi enviado um novo link de verificação para o seu endereço de e-mail.',
    'auth_verify_email_go_to_app' => 'Continuar',
    'auth_verify_email_one_step_away' => 'Falta só um passo para aderir',
    'auth_verify_email_redirecting_prefix' => 'A redirecionar em',
    'auth_verify_email_redirecting_suffix' => 'segundos...',
    'auth_verify_email_resend_button' => 'Reenviar e-mail de verificação',
    'auth_verify_email_sign_out' => 'Terminar sessão',
    'auth_verify_email_verified_body' => 'O seu e-mail foi verificado com sucesso.',
    'auth_verify_email_verified_title' => 'E-mail verificado!',
    'auth_verify_email_wrong_account' => 'Conta errada?',
    'choose_not_you' => 'Usar outro número ou e-mail',
    'choose_sub' => 'Mais do que uma pessoa usa este número. Toque em quem vai iniciar sessão.',
    'choose_title' => 'Quem está a iniciar sessão?',
    'club_waiting' => 'O teu clube está à espera. Vamos lá.',
    'create_account' => 'Criar conta',
    'didnt_receive' => 'Não recebeste o email ou expirou?',
    'email' => 'Email',
    'email_not_verified' => 'Email não verificado',
    'email_or_phone' => 'Telemóvel ou email',
    'forgot_password' => 'Esqueceste-te da palavra-passe?',
    'hide_password' => 'Ocultar palavra-passe',
    'magic_cta' => 'Enviar link de acesso',
    'magic_prompt' => 'Sem palavra-passe? Enviamos-te um link de acesso único por email.',
    'magic_sent_body' => 'Se existir uma conta com esse email, enviámos um link de acesso. Toca no botão do email para iniciar sessão — sem palavra-passe.',
    'magic_sent_title' => 'Verifica a tua caixa de entrada',
    'new_to_takeone' => 'Novo no TAKEONE?',
    'or' => 'ou',
    'password' => 'Palavra-passe',
    'remember_me' => 'Manter sessão iniciada',
    'resend_verification' => 'Reenviar email de verificação',
    'show_password' => 'Mostrar palavra-passe',
    'sign_in' => 'Iniciar sessão',
    'tab_magic' => 'Link de acesso',
    'tab_password' => 'Palavra-passe',
    'welcome_back' => 'Bem-vindo de volta',

];
