<?php

/*
|--------------------------------------------------------------------------
| explore — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/explore.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'apply_location' => 'Aplicar localização',
    'book_session' => 'Marcar sessão',
    'cat_all' => 'Todos',
    'cat_clubs' => 'Clubes',
    'cat_events' => 'Eventos',
    'cat_food_plans' => 'Planos alimentares',
    'cat_nutrition' => 'Nutrição',
    'cat_physiotherapy' => 'Fisioterapia',
    'cat_shops' => 'Lojas',
    'cat_supplements' => 'Suplementos',
    'cat_trainers' => 'Treinadores',
    'cat_venues' => 'Espaços',
    'choose_option_body' => 'Escolha uma opção para cada equipamento selecionado.',
    'choose_option_title' => 'Opção obrigatória',
    'detecting_location' => 'A detetar localização...',
    'drag_marker' => 'Arraste o marcador para definir a sua localização',
    'error_fetching_clubs' => 'Ocorreu um erro ao carregar os clubes.',
    'ev_coming_up' => 'Em breve',
    'ev_failed' => 'Não foi possível carregar os eventos. Tenta novamente.',
    'ev_finding' => 'A carregar eventos...',
    'ev_free' => 'Grátis',
    'ev_full' => 'Esgotado',
    'ev_going' => 'vão participar',
    'ev_happening_now' => 'A acontecer agora',
    'ev_live' => 'Ao vivo',
    'ev_none_hint' => 'Não há nada a decorrer ou agendado para ti neste momento.',
    'ev_none_title' => 'Sem eventos abertos',
    'ev_open' => 'Aberto',
    'ev_spots_left' => 'vagas restantes',
    'ev_starts_in' => 'Começa em',
    'ev_tba' => 'A anunciar',
    'ev_until' => 'até',
    'ev_view_event' => 'Ver evento',
    'explore' => 'Explorar',
    'failed_to_fetch_clubs' => 'Falha ao carregar os clubes. Tente novamente.',
    'finding' => 'A procurar o que está perto de você...',
    'geolocation_not_supported' => 'A geolocalização não é suportada pelo seu navegador.',
    'hero_eyebrow' => 'Descobrir por perto',
    'hero_sub' => 'Clubes, treinadores, workshops e mais perto de você',
    'hero_title' => 'Encontre o que combina com você',
    'join_club' => 'Juntar-se ao clube',
    'km_away' => 'km de distância',
    'loading' => 'A carregar...',
    'location_access_denied' => 'O acesso à localização foi recusado.',
    'location_available' => 'Localização disponível',
    'location_request_timed_out' => 'O pedido de localização expirou.',
    'location_unavailable' => 'A informação de localização não está disponível.',
    'members' => 'Membros',
    'na' => 'N/D',
    'near_me' => 'Perto de mim',
    'no_members_selected_body' => 'Selecione pelo menos um membro para continuar.',
    'no_members_selected_title' => 'Nenhum membro selecionado',
    'no_results' => 'Nenhum resultado encontrado',
    'no_results_hint' => 'Tente ajustar a pesquisa ou a localização',
    'packages' => 'Pacotes',
    'packages_required_body' => 'Escolha um pacote para cada membro selecionado.',
    'packages_required_title' => 'Pacote obrigatório',
    'payment_required_body' => 'Carregue um comprovativo de pagamento ou opte por pagar mais tarde.',
    'payment_required_title' => 'Comprovativo de pagamento obrigatório',
    'personal_trainer_badge' => 'Personal trainer',
    'please_try_again' => 'Tente novamente.',
    'rating' => 'Classificação',
    'registration_error_body' => 'Ocorreu um erro ao enviar a sua inscrição.',
    'registration_failed_title' => 'Falha na inscrição',
    'registration_submitted_body' => 'A sua inscrição foi enviada ao clube para aprovação.',
    'registration_submitted_title' => 'Inscrição enviada',
    'reviews' => 'Avaliações',
    'search_placeholder' => 'Pesquisar clubes, treinadores...',
    'set_location' => 'Definir a sua localização',
    'sports_club_badge' => 'Clube desportivo',
    'trainers' => 'Treinadores',
    'unable_to_get_location' => 'Não foi possível obter a sua localização.',
    'view_details' => 'Ver detalhes',
    'years_exp' => 'Anos de exp.',

];
