<?php

/*
|--------------------------------------------------------------------------
| security — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/security.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'add_otp_desc' => 'Adicione um código de uso único do seu aplicativo autenticador em cada login.',
    'cancel' => 'Cancelar',
    'change_password' => 'Alterar Senha',
    'change_password_desc' => 'Todas as outras sessões ativas serão desconectadas quando você alterar a senha.',
    'code_placeholder' => 'Código de 6 dígitos',
    'code_placeholder_long' => 'Código de 6 dígitos ou código de recuperação',
    'confirm_new_password' => 'Confirmar Nova Senha',
    'current_password' => 'Senha Atual',
    'disable' => 'Desativar',
    'disable_2fa' => 'Desativar 2FA',
    'disable_confirm_desc' => 'Digite um código atual do autenticador (ou um código de recuperação) para confirmar.',
    'disable_two_factor' => 'Desativar Autenticação de Dois Fatores',
    'enable_2fa' => 'Ativar 2FA',
    'lockdown_message' => 'Vamos proteger sua conta.',
    'new_password' => 'Nova Senha',
    'protected_message' => 'Sua conta está bem protegida.',
    'protected_with_app' => 'Protegida com o Google Authenticator.',
    'recovery_codes' => 'Códigos de Recuperação',
    'recovery_codes_desc' => 'Códigos de backup de uso único caso você perca o acesso ao seu autenticador.',
    'regenerate' => 'Gerar',
    'regenerate_codes' => 'Gerar novos códigos',
    'regenerate_codes_title' => 'Gerar Novos Códigos',
    'regenerate_confirm_desc' => 'Seus códigos de recuperação existentes deixarão de funcionar. Digite o código do seu autenticador para confirmar.',
    'security' => 'Segurança',
    'security_challenge_back_to_login' => 'Voltar ao login',
    'security_challenge_backup_hint' => 'Digite um dos seus códigos de backup de 8 caracteres.',
    'security_challenge_subtitle' => 'Digite o código do seu aplicativo autenticador.',
    'security_challenge_title' => 'Autenticação de Dois Fatores',
    'security_challenge_use_authenticator' => 'Usar aplicativo autenticador em vez disso',
    'security_challenge_use_recovery' => 'Usar um código de recuperação',
    'security_challenge_verify' => 'VERIFICAR',
    'security_index_2fa_disabled_desc' => 'Adicione uma camada extra de segurança à sua conta.',
    'security_index_2fa_enabled_desc' => 'Sua conta está protegida com o Google Authenticator.',
    'security_index_2fa_title' => 'Autenticação de Dois Fatores',
    'security_index_change_password' => 'Alterar Senha',
    'security_index_change_password_desc' => 'Todas as outras sessões ativas serão desconectadas quando você alterar sua senha.',
    'security_index_code_or_recovery_placeholder' => 'Código de 6 dígitos ou código de recuperação',
    'security_index_code_placeholder' => 'Código de 6 dígitos',
    'security_index_confirm_new_password' => 'Confirmar Nova Senha',
    'security_index_current_password' => 'Senha Atual',
    'security_index_disable_2fa' => 'Desativar 2FA',
    'security_index_disable_2fa_modal_desc' => 'Digite seu código atual do autenticador (ou um código de recuperação) para confirmar.',
    'security_index_disable_2fa_modal_title' => 'Desativar Autenticação de Dois Fatores',
    'security_index_disabled' => 'Desativado',
    'security_index_enable_2fa' => 'Ativar 2FA',
    'security_index_enabled' => 'Ativado',
    'security_index_new_password' => 'Nova Senha',
    'security_index_recovery_codes' => 'Códigos de Recuperação',
    'security_index_recovery_codes_desc' => 'Códigos de backup de uso único caso você perca o acesso ao seu aplicativo autenticador.',
    'security_index_regen_codes_modal_desc' => 'Seus códigos de recuperação existentes serão invalidados. Digite o código do seu autenticador para confirmar.',
    'security_index_regen_codes_modal_title' => 'Gerar Novos Códigos de Recuperação',
    'security_index_regenerate' => 'Gerar',
    'security_index_regenerate_codes' => 'Gerar Novos Códigos',
    'security_index_subtitle' => 'Gerencie a segurança da sua conta e a autenticação de dois fatores',
    'security_index_title' => 'Configurações de Segurança',
    'security_index_update_password' => 'Atualizar Senha',
    'security_recovery_codes_account_protected' => 'Sua conta agora está protegida.',
    'security_recovery_codes_copied' => 'Copiado!',
    'security_recovery_codes_copy_all' => 'Copiar Todos os Códigos',
    'security_recovery_codes_heading_enabled' => 'Autenticação de Dois Fatores Ativada',
    'security_recovery_codes_heading_new' => 'Novos Códigos de Recuperação',
    'security_recovery_codes_page_title' => 'Códigos de Recuperação',
    'security_recovery_codes_save_safe' => 'Salve esses códigos de recuperação em algum lugar seguro.',
    'security_recovery_codes_store_desc' => 'Cada código só pode ser usado uma vez.',
    'security_recovery_codes_store_safely' => 'Armazene esses códigos com segurança.',
    'security_recovery_codes_success_alert' => 'A autenticação de dois fatores foi ativada com sucesso na sua conta.',
    'security_setup_manual_entry' => 'Não consegue escanear? Digite esta chave manualmente no aplicativo:',
    'security_setup_step1_app_name' => 'Google Authenticator',
    'security_setup_step1_app_store' => 'App Store',
    'security_setup_step1_download' => 'Baixar',
    'security_setup_step1_from' => 'no seu celular a partir do',
    'security_setup_step1_heading' => 'Instale o Google Authenticator',
    'security_setup_step1_or' => 'ou',
    'security_setup_step1_play_store' => 'Play Store',
    'security_setup_step2_heading' => 'Escanear o Código QR',
    'security_setup_step2_open' => 'Abra o aplicativo, toque',
    'security_setup_step2_scan_option' => 'Escanear um código QR',
    'security_setup_step2_then_choose' => ', depois escolha',
    'security_setup_step3_heading' => 'Confirmar Seu Código',
    'security_setup_step3_subtitle' => 'Digite o código de 6 dígitos exibido no aplicativo para verificar a configuração.',
    'security_setup_subtitle' => 'Siga as etapas abaixo para proteger sua conta com o Google Authenticator.',
    'security_setup_time_based' => 'Baseado em tempo',
    'security_setup_time_based_prefix' => 'Selecionar',
    'security_setup_time_based_suffix' => 'quando solicitado.',
    'security_setup_title' => 'Configurar Autenticação de Dois Fatores',
    'security_setup_verify_button' => 'Verificar e Ativar',
    'title' => 'Configurações de Segurança',
    'two_factor_auth' => 'Autenticação de Dois Fatores',
    'two_factor_off' => 'Autenticação de dois fatores desativada',
    'two_factor_on' => 'Autenticação de dois fatores ativada',
    'update_password' => 'Atualizar Senha',

];
