<?php

/*
|--------------------------------------------------------------------------
| auth — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/auth.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'auth_desktop_login_check_inbox_after' => '. اضغط عليه لتسجيل الدخول.',
    'auth_desktop_login_check_inbox_before' => 'أرسلنا رابط دخول إلى ',
    'auth_desktop_login_check_inbox_title' => 'تفقّد بريدك الإلكتروني',
    'auth_desktop_login_email_me_link' => 'أرسل لي رابط الدخول',
    'auth_desktop_login_email_placeholder' => 'رقم الهاتف أو البريد الإلكتروني',
    'auth_desktop_login_forgot_password' => 'هل نسيت كلمة المرور؟',
    'auth_desktop_login_magic_hint' => 'لا تملك كلمة مرور؟ سنرسل لك رابط دخول لمرة واحدة عبر البريد.',
    'auth_desktop_login_password_placeholder' => 'كلمة المرور',
    'auth_desktop_login_register' => 'إنشاء حساب',
    'auth_desktop_login_remember_me' => 'تذكرني',
    'auth_desktop_login_resend_verification' => 'إعادة إرسال بريد التوثيق',
    'auth_desktop_login_sign_in' => 'تسجيل الدخول',
    'auth_desktop_login_subtitle' => 'مرحباً بعودتك! سجّل الدخول للمتابعة',
    'auth_desktop_login_tab_link' => 'رابط الدخول',
    'auth_desktop_login_tab_password' => 'كلمة المرور',
    'auth_desktop_login_unverified_hint' => 'لم تستلم البريد أو انتهت صلاحيته؟',
    'auth_desktop_login_unverified_title' => 'البريد الإلكتروني غير مُوثّق',
    'auth_desktop_login_your_email_placeholder' => 'بريدك الإلكتروني',
    'auth_forgot_password_back_to_login' => 'العودة لتسجيل الدخول',
    'auth_forgot_password_email_placeholder' => 'البريد الإلكتروني',
    'auth_forgot_password_send_reset_link' => 'إرسال رابط إعادة تعيين كلمة المرور',
    'auth_forgot_password_subtitle' => 'لا مشكلة — أدخل بريدك الإلكتروني وسنرسل لك رابط إعادة التعيين.',
    'auth_forgot_password_title' => 'هل نسيت كلمة المرور؟',
    'auth_register_birthdate' => 'تاريخ الميلاد',
    'auth_register_confirm_password' => 'تأكيد كلمة المرور',
    'auth_register_email' => 'البريد الإلكتروني',
    'auth_register_full_name' => 'الاسم الكامل',
    'auth_register_joining_club' => 'أنت تنضم إلى',
    'auth_register_mobile_number' => 'رقم الهاتف المحمول',
    'auth_register_nationality' => 'الجنسية',
    'auth_register_password' => 'كلمة المرور',
    'auth_register_submit' => 'تسجيل',
    'auth_register_subtitle' => 'أنشئ حسابك',
    'auth_register_wizard_err_generic_post' => '). يرجى المحاولة مرة أخرى.',
    'auth_register_wizard_err_generic_pre' => 'حدث خطأ ما (خطأ رقم ',
    'auth_register_wizard_err_network' => 'خطأ في الشبكة. يرجى التحقق من اتصالك والمحاولة مرة أخرى.',
    'auth_register_wizard_err_session_expired' => 'انتهت صلاحية جلستك. يرجى تحديث الصفحة والمحاولة مرة أخرى.',
    'auth_register_wizard_ph_child_name' => 'الاسم الكامل للطفل',
    'auth_register_wizard_ph_email' => 'البريد الإلكتروني',
    'auth_register_wizard_ph_full_name' => 'الاسم الكامل',
    'auth_register_wizard_ph_health' => 'يرجى وصف أي حالات صحية',
    'auth_register_wizard_ph_mobile' => 'رقم الهاتف المحمول',
    'auth_register_wizard_rel_daughter' => 'ابنة',
    'auth_register_wizard_rel_member_fallback' => 'أحد أفراد العائلة',
    'auth_register_wizard_rel_other' => 'أخرى',
    'auth_register_wizard_rel_son' => 'ابن',
    'auth_register_wizard_rel_spouse' => 'زوج/زوجة',
    'auth_register_wizard_terms_changes_body' => 'قد يتم تحديث هذه الشروط من وقت لآخر؛ ويعني استمرار استخدام الخدمة موافقتك على ذلك.',
    'auth_register_wizard_terms_changes_title' => 'التغييرات على الشروط',
    'auth_register_wizard_terms_conduct_body' => 'يُتوقع من الأعضاء الالتزام بقواعد النادي والتصرف باحترام تجاه الموظفين والأعضاء الآخرين.',
    'auth_register_wizard_terms_conduct_title' => 'قواعد السلوك',
    'auth_register_wizard_terms_confirm' => 'بتحديد المربع أدناه، فإنك تؤكد أنك قرأت هذه الشروط وتوافق عليها.',
    'auth_register_wizard_terms_default_intro' => 'مرحباً بك في :club! بالتسجيل، فإنك توافق على الشروط التالية:',
    'auth_register_wizard_terms_medical_body' => 'يرجى الإفصاح عن أي حالات صحية أو طبية قد تؤثر على المشاركة.',
    'auth_register_wizard_terms_medical_title' => 'الصحة والحالة الطبية',
    'auth_register_wizard_terms_membership_body' => 'تبدأ عضويتك فور الموافقة على تسجيلك وتأكيد الدفع (إن وُجد).',
    'auth_register_wizard_terms_membership_title' => 'العضوية',
    'auth_register_wizard_terms_payment_body' => 'جميع المدفوعات مستحقة وقت التسجيل، ما لم يتم اختيار خيار "الدفع لاحقاً".',
    'auth_register_wizard_terms_payment_title' => 'الدفع',
    'auth_register_wizard_terms_privacy_body' => 'تُستخدم بياناتك الشخصية فقط لإدارة عضويتك ولن تتم مشاركتها دون موافقتك.',
    'auth_register_wizard_terms_privacy_title' => 'الخصوصية',
    'auth_reset_password_back_to_login' => 'العودة لتسجيل الدخول',
    'auth_reset_password_confirm_password_label' => 'تأكيد كلمة المرور الجديدة',
    'auth_reset_password_email_label' => 'البريد الإلكتروني',
    'auth_reset_password_new_password_label' => 'كلمة المرور الجديدة',
    'auth_reset_password_submit' => 'إعادة تعيين كلمة المرور',
    'auth_reset_password_title' => 'إعادة تعيين كلمة المرور',
    'auth_verify_email_check_inbox_line1' => 'أرسلنا رابط توثيق إلى بريدك الإلكتروني.',
    'auth_verify_email_check_inbox_line2' => 'يرجى الضغط على الرابط لتوثيق حسابك.',
    'auth_verify_email_check_inbox_title' => 'تفقّد بريدك الإلكتروني',
    'auth_verify_email_didnt_receive' => 'لم تستلم البريد؟',
    'auth_verify_email_fresh_link_sent' => 'تم إرسال رابط توثيق جديد إلى بريدك الإلكتروني.',
    'auth_verify_email_go_to_app' => 'متابعة',
    'auth_verify_email_one_step_away' => 'خطوة أخيرة للانضمام',
    'auth_verify_email_redirecting_prefix' => 'جارٍ التحويل خلال',
    'auth_verify_email_redirecting_suffix' => 'ثانية...',
    'auth_verify_email_resend_button' => 'إعادة إرسال بريد التوثيق',
    'auth_verify_email_sign_out' => 'تسجيل الخروج',
    'auth_verify_email_verified_body' => 'تم توثيق بريدك الإلكتروني بنجاح.',
    'auth_verify_email_verified_title' => 'تم توثيق البريد الإلكتروني!',
    'auth_verify_email_wrong_account' => 'حساب خاطئ؟',
    'choose_not_you' => 'استخدم رقماً أو بريداً آخر',
    'choose_sub' => 'أكثر من شخص يستخدم هذا الرقم. اختر من يسجّل الدخول.',
    'choose_title' => 'من يسجّل الدخول؟',
    'club_waiting' => 'ناديك بانتظارك. لنبدأ.',
    'create_account' => 'إنشاء حساب',
    'didnt_receive' => 'لم تستلم البريد أو انتهت صلاحيته؟',
    'email' => 'البريد الإلكتروني',
    'email_not_verified' => 'البريد الإلكتروني غير مُوثّق',
    'email_or_phone' => 'رقم الهاتف أو البريد الإلكتروني',
    'forgot_password' => 'هل نسيت كلمة المرور؟',
    'hide_password' => 'إخفاء كلمة المرور',
    'magic_cta' => 'أرسل لي رابط الدخول',
    'magic_prompt' => 'لا تملك كلمة مرور؟ سنرسل لك رابط دخول لمرة واحدة عبر البريد.',
    'magic_sent_body' => 'إذا كان هناك حساب بهذا البريد، فقد أرسلنا رابط دخول. اضغط الزر في الرسالة لتسجيل الدخول — دون كلمة مرور.',
    'magic_sent_title' => 'تفقّد بريدك الإلكتروني',
    'new_to_takeone' => 'جديد على TAKEONE؟',
    'or' => 'أو',
    'password' => 'كلمة المرور',
    'remember_me' => 'تذكرني',
    'resend_verification' => 'إعادة إرسال بريد التوثيق',
    'show_password' => 'إظهار كلمة المرور',
    'sign_in' => 'تسجيل الدخول',
    'tab_magic' => 'رابط الدخول',
    'tab_password' => 'كلمة المرور',
    'welcome_back' => 'مرحباً بعودتك',

];
