<?php

/*
|--------------------------------------------------------------------------
| copilot — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/copilot.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'ask_name' => 'ما الاسم الذي تريد إطلاقه على النادي؟',
    'cancel' => 'إلغاء',
    'changed' => 'لا مشكلة — أخبرني بما تريد تغييره.',
    'create' => 'إنشاء',
    'created' => 'تم إنشاء :name',
    'creating' => 'جارٍ الإنشاء…',
    'draft_label' => 'مسودة — راجعها قبل الإنشاء',
    'error_create' => 'تعذّر إنشاء النادي.',
    'error_generic' => 'حدث خطأ ما. يُرجى المحاولة مرة أخرى.',
    'f_country' => 'الدولة',
    'f_currency' => 'العملة',
    'f_description' => 'الوصف',
    'f_email' => 'البريد الإلكتروني',
    'f_handle' => 'المعرّف',
    'f_name' => 'الاسم',
    'f_requirements' => 'المتطلبات',
    'f_slogan' => 'الشعار',
    'f_terms' => 'الشروط والأحكام',
    'fab_title' => 'اسأل المدرب',
    'filling_form' => 'لقد ملأت النموذج وأنا أنشئ النادي الآن.',
    'form_filled' => 'قام المدرب بملء النموذج — راجعه ثم أنشئه.',
    'generated' => 'تم إنشاؤها',
    'greeting' => 'مرحبًا، أنا المدرب. أخبرني عن النادي الذي تريد إنشاءه — اسمه على الأقل — وسأتكفّل بإعداده لك.',
    'header_subtitle' => 'إنشاء نادٍ',
    'header_title' => 'المدرب',
    'mic_denied' => 'تم رفض الوصول إلى الميكروفون.',
    'need_more' => 'قبل أن أتمكن من إعداد المسودة أحتاج إلى: :errors',
    'open_club' => 'فتح النادي',
    'placeholder' => 'صِف النادي…',
    'proposal_intro' => 'هذا هو النادي الذي سأنشئه — راجع التفاصيل واضغط «إنشاء» لتفعيله، أو أخبرني بما تريد تغييره.',
    'send' => 'إرسال',
    'start_recording' => 'اضغط للتحدث',
    'stop_recording' => 'إيقاف وإرسال',
    'toast_created' => 'تم إنشاء النادي: :name',
    'transcribing' => 'جارٍ التفريغ…',
    'voice_empty' => 'لم أسمع ذلك جيداً — يرجى المحاولة مرة أخرى.',
    'voice_off' => 'الردود الصوتية متوقفة',
    'voice_on' => 'الردود الصوتية مفعّلة',
    'voice_unsupported' => 'الإدخال الصوتي غير مدعوم على هذا الجهاز.',

];
