<?php

/*
|--------------------------------------------------------------------------
| explore — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/explore.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'apply_location' => 'تطبيق الموقع',
    'book_session' => 'احجز جلسة',
    'cat_all' => 'الكل',
    'cat_clubs' => 'الأندية',
    'cat_events' => 'الفعاليات',
    'cat_food_plans' => 'خطط الطعام',
    'cat_nutrition' => 'التغذية',
    'cat_physiotherapy' => 'العلاج الطبيعي',
    'cat_shops' => 'المتاجر',
    'cat_supplements' => 'المكمّلات',
    'cat_trainers' => 'المدرّبون',
    'cat_venues' => 'الأماكن',
    'choose_option_body' => 'اختر خياراً لكل قطعة معدات محددة.',
    'choose_option_title' => 'الخيار مطلوب',
    'detecting_location' => 'جارٍ تحديد الموقع...',
    'drag_marker' => 'اسحب المؤشّر لتحديد موقعك',
    'error_fetching_clubs' => 'حدث خطأ أثناء تحميل الأندية.',
    'ev_coming_up' => 'قادم قريباً',
    'ev_failed' => 'تعذّر تحميل الفعاليات. يرجى المحاولة مرة أخرى.',
    'ev_finding' => 'جارٍ تحميل الفعاليات...',
    'ev_free' => 'مجاني',
    'ev_full' => 'مكتمل',
    'ev_going' => 'مشارك',
    'ev_happening_now' => 'يحدث الآن',
    'ev_live' => 'مباشر',
    'ev_none_hint' => 'لا توجد فعاليات جارية أو مجدولة لك حالياً.',
    'ev_none_title' => 'لا توجد فعاليات مفتوحة',
    'ev_open' => 'متاح',
    'ev_spots_left' => 'مقعد متبقٍ',
    'ev_starts_in' => 'يبدأ خلال',
    'ev_tba' => 'يُحدد لاحقاً',
    'ev_until' => 'حتى',
    'ev_view_event' => 'عرض الفعالية',
    'explore' => 'استكشاف',
    'failed_to_fetch_clubs' => 'تعذّر تحميل الأندية. يرجى المحاولة مرة أخرى.',
    'finding' => 'جارٍ البحث عمّا يقرب منك...',
    'geolocation_not_supported' => 'المتصفح لا يدعم تحديد الموقع.',
    'hero_eyebrow' => 'اكتشف القريب منك',
    'hero_sub' => 'أندية ومدرّبون وعيادات والمزيد بالقرب منك',
    'hero_title' => 'اعثر على ما يناسبك',
    'join_club' => 'انضم إلى النادي',
    'km_away' => 'كم',
    'loading' => 'جارٍ التحميل...',
    'location_access_denied' => ' تم رفض إذن الوصول إلى الموقع.',
    'location_available' => 'الموقع متاح',
    'location_request_timed_out' => ' انتهت مهلة طلب الموقع.',
    'location_unavailable' => ' معلومات الموقع غير متوفرة.',
    'members' => 'الأعضاء',
    'na' => 'غير متوفر',
    'near_me' => 'بالقرب مني',
    'no_members_selected_body' => 'اختر عضواً واحداً على الأقل للمتابعة.',
    'no_members_selected_title' => 'لم يتم اختيار أعضاء',
    'no_results' => 'لا توجد نتائج',
    'no_results_hint' => 'حاول تعديل البحث أو الموقع',
    'packages' => 'الباقات',
    'packages_required_body' => 'اختر باقة لكل عضو محدد.',
    'packages_required_title' => 'الباقة مطلوبة',
    'payment_required_body' => 'ارفع صورة الدفع أو اختر الدفع لاحقاً.',
    'payment_required_title' => 'إثبات الدفع مطلوب',
    'personal_trainer_badge' => 'مدرّب شخصي',
    'please_try_again' => 'يرجى المحاولة مرة أخرى.',
    'rating' => 'التقييم',
    'registration_error_body' => 'حدث خطأ أثناء إرسال تسجيلك.',
    'registration_failed_title' => 'فشل التسجيل',
    'registration_submitted_body' => 'تم إرسال تسجيلك إلى النادي للموافقة.',
    'registration_submitted_title' => 'تم إرسال التسجيل',
    'reviews' => 'التقييمات',
    'search_placeholder' => 'ابحث عن أندية، مدرّبين...',
    'set_location' => 'حدّد موقعك',
    'sports_club_badge' => 'نادٍ رياضي',
    'trainers' => 'المدرّبون',
    'unable_to_get_location' => 'تعذّر تحديد موقعك.',
    'view_details' => 'عرض التفاصيل',
    'years_exp' => 'سنوات الخبرة',

];
