<?php

/*
|--------------------------------------------------------------------------
| family — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/family.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'add_family_member' => 'إضافة فرد من العائلة',
    'add_member' => 'إضافة عضو',
    'adults' => 'بالغون',
    'empty_subtitle' => 'أضف زوجاً/زوجة أو طفلاً أو معالاً لإدارة ملفه الشخصي وصحته وجدوله.',
    'member' => 'فرد',
    'members' => 'أفراد',
    'minors' => 'قاصرون',
    'my_family' => 'عائلتي',
    'no_members_yet' => 'لا يوجد أفراد عائلة بعد',
    'title' => 'العائلة',
    'under_your_care' => 'تحت رعايتك',
    'years' => 'سنة',

];
