<?php

/*
|--------------------------------------------------------------------------
| header — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/header.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'cart' => 'السلة',
    'cart_soon' => 'السلة قريباً',
    'chat' => 'الدردشة',
    'clear_all' => 'مسح الكل',
    'club_management' => 'إدارة النادي',
    'just_now' => 'الآن',
    'mark_all_read' => 'تعليم الكل كمقروء',
    'menu' => 'القائمة',
    'no_notifications' => 'لا توجد إشعارات بعد',
    'notification' => 'إشعار',
    'notifications' => 'الإشعارات',
    'personal_desc' => 'ملفي، الحجوزات، المدفوعات',
    'personal_view' => 'العرض الشخصي',
    'scan_code_placeholder' => 'ABC123',
    'scan_foreign_host' => 'رمز QR هذا يشير إلى موقع آخر، لذلك لم يتم فتحه.',
    'scan_hint' => 'وجّه الكاميرا نحو رمز QR',
    'scan_no_camera' => 'تعذّر الوصول إلى الكاميرا.',
    'scan_or_type' => 'أو اكتب الرمز المكوّن من ٦ خانات',
    'scan_qr' => 'مسح رمز QR',
    'scan_unsupported' => 'مسح رموز QR غير مدعوم في هذا المتصفّح.',
    'switch_view' => 'تبديل العرض',

];
