<?php

/*
|--------------------------------------------------------------------------
| messenger — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messenger.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'active_now' => 'نشط الآن',
    'attach_file' => 'إرفاق ملف',
    'attachment_expired' => 'انتهت صلاحية المرفق',
    'chat_deleted' => 'تم حذف المحادثة',
    'chat_options' => 'خيارات المحادثة',
    'confirm_delete' => 'حذف',
    'confirm_delete_chat_message' => 'ستُزال هذه المحادثة وسجلّها من قائمتك. وستظهر من جديد عند وصول رسالة جديدة.',
    'confirm_delete_chat_title' => 'حذف المحادثة؟',
    'confirm_delete_everyone_message' => 'ستُحذف هذه الرسالة لدى جميع المشاركين في المحادثة.',
    'confirm_delete_everyone_title' => 'حذف لدى الجميع؟',
    'confirm_delete_me_message' => 'ستُزال هذه الرسالة من عرضك أنت فقط.',
    'confirm_delete_me_title' => 'حذف لديّ؟',
    'connected' => 'متصل · فوري',
    'copy' => 'نسخ',
    'could_not_copy' => 'تعذّر النسخ',
    'could_not_delete' => 'تعذّر الحذف.',
    'could_not_delete_chat' => 'تعذّر حذف المحادثة.',
    'could_not_edit' => 'تعذّر التعديل.',
    'could_not_load' => 'تعذّر تحميل المحادثة.',
    'could_not_send' => 'تعذّر الإرسال.',
    'could_not_start' => 'تعذّر بدء المحادثة.',
    'default_user' => 'مستخدم',
    'delete_chat' => 'حذف المحادثة',
    'delete_for_everyone' => 'حذف لدى الجميع',
    'delete_for_me' => 'حذف لديّ',
    'delivers_instantly' => 'يُسلَّم فورًا',
    'download' => 'تنزيل',
    'edit' => 'تعديل',
    'edited' => 'مُعدّلة · ',
    'editing_message' => 'تعديل الرسالة',
    'enable_sounds' => 'تفعيل الأصوات',
    'encrypted_chat' => 'محادثة مشفّرة',
    'message_copied' => 'تم نسخ الرسالة',
    'message_deleted' => 'تم حذف هذه الرسالة',
    'messenger_index_active_now' => 'متصل الآن',
    'messenger_index_attach_file' => 'إرفاق ملف',
    'messenger_index_attachment_expired' => 'انتهت صلاحية المرفق',
    'messenger_index_chat_deleted' => 'تم حذف المحادثة',
    'messenger_index_chat_options' => 'خيارات المحادثة',
    'messenger_index_composer_placeholder' => 'اكتب رسالة',
    'messenger_index_copy' => 'نسخ',
    'messenger_index_delete_chat' => 'حذف المحادثة',
    'messenger_index_delete_chat_message' => 'سيتم إزالة هذه المحادثة وسجلها من قائمتك. ستظهر مجددًا إذا وصلت رسالة جديدة.',
    'messenger_index_delete_chat_title' => 'حذف المحادثة؟',
    'messenger_index_delete_everyone_message' => 'سيتم حذف هذه الرسالة لدى الجميع في المحادثة.',
    'messenger_index_delete_everyone_title' => 'حذف للجميع؟',
    'messenger_index_delete_for_everyone' => 'حذف للجميع',
    'messenger_index_delete_for_me' => 'حذف لدي فقط',
    'messenger_index_delete_me_message' => 'ستتم إزالة هذه الرسالة من صفحتك أنت فقط.',
    'messenger_index_delete_me_title' => 'حذف لدي فقط؟',
    'messenger_index_download' => 'تنزيل',
    'messenger_index_editing_message' => 'تعديل الرسالة',
    'messenger_index_empty_hint' => 'اختر محادثة أو ابحث عن شخص لبدء الدردشة.',
    'messenger_index_encrypted' => 'مشفّرة',
    'messenger_index_err_copy' => 'تعذر النسخ',
    'messenger_index_err_delete' => 'تعذر الحذف.',
    'messenger_index_err_delete_chat' => 'تعذر حذف المحادثة.',
    'messenger_index_err_edit' => 'تعذر التعديل.',
    'messenger_index_err_load_conversation' => 'تعذر تحميل المحادثة.',
    'messenger_index_err_send' => 'تعذر الإرسال.',
    'messenger_index_err_start_chat' => 'تعذر بدء المحادثة.',
    'messenger_index_message_actions' => 'خيارات الرسالة',
    'messenger_index_message_copied' => 'تم نسخ الرسالة',
    'messenger_index_message_deleted' => 'تم حذف هذه الرسالة',
    'messenger_index_no_conversations_1' => 'لا توجد محادثات بعد.',
    'messenger_index_no_conversations_2' => 'ابحث بالأعلى لبدء واحدة.',
    'messenger_index_now' => 'الآن',
    'messenger_index_photo' => '📷 صورة',
    'messenger_index_search_placeholder' => 'ابحث عن أشخاص للمراسلة…',
    'messenger_index_status_connected' => 'متصل · لحظي',
    'messenger_index_status_instant' => 'تصل الرسائل فورًا',
    'messenger_index_title' => 'الرسائل',
    'messenger_index_user_fallback' => 'مستخدم',
    'messenger_index_view_profile' => 'عرض الملف الشخصي',
    'messenger_index_you_prefix' => 'أنت:',
    'messenger_index_your_messages' => 'رسائلك',
    'new_message' => 'رسالة جديدة',
    'no_chats_sub' => 'اضغط على البحث لمراسلة أي شخص.',
    'no_chats_title' => 'لا توجد محادثات بعد.',
    'no_one_found' => 'لم يُعثر على أحد.',
    'now' => 'الآن',
    'photo' => '📷 صورة',
    'search_by_name' => 'ابحث بالاسم…',
    'search_people' => 'ابحث عن أشخاص لمراسلتهم…',
    'searching' => 'جارٍ البحث…',
    'title' => 'الرسائل',
    'view_profile' => 'عرض الملف الشخصي',
    'you_prefix' => 'أنت: ',

];
