<?php

/*
|--------------------------------------------------------------------------
| trainer — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/trainer.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'anonymous' => 'مجهول',
    'bio' => 'نبذة',
    'classes_count' => 'حصة',
    'clients' => 'العملاء',
    'coach' => 'مدرب',
    'exp_new' => 'جديد',
    'from_athletes' => 'من الرياضيين والعملاء',
    'link_copied' => 'تم نسخ الرابط',
    'no_bio' => 'لم يضف هذا المدرب نبذة بعد.',
    'no_reviews' => 'لا توجد تقييمات بعد',
    'no_reviews_note' => 'كن أول من يتدرب مع هذا المدرب.',
    'no_schedule' => 'لا يوجد جدول حصص',
    'no_schedule_note' => 'لا توجد حصص مجدولة لهذا المدرب حاليًا.',
    'rating' => 'التقييم',
    'reviews_count' => 'تقييم',
    'sessions_per_month' => 'حصة/شهر',
    'sessions_per_week' => 'حصة/أسبوع',
    'share' => 'مشاركة',
    'skills' => 'المهارات',
    'specialities' => 'التخصصات والشهادات',
    'tab_about' => 'نبذة',
    'tab_reviews' => 'التقييمات',
    'tab_schedule' => 'الجدول',
    'trainer_show_about_heading' => 'نبذة عن',
    'trainer_show_ach_client_favorite' => 'المفضل لدى العملاء',
    'trainer_show_ach_sessions_completed' => 'جلسات مكتملة',
    'trainer_show_ach_top_rated' => 'مدرب الأعلى تقييماً',
    'trainer_show_achievements_subtitle' => 'تقدير للتميز والتفاني',
    'trainer_show_achievements_title' => 'الإنجازات والمحطات',
    'trainer_show_anonymous' => 'مجهول',
    'trainer_show_biography' => 'السيرة الذاتية',
    'trainer_show_book_session' => 'حجز جلسة',
    'trainer_show_certification' => 'شهادة',
    'trainer_show_certifications' => 'الشهادات',
    'trainer_show_certifications_lower' => 'شهادات',
    'trainer_show_certifications_subtitle' => 'مؤهلات مهنية موثّقة للتحقق من صحتها',
    'trainer_show_certifications_title' => 'الشهادات والمؤهلات',
    'trainer_show_class_reactions' => 'تفاعلات الحصص',
    'trainer_show_classes_taught' => 'الحصص التي يدرّسها',
    'trainer_show_client_reviews' => 'تقييمات العملاء',
    'trainer_show_clients' => 'العملاء',
    'trainer_show_connect_social' => 'تواصل عبر وسائل التواصل الاجتماعي',
    'trainer_show_contact_information' => 'معلومات التواصل',
    'trainer_show_contact_subtitle' => 'تواصل معنا لبدء رحلتك التدريبية',
    'trainer_show_email' => 'البريد الإلكتروني',
    'trainer_show_experience' => 'الخبرة',
    'trainer_show_experience_word' => 'خبرة',
    'trainer_show_finished' => 'منتهية',
    'trainer_show_message' => 'مراسلة',
    'trainer_show_min' => 'دقيقة',
    'trainer_show_no_biography' => 'لا توجد سيرة ذاتية متاحة.',
    'trainer_show_no_certifications' => 'لم تتم إضافة أي شهادات بعد',
    'trainer_show_no_classes_day' => 'لا توجد حصص في هذا اليوم',
    'trainer_show_no_classes_scheduled' => 'لا توجد حصص مجدولة',
    'trainer_show_no_reviews' => 'لا توجد تقييمات بعد',
    'trainer_show_not_provided' => 'غير متوفر',
    'trainer_show_ongoing' => 'جارية',
    'trainer_show_phone' => 'الهاتف',
    'trainer_show_professional_subtitle' => 'مدرب محترف مكرس لرحلتك في اللياقة البدنية',
    'trainer_show_rating' => 'التقييم',
    'trainer_show_reviews_subtitle' => 'ما يقوله عملاؤنا عن تجربتهم',
    'trainer_show_schedule_subtitle' => 'جلسات تدريبية متاحة على مدار الأسبوع',
    'trainer_show_sessions' => 'الجلسات',
    'trainer_show_specialty' => 'التخصص',
    'trainer_show_tab_about' => 'نبذة',
    'trainer_show_tab_contact' => 'التواصل',
    'trainer_show_tab_reviews' => 'التقييمات',
    'trainer_show_tab_schedule' => 'الجدول',
    'trainer_show_trainer_fallback' => 'مدرب',
    'trainer_show_try_different_day' => 'جرّب اختيار يوم آخر',
    'trainer_show_upcoming' => 'قادمة',
    'trainer_show_verified' => 'موثّق',
    'trainer_show_weekly_schedule' => 'الجدول الأسبوعي',
    'trainer_show_year' => 'سنة',
    'trainer_show_years' => 'سنوات',
    'trains_at' => 'يدرّب في',
    'yr' => 'سنة',
    'yrs' => 'سنوات',

];
