<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'corner_aka' => 'आका',
    'corner_ao' => 'एओ',
    'division_label' => 'वजन श्रेणी',
    'mat' => 'मैट',
    'official_judge' => 'मूल्यांकक :n (फुकुशिन)',
    'official_judge_hint' => 'एक कोने में बैठकर उन अंकों को फ्लैग करता है जिन्हें वह देखता है।',
    'official_match_supervisor' => 'मैच सुपरवाइज़र (कंसा)',
    'official_match_supervisor_hint' => 'अधिकारियों को देखता है और आपत्तियों को सुलझाता है।',
    'official_referee' => 'मैदान कर्मचारी (शुशिन)',
    'official_referee_hint' => 'मैट पर मैच चलाता है: शुरू करता है और रोकता है, और स्कोर कॉल करता है।',
    'official_scorekeeper' => 'स्कोरकीपर',
    'official_scorekeeper_hint' => 'स्कोर और पीनल्टीज़ को शीट में रिकॉर्ड करता है।',
    'official_tatami_manager' => 'टैटामी प्रबंधक',
    'official_tatami_manager_hint' => 'मैट को अनुसूची के अनुसार चलाता है और एथलीटों को बुलाता है।',
    'official_timekeeper' => 'टाइमकीपर',
    'official_timekeeper_hint' => 'क्लॉक को रखता है: मैच का समय, स्थगित करने और अंतिम घंटी।',
    'score_ippon' => 'इप्पॉन',
    'score_wazari' => 'वजारी',
    'score_yuko' => 'यूको',
    'sport_label' => 'करेटे',
    'weigh_in' => 'वजन नापना',

];
