<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_arrange_draw' => 'Organizar quadro',
    'action_clear_draw' => 'Esvaziar quadro',
    'action_end_next_bout' => 'Terminar o próximo combate (teste)',
    'action_generate_draw' => 'Gerar quadro',
    'board_heading' => 'Ordem de entrada',
    'board_idle' => 'Sem combates em curso',
    'board_live' => 'Ao vivo',
    'board_on_deck' => 'A seguir',
    'board_stale' => 'A reconectar',
    'board_title' => 'Painel do tatame — :event',
    'call_mat_tbc' => 'o teu tatame',
    'call_opponent_tbc' => 'A confirmar',
    'call_room_body' => ':mat · combate :bout · vs :opponent',
    'call_room_title' => 'Apresenta-te na sala de chamada — :mat',
    'call_warmup_body' => ':ahead combates antes de ti · cerca de :minutes min',
    'call_warmup_title' => 'Aquece — entras em breve no :mat',
    'day_mats' => 'Dia :day: :count tatames',
    'draw_arranged' => 'Quadro atualizado 🥋',
    'draw_cleared' => 'Quadro esvaziado — todos os inscritos voltaram à lista',
    'draw_final' => 'O campeonato já começou — o quadro é final e não pode ser gerado de novo.',
    'draw_generated' => 'Quadro provisório gerado',
    'end_next_bout_done' => ':winner vence no :court. Os ecrãs desse tatame já foram avisados.',
    'end_next_bout_none' => 'Não há combates prontos para terminar — todos os combates em fila aguardam resultados anteriores.',
    'ended_locked' => 'Este campeonato terminou — os resultados são finais.',
    'gate_no_division' => 'A tua categoria de peso não faz parte das divisões deste campeonato, por isso não podes competir neste evento.',
    'gate_no_division_spectator' => 'A tua categoria de peso não faz parte das divisões deste campeonato, por isso não podes competir — mas podes assistir como espectador.',
    'gate_no_profile' => 'Adiciona o género e a data de nascimento ao teu perfil para te colocarmos numa categoria de peso.',
    'gate_no_weight' => 'Adiciona o teu peso atual ao perfil de saúde para te colocarmos numa categoria de peso.',
    'next_up_ahead' => 'combates antes',
    'next_up_done' => 'Terminaste por hoje.',
    'next_up_estimate' => 'estimativa, varia com o tatame',
    'next_up_finished' => 'Terminado',
    'next_up_none' => 'Não tens nada agendado neste momento.',
    'next_up_opponent_tbc' => 'A aguardar adversário',
    'next_up_squad' => 'A minha equipa',
    'next_up_title' => 'O meu próximo combate',
    'next_up_you_are_next' => 'És o próximo — vai para o tatame',
    'notify_draw_body' => 'O teu adversário, tatame e número de combate já estão publicados.',
    'notify_draw_title' => 'O quadro já saiu — :title',
    'notify_weigh_in_body' => 'Pesagem oficial às :time, :place. Tens de cumprir o limite da tua divisão para competir.',
    'notify_weigh_in_title' => 'Pesagem amanhã — :title',
    'result_body_done' => 'Foi o teu último combate do dia.',
    'result_body_next' => 'A seguir: :round no :mat, cerca de :minutes min',
    'result_loss_title' => 'Combate terminado',
    'result_win_title' => 'Ganhaste 🎉',
    'roster_registered' => 'Inscrito',
    'roster_unclassified' => 'Sem classificação',
    'type_label' => 'Campeonato de Karaté',

];
