<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * The product's own words, in every language, as DATA.
 *
 * ── Why this exists when `lang/<code>/*.php` already did ─────────────────────
 *
 * Generated locales were PHP files on disk, and that turned out to be three
 * problems wearing one coat:
 *
 *   1. A DEPLOY DESTROYS THEM. Only `lang/en` and `lang/ar` are tracked in
 *      git. Every language generated by `translate:interface` — eleven of them
 *      on 2026-09-09 — was untracked, on a box that is simultaneously the
 *      working directory and the rsync target for Deploy Staging. The next
 *      deploy would have taken the lot, silently, and the first sign would have
 *      been a Chinese poster in English again.
 *
 *   2. A UI CANNOT SAFELY WRITE THEM. `LangFileWriter` composes EXECUTABLE PHP
 *      out of a language model's output. That is defensible in a console
 *      command run by a developer; it is a code-execution surface as soon as a
 *      button on an admin screen can reach it. Rows are data and can never be
 *      executed (CLAUDE.md Part 3 §2).
 *
 *   3. NOBODY COULD FIX A WORD. Correcting one string meant editing a file and
 *      deploying — so in practice nobody did, which is the same reason the
 *      CONTENT translations grew a review screen and a human-wins rule.
 *
 * ── Additive, and an OVERLAY ────────────────────────────────────────────────
 *
 * This table does not replace the lang files; it sits on top of them via the
 * translation module's own loader. An empty table renders
 * exactly what the files render, so installing this changes nothing until
 * something is imported — and losing the table degrades to the files rather
 * than to a blank interface (RULE #1).
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('interface_translations', function (Blueprint $table) {
            $table->id();

            $table->string('locale', 12);

            /*
             * A lang file's namespace and group, kept apart exactly as Laravel's
             * loader takes them: `events` is group `events` with a null
             * namespace, `scoreboard::bjj_messages` is group `bjj_messages` in
             * namespace `scoreboard`. Storing the joined id instead would mean
             * splitting it again on every read.
             */
            $table->string('namespace', 64)->nullable();
            $table->string('group', 64);
            $table->string('key', 191);

            $table->text('value');

            /*
             * ⚠️ The same invariant the content translations carry: a machine
             * run NEVER overwrites what a person wrote. It is the reason a
             * correction is worth making — see App\Translation\Translations.
             */
            $table->string('origin', 12)->default('machine');

            // Which model wrote it, for when a provider turns out to be bad at
            // a language and its work has to be found again.
            $table->string('model', 64)->nullable();

            /*
             * The English this was translated FROM. When the source string is
             * edited, its translations are stale rather than wrong, and this is
             * what can tell the difference without re-reading every file.
             */
            $table->string('source_hash', 64)->nullable();

            $table->timestamps();

            // One row per string per language.
            $table->unique(['locale', 'namespace', 'group', 'key'], 'interface_translations_unique');

            // The loader's only query: everything for one file in one language.
            $table->index(['locale', 'namespace', 'group'], 'interface_translations_file');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('interface_translations');
    }
};
