<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'corner_chung' => 'चंग',
    'corner_hong' => 'हॉंग',
    'division_label' => 'वजन श्रेणी',
    'mat' => 'मैट',
    'official_center_referee' => 'केंद्रीय रेफरी',
    'official_center_referee_hint' => 'मैदान के मध्य में बाउट चलाता है।',
    'official_corner_judge' => 'कोने का जज :n',
    'official_corner_judge_hint' => 'मैदान के एक कोने से स्कोर करता है।',
    'official_court_supervisor' => 'कोर्ट सुपरवाइज़र',
    'official_court_supervisor_hint' => 'कोर्ट और उसके अधिकारियों की देखरेख करता है।',
    'official_review_jury' => 'समीक्षा जूरी',
    'official_review_jury_hint' => 'वीडियो समीक्षा अनुरोधों पर निर्णय लेता है।',
    'official_table_recorder' => 'टेबल रिकॉर्डर',
    'official_table_recorder_hint' => 'टेबल पर आधिकारिक रिकॉर्ड रखता है।',
    'official_timekeeper' => 'टाइमकीपर',
    'official_timekeeper_hint' => 'घड़ी चलाता है: राउंड का समय, रुकावटें और घंटी।',
    'score_body_kick' => 'शरीर का कूद',
    'score_head_kick' => 'सिर का कूद',
    'score_punch' => 'पंच',
    'score_turning_body' => 'शरीर के बाद का कूद',
    'score_turning_head' => 'सिर के बाद का कूद',
    'sport_label' => 'ताइक्वांडो',
    'weigh_in' => 'वजन नापना',

];
