<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Supported Locales
    |--------------------------------------------------------------------------
    |
    | Single source of truth for every language the app exposes. The locale
    | switcher, the SetLocale middleware and the <html dir/lang> attributes all
    | read from this list. To add a new language: add an entry here and drop a
    | matching set of files under lang/<code>/ — nothing else needs to change.
    |
    | Each entry:
    |   name   — English name (admin/debug use)
    |   native — name shown to the user in the switcher (in its own script)
    |   dir    — text direction: 'ltr' or 'rtl'
    |   flag   — flag-icons country code (https://github.com/lipis/flag-icons)
    |
    */

    'en' => ['name' => 'English', 'native' => 'English', 'dir' => 'ltr', 'flag' => 'us'],
    'ar' => ['name' => 'Arabic',  'native' => 'العربية', 'dir' => 'rtl', 'flag' => 'sa'],

    /*
    | Promoted 2026-09-09. `lang/pt/` was generated by `translate:interface`
    | and passed `--check` with zero rejected strings, so the INTERFACE speaks
    | Portuguese as well as the content does.
    |
    | ⚠️ Membership of THIS list is the switch. A language can be in
    | config/content_locales.php for a long time first — the organiser's words
    | are translated, the buttons are not — and it is promoted here only once
    | its lang files exist and validate. Adding a line here before that is what
    | ships a half-English product.
    */
    'pt' => ['name' => 'Portuguese', 'native' => 'Português', 'dir' => 'ltr', 'flag' => 'pt'],

    /*
    | ⚠️ THIS LIST IS THE PLATFORM'S LANGUAGES, NOT THE EVENTS'.
    |
    | A language belongs here only when the WHOLE interface is translated —
    | /me, the club admin, the settings screens, all of it — because being
    | listed here is what offers it to a member as their account language.
    |
    | An event is different and does not need this list at all. A visitor
    | reading one competition in Chinese gets `lang/zh/` applied for that event
    | alone (App\Translation\EventLocale + SetLocale), whether or not Chinese is
    | listed here. That is the whole point of the event-scoped locale.
    |
    | French and Spanish were briefly listed here on 2026-09-09 and removed the
    | same day: they had EVENT coverage, which is what was asked for, and were
    | promoted as if they had platform coverage, which they did not — leaving a
    | member who picked French with a half-English account. Generate a full
    | tier (`translate:interface fr --tier=all`) before adding one back.
    */

];
