<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'corner_aka' => 'AKA',
    'corner_ao' => 'AO',
    'division_label' => 'Kategoria e pesës',
    'mat' => 'Mat',
    'official_judge' => 'Shqyrtues :n (Fukushin)',
    'official_judge_hint' => 'Në një kënd dhe tregon pikët që shohin.',
    'official_match_supervisor' => 'Supervizor i lojës (Kansa)',
    'official_match_supervisor_hint' => 'Shikon oficierët e vetë dhe zgjidh protestat.',
    'official_referee' => 'Refere (Shushin)',
    'official_referee_hint' => 'Vetë loja në mat: fillon dhe ndalon, dhe thotë pikët.',
    'official_scorekeeper' => 'Regjistruesi i pikëve',
    'official_scorekeeper_hint' => 'Regjistron pikët dhe dënimet në fletë.',
    'official_tatami_manager' => 'Menaxheri i tatamit',
    'official_tatami_manager_hint' => 'Mbante matin në orarin dhe thotë atletët.',
    'official_timekeeper' => 'Kohëmarrësi',
    'official_timekeeper_hint' => 'Mbante kohën: koha e lojës, ndalimet dhe zilja e fundit.',
    'score_ippon' => 'Ippon',
    'score_wazari' => 'Waza-ari',
    'score_yuko' => 'Yuko',
    'sport_label' => 'Karate',
    'weigh_in' => 'Pesëm',

];
