<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'corner_aka' => 'AKA',
    'corner_ao' => 'AO',
    'division_label' => 'Catégorie de poids',
    'mat' => 'Tatami',
    'official_judge' => 'Juge :n (Fukushin)',
    'official_judge_hint' => 'Siège dans un coin et signale les points qu\'il voit.',
    'official_match_supervisor' => 'Superviseur de combat (Kansa)',
    'official_match_supervisor_hint' => 'Surveille les arbitres eux-mêmes et trancher les protestations.',
    'official_referee' => 'Arbitre (Shushin)',
    'official_referee_hint' => 'Gère le combat sur le tatami : le démarre et l\'arrête, et annonce le score.',
    'official_scorekeeper' => 'Greffier',
    'official_scorekeeper_hint' => 'Enregistre le score et les pénalités sur le tableau.',
    'official_tatami_manager' => 'Gestionnaire de tatami',
    'official_tatami_manager_hint' => 'Garde le tatami en cours de programme et appelle les athlètes.',
    'official_timekeeper' => 'Chronométrage',
    'official_timekeeper_hint' => 'Garde le compte à rebours : temps de combat, arrêts et sonnerie finale.',
    'score_ippon' => 'Ippon',
    'score_wazari' => 'Waza-ari',
    'score_yuko' => 'Yuko',
    'sport_label' => 'Karate',
    'weigh_in' => 'Poids à l\'entrée',

];
