<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'add_language' => '添加语言',
    'choose_language' => '选择语言',
    'complete' => ':done / :total',
    'continue_anyway' => '继续使用原始语言',
    'edited_by_you' => '您编辑的',
    'field_about' => '关于此事件',
    'field_cta' => '按钮文字',
    'field_division' => '组别',
    'field_fee' => '费用行',
    'field_level' => '级别',
    'field_location' => '地点',
    'field_prize' => '奖金',
    'field_requirement' => '要求',
    'field_ribbon' => '横幅',
    'field_title' => '标题',
    'interface_note' => '该事件使用 :language 编写。按钮和标签保持英文。',
    'languages' => '语言',
    'languages_sub' => '此事件在每种已阅读的语言中的内容',
    'machine' => '自动',
    'more_languages' => '其他语言',
    'needs_review' => '需要审核',
    'needs_review_note' => '原文在编写后发生了更改。',
    'no_language_found' => '没有匹配的语言。',
    'no_provider' => '未配置AI提供商。请在“管理”→“AI提供商”中添加一个，然后才能进行翻译。',
    'not_translated' => '尚未翻译',
    'nothing_yet' => '尚无人用其他语言阅读此事件。',
    'nothing_yet_note' => '一旦有人在公开页面选择该语言，它就会被编写并保存。',
    'preparing' => '正在准备 :language…',
    'preparing_failed' => '我们无法准备 :language。显示原始内容。',
    'preparing_note' => '此事件正在用 :language 编写。它只发生一次——之后的每个人都会立即收到。',
    'queued' => '已加入队列。稍后即可准备就绪。',
    'read_in' => '阅读此内容',
    'remove_language' => '删除此语言',
    'remove_language_confirm' => '删除 :language？您对该语言的修改也会被删除。机器翻译可以重新生成；您的编辑无法恢复。',
    'removed' => '语言已删除。',
    'retranslate' => '重新翻译',
    'saved' => '已保存。',
    'search_languages' => '搜索语言',
    'source_language' => '用 :language 编写',
    'translated_by_ai' => '自动翻译',

];
