<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_arrange_draw' => 'برگزاری را تنظیم کنید',
    'action_clear_draw' => 'برگزاری خالی',
    'action_end_next_bout' => 'مسابقه بعدی را پایان دهید (آزمایش)',
    'action_generate_draw' => 'ایجاد برگزاری',
    'board_heading' => 'ترتیب اجرایی',
    'board_idle' => 'مسابقه‌ای در حال اجرا نیست',
    'board_live' => 'زنده',
    'board_on_deck' => 'در صف',
    'board_stale' => 'در حال اتصال مجدد',
    'board_title' => 'برگزاری مات — :event',
    'call_mat_tbc' => 'مات شما',
    'call_opponent_tbc' => 'در انتظار',
    'call_room_body' => ':mat · مسابقه :bout · مقابل :opponent',
    'call_room_title' => 'به اتاق فراخوان بروید — :mat',
    'call_warmup_body' => ':ahead مسابقه قبل از شما · حدوداً :minutes دقیقه',
    'call_warmup_title' => 'آماده شوید — به زودی روی :mat',
    'day_mats' => 'روز :day: :count مات',
    'draw_arranged' => 'برگزاری به‌روزرسانی شد 🥋',
    'draw_cleared' => 'برگزاری خالی شد — همه ورودی‌ها دوباره در لیست هستند',
    'draw_final' => 'ماراتون شروع شده است — برگزاری نهایی است و نمی‌توان آن را دوباره ایجاد کرد.',
    'draw_generated' => 'برگزاری موقت ایجاد شد',
    'end_next_bout_done' => ':winner برنده شد روی :court. صفحه‌های نمایش در آن مات اطلاع داده شدند.',
    'end_next_bout_none' => 'هیچ مسابقه‌ای آماده برای پایان نیست — همه مسابقات در انتظار یک مسابقه قبلی هستند.',
    'ended_locked' => 'این ماراتون پایان یافته است — نتایج آن نهایی است.',
    'gate_no_division' => 'دسته وزن شما یکی از بخش‌های این ماراتون نیست، بنابراین شما مجاز به شرکت در این رویداد نیستید.',
    'gate_no_division_spectator' => 'دسته وزن شما یکی از بخش‌های این ماراتون نیست، بنابراین شما مجاز به شرکت نیستید — اما می‌توانید به عنوان تماشاچی حضور یابید.',
    'gate_no_profile' => 'جنسیت و تاریخ تولد خود را به پروفایل خود اضافه کنید تا بتوانیم شما را در یک دسته وزنی قرار دهیم.',
    'gate_no_weight' => 'وزن فعلی خود را به پروفایل سلامت خود اضافه کنید تا بتوانیم شما را در یک دسته وزنی قرار دهیم.',
    'next_up_ahead' => 'مسابقه‌های بعدی',
    'next_up_done' => 'شما امروز تمام شدید.',
    'next_up_estimate' => 'تخمین، حرکت با مات',
    'next_up_finished' => 'تمام شده',
    'next_up_none' => 'در حال حاضر هیچ چیز برای شما برنامه‌ریزی نشده است.',
    'next_up_opponent_tbc' => 'در انتظار مسابقه',
    'next_up_squad' => 'تیم من',
    'next_up_title' => 'مسابقه بعدی من',
    'next_up_you_are_next' => 'شما بعدی هستید — به مات بروید',
    'notify_draw_body' => 'ضد شما، مات و شماره مسابقه اکنون منتشر شده است.',
    'notify_draw_title' => 'برگزاری منتشر شد — :title',
    'notify_weigh_in_body' => 'وزن‌گیری رسمی در :time، :place. شما باید حد مجاز دسته وزنی خود را رعایت کنید تا بتوانید شرکت کنید.',
    'notify_weigh_in_title' => 'وزن‌گیری فردا — :title',
    'result_body_done' => 'این آخرین مسابقه روز شما بود.',
    'result_body_next' => 'بعدی: :round روی :mat، حدوداً :minutes دقیقه',
    'result_loss_title' => 'مسابقه تمام شد',
    'result_win_title' => 'شما برنده شدید 🎉',
    'roster_registered' => 'ثبت‌شده',
    'roster_unclassified' => 'بدون دسته',
    'type_label' => 'ماراتون کاراته',

];
