<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'corner_aka' => '赤',
    'corner_ao' => '青',
    'division_label' => '重量級',
    'mat' => '競技場',
    'official_judge' => '審判員 :n（副審）',
    'official_judge_hint' => '角に座り、見えたポイントを示します。',
    'official_match_supervisor' => '試合監督（観察）',
    'official_match_supervisor_hint' => '審判自身を監視し、異議を解決します。',
    'official_referee' => '審判（主審）',
    'official_referee_hint' => '競技場で試合を運営：開始・終了を管理し、スコアを呼びます。',
    'official_scorekeeper' => '記録係',
    'official_scorekeeper_hint' => 'スコアとペナルティを記録します。',
    'official_tatami_manager' => 'タタミマネージャー',
    'official_tatami_manager_hint' => '競技場のスケジュールを管理し、選手を呼び上げます。',
    'official_timekeeper' => '時間係',
    'official_timekeeper_hint' => '時計を管理：試合時間、停止時間、最終ベルを鳴らします。',
    'score_ippon' => '一歩',
    'score_wazari' => '半歩',
    'score_yuko' => '小手',
    'sport_label' => '空手',
    'weigh_in' => '体重計',

];
