<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_arrange_draw' => 'Rregullo nismën',
    'action_clear_draw' => 'Nisma bosh',
    'action_end_next_bout' => 'Përfundo bollin e mëvonshëm (test)',
    'action_generate_draw' => 'Gjenero nismën',
    'board_heading' => 'Renditja e funksionimit',
    'board_idle' => 'Nuk ka bolla në lëvizje',
    'board_live' => 'Live',
    'board_on_deck' => 'Në pritje',
    'board_stale' => 'Rilidhja',
    'board_title' => 'Tabela e matës — :event',
    'call_mat_tbc' => 'matja jote',
    'call_opponent_tbc' => 'TBC',
    'call_room_body' => ':mat · boll :bout · kundër :opponent',
    'call_room_title' => 'Raporto në dhomën e thirrjes — :mat',
    'call_warmup_body' => ':ahead bolla para tënde · rreth :minutes min',
    'call_warmup_title' => 'Ngrohu — je në :mat së shpejti',
    'day_mats' => 'Ditë :day: :count matëra',
    'draw_arranged' => 'Nisma u përditësua 🥋',
    'draw_cleared' => 'Nisma u zbraz — çdo i regjistruar është kthyer në listë',
    'draw_final' => 'Kampionati ka filluar — nismja është finale dhe nuk mund të gjenerohet sërish.',
    'draw_generated' => 'Nisma provizore u gjenerua',
    'end_next_bout_done' => ':winner fiton në :court. Ekranet në atë mat janë treguar.',
    'end_next_bout_none' => 'Nuk ka boll të gatshëm për të përfunduar — çdo boll në radhë është ende në pritje të një boll të mbushur.',
    'ended_locked' => 'Ky kampionat ka përfunduar — rezultatet e tij janë finale.',
    'gate_no_division' => 'Kategoria jote pesore nuk është një nga pjesët e këtij kampionati, prandaj nuk je i lejuar të merrësh pjesë në këtë veprim.',
    'gate_no_division_spectator' => 'Kategoria jote pesore nuk është një nga pjesët e këtij kampionati, prandaj nuk mund të merrësh pjesë — por je mirëpritur të merrësh pjesë si një parës.',
    'gate_no_profile' => 'Shto gjininë dhe datën e lindjes në profilin tënd që të mund të vendosemi në një kategori pesore.',
    'gate_no_weight' => 'Shto pesën aktuale në profilin tënd të shëndetit që të mund të vendosemi në një kategori pesore.',
    'next_up_ahead' => 'bolla para tënde',
    'next_up_done' => 'Ke përfunduar për ditën.',
    'next_up_estimate' => 'vlerësim, lëviz me matën',
    'next_up_finished' => 'I përfunduar',
    'next_up_none' => 'Nuk ka program për ty tani.',
    'next_up_opponent_tbc' => 'Duke pritur kontrarin',
    'next_up_squad' => 'Squadra ime',
    'next_up_title' => 'Bolla e mëvonshme',
    'next_up_you_are_next' => 'Je i radhës — shko në mat',
    'notify_draw_body' => 'Kontrari, matja dhe numri i bollit janë publikuar.',
    'notify_draw_title' => 'Nisma është publikuar — :title',
    'notify_weigh_in_body' => 'Pesa zyrtare në :time, :place. Duhet të mbështetësh kufirin e pjesës për të marrë pjesë.',
    'notify_weigh_in_title' => 'Pesa në morgen — :title',
    'result_body_done' => 'Kjo ishte bolla e fundit e ditës.',
    'result_body_next' => 'Tjetri: :round në :mat, rreth :minutes min',
    'result_loss_title' => 'Boll i përfunduar',
    'result_win_title' => 'Fitove 🎉',
    'roster_registered' => 'I regjistruar',
    'roster_unclassified' => 'I pa-klasifikuar',
    'type_label' => 'Kampionati i Taekwondos',

];
