<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_arrange_draw' => 'Organizar sorteo',
    'action_clear_draw' => 'Vaciar sorteo',
    'action_end_next_bout' => 'Finalizar próximo combate',
    'action_generate_draw' => 'Generar sorteo',
    'call_mat_tbc' => 'tu pista',
    'call_opponent_tbc' => 'Por confirmar',
    'call_room_body' => ':mat · combate :bout · vs :opponent',
    'call_room_title' => 'Dirígete a la sala de llamada — :mat',
    'call_warmup_body' => ':ahead combates antes de ti · aproximadamente :minutes min',
    'call_warmup_title' => 'Calentamiento — pronto estarás en :mat',
    'day_mats' => 'Día :day: :count pistas',
    'draw_arranged' => 'Sorteo actualizado 🥋',
    'draw_cleared' => 'Sorteo vaciado — todos los participantes regresan a la lista',
    'draw_final' => 'El campeonato ha comenzado — el sorteo es definitivo y no puede regenerarse.',
    'draw_generated' => 'Sorteo provisional generado',
    'end_next_bout_done' => ':winner gana en :court. Las pantallas en esa pista han sido notificadas.',
    'end_next_bout_none' => 'No hay combate listo para finalizar — todos los combates en cola aún están esperando a un competidor.',
    'ended_locked' => 'Este campeonato ha terminado — sus resultados son definitivos.',
    'gate_no_division' => 'Tu categoría de peso no es una de las divisiones de este campeonato, por lo tanto no eres elegible para competir en este evento.',
    'gate_no_division_spectator' => 'Tu categoría de peso no es una de las divisiones de este campeonato, por lo tanto no puedes competir — pero eres bienvenido a asistir como espectador.',
    'gate_no_profile' => 'Agrega tu género y fecha de nacimiento a tu perfil para poder ubicarte en una categoría de peso.',
    'gate_no_weight' => 'Agrega tu peso actual a tu perfil de salud para poder ubicarte en una categoría de peso.',
    'notify_draw_body' => 'Tu división ha sido sorteada. Abre el evento para ver a tu oponente, pista y número de combate.',
    'notify_draw_title' => 'El sorteo está listo — :title',
    'notify_weigh_in_body' => 'El pesaje comienza a las :time en :place. Trae tu identificación.',
    'notify_weigh_in_title' => 'Pesaje mañana — :title',
    'result_body_done' => 'Ese fue tu último combate del día.',
    'result_body_next' => 'Próximo: :round en :mat, aproximadamente :minutes min',
    'result_loss_title' => 'Combate finalizado',
    'result_win_title' => 'Ganaste 🎉',
    'roster_registered' => 'Registrado',
    'roster_unclassified' => 'Sin clasificar',
    'type_label' => 'Campeonato de Jiu-Jitsu',

];
