<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_arrange_draw' => 'Rregullo çelësin',
    'action_clear_draw' => 'Pastro çelësin',
    'action_end_next_bout' => 'Përfundo mëshirën e ardhshme',
    'action_generate_draw' => 'Gjenero çelësin',
    'call_mat_tbc' => 'mati indit',
    'call_opponent_tbc' => 'TBC',
    'call_room_body' => ':mat · mëshira :bout · kundër :opponent',
    'call_room_title' => 'Raporto në dhomën e thirrjes — :mat',
    'call_warmup_body' => ':ahead mëshira përpara jush · rreth :minutes min',
    'call_warmup_title' => 'Ngrohuni — jeni në :mat së shpejti',
    'day_mats' => 'Ditë :day: :count matëra',
    'draw_arranged' => 'Çelësi u përditësua 🥋',
    'draw_cleared' => 'Çelësi u pastrua — çdo i regjistruar është kthyer në listë',
    'draw_final' => 'Kampionati ka filluar — çelësi është përfundimtar dhe nuk mund të gjenerohet përsëri.',
    'draw_generated' => 'Çelësi provizor është gjeneruar',
    'end_next_bout_done' => ':winner fiton në :court. Ekranet në atë mat janë të informuar.',
    'end_next_bout_none' => 'Asnjë mëshirë nuk është gati për të përfunduar — çdo mëshirë në radhë është ende në pritje të një mëshirë.',
    'ended_locked' => 'Ky kampionat ka përfunduar — rezultatet janë përfundimtare.',
    'gate_no_division' => 'Klasa jote pesore nuk është një nga klasat e kampionatit, kështu që nuk je i lejuar të mësohet në këtë veprim.',
    'gate_no_division_spectator' => 'Klasa jote pesore nuk është një nga klasat e kampionatit, kështu që nuk mund të mësohet — por je mirëpritur të mësohet si një parës.',
    'gate_no_profile' => 'Shto gjininë dhe datën e lindjes në profilin tënd që të mund të vendosemi në një klasë pesore.',
    'gate_no_weight' => 'Shto peshën aktuale në profilin tënd të shëndetit që të mund të vendosemi në një klasë pesore.',
    'notify_draw_body' => 'Klasa jote është çelësuar. Hap veprimin për të parë mëshirën, mat-in dhe numrin e mëshirës.',
    'notify_draw_title' => 'Çelësi është dalë — :title',
    'notify_weigh_in_body' => 'Peshimi hapet në :time në :place. Merr ID-në tënde.',
    'notify_weigh_in_title' => 'Peshimi në morgen — :title',
    'result_body_done' => 'Kjo ishte mëshira e fundit e ditës së sotme.',
    'result_body_next' => 'Tjetra: :round në :mat, rreth :minutes min',
    'result_loss_title' => 'Mëshira përfundoi',
    'result_win_title' => 'Fitove 🎉',
    'roster_registered' => 'I regjistruar',
    'roster_unclassified' => 'I pa-klasifikuar',
    'type_label' => 'Kampionati i Jiu-Jitsit',

];
