<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_arrange_draw' => 'Organiser le tirage',
    'action_clear_draw' => 'Tirage vide',
    'action_end_next_bout' => 'Terminer le prochain combat (test)',
    'action_generate_draw' => 'Générer le tirage',
    'board_heading' => 'Ordre des combats',
    'board_idle' => 'Aucun combat en cours',
    'board_live' => 'En direct',
    'board_on_deck' => 'En attente',
    'board_stale' => 'Reconnexion',
    'board_title' => 'Tableau d’arène — :event',
    'call_mat_tbc' => 'votre arène',
    'call_opponent_tbc' => 'À déterminer',
    'call_room_body' => ':mat · combat :bout · contre :opponent',
    'call_room_title' => 'Rendez-vous à la salle d\'appel — :mat',
    'call_warmup_body' => ':ahead combats avant vous · environ :minutes min',
    'call_warmup_title' => 'Échauffement — vous êtes sur :mat bientôt',
    'day_mats' => 'Jour :day: :count arènes',
    'draw_arranged' => 'Tirage mis à jour 🥋',
    'draw_cleared' => 'Tirage vidé — chaque participant est de nouveau sur la liste',
    'draw_final' => 'Le championnat a commencé — le tirage est définitif et ne peut pas être régénéré.',
    'draw_generated' => 'Tirage provisoire généré',
    'end_next_bout_done' => ':winner gagne sur :court. Les écrans de cette arène ont été informés.',
    'end_next_bout_none' => 'Aucun combat n’est prêt à être terminé — tous les combats en file d’attente attendent toujours un combatant.',
    'ended_locked' => 'Ce championnat est terminé — ses résultats sont définitifs.',
    'gate_no_division' => 'Votre catégorie de poids n’est pas l’une des catégories de ce championnat, vous n’êtes donc pas éligible à participer à cet événement.',
    'gate_no_division_spectator' => 'Votre catégorie de poids n’est pas l’une des catégories de ce championnat, vous ne pouvez donc pas participer — mais vous êtes bienvenus pour assister en tant que spectateurs.',
    'gate_no_profile' => 'Ajoutez votre genre et votre date de naissance à votre profil afin que nous puissions vous classer dans une catégorie de poids.',
    'gate_no_weight' => 'Ajoutez votre poids actuel à votre profil santé afin que nous puissions vous classer dans une catégorie de poids.',
    'next_up_ahead' => 'combats avant',
    'next_up_done' => 'Vous avez terminé pour la journée.',
    'next_up_estimate' => 'estimation, se déplace avec l’arène',
    'next_up_finished' => 'Terminé',
    'next_up_none' => 'Rien de prévu pour vous en ce moment.',
    'next_up_opponent_tbc' => 'En attente d\'adversaire',
    'next_up_squad' => 'Mon équipe',
    'next_up_title' => 'Mon prochain combat',
    'next_up_you_are_next' => 'Vous êtes le suivant — allez à l’arène',
    'notify_draw_body' => 'Votre adversaire, arène et numéro de combat sont maintenant publiés.',
    'notify_draw_title' => 'Le tirage est publié — :title',
    'notify_weigh_in_body' => 'Pesée officielle à :time, :place. Vous devez atteindre la limite de votre catégorie pour pouvoir participer.',
    'notify_weigh_in_title' => 'Pesée demain — :title',
    'result_body_done' => 'C’était votre dernier combat de la journée.',
    'result_body_next' => 'Suivant :round sur :mat, environ :minutes min',
    'result_loss_title' => 'Combat terminé',
    'result_win_title' => 'Vous avez gagné 🎉',
    'roster_registered' => 'Inscrit',
    'roster_unclassified' => 'Non classé',
    'type_label' => 'Championnat de karaté',

];
