<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_add_entrants' => 'افزودن افراد',
    'action_close' => 'پایان جلسه',
    'action_queue_bout' => 'صف کردن یک مسابقه',
    'action_remove_entrant' => 'حذف فرد',
    'action_set_mats' => 'تنظیم میدان‌ها',
    'action_unqueue_bout' => 'حذف یک مسابقه',
    'bout_fought' => 'این مسابقه قبلاً برده شده است.',
    'bout_queued' => 'در صف قرار گرفت.',
    'bout_removed' => 'از صف حذف شد.',
    'console_add_people' => 'افزودن افراد',
    'console_add_selected' => 'افزودن :n به زمین',
    'console_bouts_today' => ':n امروز',
    'console_clear_pick' => 'پاک کردن',
    'console_closed' => 'این جلسه پایان یافته است.',
    'console_end_confirm' => 'پایان این جلسه تمرین؟ جدول امتیاز متوقف شده و جلسه آرشیو می‌شود.',
    'console_end_session' => 'پایان جلسه',
    'console_floor' => 'چه کسانی حاضر هستند',
    'console_floor_hint' => 'دو نفر را برای جفت شدن لمس کنید',
    'console_fought' => 'برده شده',
    'console_fought_empty' => 'هنوز مسابقه‌ای وجود ندارد.',
    'console_mat_count' => 'در حال اجرا :n',
    'console_mats' => 'میدان‌ها',
    'console_mats_label' => 'میدان‌های در حال اجرا',
    'console_no_members' => 'عضوی یافت نشد.',
    'console_open_table' => 'جدول امتیازات',
    'console_pair_hint' => 'دو نفر را از زمین انتخاب کنید',
    'console_pick_blue' => 'گوشه آبی',
    'console_pick_red' => 'گوشه قرمز',
    'console_queue' => 'صف',
    'console_queue_empty' => 'هیچ کس در صف این میدان نیست.',
    'console_queue_it' => 'صف کردن این مسابقه',
    'console_screens' => 'صفحات سالن',
    'console_search_members' => 'جستجوی اعضا',
    'console_table_needs_bout' => 'برای باز کردن جدول امتیازات یک مسابقه در این میدان صف کنید.',
    'entrant_queued' => 'در مسابقه‌ای هستند که هنوز برده نشده است.',
    'entrant_removed' => 'از زمین برداشته شد.',
    'entrants_added' => 'به زمین اضافه شد.',
    'label' => 'تمرین',
    'launch_bouts_n' => ':n مسابقه',
    'launch_eyebrow' => 'جدول امتیازات',
    'launch_lead' => 'دو نفر را روی میدان قرار دهید و سالن امتیاز را مشاهده کنید. بدون برگزاری، بدون ثبت‌نام — همین حالا باز کنید، وقتی تمرین تمام شد ببندید.',
    'launch_mats' => 'چند میدان',
    'launch_minutes' => 'طول مسابقه',
    'launch_minutes_n' => ':n دقیقه',
    'launch_no_sport' => 'این باشگاه هنوز ورزشی با جدول امتیازات میدان ندارد.',
    'launch_open_since' => 'از ساعت :time باز است',
    'launch_past' => 'جلسات قبلی',
    'launch_past_none' => 'هنوز جلسه‌ای وجود ندارد.',
    'launch_resume' => 'جلسه امروز را باز کن',
    'launch_running' => 'در حال اجرا',
    'launch_sport' => 'کدام ورزش',
    'launch_start' => 'شروع تمرین',
    'launch_title' => 'تمرین',
    'mat_n' => 'میدان :n',
    'mats_saved' => 'میدان‌ها به‌روز شدند.',
    'same_person' => 'دو نفر مختلف را انتخاب کنید.',
    'session_closed' => 'این جلسه پایان یافته است.',
    'session_ended' => 'جلسه پایان یافت.',
    'session_title' => 'تمرین · :date',
    'unknown_entrant' => 'اول باید هر دو گوشه روی زمین باشند.',
    'unknown_mat' => 'این یک میدانی نیست که این جلسه اجرا می‌شود.',

];
