<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'belt_black' => 'Siyah',
    'belt_blue' => 'Mavi',
    'belt_brown' => 'Kahverengi',
    'belt_purple' => 'Mor',
    'belt_white' => 'Beyaz',
    'corner_blue' => 'MAVİ',
    'corner_white' => 'BEYAZ',
    'division_label' => 'Kilo sınıfı',
    'mat' => 'Masa',
    'official_mat_organiser' => 'Masa Sorumlusu',
    'official_mat_organiser_hint' => 'Masayı çalıştırmayı ve sporcuları sırayla çağırmayı sağlar.',
    'official_referee' => 'Hakem',
    'official_referee_hint' => 'Masada maçı yönetir: başlatır ve durdurur, her puanı bildirir.',
    'official_scorekeeper' => 'Puan Kaydedici',
    'official_scorekeeper_hint' => 'Masada puanları, üstünlükleri ve cezaları girer.',
    'official_timekeeper' => 'Saat Tutucu',
    'official_timekeeper_hint' => 'Saati tutar: maç süresi, duraklamalar ve son zil.',
    'score_four' => '4 puan',
    'score_three' => '3 puan',
    'score_two' => '2 puan',
    'sport_label' => 'Brezilyen Jiu-Jitsu',
    'weigh_in' => 'Ağırlık kontrolü',

];
