#!/usr/bin/env bash
#
# Builds boutcam — the matside camera that records the bout AND carries the live
# feed from the SAME camera session.
#
#   ./build.sh                        # against stage
#   ./build.sh https://takeone.bh     # production
#
# It ships AS the camera (application id bh.takeone.cam), so it upgrades the
# WebView-era camera app in place rather than sitting beside it in the app list.
# One camera app on a phone, not two — an operator in a hall picking the wrong
# icon is a failure nobody diagnoses until the bout is over.
#
# It carries NO shared secret. The publish credential comes from
# /camera/{token}/live, authorised by this device's own camera token, so an APK
# that anyone may download grants nothing to whoever downloads it.
#
set -euo pipefail

cd "$(dirname "$0")"

BASE_URL="${1:-https://stage.takeone.bh}"
APP_ID="bh.takeone.cam"

export PATH="/opt/flutter/bin:$PATH"
export ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT:-/opt/android-sdk}"
export TAR_OPTIONS="${TAR_OPTIONS:---no-same-owner --no-same-permissions}"

# The launcher icon: the TAKEONE mark on a white plate, generated by
# ../tools-make-icons.php and shared with every other build in this directory.
cp -r ../android_shared_res/. android/app/src/main/res/

sed -i -E "s/applicationId = \"[^\"]+\"/applicationId = \"${APP_ID}\"/" android/app/build.gradle.kts

echo "▸ building boutcam (${APP_ID}) against ${BASE_URL}"

flutter build apk --release --dart-define="BASE_URL=${BASE_URL}"

mkdir -p ../dist
out="../dist/boutcam.apk"
mv build/app/outputs/flutter-apk/app-release.apk "$out"
rm -f build/app/outputs/flutter-apk/app-release.apk.sha1

echo
echo "✓ ${out}  ($(du -h "$out" | cut -f1))"
"${ANDROID_SDK_ROOT}/build-tools/34.0.0/aapt2" dump badging "$out" | grep -E "^package:|^application:" || true
