<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'corner_aka' => 'AKA',
    'corner_ao' => 'AO',
    'division_label' => 'Ağırlık kategorisi',
    'mat' => 'Alan (Mat)',
    'official_judge' => 'Jüri üyesi :n (Fukushin)',
    'official_judge_hint' => 'Bir köşede oturur ve gördükleri puanları işaretler.',
    'official_match_supervisor' => 'Maç sorumlusu (Kansa)',
    'official_match_supervisor_hint' => 'Resmi kişileri izler ve itirazları çözülmesini sağlar.',
    'official_referee' => 'Hakem (Shushin)',
    'official_referee_hint' => 'Maçı alan üzerinde yürütür: başlatır ve durdurur, skoru çağırır.',
    'official_scorekeeper' => 'Skor kaydedici',
    'official_scorekeeper_hint' => 'Skoru ve cezaları kağıda kaydeder.',
    'official_tatami_manager' => 'Tatami yöneticisi',
    'official_tatami_manager_hint' => 'Alanın programına göre çalışır ve sporcuları çağırır.',
    'official_timekeeper' => 'Saat kontrolcüsü',
    'official_timekeeper_hint' => 'Saat tutar: maç süresi, duraklamalar ve son zil.',
    'score_ippon' => 'İppon',
    'score_wazari' => 'Waza-ari',
    'score_yuko' => 'Yuko',
    'sport_label' => 'Karate',
    'weigh_in' => 'Ağırlık kontrolü',

];
