<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'corner_chung' => '中',
    'corner_hong' => '红',
    'division_label' => '体重级别',
    'mat' => '场地',
    'official_center_referee' => '中心裁判',
    'official_center_referee_hint' => '在场地中央主持比赛。',
    'official_corner_judge' => '角落裁判 :n',
    'official_corner_judge_hint' => '从场地一角评分。',
    'official_court_supervisor' => '场地监督员',
    'official_court_supervisor_hint' => '监督场地及其工作人员。',
    'official_review_jury' => '复核小组',
    'official_review_jury_hint' => '处理视频复查请求。',
    'official_table_recorder' => '记录员',
    'official_table_recorder_hint' => '在记录台保持官方记录。',
    'official_timekeeper' => '计时员',
    'official_timekeeper_hint' => '计时：回合时间、暂停和铃声。',
    'score_body_kick' => '踢身',
    'score_head_kick' => '踢头',
    'score_punch' => '拳击',
    'score_turning_body' => '转身踢身',
    'score_turning_head' => '转身踢头',
    'sport_label' => '跆拳道',
    'weigh_in' => '称重',

];
