<?php

/*
|--------------------------------------------------------------------------
| auth — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/auth.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'auth_desktop_login_check_inbox_after' => '. לחץ עליו כדי להתחבר.',
    'auth_desktop_login_check_inbox_before' => 'שלחנו קישור לכניסה ל-',
    'auth_desktop_login_check_inbox_title' => 'בדוק את תיבת הדוא"ל שלך',
    'auth_desktop_login_email_me_link' => 'שליחת קישור לכניסה',
    'auth_desktop_login_email_placeholder' => 'מספר טלפון או דוא"ל',
    'auth_desktop_login_forgot_password' => 'שכחת את הסיסמה?',
    'auth_desktop_login_magic_hint' => 'אין סיסמה? נשלח לך דוא"ל עם קישור לכניסה חד-פעמי.',
    'auth_desktop_login_password_placeholder' => 'סיסמה',
    'auth_desktop_login_register' => 'יצירת חשבון',
    'auth_desktop_login_remember_me' => 'זכור אותי',
    'auth_desktop_login_resend_verification' => 'שליחת דוא"ל אימות מחדש',
    'auth_desktop_login_sign_in' => 'כניסה',
    'auth_desktop_login_subtitle' => 'ברוך הבא! התחבר כדי להמשיך',
    'auth_desktop_login_tab_link' => 'קישור לכניסה',
    'auth_desktop_login_tab_password' => 'סיסמה',
    'auth_desktop_login_unverified_hint' => 'לא קיבלת את הדוא"ל או שפג תוקפו?',
    'auth_desktop_login_unverified_title' => 'הדוא"ל לא אומת',
    'auth_desktop_login_your_email_placeholder' => 'הדוא"ל שלך',
    'auth_forgot_password_back_to_login' => 'חזרה לכניסה',
    'auth_forgot_password_email_placeholder' => 'דוא"ל',
    'auth_forgot_password_send_reset_link' => 'שלח קישור לאיפוס סיסמה',
    'auth_forgot_password_subtitle' => 'אין בעיה — הזן את כתובת הדוא"ל שלך ונשלח לך קישור לאיפוס.',
    'auth_forgot_password_title' => 'שכחת את הסיסמה שלך?',
    'auth_register_birthdate' => 'תאריך לידה',
    'auth_register_confirm_password' => 'אישור סיסמה',
    'auth_register_email' => 'כתובת דוא"ל',
    'auth_register_full_name' => 'שם מלא',
    'auth_register_joining_club' => 'אתה מתחבר ל-',
    'auth_register_mobile_number' => 'מספר טלפון',
    'auth_register_nationality' => 'לאום',
    'auth_register_password' => 'סיסמה',
    'auth_register_submit' => 'הרשמה',
    'auth_register_subtitle' => 'יצירת חשבון',
    'auth_register_wizard_err_generic_post' => '). אנא נסה שוב.',
    'auth_register_wizard_err_generic_pre' => 'משהו השתבש (שגיאה',
    'auth_register_wizard_err_network' => 'שגיאת רשת. אנא בדוק את החיבור שלך ונסה שוב.',
    'auth_register_wizard_err_session_expired' => 'ההפעלה שלך פגתה. אנא רענן את הדף ונסה שוב.',
    'auth_register_wizard_ph_child_name' => 'שם מלא של הילד',
    'auth_register_wizard_ph_email' => 'כתובת דוא"ל',
    'auth_register_wizard_ph_full_name' => 'שם מלא',
    'auth_register_wizard_ph_health' => 'אנא תאר את כל התנאים הבריאותיים',
    'auth_register_wizard_ph_mobile' => 'מספר טלפון',
    'auth_register_wizard_rel_daughter' => 'בת',
    'auth_register_wizard_rel_member_fallback' => 'عضو משפחה',
    'auth_register_wizard_rel_other' => 'אחר',
    'auth_register_wizard_rel_son' => 'בן',
    'auth_register_wizard_rel_spouse' => 'בעל',
    'auth_register_wizard_terms_changes_body' => 'תנאים אלו עלולים להActualized מעת לעת; שימוש مستمر בשירות מהווה הסכמה.',
    'auth_register_wizard_terms_changes_title' => 'שינויים בתנאים',
    'auth_register_wizard_terms_conduct_body' => 'החברים מצופים לציית לתקנות המועדון ולנהוג בשלום עם הצוות והחברים האחרים.',
    'auth_register_wizard_terms_conduct_title' => 'קוד התנהגות',
    'auth_register_wizard_terms_confirm' => 'באמצעות סימון התיבה למטה, אתה מאשר שקראת והסכמת לתנאים אלו.',
    'auth_register_wizard_terms_default_intro' => 'ברוך הבא ל-:club! על ידי הרשמה, אתה מסכים לתנאים הבאים:',
    'auth_register_wizard_terms_medical_body' => 'אנא ציין כל מצב רפואי או בריאות שעשוי להשפיע על השתתפותך.',
    'auth_register_wizard_terms_medical_title' => 'בריאות ובריאות',
    'auth_register_wizard_terms_membership_body' => 'חברותך מתחילה לאחר שהרשמה אושרה ותשלום (אם נדרש) אושר.',
    'auth_register_wizard_terms_membership_title' => 'חברות',
    'auth_register_wizard_terms_payment_body' => 'כל התשלומים חייבים להיות בסיום הרשמה אלא אם נבחרה אפשרות \'תשלום מאוחר יותר\'.',
    'auth_register_wizard_terms_payment_title' => 'תשלום',
    'auth_register_wizard_terms_privacy_body' => 'המידע האישי שלך משמש רק לניהול החברות שלך ולא יועבר ללא הסכמה.',
    'auth_register_wizard_terms_privacy_title' => 'פרטיות',
    'auth_reset_password_back_to_login' => 'חזרה לכניסה',
    'auth_reset_password_confirm_password_label' => 'אשר סיסמה חדשה',
    'auth_reset_password_email_label' => 'כתובת דוא"ל',
    'auth_reset_password_new_password_label' => 'סיסמה חדשה',
    'auth_reset_password_submit' => 'איפוס סיסמה',
    'auth_reset_password_title' => 'איפוס הסיסמה שלך',
    'auth_verify_email_check_inbox_line1' => 'שלחנו קישור אימות לכתובת הדוא"ל שלך.',
    'auth_verify_email_check_inbox_line2' => 'אנא לחץ על הקישור כדי לאשר את החשבון שלך.',
    'auth_verify_email_check_inbox_title' => 'בדוק את הדוא"ל שלך',
    'auth_verify_email_didnt_receive' => 'לא קיבלת את הדוא"ל?',
    'auth_verify_email_fresh_link_sent' => 'קישור אימות חדש נשלח לכתובת הדוא"ל שלך.',
    'auth_verify_email_go_to_app' => 'המשך',
    'auth_verify_email_one_step_away' => 'שלב אחד נוסף להצטרפות',
    'auth_verify_email_redirecting_prefix' => 'הפניה בעוד',
    'auth_verify_email_redirecting_suffix' => 'שניות...',
    'auth_verify_email_resend_button' => 'שלח שוב דוא"ל אימות',
    'auth_verify_email_sign_out' => 'התנתק',
    'auth_verify_email_verified_body' => 'כתובת הדוא"ל שלך אומתה בהצלחה.',
    'auth_verify_email_verified_title' => 'דוא"ל אומת!',
    'auth_verify_email_wrong_account' => 'חשבון שגוי?',
    'choose_not_you' => 'השתמש במספר או דוא"ל אחר',
    'choose_sub' => 'יותר מאדם אחד משתמש במספר זה. הקש על האדם שמתחבר.',
    'choose_title' => 'מי מתחבר?',
    'club_waiting' => 'המועדון שלך ממתין. בוא נלך.',
    'create_account' => 'יצירת חשבון',
    'didnt_receive' => 'לא קיבלת את הדוא"ל או שפג תוקפו?',
    'email' => 'דוא"ל',
    'email_not_verified' => 'הדוא"ל לא אומת',
    'email_or_phone' => 'מספר טלפון או דוא"ל',
    'forgot_password' => 'שכחת את הסיסמה?',
    'hide_password' => 'הסתרת סיסמה',
    'magic_cta' => 'שליחת קישור לכניסה',
    'magic_prompt' => 'אין סיסמה? נשלח לך דוא"ל עם קישור לכניסה חד-פעמי.',
    'magic_sent_body' => 'אם קיים חשבון עבור כתובת הדוא"ל הזו, שלחנו קישור לכניסה. לחץ על הכפתור בדוא"ל כדי להתחבר – אין צורך בסיסמה.',
    'magic_sent_title' => 'בדוק את תיבת הדוא"ל שלך',
    'new_to_takeone' => 'חדש ב-TAKEONE?',
    'or' => 'או',
    'password' => 'סיסמה',
    'remember_me' => 'זכור אותי',
    'resend_verification' => 'שליחת דוא"ל אימות מחדש',
    'show_password' => 'הצגת סיסמה',
    'sign_in' => 'כניסה',
    'tab_magic' => 'קישור לכניסה',
    'tab_password' => 'סיסמה',
    'welcome_back' => 'ברוך הבא',

];
