<?php

/*
|--------------------------------------------------------------------------
| explore — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/explore.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'apply_location' => 'החל מיקום',
    'book_session' => '예약 תור',
    'cat_all' => 'הכל',
    'cat_clubs' => 'מועדונים',
    'cat_events' => 'אירועים',
    'cat_food_plans' => 'תוכניות אוכל',
    'cat_nutrition' => 'תזונה',
    'cat_physiotherapy' => 'פיזיותרפיה',
    'cat_shops' => 'חנויות',
    'cat_supplements' => 'תוספים',
    'cat_trainers' => 'מאמנים',
    'cat_venues' => 'מרחבים',
    'choose_option_body' => 'בחר אפשרות לכל פריט ציוד נבחר.',
    'choose_option_title' => 'דרוש אפשרות',
    'detecting_location' => 'מאתר מיקום...',
    'drag_marker' => 'גרור את הסמן כדי להגדיר את המיקום',
    'error_fetching_clubs' => 'אירעה שגיאה במהלך טעינת מועדונים.',
    'ev_coming_up' => 'בקרוב',
    'ev_failed' => 'טעינת האירועים נכשלה. נסה שוב.',
    'ev_finding' => 'טוען אירועים...',
    'ev_free' => 'חינם',
    'ev_full' => 'מלא',
    'ev_going' => 'מתבצע',
    'ev_happening_now' => 'מתרחש עכשיו',
    'ev_live' => 'חיים',
    'ev_none_hint' => 'אין דבר שפועל או מתוכנן עבורך כרגע.',
    'ev_none_title' => 'אין אירועים פתוחים',
    'ev_open' => 'פתוח',
    'ev_spots_left' => 'מקומות פנויים',
    'ev_starts_in' => 'מתחיל בעוד',
    'ev_tba' => 'בקרוב',
    'ev_until' => 'עד',
    'ev_view_event' => 'הצגת אירוע',
    'explore' => 'סייר',
    'failed_to_fetch_clubs' => 'טעינת מועדונים נכשלה. אנא נסה שוב.',
    'finding' => 'מחפש מה קרוב אליך...',
    'geolocation_not_supported' => 'מיקום לא נתמך על ידי הדפדפן.',
    'hero_eyebrow' => 'מצא קרוב אליך',
    'hero_sub' => 'מועדונים, מאמנים, קורסים ועוד קרוב אליך',
    'hero_title' => 'מצא את התאמה מושלמת',
    'join_club' => 'הצטרף למועדון',
    'km_away' => 'ק"מ מרוחק',
    'loading' => 'טוען...',
    'location_access_denied' => 'נ_access למיקום נדחה.',
    'location_available' => 'מיקום זמין',
    'location_request_timed_out' => 'בקשת המיקום תקועה.',
    'location_unavailable' => 'מידע מיקום לא זמין.',
    'members' => 'חברים',
    'na' => 'לא זמין',
    'near_me' => 'קרוב אלי',
    'no_members_selected_body' => 'בחר לפחות חבר אחד כדי להמשיך.',
    'no_members_selected_title' => 'לא נבחרו חברים',
    'no_results' => 'לא נמצאו תוצאות',
    'no_results_hint' => 'נסה להתאים את החיפוש או את המיקום',
    'packages' => 'חבילות',
    'packages_required_body' => 'בחר חבילת שירות לכל חבר נבחר.',
    'packages_required_title' => 'דרוש חבילת שירות',
    'payment_required_body' => 'העלה צילום מסך של התשלום או בחר לשלם מאוחר יותר.',
    'payment_required_title' => 'דרוש אישור תשלום',
    'personal_trainer_badge' => 'מאמן אישי',
    'please_try_again' => 'אנא נסה שוב.',
    'rating' => 'דירוג',
    'registration_error_body' => 'משהו השתבש במהלך שליחת ההרשמה.',
    'registration_failed_title' => 'ההרשמה נכשלה',
    'registration_submitted_body' => 'ההרשמה שלך נשלחה למועדון לאישור.',
    'registration_submitted_title' => 'ההרשמה נשלחה',
    'reviews' => 'ביקורות',
    'search_placeholder' => 'חפש מועדונים, מאמנים...',
    'set_location' => 'הגדר את המיקום',
    'sports_club_badge' => 'מועדון ספורט',
    'trainers' => 'מאמנים',
    'unable_to_get_location' => 'לא ניתן לקבל את המיקום.',
    'view_details' => 'הצג פרטים',
    'years_exp' => 'שנות ניסיון',

];
