<?php

/*
|--------------------------------------------------------------------------
| header — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/header.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'cart' => 'עגלת קניות',
    'cart_soon' => 'עגלת קניות בקרוב',
    'chat' => 'צ\'אט',
    'clear_all' => 'נקה הכל',
    'club_management' => 'ניהול מועדון',
    'just_now' => 'לפני רגע',
    'mark_all_read' => 'סמן הכל כנקרא',
    'menu' => 'תפריט',
    'no_notifications' => 'אין התראות עדיין',
    'notification' => 'התראה',
    'notifications' => 'התראות',
    'personal_desc' => 'הפרופיל שלי, ההזמנות, התשלומים',
    'personal_view' => 'תצוגה אישית',
    'scan_code_placeholder' => 'ABC123',
    'scan_foreign_host' => 'קוד QR זה מצביע לאתר אחר, לכן לא נפתח.',
    'scan_hint' => 'הצב את המצלמה על קוד QR',
    'scan_no_camera' => 'לא ניתן לגשת למצלמה.',
    'scan_or_type' => 'או escribir את הקוד בן 6 תווים',
    'scan_qr' => 'סרוק קוד QR',
    'scan_unsupported' => 'סריקת QR אינה נתמכת בדפדפן זה.',
    'switch_view' => 'החלף תצוגה',

];
