<?php

/*
|--------------------------------------------------------------------------
| security — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/security.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'add_otp_desc' => 'הוסף קוד חד-פעמי מהאפליקציה שלך לאימות בכל התחברות.',
    'cancel' => 'בטל',
    'change_password' => 'שנה סיסמה',
    'change_password_desc' => 'כל הجلسיות הפעילות האחרות ינותקו כאשר תשנה את הסיסמה.',
    'code_placeholder' => 'קוד 6 ספרות',
    'code_placeholder_long' => 'קוד 6 ספרות או קוד חזרה',
    'confirm_new_password' => 'אימות סיסמה חדשה',
    'current_password' => 'סיסמה נוכחית',
    'disable' => 'השבת',
    'disable_2fa' => 'השבת אימות דו-שלבי',
    'disable_confirm_desc' => 'הזן קוד אימות נוכחי (או קוד חזרה) לאישור.',
    'disable_two_factor' => 'השבת אימות דו-שלבי',
    'enable_2fa' => 'הפעל אימות דו-שלבי',
    'lockdown_message' => 'נהפוך את החשבון שלך למאובטח יותר.',
    'new_password' => 'סיסמה חדשה',
    'protected_message' => 'החשבון שלך מוגן היטב.',
    'protected_with_app' => 'מוגן עם Google Authenticator.',
    'recovery_codes' => 'קודי חזרה',
    'recovery_codes_desc' => 'קודי גיבוי חד-פעמיים במקרה שתאבד את האפליקציה שלך לאימות.',
    'regenerate' => 'צור מחדש',
    'regenerate_codes' => 'צור קודי חזרה',
    'regenerate_codes_title' => 'צור קודי חזרה',
    'regenerate_confirm_desc' => 'קודי החזרה הקיימים שלך יפסיקו לעבוד. הזן את הקוד שלך לאימות כדי לאשר.',
    'security' => 'אבטחה',
    'security_challenge_back_to_login' => 'חזור לכניסה',
    'security_challenge_backup_hint' => 'הזן אחד מקודי החזרה ה-8 תווים.',
    'security_challenge_subtitle' => 'הזן את הקוד מהאפליקציה שלך לאימות.',
    'security_challenge_title' => 'אימות דו-שלבי',
    'security_challenge_use_authenticator' => 'השתמש באפליקציה לאימות במקום זאת',
    'security_challenge_use_recovery' => 'השתמש בקוד חזרה',
    'security_challenge_verify' => 'אימות',
    'security_index_2fa_disabled_desc' => 'הוסף שכבה נוספת של אבטחה לחשבון שלך.',
    'security_index_2fa_enabled_desc' => 'החשבון שלך מוגן עם Google Authenticator.',
    'security_index_2fa_title' => 'אימות דו-שלבי',
    'security_index_change_password' => 'שנה סיסמה',
    'security_index_change_password_desc' => 'כל הجلسיות הפעילות האחרות ינותקו כאשר תשנה את הסיסמה.',
    'security_index_code_or_recovery_placeholder' => 'קוד 6 ספרות או קוד חזרה',
    'security_index_code_placeholder' => 'קוד 6 ספרות',
    'security_index_confirm_new_password' => 'אימות סיסמה חדשה',
    'security_index_current_password' => 'סיסמה נוכחית',
    'security_index_disable_2fa' => 'השבת אימות דו-שלבי',
    'security_index_disable_2fa_modal_desc' => 'הזן את הקוד שלך לאימות נוכחי (או קוד חזרה) לאישור.',
    'security_index_disable_2fa_modal_title' => 'השבת אימות דו-שלבי',
    'security_index_disabled' => 'מושבת',
    'security_index_enable_2fa' => 'הפעל אימות דו-שלבי',
    'security_index_enabled' => 'מופעל',
    'security_index_new_password' => 'סיסמה חדשה',
    'security_index_recovery_codes' => 'קודי חזרה',
    'security_index_recovery_codes_desc' => 'קודי גיבוי חד-פעמיים אם תאבד גישה לאפליקציה שלך לאימות.',
    'security_index_regen_codes_modal_desc' => 'קודי החזרה הקיימים שלך יאבדו. הזן את הקוד שלך לאימות כדי לאשר.',
    'security_index_regen_codes_modal_title' => 'צור מחדש קודי חזרה',
    'security_index_regenerate' => 'צור מחדש',
    'security_index_regenerate_codes' => 'צור קודי חזרה',
    'security_index_subtitle' => 'נהל את אבטחת החשבון שלך ואימות דו-שלבי',
    'security_index_title' => 'הגדרות אבטחה',
    'security_index_update_password' => 'עדכן סיסמה',
    'security_recovery_codes_account_protected' => 'החשבון שלך מוגן כעת.',
    'security_recovery_codes_copied' => 'הועתק!',
    'security_recovery_codes_copy_all' => 'העתק את כל הקודים',
    'security_recovery_codes_heading_enabled' => 'אימות דו-שלבי מופעל',
    'security_recovery_codes_heading_new' => 'קודים חלופיים חדשים',
    'security_recovery_codes_page_title' => 'קודים חלופיים',
    'security_recovery_codes_save_safe' => 'שמור את הקודים החלופיים במקום בטוח.',
    'security_recovery_codes_store_desc' => 'כל קוד ניתן לשימוש פעם אחת בלבד.',
    'security_recovery_codes_store_safely' => 'אחסן את הקודים בצורה בטוחה.',
    'security_recovery_codes_success_alert' => 'אימות דו-שלבי הופעל בהצלחה על החשבון שלך.',
    'security_setup_manual_entry' => 'לא ניתן לסרוק? הזן מפתח זה ידנית באפליקציה:',
    'security_setup_step1_app_name' => 'Google Authenticator',
    'security_setup_step1_app_store' => 'App Store',
    'security_setup_step1_download' => 'הורד',
    'security_setup_step1_from' => 'במכשיר שלך מ-',
    'security_setup_step1_heading' => 'התקן את Google Authenticator',
    'security_setup_step1_or' => 'או',
    'security_setup_step1_play_store' => 'Play Store',
    'security_setup_step2_heading' => 'סרוק את קוד ה-QR',
    'security_setup_step2_open' => 'פתח את האפליקציה, הקש',
    'security_setup_step2_scan_option' => 'סרוק קוד QR',
    'security_setup_step2_then_choose' => ', ואז בחר',
    'security_setup_step3_heading' => 'אמת את הקוד שלך',
    'security_setup_step3_subtitle' => 'הזן את הקוד בן 6 הספרות המופיע באפליקציה כדי לאמת את ההגדרה.',
    'security_setup_subtitle' => 'לך על הצעדים הבאים כדי להגן על החשבון שלך באמצעות Google Authenticator.',
    'security_setup_time_based' => 'מבוסס זמן',
    'security_setup_time_based_prefix' => 'בחר',
    'security_setup_time_based_suffix' => 'כאשר מופיע.',
    'security_setup_title' => 'הגדר אימות דו-שלבי',
    'security_setup_verify_button' => 'אמת והפעל',
    'title' => 'הגדרות אבטחה',
    'two_factor_auth' => 'אימות דו-שלבי',
    'two_factor_off' => 'אימות דו-שלבי מושבת',
    'two_factor_on' => 'אימות דו-שלבי מופעל',
    'update_password' => 'עדכן סיסמה',

];
