<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_arrange_draw' => 'ترتيب القرعة',
    'action_clear_draw' => 'إفراغ القرعة',
    'action_end_next_bout' => 'إنهاء النزال التالي (تجربة)',
    'action_generate_draw' => 'إنشاء القرعة',
    'board_heading' => 'ترتيب النزالات',
    'board_idle' => 'لا توجد نزالات جارية',
    'board_live' => 'مباشر',
    'board_on_deck' => 'التالي',
    'board_stale' => 'إعادة الاتصال',
    'board_title' => 'شاشة البساط — :event',
    'call_mat_tbc' => 'بساطك',
    'call_opponent_tbc' => 'يُحدَّد لاحقاً',
    'call_room_body' => ':mat · النزال :bout · ضد :opponent',
    'call_room_title' => 'توجّه إلى غرفة النداء — :mat',
    'call_warmup_body' => 'يسبقك :ahead نزال · حوالي :minutes دقيقة',
    'call_warmup_title' => 'استعد للإحماء — نزالك على :mat قريباً',
    'day_mats' => 'اليوم :day: :count بساط',
    'draw_arranged' => 'تم تحديث القرعة 🥋',
    'draw_cleared' => 'أُفرغت القرعة — عاد جميع المشاركين إلى القائمة',
    'draw_final' => 'انطلقت البطولة — القرعة نهائية ولا يمكن إعادة إنشائها.',
    'draw_generated' => 'تم إنشاء القرعة المبدئية',
    'end_next_bout_done' => 'فاز :winner على :court. تم إبلاغ شاشات هذا البساط.',
    'end_next_bout_none' => 'لا يوجد نزال جاهز للإنهاء — كل النزالات المتبقية تنتظر نتائج سابقة.',
    'ended_locked' => 'انتهت هذه البطولة — نتائجها نهائية.',
    'gate_no_division' => 'فئتك الوزنية ليست من فئات هذه البطولة، لذلك لا يمكنك المشاركة فيها.',
    'gate_no_division_spectator' => 'فئتك الوزنية ليست من فئات هذه البطولة، لذلك لا يمكنك المنافسة — لكن يمكنك الحضور كمتفرّج.',
    'gate_no_profile' => 'أضف الجنس وتاريخ الميلاد إلى ملفك الشخصي لنتمكن من تحديد فئتك الوزنية.',
    'gate_no_weight' => 'أضف وزنك الحالي إلى ملفك الصحي لنتمكن من تحديد فئتك الوزنية.',
    'next_up_ahead' => 'نزال قبلك',
    'next_up_done' => 'انتهت نزالاتك لليوم.',
    'next_up_estimate' => 'تقدير يتغيّر مع سير البساط',
    'next_up_finished' => 'انتهى',
    'next_up_none' => 'لا يوجد نزال مجدول لك حالياً.',
    'next_up_opponent_tbc' => 'بانتظار المنافس',
    'next_up_squad' => 'فريقي',
    'next_up_title' => 'نزالي القادم',
    'next_up_you_are_next' => 'أنت التالي — توجّه إلى البساط',
    'notify_draw_body' => 'تم نشر منافسك ورقم البساط ورقم النزال.',
    'notify_draw_title' => 'صدرت القرعة — :title',
    'notify_weigh_in_body' => 'الوزن الرسمي الساعة :time في :place. يجب أن تحقق وزن فئتك للمشاركة.',
    'notify_weigh_in_title' => 'الوزن الرسمي غداً — :title',
    'result_body_done' => 'كان ذلك آخر نزال لك اليوم.',
    'result_body_next' => 'التالي: :round على :mat، حوالي :minutes دقيقة',
    'result_loss_title' => 'انتهى النزال',
    'result_win_title' => 'فزت 🎉',
    'roster_registered' => 'مسجّل',
    'roster_unclassified' => 'غير مصنّف',
    'type_label' => 'بطولة تايكوندو',

];
