<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_arrange_draw' => 'Çekilişi düzenle',
    'action_clear_draw' => 'Boş çekiliş',
    'action_end_next_bout' => 'Bir sonraki maçı bitir (test)',
    'action_generate_draw' => 'Çekiliş oluştur',
    'board_heading' => 'Çalışma sırası',
    'board_idle' => 'Oynanan maç yok',
    'board_live' => 'Canlı',
    'board_on_deck' => 'Hazır',
    'board_stale' => 'Yeniden bağlanıyor',
    'board_title' => 'Sahne panosu — :event',
    'call_mat_tbc' => 'sahneniz',
    'call_opponent_tbc' => 'Yapılacak',
    'call_room_body' => ':mat · maç :bout · :opponent ile',
    'call_room_title' => 'Çağrı odasına git — :mat',
    'call_warmup_body' => ':ahead maç önceki · yaklaşık :minutes dk',
    'call_warmup_title' => 'Isınma — :mat yakında',
    'day_mats' => 'Gün :day: :count sahne',
    'draw_arranged' => 'Çekiliş güncellendi 🥋',
    'draw_cleared' => 'Çekiliş boşaltıldı — her katılımcı listede tekrar yer alıyor',
    'draw_final' => 'Şampiyonluk başladı — çekiliş son ve yeniden oluşturulamaz.',
    'draw_generated' => 'Geçici çekiliş oluşturuldu',
    'end_next_bout_done' => ':winner :court sahnesinde kazandı. Bu sahnedeki ekranlara bildirildi.',
    'end_next_bout_none' => 'Bitirilecek bir maç yok — her sıradaki maç hâlâ besleyici bekliyor.',
    'ended_locked' => 'Bu şampiyonluk sona erdi — sonuçları kesindir.',
    'gate_no_division' => 'Ağırlık kategoriniz bu şampiyonluğun bölümlerinden biri değil, bu yüzden bu etkinlikte yarışamazsınız.',
    'gate_no_division_spectator' => 'Ağırlık kategoriniz bu şampiyonluğun bölümlerinden biri değil, bu yüzden yarışamazsınız — ama izleyici olarak katılabilirsiniz.',
    'gate_no_profile' => 'Profilinize cinsiyetinizi ve doğum tarihinizi ekleyin ki ağırlık kategorisine yerleştirilebilelim.',
    'gate_no_weight' => 'Profilinize mevcut ağırlığınızı ekleyin ki ağırlık kategorisine yerleştirilebilelim.',
    'next_up_ahead' => 'maç önce',
    'next_up_done' => 'Bugün için tamamladınız.',
    'next_up_estimate' => 'tahmini, sahneyle hareket eder',
    'next_up_finished' => 'Tamamlandı',
    'next_up_none' => 'Şu anda sizin için planlanan bir şey yok.',
    'next_up_opponent_tbc' => 'Rakip bekleniyor',
    'next_up_squad' => 'Kurumum',
    'next_up_title' => 'Sonraki maçım',
    'next_up_you_are_next' => 'Sıradasınız — sahneye git',
    'notify_draw_body' => 'Rakibiniz, sahne ve maç numaranız artık yayınlandı.',
    'notify_draw_title' => 'Çekiliş yayınlandı — :title',
    'notify_weigh_in_body' => 'Resmi ağırlık kontrolü :time, :place. Yarışmak için bölgenin limitine ulaşmanız gerekir.',
    'notify_weigh_in_title' => 'Yarın ağırlık kontrolü — :title',
    'result_body_done' => 'Bugünün son maçınız.',
    'result_body_next' => 'Sonraki: :round :mat üzerinde, yaklaşık :minutes dk',
    'result_loss_title' => 'Maç bitti',
    'result_win_title' => 'Kazandınız 🎉',
    'roster_registered' => 'Kayıtlı',
    'roster_unclassified' => 'Kategorisiz',
    'type_label' => 'Karate Şampiyonluğu',

];
