<?php

/*
|--------------------------------------------------------------------------
| auth — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/auth.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'auth_desktop_login_check_inbox_after' => '۔ اس پر کلک کریں تاکہ سائن ان کر سکیں۔',
    'auth_desktop_login_check_inbox_before' => 'ہم نے لاگ ان لنک بھیجی ہے',
    'auth_desktop_login_check_inbox_title' => 'اپنی ان باکس چیک کریں',
    'auth_desktop_login_email_me_link' => 'میرے لیے لاگ ان لنک بھیجیں',
    'auth_desktop_login_email_placeholder' => 'فون نمبر یا ای میل',
    'auth_desktop_login_forgot_password' => 'پاس ورڈ بھول گئے؟',
    'auth_desktop_login_magic_hint' => 'کوئی پاس ورڈ نہیں؟ ہم آپ کو ایک بار کے لیے لاگ ان لنک بھیجیں گے۔',
    'auth_desktop_login_password_placeholder' => 'پاس ورڈ',
    'auth_desktop_login_register' => 'اکاؤنٹ بنائیں',
    'auth_desktop_login_remember_me' => 'مجھے یاد رکھیں',
    'auth_desktop_login_resend_verification' => 'تصدیقی ای میل دوبارہ بھیجیں',
    'auth_desktop_login_sign_in' => 'سائن ان کریں',
    'auth_desktop_login_subtitle' => 'ویلکم ایک بار پھر! جاری رکھنے کے لیے سائن ان کریں',
    'auth_desktop_login_tab_link' => 'لاگ ان لنک',
    'auth_desktop_login_tab_password' => 'پاس ورڈ',
    'auth_desktop_login_unverified_hint' => 'ای میل نہیں ملی یا اس کی میعاد ختم ہو گئی؟',
    'auth_desktop_login_unverified_title' => 'ای میل تصدیق نہیں ہوئی',
    'auth_desktop_login_your_email_placeholder' => 'آپ کا ای میل',
    'auth_forgot_password_back_to_login' => 'لاگ ان پر واپس جائیں',
    'auth_forgot_password_email_placeholder' => 'ای میل',
    'auth_forgot_password_send_reset_link' => 'پاس ورڈ ری سیٹ لنک بھیجیں',
    'auth_forgot_password_subtitle' => 'کوئی بھی کمی نہیں — اپنا ای میل درج کریں اور ہم آپ کو ری سیٹ لنک بھیجیں گے۔',
    'auth_forgot_password_title' => 'اپنا پاس ورڈ بھول گئے؟',
    'auth_register_birthdate' => 'پیدائش کی تاریخ',
    'auth_register_confirm_password' => 'پاس ورڈ کی تصدیق کریں',
    'auth_register_email' => 'ای میل ایڈریس',
    'auth_register_full_name' => 'پورا نام',
    'auth_register_joining_club' => 'آپ جوڑے جا رہے ہیں',
    'auth_register_mobile_number' => 'موبائل نمبر',
    'auth_register_nationality' => 'ملکیت',
    'auth_register_password' => 'پاس ورڈ',
    'auth_register_submit' => 'رجسٹر کریں',
    'auth_register_subtitle' => 'اپنا اکاؤنٹ بنائیں',
    'auth_register_wizard_err_generic_post' => ')۔ براہ کرم دوبارہ کوشش کریں۔',
    'auth_register_wizard_err_generic_pre' => 'کچھ غلط ہو گیا (خرابی',
    'auth_register_wizard_err_network' => 'نیٹ ورک کی خرابی۔ براہ کرم اپنے کنیکشن کو چیک کریں اور دوبارہ کوشش کریں۔',
    'auth_register_wizard_err_session_expired' => 'آپ کی سیشن ختم ہو گئی ہے۔ براہ کرم صفحہ کو ریفریش کریں اور دوبارہ کوشش کریں۔',
    'auth_register_wizard_ph_child_name' => 'بچے کا پورا نام',
    'auth_register_wizard_ph_email' => 'ای میل پتہ',
    'auth_register_wizard_ph_full_name' => 'پورا نام',
    'auth_register_wizard_ph_health' => 'براہ کرم کسی بھی صحتی حالت کی تفصیل دیں',
    'auth_register_wizard_ph_mobile' => 'موبائل نمبر',
    'auth_register_wizard_rel_daughter' => 'بیٹی',
    'auth_register_wizard_rel_member_fallback' => 'خاندانی ارکان',
    'auth_register_wizard_rel_other' => 'دیگر',
    'auth_register_wizard_rel_son' => 'بیٹا',
    'auth_register_wizard_rel_spouse' => 'شادی شدہ',
    'auth_register_wizard_terms_changes_body' => 'یہ شرائط وقت کے ساتھ تازہ کی جا سکتی ہیں؛ سروس کا جاری استعمال قبولیت کا پیش کرتا ہے۔',
    'auth_register_wizard_terms_changes_title' => 'شرائط میں تبدیلیاں',
    'auth_register_wizard_terms_conduct_body' => 'رکنین کو کلب کے قواعد کو پیروی کرنے اور اسٹاف اور دوسرے رکنین کے ساتھ محترم رفتار کرنے کی اپیل کی جاتی ہے۔',
    'auth_register_wizard_terms_conduct_title' => 'آپریشن کے قواعد',
    'auth_register_wizard_terms_confirm' => 'نیچے دی گئی بکس کو چیک کر کے، آپ تصدیق کرتے ہیں کہ آپ نے اس شرائط کو پڑھا ہے اور اس سے رضامند ہیں۔',
    'auth_register_wizard_terms_default_intro' => ':club میں خوش آمدید! رجسٹر کرتے وقت آپ مندرجہ ذیل شرائط کو قبول کرتے ہیں:',
    'auth_register_wizard_terms_medical_body' => 'براہ کرم کسی بھی طبی یا صحت کی حالت کو درج کریں جو شرکت کے لیے اثر انداز ہو سکتی ہے۔',
    'auth_register_wizard_terms_medical_title' => 'طبی اور صحت',
    'auth_register_wizard_terms_membership_body' => 'آپ کی رکنیت اس وقت شروع ہوتی ہے جب آپ کی رجسٹریشن کی تصدیق ہو جائے اور اگر ضرورت ہو تو ادائیگی کی تصدیق ہو جائے۔',
    'auth_register_wizard_terms_membership_title' => 'رکنیت',
    'auth_register_wizard_terms_payment_body' => 'سب سے پہلے رجسٹریشن کے وقت ادائیگی ضروری ہوتی ہے جب تک کہ \'بعد میں ادائیگی\' کا آپشن منتخب نہ ہو۔',
    'auth_register_wizard_terms_payment_title' => 'ادائیگی',
    'auth_register_wizard_terms_privacy_body' => 'آپ کی ذاتی معلومات صرف آپ کے اشتہار کو منظم کرنے کے لیے استعمال کی جاتی ہے اور رضامندی کے بغیر شیئر نہیں کی جاتی۔',
    'auth_register_wizard_terms_privacy_title' => 'پرائیویسی',
    'auth_reset_password_back_to_login' => 'لاگ ان پر واپس جائیں',
    'auth_reset_password_confirm_password_label' => 'نیا پاس ورڈ تصدیق کریں',
    'auth_reset_password_email_label' => 'ای میل پتہ',
    'auth_reset_password_new_password_label' => 'نیا پاس ورڈ',
    'auth_reset_password_submit' => 'پاس ورڈ ری سیٹ کریں',
    'auth_reset_password_title' => 'اپنا پاس ورڈ ری سیٹ کریں',
    'auth_verify_email_check_inbox_line1' => 'ہم نے آپ کے ای میل پتہ پر ایک تصدیقی لنک بھیج دی ہے۔',
    'auth_verify_email_check_inbox_line2' => 'براہ کرم اپنے اکاؤنٹ کو تصدیق کرنے کے لیے لنک پر کلک کریں۔',
    'auth_verify_email_check_inbox_title' => 'اپنے ای میل کو چیک کریں',
    'auth_verify_email_didnt_receive' => 'ای میل نہیں ملی؟',
    'auth_verify_email_fresh_link_sent' => 'آپ کے ای میل پتہ پر ایک نیا تصدیقی لنک بھیج دیا گیا ہے۔',
    'auth_verify_email_go_to_app' => 'جاری رکھیں',
    'auth_verify_email_one_step_away' => 'شامل ہونے کے لیے ایک اور مرحلہ',
    'auth_verify_email_redirecting_prefix' => 'میں ری ڈائریکٹ ہو رہا ہے',
    'auth_verify_email_redirecting_suffix' => 'سیکنڈز...',
    'auth_verify_email_resend_button' => 'تصدیقی ای میل دوبارہ بھیجیں',
    'auth_verify_email_sign_out' => 'سائن آؤٹ کریں',
    'auth_verify_email_verified_body' => 'آپ کا ای میل کامیابی سے تصدیق کر دی گئی ہے۔',
    'auth_verify_email_verified_title' => 'ای میل تصدیق شدہ ہو گیا!',
    'auth_verify_email_wrong_account' => 'غلط اکاؤنٹ؟',
    'choose_not_you' => 'ایک مختلف نمبر یا ای میل استعمال کریں',
    'choose_sub' => 'اس نمبر کو استعمال کرنے والے ایک سے زیادہ افراد ہیں۔ جو شخص سائن ان ہو رہا ہے اس پر ٹیپ کریں۔',
    'choose_title' => 'کون سائن ان ہو رہا ہے؟',
    'club_waiting' => 'آپ کا کلب انتظار کر رہا ہے۔ چلیں۔',
    'create_account' => 'اکاؤنٹ بنائیں',
    'didnt_receive' => 'ای میل نہیں ملی یا اس کی میعاد ختم ہو گئی؟',
    'email' => 'ای میل',
    'email_not_verified' => 'ای میل تصدیق نہیں ہوئی',
    'email_or_phone' => 'فون نمبر یا ای میل',
    'forgot_password' => 'پاس ورڈ بھول گئے؟',
    'hide_password' => 'پاس ورڈ چھپائیں',
    'magic_cta' => 'میرے لیے لاگ ان لنک بھیجیں',
    'magic_prompt' => 'کوئی پاس ورڈ نہیں؟ ہم آپ کو ایک بار کے لیے لاگ ان لنک بھیجیں گے۔',
    'magic_sent_body' => 'اگر اس ای میل کے لیے کوئی اکاؤنٹ موجود ہے، تو ہم نے لاگ ان لنک بھیج دی ہے۔ سائن ان کرنے کے لیے ای میل میں بٹن پر کلک کریں — کوئی پاس ورڈ ضروری نہیں۔',
    'magic_sent_title' => 'اپنی ان باکس چیک کریں',
    'new_to_takeone' => 'TAKEONE کے نئے؟',
    'or' => 'یا',
    'password' => 'پاس ورڈ',
    'remember_me' => 'مجھے یاد رکھیں',
    'resend_verification' => 'تصدیقی ای میل دوبارہ بھیجیں',
    'show_password' => 'پاس ورڈ دکھائیں',
    'sign_in' => 'سائن ان کریں',
    'tab_magic' => 'لاگ ان لنک',
    'tab_password' => 'پاس ورڈ',
    'welcome_back' => 'ویلکم ایک بار پھر',

];
