<?php

/*
|--------------------------------------------------------------------------
| header — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/header.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'cart' => 'گاڑی',
    'cart_soon' => 'گاڑی جلد آرہی ہے',
    'chat' => 'چیٹ',
    'clear_all' => 'سبھی صاف کریں',
    'club_management' => 'کلب مینجمنٹ',
    'just_now' => 'ابھی ابھی',
    'mark_all_read' => 'سبھی کو پڑھا گیا کریں',
    'menu' => 'مینو',
    'no_notifications' => 'ابھی تک کوئی نوٹیفیکیشن نہیں',
    'notification' => 'نوٹیفیکیشن',
    'notifications' => 'نوٹیفیکیشنز',
    'personal_desc' => 'میرا پروفائل، بُکنگز، ادائیگیاں',
    'personal_view' => 'ذاتی ویو',
    'scan_code_placeholder' => 'ABC123',
    'scan_foreign_host' => 'یہ QR کوڈ دوسری ویب سائٹ کی طرف جا رہا ہے، اس لیے اسے کھولا نہیں گیا۔',
    'scan_hint' => 'اپنی کیمرہ کو QR کوڈ پر رکھیں',
    'scan_no_camera' => 'کیمرہ تک رسائی نہیں ہو سکی۔',
    'scan_or_type' => 'یا 6 حرفوں کا کوڈ ٹائپ کریں',
    'scan_qr' => 'QR کوڈ سکین کریں',
    'scan_unsupported' => 'اس براؤزر میں QR سکیننگ کی حمایت نہیں ہے۔',
    'switch_view' => 'ویو سوئچ کریں',

];
