<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_add_entrants' => 'लोग जोड़ें',
    'action_close' => 'सत्र समाप्त करें',
    'action_queue_bout' => 'एक बाउट कतार में डालें',
    'action_remove_entrant' => 'लोग हटाएं',
    'action_set_mats' => 'मैट्स सेट करें',
    'action_unqueue_bout' => 'एक बाउट कतार से हटाएं',
    'bout_fought' => 'वह बाउट पहले से ही लड़ा जा चुकी है।',
    'bout_queued' => 'कतार में डाला गया।',
    'bout_removed' => 'कतार से हटाया गया।',
    'console_add_people' => 'लोग जोड़ें',
    'console_add_selected' => 'फ्लोर पर :n जोड़ें',
    'console_bouts_today' => ':n आज',
    'console_clear_pick' => 'साफ करें',
    'console_closed' => 'यह सेशन समाप्त हो चुका है।',
    'console_end_confirm' => 'इस स्पैरिंग सेशन को समाप्त करें? स्कोरबोर्ड रुक जाएगा और सेशन संग्रहीत हो जाएगा।',
    'console_end_session' => 'सेशन समाप्त करें',
    'console_floor' => 'यहाँ कौन है',
    'console_floor_hint' => 'दो लोगों को जोड़ने के लिए टैप करें',
    'console_fought' => 'लड़ाई हुई',
    'console_fought_empty' => 'अभी तक कोई बाउट नहीं।',
    'console_mat_count' => 'चल रहा :n',
    'console_mats' => 'मैट्स',
    'console_mats_label' => 'मैट्स चल रहे हैं',
    'console_no_members' => 'कोई सदस्य नहीं मिला।',
    'console_open_table' => 'स्कोरिंग टेबल',
    'console_pair_hint' => 'फ्लोर से दो लोग चुनें',
    'console_pick_blue' => 'नीला कोर्नर',
    'console_pick_red' => 'लाल कोर्नर',
    'console_queue' => 'कतार',
    'console_queue_empty' => 'इस मैट पर कोई कतार नहीं है।',
    'console_queue_it' => 'इस बाउट को कतार में डालें',
    'console_screens' => 'हॉल स्क्रीन्स',
    'console_search_members' => 'सदस्य खोजें',
    'console_table_needs_bout' => 'इस मैट पर एक बाउट कतार में डालें ताकि उसका स्कोरिंग टेबल खुले।',
    'entrant_queued' => 'वे एक ऐसी बाउट में हैं जो अभी तक नहीं लड़ी गई है।',
    'entrant_removed' => 'फ्लोर से हटाया गया।',
    'entrants_added' => 'फ्लोर पर जोड़ा गया।',
    'label' => 'स्पैरिंग',
    'launch_bouts_n' => ':n बाउट्स',
    'launch_eyebrow' => 'ट्रेनिंग स्कोरबोर्ड',
    'launch_lead' => 'दो लोगों को एक मैट पर रखें और हॉल स्कोर देखेगा। कोई ड्रा नहीं, कोई एंट्री नहीं — अभी खोलें, ट्रेनिंग समाप्त होने पर बंद करें।',
    'launch_mats' => 'कितने मैट्स',
    'launch_minutes' => 'बाउट की लंबाई',
    'launch_minutes_n' => ':n मिनट',
    'launch_no_sport' => 'इस क्लब में अभी तक कोई मैट स्कोरबोर्ड वाला खेल नहीं है।',
    'launch_open_since' => ':time से खोला गया',
    'launch_past' => 'पहले के सेशन',
    'launch_past_none' => 'अभी तक कोई सेशन नहीं।',
    'launch_resume' => 'आज का सेशन खोलें',
    'launch_running' => 'अभी चल रहा है',
    'launch_sport' => 'कौन सा खेल',
    'launch_start' => 'स्पैरिंग शुरू करें',
    'launch_title' => 'स्पैरिंग',
    'mat_n' => 'मैट :n',
    'mats_saved' => 'मैट्स अपडेट किए गए।',
    'same_person' => 'दो अलग-अलग लोग चुनें।',
    'session_closed' => 'यह सेशन समाप्त हो चुका है।',
    'session_ended' => 'सेशन समाप्त किया गया।',
    'session_title' => 'स्पैरिंग · :date',
    'unknown_entrant' => 'पहले दोनों कोर्नर फ्लोर पर होने चाहिए।',
    'unknown_mat' => 'वह एक मैट नहीं है जो इस सेशन में चल रहा है।',

];
