<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'corner_chung' => 'CHUNG',
    'corner_hong' => 'HONG',
    'division_label' => 'Catégorie de poids',
    'mat' => 'Tapis',
    'official_center_referee' => 'Arbitre central',
    'official_center_referee_hint' => 'Dirige le combat au centre de la cour.',
    'official_corner_judge' => 'Juge de coin :n',
    'official_corner_judge_hint' => 'Évalue depuis un coin de la cour.',
    'official_court_supervisor' => 'Superviseur de la cour',
    'official_court_supervisor_hint' => 'Surveille la cour et ses officiels.',
    'official_review_jury' => 'Jury d\'examen',
    'official_review_jury_hint' => 'Tranche sur les demandes de relecture vidéo.',
    'official_table_recorder' => 'Greffier de table',
    'official_table_recorder_hint' => 'Tient le registre officiel à la table.',
    'official_timekeeper' => 'Chronométrage',
    'official_timekeeper_hint' => 'Gère l\'horloge : temps de round, arrêts et sonnerie.',
    'score_body_kick' => 'Coup de pied au corps',
    'score_head_kick' => 'Coup de pied à la tête',
    'score_punch' => 'Punch',
    'score_turning_body' => 'Coups de pied tournant au corps',
    'score_turning_head' => 'Coups de pied tournant à la tête',
    'sport_label' => 'Taekwondo',
    'weigh_in' => 'Poids à l\'entrée',

];
