<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'add_language' => 'أضف لغة',
    'choose_language' => 'اختر اللغة',
    'complete' => ':done من :total',
    'continue_anyway' => 'تابع بالنص الأصلي',
    'edited_by_you' => 'عدّلتها بنفسك',
    'field_about' => 'عن الحدث',
    'field_cta' => 'نص الزر',
    'field_division' => 'الفئة',
    'field_fee' => 'بند الرسوم',
    'field_level' => 'المستوى',
    'field_location' => 'المكان',
    'field_prize' => 'الجائزة',
    'field_requirement' => 'متطلب',
    'field_ribbon' => 'الشريط',
    'field_title' => 'العنوان',
    'interface_note' => 'الحدث بـ:language، أما الأزرار والعناوين فتبقى بالإنجليزية.',
    'languages' => 'اللغات',
    'languages_sub' => 'ما يقوله هذا الحدث بكل لغة قُرئ بها',
    'machine' => 'آلية',
    'more_languages' => 'لغة أخرى',
    'needs_review' => 'بحاجة إلى مراجعة',
    'needs_review_note' => 'تغيّر النص الأصلي بعد كتابة هذه الترجمة.',
    'no_language_found' => 'لا توجد لغة مطابقة.',
    'no_provider' => 'لا يوجد مزوّد ذكاء اصطناعي مُعدّ. أضف واحداً من لوحة الإدارة ← مزوّدو الذكاء الاصطناعي قبل كتابة الترجمات.',
    'not_translated' => 'لم تُترجم بعد',
    'nothing_yet' => 'لم يقرأ أحد هذا الحدث بلغة أخرى بعد.',
    'nothing_yet_note' => 'ما إن يختار أحدهم لغة في الصفحة العامة حتى تُكتب وتُحفظ.',
    'preparing' => 'جارٍ التحضير بـ:language…',
    'preparing_failed' => 'تعذّر التحضير بـ:language الآن. سيُعرض النص الأصلي.',
    'preparing_note' => 'يُكتب هذا الحدث الآن بـ:language. يحدث هذا مرة واحدة فقط — ومن يأتي بعدك يراه فوراً.',
    'queued' => 'أُضيف إلى قائمة الانتظار. سيجهز بعد لحظات.',
    'read_in' => 'اقرأه بـ',
    'remove_language' => 'احذف هذه اللغة',
    'remove_language_confirm' => 'حذف :language؟ ستُحذف تعديلاتك عليها أيضاً. الترجمة الآلية يمكن إعادة توليدها، أما تعديلاتك فلا.',
    'removed' => 'حُذفت اللغة.',
    'retranslate' => 'أعد الترجمة',
    'saved' => 'تم الحفظ.',
    'search_languages' => 'ابحث عن لغة',
    'source_language' => 'كُتب بـ:language',
    'translated_by_ai' => 'ترجمة آلية',


    'on_the_poster' => 'على الملصق',
    'on_the_poster_sub' => 'اللغات التي يمكن للقارئ اختيارها',
    'offer_every_language' => 'إتاحة كل اللغات',
    'offer_every_language_note' => 'يمكن للقارئ اختيار أي من :count لغة نترجم إليها.',
    'every_language' => 'كل اللغات (:count)',
    'n_languages' => ':count لغة',
    'save_poster_languages' => 'حفظ',
    'offered_saved' => 'تم حفظ لغات الملصق.',
    'hiding_keeps_words' => 'إخفاء لغة يحفظ نصّها — بما في ذلك أي تصحيح كتبته بنفسك — جاهزًا لحين إتاحتها مرة أخرى. وللتخلّص من النص نهائيًا، افتح تلك اللغة واحذفها.',
    'always' => 'دائمًا',
    'written' => 'مكتوبة',
    'not_on_poster' => 'مخفية',
    'not_on_poster_note' => 'هذه اللغة ليست على الملصق، فلا يمكن لأحد قراءتها الآن. نصّها محفوظ — اضغط لإعادتها.',
];
