<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'belt_black' => 'Noir',
    'belt_blue' => 'Bleu',
    'belt_brown' => 'Marron',
    'belt_purple' => 'Violet',
    'belt_white' => 'Blanc',
    'corner_blue' => 'BLEU',
    'corner_white' => 'BLANC',
    'division_label' => 'Catégorie de poids',
    'mat' => 'Tatami',
    'official_mat_organiser' => 'Organisateur du tatami',
    'official_mat_organiser_hint' => 'Garde le tatami en activité pour programmer et appelle les athlètes.',
    'official_referee' => 'Arbitre',
    'official_referee_hint' => 'Gère le combat sur le tatami : le démarre et l\'arrête, et signale chaque point.',
    'official_scorekeeper' => 'Greffier',
    'official_scorekeeper_hint' => 'Saisit les points, les avantages et les pénalités à la table.',
    'official_timekeeper' => 'Chronométrage',
    'official_timekeeper_hint' => 'Gère l\'horloge : temps de combat, arrêts et sonnerie finale.',
    'score_four' => '4 points',
    'score_three' => '3 points',
    'score_two' => '2 points',
    'sport_label' => 'Jiu-Jitsu brésilien',
    'weigh_in' => 'Poids de combat',

];
