<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'corner_chung' => 'چونگ',
    'corner_hong' => 'هونگ',
    'division_label' => 'دسته وزنی',
    'mat' => 'میدان',
    'official_center_referee' => 'داور مرکزی',
    'official_center_referee_hint' => 'بازی را در مرکز میدان انجام می‌دهد.',
    'official_corner_judge' => 'داور گوشه :n',
    'official_corner_judge_hint' => 'امتیاز می‌دهد از یک گوشه از میدان.',
    'official_court_supervisor' => 'نظارت‌کننده میدان',
    'official_court_supervisor_hint' => 'نظارت بر میدان و اعضای آن را انجام می‌دهد.',
    'official_review_jury' => 'پیشخوان بازنگری',
    'official_review_jury_hint' => 'براساس درخواست‌های بازنگری ویدئویی قوانین را تعیین می‌کند.',
    'official_table_recorder' => 'ثبت‌کننده جدول',
    'official_table_recorder_hint' => 'ثبت‌کننده رکورد رسمی در جدول.',
    'official_timekeeper' => 'نگهبان زمان',
    'official_timekeeper_hint' => 'نگهبان زمان: زمان دوره، توقفات و زنگ.',
    'score_body_kick' => 'پای چرخان به بدن',
    'score_head_kick' => 'پای چرخان به سر',
    'score_punch' => 'ضربه دست',
    'score_turning_body' => 'پاهای چرخان به بدن',
    'score_turning_head' => 'پاهای چرخان به سر',
    'sport_label' => 'تکواندو',
    'weigh_in' => 'اندازه‌گیری وزن',

];
