<?php

/*
|--------------------------------------------------------------------------
| auth — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/auth.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'auth_desktop_login_check_inbox_after' => '. Oturum açmak için tıklayın.',
    'auth_desktop_login_check_inbox_before' => 'Bir giriş bağlantısı gönderdik',
    'auth_desktop_login_check_inbox_title' => 'Gelen kutunuzu kontrol edin',
    'auth_desktop_login_email_me_link' => 'Bana giriş bağlantısı e-posta ile gönder',
    'auth_desktop_login_email_placeholder' => 'Telefon numarası veya e-posta',
    'auth_desktop_login_forgot_password' => 'Şifremi unuttum?',
    'auth_desktop_login_magic_hint' => 'Şifre yok mu? Size tek seferlik bir giriş bağlantısı e-posta ile gönderelim.',
    'auth_desktop_login_password_placeholder' => 'Şifre',
    'auth_desktop_login_register' => 'Hesap oluştur',
    'auth_desktop_login_remember_me' => 'Beni hatırla',
    'auth_desktop_login_resend_verification' => 'Doğrulama e-postasını yeniden gönder',
    'auth_desktop_login_sign_in' => 'Giriş Yap',
    'auth_desktop_login_subtitle' => 'Tekrar hoş geldiniz! Devam etmek için oturum açın',
    'auth_desktop_login_tab_link' => 'Giriş Bağlantısı',
    'auth_desktop_login_tab_password' => 'Şifre',
    'auth_desktop_login_unverified_hint' => 'E-postayı almadınız mı veya süresi dolmuş mu?',
    'auth_desktop_login_unverified_title' => 'E-posta doğrulanmadı',
    'auth_desktop_login_your_email_placeholder' => 'E-postanız',
    'auth_forgot_password_back_to_login' => 'Giriş ekranına dön',
    'auth_forgot_password_email_placeholder' => 'E-posta',
    'auth_forgot_password_send_reset_link' => 'Şifre Sıfırlama Bağlantısı Gönder',
    'auth_forgot_password_subtitle' => 'Endişelenmeyin — e-postanızı girin ve size sıfırlama bağlantısı göndereceğiz.',
    'auth_forgot_password_title' => 'Şifrenizi mi unuttunuz?',
    'auth_register_birthdate' => 'Doğum Tarihi',
    'auth_register_confirm_password' => 'Şifreyi Onayla',
    'auth_register_email' => 'E-posta Adresi',
    'auth_register_full_name' => 'Tam Ad',
    'auth_register_joining_club' => 'Katılıyorsunuz',
    'auth_register_mobile_number' => 'Mobil Numarası',
    'auth_register_nationality' => 'Milliyet',
    'auth_register_password' => 'Şifre',
    'auth_register_submit' => 'Kayıt Ol',
    'auth_register_subtitle' => 'Hesabınızı oluşturun',
    'auth_register_wizard_err_generic_post' => '). Lütfen tekrar deneyin.',
    'auth_register_wizard_err_generic_pre' => 'Bir şeyler ters gitti (hata',
    'auth_register_wizard_err_network' => 'Ağ hatası. Lütfen bağlantınızı kontrol edin ve tekrar deneyin.',
    'auth_register_wizard_err_session_expired' => 'Oturumunuzun süresi doldu. Lütfen sayfayı yenileyin ve tekrar deneyin.',
    'auth_register_wizard_ph_child_name' => 'Çocuğunun Tam Adı',
    'auth_register_wizard_ph_email' => 'E-posta Adresi',
    'auth_register_wizard_ph_full_name' => 'Tam Ad',
    'auth_register_wizard_ph_health' => 'Lütfen herhangi bir sağlık durumunu açıklayın',
    'auth_register_wizard_ph_mobile' => 'Mobil Numarası',
    'auth_register_wizard_rel_daughter' => 'Kız',
    'auth_register_wizard_rel_member_fallback' => 'Aile Üyesi',
    'auth_register_wizard_rel_other' => 'Diğer',
    'auth_register_wizard_rel_son' => 'Oğlan',
    'auth_register_wizard_rel_spouse' => 'Eş',
    'auth_register_wizard_terms_changes_body' => 'Bu şartlar zaman zaman güncellenebilir; hizmetin kullanılmasına devam edilmesi, bu şartları kabul ettiğiniz anlamına gelir.',
    'auth_register_wizard_terms_changes_title' => 'Kullanım Şartları Güncellendi',
    'auth_register_wizard_terms_conduct_body' => 'Üyelerin kulübün kurallarını takip etmeleri ve personel ile diğer üyelerle saygılı davranmaları beklenir.',
    'auth_register_wizard_terms_conduct_title' => 'Davranış Kuralları',
    'auth_register_wizard_terms_confirm' => 'Aşağıdaki kutuyu işaretleyerek, bu şartları okuduğunuzu ve kabul ettiğinizi onaylıyorsunuz.',
    'auth_register_wizard_terms_default_intro' => ':club\'e hoş geldiniz! Kayıt olarak aşağıdaki şartları kabul edersiniz:',
    'auth_register_wizard_terms_medical_body' => 'Lütfen katılımı etkileyebilecek herhangi bir tıbbi veya sağlık durumunu bildirin.',
    'auth_register_wizard_terms_medical_title' => 'Tıbbi ve Sağlık',
    'auth_register_wizard_terms_membership_body' => 'Üyeliğiniz, kayıt onaylandıktan ve ödeme (gerekliyse) onaylandıktan sonra başlar.',
    'auth_register_wizard_terms_membership_title' => 'Üyelik',
    'auth_register_wizard_terms_payment_body' => 'Tüm ödemeler, \'daha sonra öde\' seçeneği seçilmediyse kayıt sırasında ödenmelidir.',
    'auth_register_wizard_terms_payment_title' => 'Ödeme',
    'auth_register_wizard_terms_privacy_body' => 'Kişisel verileriniz sadece üyelik yönetimi amacıyla kullanılır ve onayınız olmadan paylaşılmaz.',
    'auth_register_wizard_terms_privacy_title' => 'Gizlilik',
    'auth_reset_password_back_to_login' => 'Giriş ekranına dön',
    'auth_reset_password_confirm_password_label' => 'Yeni Şifreyi Onayla',
    'auth_reset_password_email_label' => 'E-posta Adresi',
    'auth_reset_password_new_password_label' => 'Yeni Şifre',
    'auth_reset_password_submit' => 'Şifreyi Sıfırla',
    'auth_reset_password_title' => 'Şifrenizi sıfırlayın',
    'auth_verify_email_check_inbox_line1' => 'E-posta adresinize bir doğrulama bağlantısı gönderdik.',
    'auth_verify_email_check_inbox_line2' => 'Hesabınızı doğrulamak için lütfen bağlantıya tıklayın.',
    'auth_verify_email_check_inbox_title' => 'E-postanızı kontrol edin',
    'auth_verify_email_didnt_receive' => 'E-postayı almadınız mı?',
    'auth_verify_email_fresh_link_sent' => 'E-posta adresinize yeni bir doğrulama bağlantısı gönderildi.',
    'auth_verify_email_go_to_app' => 'Devam Et',
    'auth_verify_email_one_step_away' => 'Katılmak için bir adım daha',
    'auth_verify_email_redirecting_prefix' => 'Yönlendiriliyor',
    'auth_verify_email_redirecting_suffix' => 'saniye...',
    'auth_verify_email_resend_button' => 'Doğrulama E-postasını Yeniden Gönder',
    'auth_verify_email_sign_out' => 'Çıkış yap',
    'auth_verify_email_verified_body' => 'E-postanız başarıyla doğrulandı.',
    'auth_verify_email_verified_title' => 'E-posta Doğrulandı!',
    'auth_verify_email_wrong_account' => 'Yanlış hesap?',
    'choose_not_you' => 'Farklı bir numara veya e-posta kullanın',
    'choose_sub' => 'Bu numarayı birden fazla kişi kullanıyor. Giriş yapan kişiyi seçin.',
    'choose_title' => 'Kim giriş yapıyor?',
    'club_waiting' => 'Klubunuz bekliyor. Hadi gidelim.',
    'create_account' => 'Hesap oluştur',
    'didnt_receive' => 'E-postayı almadınız mı veya süresi dolmuş mu?',
    'email' => 'E-posta',
    'email_not_verified' => 'E-posta doğrulanmadı',
    'email_or_phone' => 'Telefon numarası veya e-posta',
    'forgot_password' => 'Şifremi unuttum?',
    'hide_password' => 'Şifreyi gizle',
    'magic_cta' => 'Bana giriş bağlantısı e-posta ile gönder',
    'magic_prompt' => 'Şifre yok mu? Size tek seferlik bir giriş bağlantısı e-posta ile gönderelim.',
    'magic_sent_body' => 'Bu e-posta adresi için bir hesap varsa, bir giriş bağlantısı gönderdik. Oturum açmak için e-postadaki butona tıklayın — şifre gerekmiyor.',
    'magic_sent_title' => 'Gelen kutunuzu kontrol edin',
    'new_to_takeone' => 'TAKEONE\'da yeni misiniz?',
    'or' => 'veya',
    'password' => 'Şifre',
    'remember_me' => 'Beni hatırla',
    'resend_verification' => 'Doğrulama e-postasını yeniden gönder',
    'show_password' => 'Şifreyi göster',
    'sign_in' => 'Giriş Yap',
    'tab_magic' => 'Giriş bağlantısı',
    'tab_password' => 'Şifre',
    'welcome_back' => 'Tekrar hoş geldiniz',

];
