<?php

/*
|--------------------------------------------------------------------------
| explore — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/explore.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'apply_location' => 'Konumu Uygula',
    'book_session' => 'Oturum Randevusu Al',
    'cat_all' => 'Tümü',
    'cat_clubs' => 'Kulüpler',
    'cat_events' => 'Etkinlikler',
    'cat_food_plans' => 'Besin Planları',
    'cat_nutrition' => 'Beslenme',
    'cat_physiotherapy' => 'Fizyoterapi',
    'cat_shops' => 'Mağazalar',
    'cat_supplements' => 'TakeOne',
    'cat_trainers' => 'Antrenörler',
    'cat_venues' => 'Tesisler',
    'choose_option_body' => 'Her seçilen ekipman öğesi için bir seçenek seçin.',
    'choose_option_title' => 'Seçenek gerekli',
    'detecting_location' => 'Konum tespit ediliyor...',
    'drag_marker' => 'Konumunuzu ayarlamak için işaretçiyi sürükleyin',
    'error_fetching_clubs' => 'Kulüpler yüklenirken bir hata oluştu.',
    'ev_coming_up' => 'Yaklaşan',
    'ev_failed' => 'Etkinlikler yüklenemedi. Lütfen tekrar deneyin.',
    'ev_finding' => 'Etkinlikler yükleniyor...',
    'ev_free' => 'Ücretsiz',
    'ev_full' => 'Dolu',
    'ev_going' => 'devam ediyor',
    'ev_happening_now' => 'Şu anda yapılıyor',
    'ev_live' => 'Canlı',
    'ev_none_hint' => 'Şu anda sizin için çalışan veya planlanan hiçbir şey yok.',
    'ev_none_title' => 'Açık etkinlik yok',
    'ev_open' => 'Açık',
    'ev_spots_left' => 'boş yer kaldı',
    'ev_starts_in' => 'Başlangıç süresi',
    'ev_tba' => 'Yapılacak',
    'ev_until' => 'kadar',
    'ev_view_event' => 'Etkinliği görüntüle',
    'explore' => 'Keşfet',
    'failed_to_fetch_clubs' => 'Kulüpler yüklenemedi. Lütfen tekrar deneyin.',
    'finding' => 'Yakınlardaki şeyleri buluyor...',
    'geolocation_not_supported' => 'Tarayıcınız konum belirleme özelliğini desteklemiyor.',
    'hero_eyebrow' => 'Yakınlardaki sporları keşfedin',
    'hero_sub' => 'Sizin çevrenizdeki kulüpler, antrenörler, klinikler ve daha fazlası',
    'hero_title' => 'Müperfect Uygunluğu Bulun',
    'join_club' => 'Kulübe Katıl',
    'km_away' => 'km uzaklıkta',
    'loading' => 'Yükleniyor...',
    'location_access_denied' => 'Konum erişimi reddedildi.',
    'location_available' => 'Konum mevcut',
    'location_request_timed_out' => 'Konum isteği zaman aşımına uğradı.',
    'location_unavailable' => 'Konum bilgisi kullanılamıyor.',
    'members' => 'Üyeler',
    'na' => 'Yok',
    'near_me' => 'Yakınlarda',
    'no_members_selected_body' => 'Devam etmek için en az bir üye seçin.',
    'no_members_selected_title' => 'Üye seçilmedi',
    'no_results' => 'Sonuç Bulunamadı',
    'no_results_hint' => 'Aramanızı veya konumunuzu ayarlamayı deneyin',
    'packages' => 'Paketler',
    'packages_required_body' => 'Her seçilen üye için bir paket seçin.',
    'packages_required_title' => 'Paket gerekli',
    'payment_required_body' => 'Bir ödeme ekran görüntüsü yükleyin veya daha sonra ödeme yapmayı seçin.',
    'payment_required_title' => 'Ödeme kanıtı gerekli',
    'personal_trainer_badge' => 'Kişisel Antrenör',
    'please_try_again' => 'Lütfen tekrar deneyin.',
    'rating' => 'Değerlendirme',
    'registration_error_body' => 'Kaydınızı gönderirken bir hata oluştu.',
    'registration_failed_title' => 'Kayıt başarısız',
    'registration_submitted_body' => 'Kaydınız kulübe onay için gönderildi.',
    'registration_submitted_title' => 'Kayıt gönderildi',
    'reviews' => 'Yorumlar',
    'search_placeholder' => 'Kulüpleri, antrenörleri ara...',
    'set_location' => 'Konumunuzu Ayarlayın',
    'sports_club_badge' => 'Spor Kulübü',
    'trainers' => 'Antrenörler',
    'unable_to_get_location' => 'Konumunuzu alamıyor.',
    'view_details' => 'Detayları Gör',
    'years_exp' => 'Yıl Deneyim',

];
