<?php

/*
|--------------------------------------------------------------------------
| security — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/security.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'add_otp_desc' => 'Her girişte kimlik doğrulayıcı uygulamanızdan tek seferlik kod girin.',
    'cancel' => 'İptal',
    'change_password' => 'Parolayı Değiştir',
    'change_password_desc' => 'Bunu değiştirdiğinizde diğer tüm etkin oturumlar oturum kapatılır.',
    'code_placeholder' => '6 haneli kod',
    'code_placeholder_long' => '6 haneli veya kurtarma kodu',
    'confirm_new_password' => 'Yeni Parolayı Onayla',
    'current_password' => 'Mevcut Parola',
    'disable' => 'Devre Dışı Bırak',
    'disable_2fa' => '2FA\'yı Devre Dışı Bırak',
    'disable_confirm_desc' => 'Onaylamak için mevcut bir kimlik doğrulayıcı kodu (veya kurtarma kodu) girin.',
    'disable_two_factor' => 'İki Faktörlü Kimlik Doğrulamayı Devre Dışı Bırak',
    'enable_2fa' => '2FA\'yı Etkinleştir',
    'lockdown_message' => 'Hesabınızı kitleyelim.',
    'new_password' => 'Yeni Parola',
    'protected_message' => 'Hesabınız iyi korunuyor.',
    'protected_with_app' => 'Google Authenticator ile korunuyor.',
    'recovery_codes' => 'Kurtarma Kodları',
    'recovery_codes_desc' => 'Kimlik doğrulayıcınıza erişiminizi kaybettiğinizde kullanabileceğiniz tek seferlik yedek kodlar.',
    'regenerate' => 'Yeniden Oluştur',
    'regenerate_codes' => 'Kodları Yeniden Oluştur',
    'regenerate_codes_title' => 'Kodları Yeniden Oluştur',
    'regenerate_confirm_desc' => 'Mevcut kurtarma kodlarınız çalışmayacaktır. Onaylamak için kimlik doğrulayıcı kodunuzu girin.',
    'security' => 'Güvenlik',
    'security_challenge_back_to_login' => 'Giriş ekranına geri dön',
    'security_challenge_backup_hint' => '8 karakterli yedek kodlarınızdan birini girin.',
    'security_challenge_subtitle' => 'Kimlik doğrulayıcı uygulamanızdan kodu girin.',
    'security_challenge_title' => 'İki Faktörlü Kimlik Doğrulama',
    'security_challenge_use_authenticator' => 'Kimlik doğrulayıcı uygulamasını kullan',
    'security_challenge_use_recovery' => 'Kurtarma kodunu kullan',
    'security_challenge_verify' => 'DOĞRULA',
    'security_index_2fa_disabled_desc' => 'Hesabınıza ekstra bir güvenlik katmanı ekleyin.',
    'security_index_2fa_enabled_desc' => 'Hesabınız Google Authenticator ile korunuyor.',
    'security_index_2fa_title' => 'İki Faktörlü Kimlik Doğrulama',
    'security_index_change_password' => 'Parolayı Değiştir',
    'security_index_change_password_desc' => 'Parolanızı değiştirdiğinizde diğer tüm etkin oturumlar oturum kapatılır.',
    'security_index_code_or_recovery_placeholder' => '6 haneli kod veya kurtarma kodu',
    'security_index_code_placeholder' => '6 haneli kod',
    'security_index_confirm_new_password' => 'Yeni Parolayı Onayla',
    'security_index_current_password' => 'Mevcut Parola',
    'security_index_disable_2fa' => '2FA\'yı Devre Dışı Bırak',
    'security_index_disable_2fa_modal_desc' => 'Onaylamak için mevcut kimlik doğrulayıcı kodunuzu (veya bir kurtarma kodu) girin.',
    'security_index_disable_2fa_modal_title' => 'İki Faktörlü Kimlik Doğrulamayı Devre Dışı Bırak',
    'security_index_disabled' => 'Devre Dışı',
    'security_index_enable_2fa' => '2FA\'yı Etkinleştir',
    'security_index_enabled' => 'Etkin',
    'security_index_new_password' => 'Yeni Parola',
    'security_index_recovery_codes' => 'Kurtarma Kodları',
    'security_index_recovery_codes_desc' => 'Kimlik doğrulama uygulusuna erişiminizi kaybetmeniz durumunda tek seferlik yedek kodlar.',
    'security_index_regen_codes_modal_desc' => 'Kurtarma Kodları',
    'security_index_regen_codes_modal_title' => 'Kimlik doğrulayıcı uygulamanıza erişiminizi kaybettiğinizde tek seferlik yedek kodlar.',
    'security_index_regenerate' => 'Yeniden Oluştur',
    'security_index_regenerate_codes' => 'Kodları Yeniden Oluştur',
    'security_index_subtitle' => 'Hesap güvenliğinizi ve iki faktörlü kimlik doğrulamayı yönetin',
    'security_index_title' => 'Güvenlik Ayarları',
    'security_index_update_password' => 'Parolayı Güncelle',
    'security_recovery_codes_account_protected' => 'Hesabınız artık korunuyor.',
    'security_recovery_codes_copied' => 'Kopyalandı!',
    'security_recovery_codes_copy_all' => 'Tüm Kodları Kopyala',
    'security_recovery_codes_heading_enabled' => 'İki Adımlı Kimlik Doğrulama Etkin',
    'security_recovery_codes_heading_new' => 'Yeni Kurtarma Kodları',
    'security_recovery_codes_page_title' => 'Kurtarma Kodları',
    'security_recovery_codes_save_safe' => 'Bu kurtarma kodlarını güvenli bir yerde saklayın.',
    'security_recovery_codes_store_desc' => 'Her kod sadece bir kez kullanılabilir.',
    'security_recovery_codes_store_safely' => 'Bu kodları güvenli bir şekilde saklayın.',
    'security_recovery_codes_success_alert' => 'İki adımlı kimlik doğrulama hesabınızda başarıyla etkinleştirildi.',
    'security_setup_manual_entry' => 'Tarama yapılamıyor mu? Uygulamada şu anahtarı manuel olarak girin:',
    'security_setup_step1_app_name' => 'Google Authenticator',
    'security_setup_step1_app_store' => 'App Store',
    'security_setup_step1_download' => 'İndir',
    'security_setup_step1_from' => 'telefonunuzdan',
    'security_setup_step1_heading' => 'Google Authenticator’ı Yükleyin',
    'security_setup_step1_or' => 'veya',
    'security_setup_step1_play_store' => 'Play Store',
    'security_setup_step2_heading' => 'QR Kodunu Tara',
    'security_setup_step2_open' => 'Uygulamayı açın, dokunun',
    'security_setup_step2_scan_option' => 'Bir QR kodu tara',
    'security_setup_step2_then_choose' => 'ardından şunu seçin',
    'security_setup_step3_heading' => 'Kodunuzu Onaylayın',
    'security_setup_step3_subtitle' => 'Kurulumu doğrulamak için uygulamada gösterilen 6 haneli kodu girin.',
    'security_setup_subtitle' => 'Hesabınızı Google Authenticator ile korumak için aşağıdaki adımları izleyin.',
    'security_setup_time_based' => 'Zaman tabanlı',
    'security_setup_time_based_prefix' => 'Seçin',
    'security_setup_time_based_suffix' => 'istemede bulunduğunda.',
    'security_setup_title' => 'İki Adımlı Kimlik Doğrulama Kurulumu',
    'security_setup_verify_button' => 'Onayla ve Etkinleştir',
    'title' => 'Güvenlik Ayarları',
    'two_factor_auth' => 'İki Faktörlü Kimlik Doğrulama',
    'two_factor_off' => 'İki faktörlü kimlik doğrulama kapalı',
    'two_factor_on' => 'İki faktörlü kimlik doğrulama açık',
    'update_password' => 'Parolayı Güncelle',

];
