<?php

/*
|--------------------------------------------------------------------------
| auth — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/auth.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'auth_desktop_login_check_inbox_after' => 'ارسال کرده‌ایم. آن را کلیک کنید تا وارد شوید.',
    'auth_desktop_login_check_inbox_before' => 'ما یک لینک ورود به',
    'auth_desktop_login_check_inbox_title' => 'صندوق ورودی خود را چک کنید',
    'auth_desktop_login_email_me_link' => 'ارسال لینک ورود به ایمیل',
    'auth_desktop_login_email_placeholder' => 'شماره تلفن یا ایمیل',
    'auth_desktop_login_forgot_password' => 'رمز عبور را فراموش کرده‌اید؟',
    'auth_desktop_login_magic_hint' => 'رمز عبور ندارید؟ ما یک لینک ورود یک‌باره به ایمیل شما ارسال خواهیم کرد.',
    'auth_desktop_login_password_placeholder' => 'رمز عبور',
    'auth_desktop_login_register' => 'ایجاد حساب کاربری',
    'auth_desktop_login_remember_me' => 'مرا به خاطر بسپار',
    'auth_desktop_login_resend_verification' => 'ارسال مجدد ایمیل تأیید',
    'auth_desktop_login_sign_in' => 'ورود',
    'auth_desktop_login_subtitle' => 'خوش آمدید! برای ادامه وارد شوید',
    'auth_desktop_login_tab_link' => 'لینک ورود',
    'auth_desktop_login_tab_password' => 'رمز عبور',
    'auth_desktop_login_unverified_hint' => 'ایمیل را دریافت نکرده‌اید یا منقضی شده؟',
    'auth_desktop_login_unverified_title' => 'ایمیل تأیید نشده',
    'auth_desktop_login_your_email_placeholder' => 'ایمیل شما',
    'auth_forgot_password_back_to_login' => 'بازگشت به ورود',
    'auth_forgot_password_email_placeholder' => 'ایمیل',
    'auth_forgot_password_send_reset_link' => 'ارسال لینک بازنشانی رمز عبور',
    'auth_forgot_password_subtitle' => 'مشکلی نیست — ایمیل خود را وارد کنید و ما یک لینک بازنشانی برایتان ارسال خواهیم کرد.',
    'auth_forgot_password_title' => 'رمز عبور خود را فراموش کرده‌اید؟',
    'auth_register_birthdate' => 'تاریخ تولد',
    'auth_register_confirm_password' => 'تکرار رمز عبور',
    'auth_register_email' => 'آدرس ایمیل',
    'auth_register_full_name' => 'نام کامل',
    'auth_register_joining_club' => 'شما عضو',
    'auth_register_mobile_number' => 'شماره موبایل',
    'auth_register_nationality' => 'ملیت',
    'auth_register_password' => 'رمز عبور',
    'auth_register_submit' => 'ثبت نام',
    'auth_register_subtitle' => 'حساب کاربری خود را ایجاد کنید',
    'auth_register_wizard_err_generic_post' => '). لطفاً دوباره امتحان کنید.',
    'auth_register_wizard_err_generic_pre' => 'مشکلی پیش آمد (خطا',
    'auth_register_wizard_err_network' => 'خطای شبکه. لطفاً اتصال خود را بررسی کنید و دوباره امتحان کنید.',
    'auth_register_wizard_err_session_expired' => 'نشست شما منقضی شده است. لطفاً صفحه را تازه کنید و دوباره امتحان کنید.',
    'auth_register_wizard_ph_child_name' => 'نام کامل فرزند',
    'auth_register_wizard_ph_email' => 'آدرس ایمیل',
    'auth_register_wizard_ph_full_name' => 'نام کامل',
    'auth_register_wizard_ph_health' => 'لطفاً هرگونه شرایط سلامتی خود را توضیح دهید',
    'auth_register_wizard_ph_mobile' => 'شماره موبایل',
    'auth_register_wizard_rel_daughter' => 'دختر',
    'auth_register_wizard_rel_member_fallback' => 'عضو خانواده',
    'auth_register_wizard_rel_other' => 'دیگر',
    'auth_register_wizard_rel_son' => 'پسر',
    'auth_register_wizard_rel_spouse' => 'همسر',
    'auth_register_wizard_terms_changes_body' => 'این شرایط ممکن است از زمانی به زمانی به‌روزرسانی شوند؛ استفاده مداوم از سرویس به معنای پذیرش آن است.',
    'auth_register_wizard_terms_changes_title' => 'تغییرات در شرایط',
    'auth_register_wizard_terms_conduct_body' => 'اعضا مورد انتظار است که قوانین باشگاه را رعایت کنند و با رفتاری محترمانه نسبت به کارکنان و سایر اعضا رفتار کنند.',
    'auth_register_wizard_terms_conduct_title' => 'رویه رفتاری',
    'auth_register_wizard_terms_confirm' => 'با علامت زدن کادر زیر، تأیید می‌کنید که این شرایط را خوانده‌اید و با آن موافقت دارید.',
    'auth_register_wizard_terms_default_intro' => 'خوش آمدید به :club! با ثبت نام، شما با شرایط زیر موافقت می‌کنید:',
    'auth_register_wizard_terms_medical_body' => 'لطفاً هرگونه شرایط پزشکی یا سلامتی که ممکن است بر شرکت شما تأثیر بگذارد را اعلام کنید.',
    'auth_register_wizard_terms_medical_title' => 'سلامتی و پزشکی',
    'auth_register_wizard_terms_membership_body' => 'عضویت شما زمانی شروع می‌شود که ثبت نام شما تأیید شود و پرداخت (در صورت لزوم) تأیید شود.',
    'auth_register_wizard_terms_membership_title' => 'عضویت',
    'auth_register_wizard_terms_payment_body' => 'تمام پرداخت‌ها در زمان ثبت نام صورت می‌گیرد مگر اینکه گزینه \'پرداخت بعداً\' انتخاب شود.',
    'auth_register_wizard_terms_payment_title' => 'پرداخت',
    'auth_register_wizard_terms_privacy_body' => 'داده‌های شخصی شما فقط برای مدیریت عضویت شما استفاده شده و بدون رضایتsharing نخواهد شد.',
    'auth_register_wizard_terms_privacy_title' => 'حریم خصوصی',
    'auth_reset_password_back_to_login' => 'بازگشت به ورود',
    'auth_reset_password_confirm_password_label' => 'تأیید رمز عبور جدید',
    'auth_reset_password_email_label' => 'آدرس ایمیل',
    'auth_reset_password_new_password_label' => 'رمز عبور جدید',
    'auth_reset_password_submit' => 'بازنشانی رمز عبور',
    'auth_reset_password_title' => 'رمز عبور خود را بازنشانی کنید',
    'auth_verify_email_check_inbox_line1' => 'ما یک لینک تأیید به آدرس ایمیل شما ارسال کرده‌ایم.',
    'auth_verify_email_check_inbox_line2' => 'لطفاً روی لینک کلیک کنید تا حساب شما تأیید شود.',
    'auth_verify_email_check_inbox_title' => 'ایمیل خود را بررسی کنید',
    'auth_verify_email_didnt_receive' => 'ایمیل دریافت نشد؟',
    'auth_verify_email_fresh_link_sent' => 'یک لینک تأیید تازه به آدرس ایمیل شما ارسال شده است.',
    'auth_verify_email_go_to_app' => 'ادامه',
    'auth_verify_email_one_step_away' => 'یک مرحله دیگر برای عضویت',
    'auth_verify_email_redirecting_prefix' => 'در حال تغییر در',
    'auth_verify_email_redirecting_suffix' => 'ثانیه...',
    'auth_verify_email_resend_button' => 'ارسال مجدد ایمیل تأیید',
    'auth_verify_email_sign_out' => 'خروج',
    'auth_verify_email_verified_body' => 'ایمیل شما با موفقیت تأیید شد.',
    'auth_verify_email_verified_title' => 'ایمیل تأیید شد!',
    'auth_verify_email_wrong_account' => 'حساب اشتباه؟',
    'choose_not_you' => 'از شماره یا ایمیل دیگری استفاده کنید',
    'choose_sub' => 'بیش از یک نفر از این شماره استفاده می‌کند. روی فردی که در حال ورود است، ضربه بزنید.',
    'choose_title' => 'چه کسی در حال ورود است؟',
    'club_waiting' => 'باشگاه شما در انتظار است. بیا برویم.',
    'create_account' => 'ایجاد حساب کاربری',
    'didnt_receive' => 'ایمیل را دریافت نکرده‌اید یا منقضی شده؟',
    'email' => 'ایمیل',
    'email_not_verified' => 'ایمیل تأیید نشده',
    'email_or_phone' => 'شماره تلفن یا ایمیل',
    'forgot_password' => 'رمز عبور را فراموش کرده‌اید؟',
    'hide_password' => 'پنهان کردن رمز عبور',
    'magic_cta' => 'ارسال لینک ورود به ایمیل',
    'magic_prompt' => 'رمز عبور ندارید؟ ما یک لینک ورود یک‌باره به ایمیل شما ارسال خواهیم کرد.',
    'magic_sent_body' => 'اگر حسابی برای این ایمیل وجود داشته باشد، ما یک لینک ورود ارسال کرده‌ایم. روی دکمه موجود در ایمیل کلیک کنید تا وارد شوید — نیازی به رمز عبور نیست.',
    'magic_sent_title' => 'صندوق ورودی خود را چک کنید',
    'new_to_takeone' => 'جدید در TAKEONE؟',
    'or' => 'یا',
    'password' => 'رمز عبور',
    'remember_me' => 'مرا به خاطر بسپار',
    'resend_verification' => 'ارسال مجدد ایمیل تأیید',
    'show_password' => 'نمایش رمز عبور',
    'sign_in' => 'ورود',
    'tab_magic' => 'لینک ورود',
    'tab_password' => 'رمز عبور',
    'welcome_back' => 'خوش آمدید',

];
