<?php

/*
|--------------------------------------------------------------------------
| header — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/header.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'cart' => 'سبد خرید',
    'cart_soon' => 'زمانی که سبد خرید آماده است',
    'chat' => 'چت',
    'clear_all' => 'پاک کردن همه',
    'club_management' => 'مدیریت باشگاه',
    'just_now' => 'همین الان',
    'mark_all_read' => 'علامت‌گذاری همه به عنوان خوانده شده',
    'menu' => 'منو',
    'no_notifications' => 'هنوز اعلانی وجود ندارد',
    'notification' => 'اعلان',
    'notifications' => 'اعلان‌ها',
    'personal_desc' => 'پروفایل من، رزروها، پرداخت‌ها',
    'personal_view' => 'نمای شخصی',
    'scan_code_placeholder' => 'ABC123',
    'scan_foreign_host' => 'این کد QR به سایت دیگری اشاره می‌کند، بنابراین باز نشد.',
    'scan_hint' => 'دوربین خود را روی یک کد QR قرار دهید',
    'scan_no_camera' => 'دسترسی به دوربین امکان‌پذیر نیست.',
    'scan_or_type' => 'یا کد شش‌رقمی را تایپ کنید',
    'scan_qr' => 'اسکن کد QR',
    'scan_unsupported' => 'اسکن کد QR در این مرورگر پشتیبانی نمی‌شود.',
    'switch_view' => 'تغییر نمایش',

];
