<?php

/*
|--------------------------------------------------------------------------
| security — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/security.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'add_otp_desc' => 'هنگام ورود، یک کد یک‌بار مصرف از برنامه احراز هویت خود وارد کنید.',
    'cancel' => 'لغو',
    'change_password' => 'تغییر گذرواژه',
    'change_password_desc' => 'هنگام تغییر گذرواژه، تمام جلسات فعال دیگر از سیستم خارج می‌شوند.',
    'code_placeholder' => 'کد 6 رقمی',
    'code_placeholder_long' => 'کد 6 رقمی یا کد بازیابی',
    'confirm_new_password' => 'تأیید گذرواژه جدید',
    'current_password' => 'گذرواژه فعلی',
    'disable' => 'غیرفعال کردن',
    'disable_2fa' => 'غیرفعال کردن 2FA',
    'disable_confirm_desc' => 'برای تأیید، یک کد احراز هویت فعلی (یا یک کد بازیابی) وارد کنید.',
    'disable_two_factor' => 'غیرفعال کردن احراز هویت دو مرحله‌ای',
    'enable_2fa' => 'فعال کردن 2FA',
    'lockdown_message' => 'بیایید حساب خود را قفل کنیم.',
    'new_password' => 'گذرواژه جدید',
    'protected_message' => 'حساب شما به خوبی محافظت شده است.',
    'protected_with_app' => 'با Google Authenticator محافظت شده.',
    'recovery_codes' => 'کد های بازیابی',
    'recovery_codes_desc' => 'کد های پشتیبان یک‌بار مصرف در صورت از دست دادن احراز هویت.',
    'regenerate' => 'تولید مجدد',
    'regenerate_codes' => 'تولید مجدد کد ها',
    'regenerate_codes_title' => 'تولید مجدد کد ها',
    'regenerate_confirm_desc' => 'کد های بازیابی موجود شما دیگر کار نخواهند کرد. برای تأیید، کد احراز هویت خود را وارد کنید.',
    'security' => 'امنیت',
    'security_challenge_back_to_login' => 'بازگشت به ورود',
    'security_challenge_backup_hint' => 'یکی از ۸ کاراکتر کد های پشتیبان خود را وارد کنید.',
    'security_challenge_subtitle' => 'کد از برنامه احراز هویت خود را وارد کنید.',
    'security_challenge_title' => 'احراز هویت دو مرحله‌ای',
    'security_challenge_use_authenticator' => 'به جای آن از برنامه احراز هویت استفاده کنید',
    'security_challenge_use_recovery' => 'از یک کد بازیابی استفاده کنید',
    'security_challenge_verify' => 'تأیید',
    'security_index_2fa_disabled_desc' => 'یک لایه اضافی امنیت برای حساب خود اضافه کنید.',
    'security_index_2fa_enabled_desc' => 'حساب شما با Google Authenticator محافظت شده است.',
    'security_index_2fa_title' => 'احراز هویت دو مرحله‌ای',
    'security_index_change_password' => 'تغییر گذرواژه',
    'security_index_change_password_desc' => 'هنگام تغییر گذرواژه، تمام جلسات فعال دیگر از سیستم خارج می‌شوند.',
    'security_index_code_or_recovery_placeholder' => 'کد 6 رقمی یا کد بازیابی',
    'security_index_code_placeholder' => 'کد 6 رقمی',
    'security_index_confirm_new_password' => 'تأیید گذرواژه جدید',
    'security_index_current_password' => 'گذرواژه فعلی',
    'security_index_disable_2fa' => 'غیرفعال کردن 2FA',
    'security_index_disable_2fa_modal_desc' => 'برای تأیید، کد احراز هویت فعلی (یا یک کد بازیابی) وارد کنید.',
    'security_index_disable_2fa_modal_title' => 'غیرفعال کردن احراز هویت دو مرحله‌ای',
    'security_index_disabled' => 'غیرفعال شده',
    'security_index_enable_2fa' => 'فعال کردن 2FA',
    'security_index_enabled' => 'فعال شده',
    'security_index_new_password' => 'گذرواژه جدید',
    'security_index_recovery_codes' => 'کد های بازیابی',
    'security_index_recovery_codes_desc' => 'کد های پشتیبان یک‌بار مصرف در صورت از دست دادن دسترسی به برنامه احراز هویت.',
    'security_index_regen_codes_modal_desc' => 'کد های بازیابی موجود شما نا معتبر خواهند شد. برای تأیید، کد احراز هویت خود را وارد کنید.',
    'security_index_regen_codes_modal_title' => 'تولید مجدد کد های بازیابی',
    'security_index_regenerate' => 'تولید مجدد',
    'security_index_regenerate_codes' => 'تولید مجدد کد ها',
    'security_index_subtitle' => 'مدیریت امنیت حساب و احراز هویت دو مرحله‌ای',
    'security_index_title' => 'تنظیمات امنیتی',
    'security_index_update_password' => 'به‌روزرسانی گذرواژه',
    'security_recovery_codes_account_protected' => 'حساب شما اکنون محافظت شده است.',
    'security_recovery_codes_copied' => 'کپی شد!',
    'security_recovery_codes_copy_all' => 'کپی تمام کدها',
    'security_recovery_codes_heading_enabled' => 'احراز هویت دو مرحله‌ای فعال شد',
    'security_recovery_codes_heading_new' => 'کدهای بازیابی جدید',
    'security_recovery_codes_page_title' => 'کدهای بازیابی',
    'security_recovery_codes_save_safe' => 'این کدهای بازیابی را در جایی امن ذخیره کنید.',
    'security_recovery_codes_store_desc' => 'هر کد فقط قابل استفاده یک بار است.',
    'security_recovery_codes_store_safely' => 'این کدها را به‌طور امن ذخیره کنید.',
    'security_recovery_codes_success_alert' => 'احراز هویت دو مرحله‌ای با موفقیت روی حساب شما فعال شد.',
    'security_setup_manual_entry' => 'نمی‌توانید اسکن کنید؟ کلید زیر را به صورت دستی در اپلیکیشن وارد کنید:',
    'security_setup_step1_app_name' => 'اعتبارسنجی گوگل',
    'security_setup_step1_app_store' => 'فروشگاه اپل',
    'security_setup_step1_download' => 'دانلود',
    'security_setup_step1_from' => 'روی تلفن همراه خود از',
    'security_setup_step1_heading' => 'نصب اعتبارسنجی گوگل',
    'security_setup_step1_or' => 'یا',
    'security_setup_step1_play_store' => 'فروشگاه پلی',
    'security_setup_step2_heading' => 'اسکن کد QR',
    'security_setup_step2_open' => 'اپلیکیشن را باز کنید، ضربه بزنید',
    'security_setup_step2_scan_option' => 'اسکن یک کد QR',
    'security_setup_step2_then_choose' => '، سپس انتخاب کنید',
    'security_setup_step3_heading' => 'کد خود را تأیید کنید',
    'security_setup_step3_subtitle' => 'کد 6 رقمی نمایش داده شده در اپلیکیشن را وارد کنید تا راه‌اندازی تأیید شود.',
    'security_setup_subtitle' => 'مراحل زیر را دنبال کنید تا حساب خود را با اعتبارسنجی گوگل امن کنید.',
    'security_setup_time_based' => 'بر اساس زمان',
    'security_setup_time_based_prefix' => 'انتخاب کنید',
    'security_setup_time_based_suffix' => 'وقتی درخواست شود.',
    'security_setup_title' => 'راه‌اندازی احراز هویت دو مرحله‌ای',
    'security_setup_verify_button' => 'تأیید و فعال‌سازی',
    'title' => 'تنظیمات امنیتی',
    'two_factor_auth' => 'احراز هویت دو مرحله‌ای',
    'two_factor_off' => 'احراز هویت دو مرحله‌ای خاموش است',
    'two_factor_on' => 'احراز هویت دو مرحله‌ای روشن است',
    'update_password' => 'به‌روزرسانی گذرواژه',

];
