<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'belt_black' => '黒',
    'belt_blue' => '青',
    'belt_brown' => '茶',
    'belt_purple' => '紫',
    'belt_white' => '白',
    'corner_blue' => '青',
    'corner_white' => '白',
    'division_label' => '重量級',
    'mat' => 'マット',
    'official_mat_organiser' => 'マット管理者',
    'official_mat_organiser_hint' => 'マットの進行を管理し、選手を呼ぶ。',
    'official_referee' => '審判',
    'official_referee_hint' => 'マットで試合を進行させる：開始・停止、そしてすべての得点を示す。',
    'official_scorekeeper' => '記録係',
    'official_scorekeeper_hint' => 'テーブルで得点、優勢、ペナルティを入力する。',
    'official_timekeeper' => '時間係',
    'official_timekeeper_hint' => '時計を管理する：試合時間、停止時間、最終ベル。',
    'score_four' => '4点',
    'score_three' => '3点',
    'score_two' => '2点',
    'sport_label' => 'ブラジリアン柔術',
    'weigh_in' => '体重計',

];
