<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'action_arrange_draw' => 'ड्रा व्यवस्थित करें',
    'action_clear_draw' => 'ड्रा साफ़ करें',
    'action_end_next_bout' => 'अगली मैच समाप्त करें',
    'action_generate_draw' => 'ड्रा उत्पन्न करें',
    'call_mat_tbc' => 'आपका मैट',
    'call_opponent_tbc' => 'प्रत्याशित',
    'call_room_body' => ':mat · मैच :bout · :opponent के खिलाफ',
    'call_room_title' => 'कॉल रूम में जाएं — :mat',
    'call_warmup_body' => ':ahead मैच आपके आगे हैं · लगभग :minutes मिनट',
    'call_warmup_title' => 'तालियाँ बजाएं — आप :mat पर जल्दी आएंगे',
    'day_mats' => 'दिन :day: :count मैट्स',
    'draw_arranged' => 'ड्रा अपडेट किया गया 🥋',
    'draw_cleared' => 'ड्रा खाली किया गया — प्रत्येक प्रवेशक सूची पर वापस है',
    'draw_final' => 'चैंपियनशिप शुरू हो चुकी है — ड्रा अंतिम है और फिर से उत्पन्न नहीं किया जा सकता।',
    'draw_generated' => 'अस्थायी ड्रा उत्पन्न हुआ',
    'end_next_bout_done' => ':winner को :court पर जीत देता है। उस मैट पर स्क्रीन को सूचित किया गया है।',
    'end_next_bout_none' => 'कोई मैच खत्म करने के लिए तैयार नहीं है — प्रत्येक लंबित मैच अभी भी एक फीडर की प्रतीक्षा में है।',
    'ended_locked' => 'यह चैंपियनशिप समाप्त हो चुकी है — इसके परिणाम अंतिम हैं।',
    'gate_no_division' => 'आपका वजन वर्ग इस चैंपियनशिप के विभाजनों में से कोई नहीं है, इसलिए आप इस घटना में प्रतियोगिता नहीं कर सकते।',
    'gate_no_division_spectator' => 'आपका वजन वर्ग इस चैंपियनशिप के विभाजनों में से कोई नहीं है, इसलिए आप प्रतियोगिता नहीं कर सकते — लेकिन आप दर्शक के रूप में भाग ले सकते हैं।',
    'gate_no_profile' => 'अपने प्रोफाइल में अपना लिंग और जन्मतिथि जोड़ें ताकि हम आपको एक वजन वर्ग में स्थान दे सकें।',
    'gate_no_weight' => 'अपने प्रोफाइल में अपना वर्तमान वजन जोड़ें ताकि हम आपको एक वजन वर्ग में स्थान दे सकें।',
    'notify_draw_body' => 'आपका विभाजन ड्रॉन किया गया है। अपने प्रतियोगी, मैट और मैच संख्या देखने के लिए घटना खोलें।',
    'notify_draw_title' => 'ड्रा उत्पन्न हुआ — :title',
    'notify_weigh_in_body' => 'वजन निर्धारण :time पर :place पर खुलता है। अपना पहचान पत्र लाएं।',
    'notify_weigh_in_title' => 'कल वजन निर्धारण — :title',
    'result_body_done' => 'यह आपका दिन का अंतिम मैच था।',
    'result_body_next' => 'अगला: :round :mat पर, लगभग :minutes मिनट',
    'result_loss_title' => 'मैच समाप्त',
    'result_win_title' => 'आपने जीत ली 🎉',
    'roster_registered' => 'पंजीकृत',
    'roster_unclassified' => 'अनवर्गीकृत',
    'type_label' => 'जीयू-जिट्स चैंपियनशिप',

];
