<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'corner_aka' => 'AKA',
    'corner_ao' => 'AO',
    'division_label' => 'Categoria de peso',
    'mat' => 'Pista',
    'official_judge' => 'Juiz :n (Fukushin)',
    'official_judge_hint' => 'Senta num canto e sinaliza os pontos que vê.',
    'official_match_supervisor' => 'Supervisor da Luta (Kansa)',
    'official_match_supervisor_hint' => 'Observa os árbitros e decide protestos.',
    'official_referee' => 'Árbitro (Shushin)',
    'official_referee_hint' => 'Gerencia a luta na pista: inicia e interrompe, e anuncia o placar.',
    'official_scorekeeper' => 'Marcador de Pontos',
    'official_scorekeeper_hint' => 'Registra o placar e as penalidades no formulário.',
    'official_tatami_manager' => 'Gerente do Tatame',
    'official_tatami_manager_hint' => 'Mantém a pista em ordem de horário e chama os atletas.',
    'official_timekeeper' => 'Cronometrista',
    'official_timekeeper_hint' => 'Controla o relógio: tempo da luta, paradas e sino final.',
    'score_ippon' => 'Ippon',
    'score_wazari' => 'Waza-ari',
    'score_yuko' => 'Yuko',
    'sport_label' => 'Karate',
    'weigh_in' => 'Pesagem',

];
