<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'corner_aka' => '赤红',
    'corner_ao' => '青色',
    'division_label' => '体重级别',
    'mat' => '场地',
    'official_judge' => '裁判 :n（副裁）',
    'official_judge_hint' => '坐在角落，标记他们看到的得分。',
    'official_match_supervisor' => '比赛监督（裁判长）',
    'official_match_supervisor_hint' => '监督裁判本身，并处理申诉。',
    'official_referee' => '裁判（主裁）',
    'official_referee_hint' => '在场地中主持比赛：开始和停止比赛，并宣布得分。',
    'official_scorekeeper' => '记分员',
    'official_scorekeeper_hint' => '记录得分和罚分在记分表上。',
    'official_tatami_manager' => '场地管理员',
    'official_tatami_manager_hint' => '维持场地运行与赛程，并叫运动员上场。',
    'official_timekeeper' => '计时员',
    'official_timekeeper_hint' => '控制计时器：比赛时间、暂停和终场铃声。',
    'score_ippon' => '一本',
    'score_wazari' => '十字',
    'score_yuko' => '有型',
    'sport_label' => '空手道',
    'weigh_in' => '称重',

];
