<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'corner_aka' => 'آکا',
    'corner_ao' => 'آو',
    'division_label' => 'دسته وزنی',
    'mat' => 'مات',
    'official_judge' => 'داده‌گیر :n (فوکوشین)',
    'official_judge_hint' => 'در گوشه جای می‌گیرد و امتیازهایی که مشاهده می‌کند را نشان می‌دهد.',
    'official_match_supervisor' => 'سرپرست مسابقه (کانسا)',
    'official_match_supervisor_hint' => 'مراقب رسمیان خود است و اعتراضات را حل می‌کند.',
    'official_referee' => 'حکم‌گذار (شوشین)',
    'official_referee_hint' => 'مسابقه را در مات اجرا می‌کند: آغاز و توقف آن را انجام می‌دهد و امتیاز را صدا می‌کند.',
    'official_scorekeeper' => 'ثبت‌کننده امتیاز',
    'official_scorekeeper_hint' => 'امتیاز و مجازات‌ها را روی برگه ثبت می‌کند.',
    'official_tatami_manager' => 'مدیر تاتامی',
    'official_tatami_manager_hint' => 'مات را به زمان‌بندی می‌آورد و ورزشکاران را فرا می‌خواند.',
    'official_timekeeper' => 'نگهبان زمان',
    'official_timekeeper_hint' => 'ساعت را نگه می‌دارد: زمان مسابقه، توقف‌ها و زنگ نهایی.',
    'score_ippon' => 'ایپون',
    'score_wazari' => 'وازا‌اری',
    'score_yuko' => 'یوکو',
    'sport_label' => 'کاراته',
    'weigh_in' => 'اندازه‌گیری وزن',

];
