<?php

/*
|--------------------------------------------------------------------------
| messages — machine translated
|--------------------------------------------------------------------------
|
| Generated by `php artisan translate:interface`, and validated against
| lang/en/messages.php before it was written: placeholders, plural
| forms, HTML tags and numbers all had to survive.
|
| (The header deliberately names no class. These files live inside event
|  packages and modules, and ModuleBoundaryTest reads FILE CONTENTS — a
|  private class name in a comment here fails the build for a reference
|  that does not exist.)
|
| SAFE TO EDIT. A key you change here is never overwritten by a later
| run — the generator only ever fills in keys that are absent. Correct
| anything that reads badly; it will stay corrected.
|
| A key missing from this file falls back to English on its own, per key,
| so this file is useful even when it is incomplete.
*/

return [

    'corner_chung' => 'تشونغ',
    'corner_hong' => 'هونغ',
    'division_label' => 'الفئة الوزنية',
    'mat' => 'بساط',
    'official_center_referee' => 'حكم الوسط',
    'official_center_referee_hint' => 'يدير النزال في وسط الساحة.',
    'official_corner_judge' => 'حكم زاوية :n',
    'official_corner_judge_hint' => 'يحتسب النقاط من زاوية الساحة.',
    'official_court_supervisor' => 'مشرف الساحة',
    'official_court_supervisor_hint' => 'يشرف على الساحة وطاقم حكامها.',
    'official_review_jury' => 'لجنة المراجعة',
    'official_review_jury_hint' => 'يبتّ في طلبات المراجعة بالفيديو.',
    'official_table_recorder' => 'مسجّل الطاولة',
    'official_table_recorder_hint' => 'يحفظ السجل الرسمي على الطاولة.',
    'official_timekeeper' => 'مسجّل الوقت',
    'official_timekeeper_hint' => 'يضبط الوقت: زمن الشوط والتوقفات والصافرة.',
    'score_body_kick' => 'ركلة للجسم',
    'score_head_kick' => 'ركلة للرأس',
    'score_punch' => 'لكمة',
    'score_turning_body' => 'ركلة دورانية للجسم',
    'score_turning_head' => 'ركلة دورانية للرأس',
    'sport_label' => 'التايكوندو',
    'weigh_in' => 'الوزن الرسمي',

];
